- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/main/resources/log4j2.xml
This includes general engine initialization, interval processing, and
SAM/BAM reader querying.
Also remove puzzling "FRED" prefix from our log output :)
Resolves #250
> Output log messages during engine operations that may be time-consuming.

- README.md
the travis status button broke when we became public
updating it to point to the new travis-ci.org url
> updating the travis status button

- src/test/java/org/broadinstitute/hellbender/tools/picard/illumina/IlluminaBasecallsToFastqTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/illumina/IlluminaBasecallsToSamTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/illumina/parser/IlluminaDataProviderTest.java
due to broken picard tests, we need to disable them. https://github.com/broadinstitute/hellbender/issues/364
fixing them is the highest priority item for the next iteration. @lbergelson please review
> disable all broken picard tests

- README.md
There have been requests for some additional clarity on "how
much test coverage is enough" for hellbender tools. Rather than
mandate a particular coverage target, I proposed a more flexible
set of guidelines which I've added to the README in this commit.
> Add test coverage requirements for hellbender tools to README

- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java
- src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/clipping/ReadClipperTestUtils.java
ported BadCigarFilter (in Hellbender filters have positive names, in concordance with Java filter semantics) + tests (added 2 tests to cover 2 more branches, 1 branch seems unreachable).
@vruano  please review
addresses https://github.com/broadinstitute/hellbender/issues/373
> GoodCigarFilter + tests

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
- src/main/java/org/broadinstitute/hellbender/utils/GenomeLoc.java
- src/main/java/org/broadinstitute/hellbender/utils/SimpleInterval.java
- src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollectionTest.java
- src/test/java/org/broadinstitute/hellbender/utils/SimpleIntervalUnitTest.java
Adding validation to the SimpleInterval(String) constructor
Making GenomeLoc implement Locatable
Replacing all instances of SimpleInterval( locatable.getContig(), locatable.getStart(), locatable.getEnd()) with the new constructor
fixes #438  and #436
> Adding SimpleInterval(Locatable) constructor

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalFeatureInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalIntervalArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalReferenceInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalVariantInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReferenceInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredFeatureInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredIntervalArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredReferenceInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/ApplyBQSR.java
- src/main/java/org/broadinstitute/hellbender/tools/ClipReads.java
- src/main/java/org/broadinstitute/hellbender/tools/FixMisencodedBaseQualityReads.java
- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
- src/main/java/org/broadinstitute/hellbender/tools/PrintReads.java
- src/main/java/org/broadinstitute/hellbender/tools/SplitReads.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipeline.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/PrintReadsWithReference.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
- src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollectionTest.java
- src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReadInputArgumentCollectionTest.java
- src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReferenceInputArgumentCollectionTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/CountReadsDataflowIntegrationTest.java
GATKTool now instantiates appropriate argument collections based on the value of requiresReads, requieresReference, and requiresIntervals
these use the standard argument parsing system and show up in help instead of being a special case
Features/variants are still handled specially because they are handled differently
added Optional/Required versions of these and Feature/Variant argument collections
addresses a special case of #149
> improve the handling of GATKTool optionally required arguments

- src/main/java/org/broadinstitute/hellbender/utils/SimpleInterval.java
- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
Adding a new `Utils.nonNull` which is a fluent style assert to throw `IllegalArgumentException` on nulls.
> Removing my abuse of Objects.nonNull()

- src/test/java/org/broadinstitute/hellbender/utils/report/GATKReportUnitTest.java
- testSortingFile.txt
It looks like a test was generating a top level `testSortingFile.txt every time it ran, which accidentally got committed.
I've replaced this with a tmp file.
I took the opportunity to make a few cosmetic improvements to the test file as well.
Fixes #471
> deleted testSortingFile.txt

- .travis.yml
it's not being used for anything at the moment and it's causing problems for external pull requests
> removing the client_secret for dataflow

- src/test/java/org/broadinstitute/hellbender/utils/codecs/table/TableCodecUnitTest.java
This request removes all calls to getChr() in the code by replacing calls to getChr() with calls to getContig() and removing a redundant assertion that contains a call to getChr().
To complete the removal of getChr() from the code, we could:
Remove the getChr() method overrides in the TableFeature and ArtificialTestFeature classes and convert these classes from implementing the Feature interface to implementing the Locatable interface.
Remove the definition of the Feature interface from htsjdk.tribble (since all Feature does is add getChr() to the Locatable interface), and replace all references to the Feature interface in the tools and libraries with references to the Locatable interface.
These steps will also remove the deprecation warnings for getChr() (part of #377).
> #259 - replace calls to getChr() with getContig().

- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
- src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/clipping/ReadClipperUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/CigarUtilsUnitTest.java
tests for CigarUtils + refactored methods in CigarUtils. 
Did not add tests to isValid because pull req #380 is addressing this method.
There's a potential issue in countRefBasesBasedOnCigar - it's not clear why the implementation does what it does. @amilev can you comment on the intended semantics of this method and whether it can/should use `CigarOperator.consumesReferenceBases`?
addresses #153 and #450 
@vruano please review.
> cigar utils tests

- README.md
- build.gradle
gradle uploadArchives will perform a maven release (currently a snapshot release)
Unfortunately the maven plugin has an "install" task which installs to the local repo, so it's now necessary to specify `installApp` or `installDist` instead of just `gradle install`
> Adding maven upload to build.gradle.

- src/main/java/org/broadinstitute/hellbender/tools/recalibration/covariates/ContextCovariate.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/covariates/CycleCovariate.java
- src/test/java/org/broadinstitute/hellbender/tools/recalibration/ContextCovariateUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/recalibration/CycleCovariateUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/recalibration/ReadCovariatesUnitTest.java
I reenabled ReadCovariateUnit tests (disabled in GATK3 because it was failing) and added a bunch of code to make it tests the right thing. A lot of testing problems with reverse-strand reads is fixed now.
fixes #412
> re-enable read covariates unit test

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/ReadsSource.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipeline.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsSourceTest.java
I created a minimal branch to clean up the way we were passing around credentials. We create a GCSOptions class instead of a DataflowPipelineOptions when we create the pipeline and pass in secrets in at the point instead at the ReadSources level. ReadSources now takes a pipeline instead of the secrets file location.
This isn't a long term solution. We should switch the code to get rid of the GenomicsSecret and instead use the more general secret. I think much of the secets factory junk can go away now (they dated from a time when the Dataflow API wasn't built out much.
All tests passed locally. Oddly, I now am sometimes getting a dialog about DSDE needing access to basic information about my Google account, not sure source of the issue (maybe the secret I grabbed?), if it's repeatable, or …
> Da credentials

- .travis.yml
- README.md
- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectBaseDistributionByCycle.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectGcBiasMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectInsertSizeMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/MeanQualityByCycle.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/QualityScoreDistribution.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectRrbsMetrics.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/AnalyzeCovariatesIntegrationTest.java
This allow us to simplify our R installation in Travis.  
R tests now only test Rscript executor
Using standard ubuntu R in travis instead of the more up to date one
Removing installation of R packages as part of gradle and travis builds
Updating readme
> Making plotting with R require an explicit flag

- src/test/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorUprootedUnitTest.java
This is a copy of the BaseRecalibratorUnitTest, changed to run on BaseRecalibratorUprooted. Done to  allay fears that a change to BRU might break its base-recalibration abilities.
> test for BaseRecalibratorUprooted to match BaseRecalibrator

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataFlowSAMFn.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/PTransformSAM.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/ReadsSource.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/SAMSerializableFunction.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipeline.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountBasesDataflowTransform.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/PrintReadsDataflowTransform.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsSourceTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/SAMSerializableFunctionTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipelineTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountBasesTransformUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/PrintReadsTransformUnitTest.java
Passing a `SAMFileHeader` since it's serializable now.  A minor reduction in hacky workarounds.
> changing dataflow SAM classes to pass around a SAMHeader

- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/RecalibrationTablesMerger.java
- src/test/java/org/broadinstitute/hellbender/tools/recalibration/RecalibrationTablesMergerUnitTest.java
This is how the dataflow process merges the intermediate results. Since it's testable independently, I thought I'd check it in as a unit.
> Dataflow merge of RecalibrationTables, and corresponding test

- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/BQSR_Dataflow.java
- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/CalibrationTablesBuilder.java
- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/RecalibrationTablesMerger.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibrationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorUprooted.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/DF_BaseRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/RecalDatum.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/RecalibrationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/RecalibrationTables.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/covariates/ContextCovariate.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/covariates/Covariate.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/covariates/CycleCovariate.java
- src/main/java/org/broadinstitute/hellbender/utils/collections/NestedIntegerArray.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtils.java
- src/test/java/org/broadinstitute/hellbender/dev/CalibrationTablesBuilderIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/DF_BaseRecalibratorIntegrationTest.java
* DF_BaseRecalibrator tool, can be called from the command line. Same syntax as BaseRecalibrator.
* BaseRecalibrator's integration tests ported to this Dataflow version.
* Small changes to make types serializable.
* Note that this pull request is an intermediate step as it only works for local computations.
(this depends on [PR#522](https://github.com/broadinstitute/hellbender/pull/522))
> Dataflow BaseRecalibrator, local only

- src/main/java/org/broadinstitute/hellbender/utils/variant/SkeletonVariant.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/Variant.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/VariantContextVariantAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/VariantUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/VariantContextVariantAdapterTest.java
We need a interface for variants that can be backed by the Google variant as well as VariantContext (from htsjdk). At first, we only need interval and isSNP/isIndel, so that's the interface right now. This shouldn't impact clients much as the interface interface grows because it will initially only be filled by Hellbender code.
> Variants interface, two implementations, and a test

- build.gradle
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorDataflow.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilter.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorDataflowIntegrationTest.java
This version introduces a change that (at least on my machine) fixes the mysterious "happens only on the command line" test failure.
Also uses a newer version of genomics-dataflow because I had to fix a bug there for API_KEY to work in our setting.
Finally, this version also moves the files around so they match the local tree, and changes the environment variables naming scheme to be a little more consistent.
> use API key for testing, fix mysterious cmdline-only bug

- .travis.yml
travis got their act together and enabled at installation of the base R packages in their container build
this removes all uses of sudo so we can make use of the container builds which have faster dispatch
> moving to sudo-less build

- src/main/java/org/broadinstitute/hellbender/utils/test/ReadClipperTestUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReadsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/clipping/ReadClipperUnitTest.java
These take several minutes currently, reducing the number of iterations by an order of magnitude speeds them up and shouldn't greatly impact the effectiveness of the tests.
> reduce number of iterations in SplitNCigarReadsTests

- .travis.yml
travis is now using the gradlew wrapper, which handles this download for us
> removing uncessary gradle download

- build.gradle
- src/main/java/org/broadinstitute/hellbender/CommandLineProgramTest.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/GATKTestPipeline.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/CountBasesDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/CountReadsDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipelineTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/FlagStatDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/PrintReadsDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountBasesTransformUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountReadsTransformUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/FlagStatTransformUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/PrintReadsTransformUnitTest.java
Set the system property 'dataflowRunner' to the simple classname of the
runner you wish to use. E.g.
gradle test -Dtest.single=CountBasesDataflowUnitTest -DdataflowRunner=SparkPipelineRunner
> Allow use of SparkPipelineRunner for dataflow tests.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/ReadsSource.java
- src/main/java/org/broadinstitute/hellbender/utils/SimpleInterval.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsSourceTest.java
- src/test/java/org/broadinstitute/hellbender/utils/dataflow/BucketUtilsTest.java
- src/test/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtilsUnitTest.java
This is achieved by i) using HadoopBAM to read BAM files from HDFS, and
ii) adding a shadowJar target to build app JAR suitable for running with Spark.
Note that this uses Spark's spark-submit script to run on the cluster - this is to avoid including the Spark classes in the hellbender JAR itself, so that it can run on different versions of Spark. We might consider making a runnable JAR at some point in the future though.
I tested this on a standalone cluster (running with Java 8) as follows:
```bash
export SPARK_HOME=~/sw/spark-1.3.1-bin-hadoop2.6/ 
PATH=$PATH:$SPARK_HOME/bin 
$SPARK_HOME/sbin/start-all.sh
export HADOOP_HOME=~/sw/hadoop-2.7.0
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop.pseudo/
export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
(cd $HADOOP_HOME; start-hdfs2)
hadoop …
```
> Allow dataflow command line programs to run on a Hadoop/Spark cluster.

- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/SmallBamWriterTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorDataflowIntegrationTest.java
The help message was wrong when an environment variable was missing. I've changed it so the same string is used to lookup the variable and report it missing so that can't ever be broken again.  This does change it from loading the variables once at startup to loading them every time they are queried.  I assumed that isn't an issue, but I can change it to cache them if someone can see a problem with that.
> fixing #571

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/MarkDuplicatesDataflow.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
updating dataflow and htsjdk to newest versions
adding gradle versions plugin to help with identifying dependencies that need updates
This broke one of our spark related tests so I've excluded it for now.  See #581.  It should be reeneabled when https://github.com/cloudera/spark-dataflow/issues/49 is complete.
> updating dependencies

- src/test/java/org/broadinstitute/hellbender/dev/CalibrationTablesBuilderIntegrationTest.java
`CalibrationTablesBuilderIntegrationTest` was creating a file called `test-table-pre.txt` in the hellbender root directory.
It now creates a temporary file instead.
> stop test from putting file in hellbender root dir

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineParser.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineParserTest.java
This is a new PR for these changes, with @lbergelson's comments addressed.
> Help should print required arguments first.

- .travis.yml
- build.gradle
This fixes the unit tests running on Spark.
> Increase Kyro buffer size for large objects in Spark.

- src/main/java/org/broadinstitute/hellbender/dev/BunnyLog.java
- src/main/java/org/broadinstitute/hellbender/dev/DoFnWLog.java
- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/BaseRecalibratorDataflowUtils.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorDataflow.java
- src/test/java/org/broadinstitute/hellbender/dev/BunnyLogTest.java
This code adds log statements with "START" and "END" keywords so that we can then process the logs and see (i) how many times a specific operation was called, (ii) how long the operation took (per call, or in aggregate).
In addition it has the notion of intermediate "steps" so we can drill down individual operations.
> added logging to help with perf debugging.

- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/BaseRecalibratorDataflowUtils.java
The indent there was sometimes 2 spaces, sometimes 4 spaces. The IDE likes to auto-format things sometimes, causing havoc when we're trying to have nice, simple, small commits.
One solution is to let the IDE format things its way, so then things are consistent and if someone's IDE takes liberties and auto-formats a function then, well, it has no effect because the function's already the way the IDE likes it.
Besides, consistent whitespace makes code easier to read.
> consistent whitespace in BaseRecalibratorDataflowUtils

- circle.yml
This should hopefully fix the out of memory errors on CircleCI, although it's hard to test since they happen kind of randomly.
> limiting gradle memory usage on circle ci

- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorWorker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/ExomeReadCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterUnitTest.java
Questions: I'm not sure how to integrate the count summary and output from these in hellbender. GATK uses a collection of filters, so it can query each filter individually for a count. Hellbender uses a single filter lambda, which represents a sequence of and'd and or'd filters, so the filter itself needs to report all of the counts based on component filter conditions.
> Add support for CountedReadFilters in ReadWalkers.

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
This allows CRAM files to be used in the existing structure. Fixes #606
> Pass reference into SAM Reader for CRAM support

- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorDataflow.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorDataflowIntegrationTest.java
Now that sequence dictionary validation is in, we can re-enable this test,
which was previously failing with a java.lang.OutOfMemoryError due to lack
of upfront validation of the reads vs. reference sequence dictionaries.
> Fix BQSR Dataflow test that was failing due to lack of sequence dictionary validation

- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/BaseRecalOutputSource.java
- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/BaseRecalibratorDataflowUtils.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/AnalyzeCovariates.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineParserTest.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectAlignmentSummaryMetricsTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectInsertSizeMetricsTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectRnaSeqMetricsTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectRrbsMetricsTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/interval/BedToIntervalListTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/AddCommentsToBamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/CleanSamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionaryIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/FastqToSamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/GatherBamFilesIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/MergeBamAlignmentIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/MergeSamFilesIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/RevertSamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/SamFormatConverterIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/SamToFastqIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/vcf/AbstractVcfMergingClpTester.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/vcf/SortVcfTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/vcf/filter/FilterVcfTest.java
- src/test/java/org/broadinstitute/hellbender/utils/text/parsers/TabbedTextFileWithHeaderParserTest.java
Replacing instances of `File.createTempFile` with `BaseTest.createTempFile` since it automatically cleans up it's tmp files and is therefore safer to use.
Deleting now extraneous instances of `deleteOnExit`
I left a usage of `File.createTempFile in IOUtils.writeTempResource because it's some thing used only by the `RscriptExcecutor` and I'm afraid it might continue running Rscripts after the java VM shutsdown and will break if we clean up the temp files while it's running. 
I Left another usage in `IOUtils.createTempDir`.  It's unclear to me if changing the semantics of this method will have any ill effects.  We should investigate further.  I think we should probably move this method to `BaseTest` as well at some point just for symmetry's sake.
Fixes #667
> Replace File.createTempFile with BaseTest's

- .travis.yml
- README.md
Every travis build will upload it's test results to gs://hellbender/test/build_reports/<somepath>
The end of the build log shows the publicly accessible url for the test results.
> Uploading the test results from travis

- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java
Tests that need to access data in a GCS bucket (but not run an actual pipeline)
need a PipelineOptions object containing our API key. This new method makes
it for them.
> Add a method BaseTest.getAuthenticatedPipelineOptions() useful for bucket-based unit tests

- src/main/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsPreprocessingPipelineTestData.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReferenceShardUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/datasources/VariantShardUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/KeyReadsByUUIDUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/RemoveDuplicateReadVariantPairsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/KeyVariantsByReadUnitTest.java
Now, we many Dataflow tests have reads, variants, and reference bases on contig "2" as well as "1". I also added a useful utility DoFn: PrintCollection.
> Adding a second contig to Dataflow tests.

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/coders/PairedEndsCoder.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ReadsPreprocessingPipeline.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/MarkDuplicates.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/MarkDuplicatesDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/MarkDuplicatesUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/PairedEnds.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/ReadsKey.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/ReadsKeyTest.java
I moved Mark duplicates into it's own package (instead of a single file). There is more refactoring that could be done. I might stop here for now and sync with @jean-philippe-martin on his planned changes.
> More refactoring of Mark duplicates and pipeline hookup

- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ReadsPreprocessingPipelineIntegrationTest.java
Just checks that the input and output bams are equal (which is still the
case for a bam with no duplicates). Once BQSR is hooked up we'll have
to update the expected output for this test.
This is intended as a starting point for the more meaningful tests we
eventually want to have.
> Add an initial stub end-to-end integration test for the ReadsPreProcessingPipeline

- build.gradle
- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/BaseRecalOutputSource.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/ApplyWholeBQSRDataflow.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorDataflow.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/coders/GATKReadCoder.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReadsDataflowSource.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/transforms/RefBasesFromAPI.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipeline.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/SmallBamWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/DataflowTestUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/GATKTestPipeline.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsDataflowSourceTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/coders/GATKReadCoderUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/KeyReadsByRefShardUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/PairReadsWithRefBasesUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/RefBasesFromAPIUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/RemoveDuplicateReadVariantPairsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/AddContextDataToReadUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/KeyVariantsByReadUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/SmallBamWriterTest.java
fixes #754
updating spark along side the dataflow jump
also updating other dependencies as well
changing GatkTestPipeline to downgrade a naming error to a warning
replacing calls to setName
replacing calls to setCoder with calls to withCoder when possible
hooking up the validation stringency for local files
fixes #745
disabling failing test and opening #774 to reenable it
> updating the dataflow sdk version

- build.gradle
This upgrades Spark Dataflow to the correct version of Dataflow (Spark Dataflow 0.3.0 targets 0.4.150710). This fixes the runtime exception when running Spark tests due to library mismatches.
> Upgrade to Spark Dataflow 0.4.0, which implements Dataflow 0.4.150727.

- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorDataflow.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/RefAPIMetadata.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/RefWindowFunctions.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/transforms/KeyReadsByRefShard.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/transforms/PairReadWithRefBases.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/transforms/RefBasesFromAPI.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/AddContextDataToRead.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/RefBasesForReads.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ReadsPreprocessingPipeline.java
- src/main/java/org/broadinstitute/hellbender/utils/baq/BAQ.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsPreprocessingPipelineTestData.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/KeyReadsByRefShardUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/PairReadsWithRefBasesUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/RefBasesFromAPIUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/AddContextDataToReadUnitTest.java
-Can now request arbitrary windows of reference bases for each read in AddContextDataToRead
-Wrote a reference window function for BQSR that retrieves for each read exactly the reference
bases required by the BQSR algorithm.
-Comprehensive unit tests
> Allow clients to request additional bases of reference context in AddContextDataToRead by passing in a function

- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/MarkDuplicatesUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/PairedEnds.java
I found all of the cases of .set* on reads and made copies before the mutation so the original wouldn't be changed. I also added comments to the .set*s so we know we've fixed these.
> Adding defensive copies in MarkDuplicates since we mutate the reads.

- build.gradle
This should resolve #650.
This may require a change to the hellbender-protected build to include sonatype snapshots as an available maven repo if it doesn't already.  This is the same issue as #779.
> Force google-http-client-assembly to 1.21.SNAPSHOT

- .travis.yml
- build.gradle
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/RefAPISourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/SmallBamWriterTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/FlagStatDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSRDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorDataflowIntegrationTest.java
@jean-philippe-martin I think this might be a slightly better approach then merging the cloud tests into the main tests.  This just adds another build to the matrix so we have 1 for mandatory cloud tests and 1 for todo cloud tests.  That way we don't dramatically increase the build time by mashing the cloud tests into the main ones.
> make working cloud tests mandatory

- README.md
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/resources/large/.gitattributes
- src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam
- src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam.bai
- src/test/resources/large/dbsnp_138.b37.20.21.vcf
- src/test/resources/large/dbsnp_138.b37.20.21.vcf.idx
- src/test/resources/large/human_g1k_v37.20.21.dict
- src/test/resources/large/human_g1k_v37.20.21.fasta
- src/test/resources/large/human_g1k_v37.20.21.fasta.fai
-Added a "large files" directory to src/test/resoureces containing files managed
by "git lfs" rather than checked directly into the hellbender repository.
Updated setup instructions in README appropriately to reflect new requirement
for git lfs.
-Added a bam with ~600,000 reads from chromosomes 20 and 21, as well as ~50000
unmapped reads.
-Added a snippet of the b37 reference with all of chromosomes 20 and 21.
-Added a DBSNP vcf containing variants overlapping the reads in the bam above.
> Add large files for testing, tracked using git-lfs

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/SmallBamWriter.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/SmallBamWriterTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ApplyBQSRDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/BaseRecalibratorDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/MarkDuplicatesDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ReadsPreprocessingPipelineIntegrationTest.java
for writing BAM files. This reduces memory usage since the reads
don't need to all be stored in memory.
Also add some missing calls to addDataflowRunnerArgs in the integration
tests to ensure the correct dataflow runner is being picked up.
This is related to https://github.com/broadinstitute/hellbender/issues/771, for the Spark/Hadoop side.
> When running on Spark (or writing to HDFS), use the Hadoop-BAM library

- .travis.yml
- build.gradle
after the addition of travis_wait gradle check travis was executing gradle check twice
with ./gradlew and one with gradle.  This was happening because it was being run onces explicitly in the install phase and once implicitly in the script phase
this was causing some strange issues
instead of using travis_wait, I made the dataflow cloud tests output status information as they go
this similarly prevents travis from timing out due to lack of output, but doesn't need the travis_wait
if we add any really long running dataflow tests, or really highly spammy ones we'll have to revisit this
> fixing double running of gradle check

- src/main/java/org/broadinstitute/hellbender/CommandLineProgramTest.java
- src/main/java/org/broadinstitute/hellbender/cmdline/Argument.java
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineParser.java
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineParserTest.java
- src/test/java/org/broadinstitute/hellbender/tools/IntegrationTestSpec.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/BaseRecalibratorDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
Arguments may now define `sensitive`.  Sensitive arguments will be printed as **** instead of as their value.
Removed output of raw command line from IntegrationTestSpec.  The censored command line is output by the command line program itself.
These changes are far from bulletproof.  Sensitive arguments may be leaked stack traces or errors, but it should fix the worst offenders.
> Hiding apiKey from output

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/BaseRecalibratorDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ReadsPreprocessingPipeline.java
- src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/CRAMSupportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java
-Require that the reference dictionary be a superset of the reads dictionary
only when there is at least one CRAM input.
-When determining whether a superset relationship exists, do not take extended
attributes (like the sequence MD5) into account; only consider the contig names
and lengths.
-Do not require common contigs to occur at the same absolute indices across
dictionaries (but do require that they occur in the same relative order).
Contig indices were an issue for GATK3, but since hellbender relies on contig
names for queries we can afford to disable this annoying check. If we later find
that we need to turn it back on, we can easily do so.
-Updated tests appropriately:
-Added test cases showing that extended attributes are ignored when checking
for a superset.
-Added test cases …
> Make sequence dictionary validation a bit less strict

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/programgroups/SparkProgramGroup.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/RefAPISource.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReferenceDataflowSource.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReferenceShard.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/VariantShard.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithRefBases.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariants.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JsonSerializer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/VariantContextVariantAdapter.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsPreprocessingPipelineTestData.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/RemoveDuplicateReadVariantPairsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/AddContextDataToReadUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/KeyVariantsByReadUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithRefBasesSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariantsSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkTestUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSourceUnitTest.java
A few things worth mentioning.
1) This skeleton is mostly a direct port of the existing Dataflow pipeline.
2) I had to modify some test data because there is a (masked) bug in the Dataflow code, see #795.
3) Serialization was a slight pain and I had to bump the kryo version to the latest 2.x, as well as add two custom Serializers. If there's a cleaner way to handle any of that I'm all ears.
4) I'm using Hadoop-bam for reading and writing reads and variants.
5) There are unit tests for all code except for the skeleton itself. I've run it on a cluster on my machine successfully, but haven't written the tests (which will take a little while to design and get right).
> Initial Spark dataflow commit, basic skeleton with some tests.

- .travis.yml
- build.gradle
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithRefBasesSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariantsSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSourceUnitTest.java
The Spark Dataflow tests started failing after the Spark code merge. The problem is that Spark Dataflow uses a shared SparkContext, while the new Spark codes uses a context per test, and there is an odd interaction where calling `stop()` on a context sets its static SparkEnv to null, which then causes the Spark Dataflow shared context to fail.
This fix puts all of the new Spark tests into a `spark` group, so they don't run together. A longer term fix is to have a single shared Spark Context for both Spark and Spark Dataflow. (See discussion here: https://issues.apache.org/jira/browse/SPARK-2243) This will require some changes to Spark Dataflow.
I also removed the Travis `DATAFLOW_RUNNER=SparkPipelineRunner CLOUD=mandatory` combination, which we talked about removing before since it's not …
> Put Spark tests in a 'spark' group so they don't conflict with Spark Dataflow

- build.gradle
There were a couple of things I needed to do to get the new Spark code running on a cluster:
i. Go back to using Spark's version of Kryo.
Using a different version of Kryo is not actually needed (2.21 used by Spark passes the tests), and actually caused errors on the cluster when run with `--conf spark.driver.userClassPathFirst=true` (which is needed to avoid other library conflicts, like with jopt-simple).
ii. Exclude Spark from the JAR file to avoid library conflicts.
It's normal to exclude Spark and Hadoop from JAR files since they are supplied by `spark-submit`. Since Gradle doesn't have a 'provided' dependency (see https://github.com/broadinstitute/hellbender/issues/836), I had to do a bit of a workaround with the `shadowJar` target, which is now `sparkJar`. 
Here's the command I …
> Fixes to run (pure) Spark commands on a cluster

- src/main/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/MarkDuplicatesDataflowTester.java
- src/test/java/org/broadinstitute/hellbender/utils/read/testers/SamFileTester.java
DataflowUtils#getReadsFromLocalBams will return unmapped reads if they have a start position that overlaps an interval, but the Hadoop version will filter them out. This change fixes this inconsistency, and makes the MarkDuplicates dataflow tests use the Spark Dataflow runner if it's specified on the command line (it used to ignore the setting).
The change to the MarkDuplicates test also uncovered another problem where some tests failed with "Mate unmapped flag should not be set for unpaired read". I fixed this by moving from `com.google.cloud.genomics.utils.ReadUtils.makeRead` and `GoogleGenomicsReadToGATKReadAdapter` (which are lossy, and presumably caused the failures) to `SAMRecordToGATKReadAdapter`.
> Make getReadsFromHadoopBam consistent with the local case

- src/main/java/org/broadinstitute/hellbender/utils/collections/IntervalsSkipList.java
- src/test/java/org/broadinstitute/hellbender/utils/collections/IntervalsSkipListTest.java
Holds Locatables (e.g. variants) and offers an efficient "queryOverlapping" operation.
> IntervalSkipList

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithRefBasesSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariantsSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/ReadsPreprocessingPipelineSparkTestData.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java
This improves the serialized size considerably, which has a very big effect on the amount of data going through the shuffle.
* SAMRecordToGATKReadAdapterSerializer uses BAMRecordCodec for a compact serialization format.
* Record headers are not needed since GATKRead is intended to abstract them away. Note that the reference name is serialized separately so it can be preserved.
* ReadsPreprocessingPipelineSparkTestData creates reads with zero UUIDs since they are not used in Spark.
> Add a Spark Kryo serializer for SAMRecords.

- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/MarkDuplicatesUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/ReadsKey.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadCoordinateComparator.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/MarkDuplicatesSparkTester.java
This is based on @davidadamsphd's initial work to port mark duplicates to Spark. It's not finished yet, but I wanted to post this for discussion. In particular 7 of the 56 mark duplicates integration tests are failing with "Cannot get mate information for an unpaired read" - I'm not sure how to address that. I'd appreciate some help on this one.
The code currently has four shuffles: one groupBy in transformFragments (in MarkDuplicatesSparkUtils), two groupBys in transformReads, and one combine (foldByKey) in generateMetrics. The combine is more efficient than the others since it can run on the map side, reducing the amount of data that goes through the shuffle.
I think it may be possible to merge the processing of the fragments and the reads to eliminate a shuffle - so there are only two …
> Mark Duplicates for Spark

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortBamSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/SmallBamWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/BDGAlignmentRecordToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKReadToBDGAlignmentRecordConverter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadsWriteFormat.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
Add support for reading/writing Parquet via ADAM/BDG `AlignmentRecord` type.
Not ready for merge.
> Initial ADAM Parquet I/O support

- src/main/java/org/broadinstitute/hellbender/utils/read/BDGAlignmentRecordToGATKReadAdapter.java
Following up on a comment in #904.
Fixing this is not as important at the moment because the AlignmentRecord type is only being used with Spark.  But this is a precaution so we don't forget about it.
> Remove uuidRandom from BDGAlignmentRecordToGATKReadAdapter

- build.gradle
The ADAM jar was pulling in dependencies that should not be in the sparkJar since they stop it working on a cluster.
> Exclude unnecessary transitive dependencies from ADAM.

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/ReadCovariates.java
wrapping ReadCovariate.keyCache in a ThreadLocal to prevent multithreading issues
changing worker type for dataflow to 4-core
> fixing dataflow/spark bqsr concurrency issues

- src/main/java/org/broadinstitute/hellbender/utils/LoggingUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
Making java.util.logging obey our verbosity setting
setting our logging level to WARN in tests
> reducing log spam

- src/test/resources/large/.gitattributes
- src/test/resources/large/dbsnp_138.b37.1.1-65M.vcf
- src/test/resources/large/dbsnp_138.b37.1.1-65M.vcf.idx
Requires a "git lfs pull" to access. File size is ~230 MB.
> Add a dbsnp 138 vcf snippet with variants from the first 65 mbp of chromosome 1

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/ApplyBQSRSparkFn.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationTables.java
Turns out these may not be needed in spark (unlike in dataflow).
Let's get expert confirmation that this is the case, however,
before merging.
> Remove protective copying operations from the spark BQSR

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSparkIntegrationTest.java
Added handling of interval to count reads.
Additional tests are ported from the dataflow side: CountReadsDataflowIntegrationTest
Note that the semantics of no specifying any -L is to count **all** reads, aligned and unaligned.
> interval handing in count reads + tests

- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/PairedEnds.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/ReadsKey.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/ReadsKeyTest.java
This is not ready to be merged since 4 tests are failing (MarkDuplicatesSparkIntegrationTest#testMarkDuplicatesSparkIntegrationTestLocal).
The thing that is different about these tests is that they have paired reads where the read names differ for the two reads in a pair. So handling these as fragments *after* grouping by read group and name means that the reads are not brought together in the way that they are being in the current version (with the extra shuffle). It's possible there's a fix for this, but I haven't spotted it yet. Extra eyes on this would be welcome.
> Remove one shuffle by processing fragments and paired ends together.

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
This was causing all mapped reads to be discarded.
> Fix for ReadsPipelineSpark: do not invoke MarkDuplicatesSpark.mark() with parallelism == 0

- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
FeatureDataSource was not correctly keeping track of the interval covered
by the contents of its cache, and as a result was producing many more
cache misses than it should have.
> Fix performance bug in the FeatureDataSource caching code

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
These are options that we've found it necessary to use in order to
get hellbender tools to play nice with Spark.
> Bake some commonly-used Spark options into SparkCommandLineProgram

- README.md
Added links to current GATK website + repos to stave off possible confusion as mentioned in #945
> Update README before changing repo name to GATK

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReferenceDataflowSource.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReferenceSource.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/BroadcastJoinReadsWithRefBases.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariants.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JoinStrategy.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/ShuffleJoinReadsWithRefBases.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/DirectFullByteArrayByteAccess.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithRefBasesSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/resources/large/.gitattributes
- src/test/resources/large/human_g1k_v37.20.21.2bit
please review any of @droazen @tomwhite @davidadamsphd
> Add reference broadcasting to BQSR

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/ApplyBQSRSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortBamSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
-Created a new base class for Spark tools, GATKSparkTool, that centrally manages
and validates standard tool inputs (reads, reference, and intervals). This allows
us to enforce consistency across tools, delete duplicated boilerplate code from tools
to load inputs, and perform standard kinds of validation (eg., sequence dictionary
validation) in one place.
-Tools that don't fit into the pattern established by GATKSparkTool can still extend
SparkCommandLineProgram directly.
-This is just a first step -- there is still much work to be done to unify our data source
classes and transparently handle inputs from different sources (GCS, hdfs, files), but
having inputs centrally managed should make the remaining tasks much easier.
> GATKSparkTool: first step towards unifying handling of standard tool inputs in Spark

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
By making JavaSparkContext, we can have functions within a program be called from within map and other parallel functions (JavaSparkContext isn't Serializable). Marking the others as transient gives us a boost in efficiency.
> Remove JavaSparkContext member from GATKSparkTool

- .travis.yml
- build.gradle
Removing the spark dataflow runner build and the cloud_todo_build from travis.
Left in the logic for dealing with the cloud_todo in case we have similar problems in the future.  I can strip it out of if th
> removing irrelevant builds from each travis run

- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
We were having trouble serializing this lambda when using the BROADCAST strategy
in BQSR for reasons we still don't understand. This fixes the issue for now and
enables us to test out BROADCAST.
> Change BQSR_REFERENCE_WINDOW_FUNCTION to use a static class instead of a lambda

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/IntervalWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ProgressMeter.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
- src/main/resources/log4j2.xml
- src/test/java/org/broadinstitute/hellbender/engine/ProgressMeterUnitTest.java
-Prints the current locus, the elapsed time, number of records processed,
and the rate at which records are being processed.
-Hooked up for ReadWalkers, VariantWalkers, and IntervalWalkers
-A new command-line arg in GATKTool allows control over the frequency of
progress meter updates
-Tweaked the log4j output format to create more screen space for logger output.
Resolves #974 (for alpha purposes)
> A basic progress meter for walker-based tools

- README.md
fixing an incorrect option name in the spark documentation in the README
> fixing the CLI option for sparkMaster in README

- build.gradle
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSourceUnitTest.java
Now that ADAM 0.18 has been released.
Fixes #957.
> Re-enable ReferenceTwoBitSourceUnitTest

- src/main/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/BDGAlignmentRecordToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/test/ReadsPreprocessingPipelineTestData.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/MinimalVariant.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/Variant.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/VariantContextVariantAdapter.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/ReadsPreprocessingPipelineSparkTestData.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQualitySumPerAlleleBySampleUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/CoverageUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerAlleleBySampleUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/LikelihoodRankSumTestUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/MappingQualityZeroUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/OxoGReadCountsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/QualByDepthUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandOddsRatioUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/downsampling/AlleleBiasedDownsamplingUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/genotyper/PerReadAlleleLikelihoodMapUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/VariantContextVariantAdapterTest.java
We needed UUIDs for Dataflow, but they are just a hinderance in Spark.
In this PR, I removed every reference to UUID that was related to the original Dataflow code. I also fixed some unit tests that were implicitly depending on the UUIDs to have test reads not equal. The fix was to give the test reads different names.
> Removing UUID from reads and variants

- build.gradle
- src/main/java/org/broadinstitute/hellbender/metrics/MetricsUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectBaseDistributionByCycleSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectQualityYieldMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MeanQualityByCycleSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/QualityScoreDistributionSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/metrics/MetricsUtilsTest.java
- src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsTest.java
change MarkDuplicatesSpark and MarkDuplicatesSparkUtils so that metrics can be written to hdfs:// and gs:// paths.
Fixes #1025 
Fixes #1026
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/gatk/1044)
> allow MD Spark to write metrics to hdfs and gcs

- build.gradle
exclude slf4j-jdk14 backend in order to prevent a runtime warning
fixes #1063
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/gatk/1077)
> fix slf4j multiple bindings on classpath warning

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactoryUnitTest.java
moving settings from SparkCommandLineProgram to SparkContextFactory
the settings that were being applied to SparkContext.getConf were pointless since getConf is a copy of the configuration
instead they're applied to the SparkConfig in SparkContextFactory.getSparkContext
fixes #1096
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/gatk/1097)
> changing where require GATK spark settings are applied

- README.md
updating our git lfs recommendation to a newer version to avoid the problems Geraldine had.
fixes #952
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/gatk/1108)
> updating git-lfs information in readme

- src/main/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
PR #1068 had the unintended side effect of removing the method responsible for
stripping out SAMFileHeaders on Spark. This commit restores that method, and adds
a unit test to verify that all reads emitted by ReadSparkSource are headerless.
> Fix regression in ReadSparkSource: null out SAMFileHeaders when loading reads

- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/transformers/BQSRReadTransformer.java
- src/main/java/org/broadinstitute/hellbender/utils/collections/NestedIntegerArray.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/covariates/ContextCovariate.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/covariates/StandardCovariateList.java
- src/test/java/org/broadinstitute/hellbender/utils/collections/NestedIntegerArrayUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationTablesUnitTest.java
Simple code changes that improve performance of BaseRecalibrator by ~20%. 
NOTE: this is not related to removing indels. That will come later and is expected to improve performance further.
According to my tests, we now beat GATK3 on the infamous first 10Mb of chr1 in CEUTrio.HiSeq.WGS.b37.NA12878.bam
@droazen  can you review? some of those changes are similar to those in #1099
> BaseRecalibrator speedup >20%

- src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
Some questions before this is code reviewed in detail:
1) A number of query methods in GoogleGenomicsReadAdapter adapter
throw if the corresponding field is not present in the underlying read. For some
of these there are guard methods you can call to avoid this (see for example
the changes in ReadUtils.java), but for some of the others I'm not sure how to
usefully query the state without already knowing the answer, ie.:
-isSupplementaryAlignment
-isSecondaryAlignment,
-failsVendorQualityCheck
-isDuplicate
-mateIsReverseStrand
To have fidelity with SAMRecord.getSAMString , we need to be able to query these
(as does ReadUtils.getFlags, which has a similar problem, but I changed that to
use guard methods to prevent throwing). In a couple of cases I had to change
the Read adapter to not …
> Implementation of GATKRead.getSAMString.

- build.gradle
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java
This brings in recently-merged changes related to headerless SAMRecords
that are needed in order to enable the faster SAMRecord serializer
(SAMRecordToGATKReadAdapterSerializer)
Temporarily disabled the SAMRecordToGATKReadAdapterSerializerUnitTest
pending updates in PR #1127.
> Temporarily switch to htsjdk 1.141-6dceff7-SNAPSHOT

- .travis.yml
- build.gradle
set the maximum memory used by the test jvm to 2g
should prevent at least 1 cause of travis from falling over at random (fixes #1113), but since it's intermittent it's hard to tell if it's really fixed or not
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/gatk/1124)
> setting test jvm maximum memory

- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkShardedIntegrationTest.java
To help avoid user confusion.
Resolves #1172
> Rename BaseRecalibratorSparkOptimized to BaseRecalibratorSparkSharded

- src/main/java/htsjdk/samtools/GATKReadSparkCodec.java
- src/main/java/htsjdk/samtools/SAMRecordSparkCodec.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializer.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialReadUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/ReadsPreprocessingPipelineSparkTestData.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java
This change enables SAMRecordToGATKReadAdapterSerializer, which has been in the codebase for a while now, just not explicitly enabled. We've been using it for manual testing and haven't seen any problems with it. All unit tests pass. The performance improvement is striking: running mark duplicates locally went from ~120s to ~36s (https://github.com/broadinstitute/gatk/issues/1047).
In terms of the change this makes, it means that the header is not present on SAMRecord, but since operations on reads go through the GATKRead interface (which does not need the header), the change is safe. Note also that SAMRecordToGATKReadAdapterSerializer explicitly serializes the reference name (and the mate reference name) so that the round trip serialization/deserialization works.
> Use a custom Spark (Kryo) serializer for reads.

- build.gradle
The build is failing since 1.21.0-SNAPSHOT is no longer available in any Maven repositories. It looks like 1.21.0 was released last week: https://repo1.maven.org/maven2/com/google/http-client/google-http-client/, and changing the build to use that version seems to fix the problem.
Related to #650.
> Change google-http-client version from SNAPSHOT now that 1.21.0 is out.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
This it for https://github.com/broadinstitute/gatk/issues/972. By adding `-Dgatk.spark.debug=true` you can run a single Spark test and look at the Spark UI (on http://localhost:4040/) as it runs.
> Allow Spark UI to run during tests by setting the gatk.spark.debug system property

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/PairedEnds.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
fix for 2 remaining tests in https://github.com/broadinstitute/gatk/issues/1042
It introduces (from picard) the RF/FR orientation for pairs for marking optical dups.
> fix for optical dups in spark

- src/test/java/org/broadinstitute/hellbender/tools/SplitReadsIntegrationTest.java
The SplitReads integration tests will fail once we upgrade htsjdk without this.
> Filter out SRA readers in SplitReads tests in prep for htsjdk upgrade.

- build.gradle
The current fatJar gradle task does not properly merge resource files, causing an error when you try to run a Spark tool from the resulting jar. This PR replaces the fatJar task by configuring our shadowJar task to properly merge resource files. I've attempted to share configuration with the sparkJar task, which is also of type ShadowJar. Discussed briefly with @lbergelson.
> Remove fatJar gradle task and replace with a reconfigured shadowJar task

- build.gradle
- src/main/java/htsjdk/samtools/reference/HadoopReferenceSequenceFileFactory.java
This change is dependent on [this recent change](https://github.com/samtools/htsjdk/commit/4f550e1f1afabf21467957fa672ca2a4ad457897#diff-b678735810949d4263df7bd0fffdecb8L42) in htsjdk (and the build will fail without it). Once htsjdk2.0 is available we'll upgrade it  in this branch/pr so the two changes can go in together.
> Upgrade to htsjdk2.0.0 and update HadoopReferenceSequenceFileFactory for nio path changes.

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/GatherBamFiles.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/GatherBamFilesIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/SortSamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/ValidateSamFileIntegrationTest.java
This contains a change to toggle the presorted flag used by GatherBAMFiles, and enables some CRAM tests that were previously broken due to htsjdk bugs. Fixes https://github.com/broadinstitute/gatk/issues/1138 and all but one from https://github.com/broadinstitute/gatk/issues/1141.
> Re-enable htsjdk-dependent CRAM tests.

- build.gradle
- gatk-launch
- settings.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
this is a script which can be used after running gradle installDist to run spark jobs
it can be used identically to ths build/install/bin/gatk script, but has extra features for dealing with spark
running a spark tool and supplying the option --sparkTarget with LOCAL, CLUSTER, or GCS has special behavior
LOCAL will run the tool in the in memory spark runner
CLUSTER along with an appropriate --sparkMaster will run on an accessible spark cluster using spark-submit
arguments to spark-submit may be specified before the arguments to GATK by separating them with a --
GCS will submit jobs to google dataproc using gcloud
common arguments for spark submit will be adapted to match the gcloud formating
this will fail if gcloud isn't installed
if GATK_GCS_STAGING is specified, the jar will be …
> adding gatk-launch script to make it easier to run spark

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
Fixes https://github.com/broadinstitute/gatk/issues/1143.
> Revert htsjdk clearOptions workaround in createVCFWriter.

- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
Since writing a single or sharded output bam is orthogonal to the "parallelism" setting, add a
--shardedOutput arg to MarkDuplicatesSpark and use that to decide whether to write a single or
sharded bam instead of using the value of --parallelism.
Resolves #1335
> Add a --shardedOutput argument to MarkDuplicatesSpark, for consistency with BQSRPipelineSpark and ReadsPipelineSpark

- src/main/java/org/broadinstitute/hellbender/tools/FixMisencodedBaseQualityReads.java
- src/main/java/org/broadinstitute/hellbender/tools/PrintReads.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareBaseQualities.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/RevertBaseQualityScores.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/UnmarkDuplicates.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
fixes #https://github.com/broadinstitute/gatk/issues/1311
> use standard arg names in SelectVariants (and use constants everywhere)

- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
This test case is overkill, since the test just before it in the
DataProvider is sufficient to detect bugs in ReadsSparkSink such
as the one we encountered last week. We also think it is responsible
for the recent intermittent timeouts in travis.
Resolves #1342
> Remove an excessively long-running test case in ReadsSparkSink

- src/main/java/org/broadinstitute/hellbender/CommandLineProgramTest.java
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
This is a temporary and imperfect fix -- the ultimate fix is
https://github.com/broadinstitute/gatk/issues/1347
Resolves #1306
> Rename VERBOSITY argument slightly to avoid collision with -V for variant input

- src/main/java/org/broadinstitute/hellbender/Main.java
fixes https://github.com/broadinstitute/gatk/issues/1301
it turns out `-h` was fine but `--help` was not so I just made it accept `--help`
> add --help as a valid 'command'

- gatk-launch
fixes https://github.com/broadinstitute/gatk/issues/1284
adds these lines output of running `./gatk-lauch` with no arguments
```
gatk-launch --help     #Print the list of available tools
gatk-launch Tool -help #Print help on a particular tool
```
> add help options to gatk-launch

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineParser.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeBamAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/SamToFastq.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/MergeBamAlignmentIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/SamToFastqIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSRIntegrationTest.java
fixes #1300
and a few more cases that got uncovered in MergeBamAlignment and SamToFastq. Added some test to check that arguments are printed twice.
> help mutex fixes

- gatk-launch
- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineArgumentCollectionTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactoryUnitTest.java
using --conf passes args into the spark configuration
these args will take precendence over spark args specified in any other way
moved --sparkMaster and --conf to their own SparkCommandLineArgumentCollection
passing spark options through to gatk with DIRECT, this will only work with --sparkMaster and --conf.
fixes #1339
> adding --conf option to SparkCommandLineProgram

- gatk-launch
gatk-launch will now choose the most recent spark jar if there are multiple
fixes #1316
> gatk-launch chooses the newest spark jar

- README.md
-Delete now-inaccurate note about gatk-launch not supporting multiple spark jars in build/libs
-Clarify usage of gradlew script
> Small post-alpha README fixes

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
@droazen or @davidadamsphd, I think you mentioned you had a problem with CRC files getting out of sync? There's no real need to generate them for local files (they are built-in for HDFS, and don't cause a problem there). This fix should do it.
> Suppress writing CRC files for local filesystem.

- src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/HashedListTargetCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/TargetCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/TargetCollectionUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/TargetsToolsTestUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverageIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/HashedListTargetCollectionUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/TargetCollectionUnitTest.java
Renamed:
* ExomeReadCounts -> CalculateTargetCoverage
* Exome -> Targets or TargetCollection (Only in code related to the old ExomeReadCounts class.)
* Exon  -> Target (Only in code related to the old ExomeReadCounts class.)
Addresses issue #1252
> Renames Exon to Target

- src/main/java/org/broadinstitute/hellbender/transformers/BQSRReadTransformer.java
- src/main/java/org/broadinstitute/hellbender/utils/LRUCache.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/covariates/CovariateKeyCache.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/covariates/ReadCovariates.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/ReadRecalibrationInfoUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReportUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/covariates/ContextCovariateUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/covariates/CycleCovariateUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/covariates/ReadCovariatesUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/covariates/ReadGroupCovariateUnitTest.java
part of https://github.com/broadinstitute/gatk/issues/914
we do need some caching because the new array creation would happen on every read. For non-spark, the caching going to be on the walker level (ie no change because we're 1-threaded), for spark we get 1 cache per partition in baseRecalibration phase but then there is 1 per read in applyBQSRSpark). The latter is going to cause problems - see https://github.com/broadinstitute/gatk/issues/1381
> removing mutable static cache from BQSR

- src/main/java/org/broadinstitute/hellbender/engine/spark/NonChecksumLocalFileSystem.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
I had another go at this. Passes tests and doesn't cause the problem on a cluster that Adam encountered (https://github.com/broadinstitute/gatk/issues/1389).
Fixes #1266.
> Suppress writing CRC files for local filesystem. (Second attempt.)

- src/main/java/org/broadinstitute/hellbender/utils/test/IntegrationTestSpec.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/test/IntegrationTestSpecUnitTest.java
fixes #1164
the problem was that the test spec was incorrect - no placeholders.
I fixed the spec and added a check for specs in general and added a test to show that the check does work.
for @droazen
> checking test spec for correctness

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/engine/GATKToolUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java
Fixes https://github.com/broadinstitute/gatk/issues/611. Uses  "validationStringency" as the argument; PicardCommandLineProgram currently uses "VALIDATION_STRINGENCY"; should we align all of these to use the same name?
I've done the same work for ReadSparkSource and GATKSparkTool but it requires a Hadoop-BAM upgrade so its in a separate PR.
> Command line validation stringency argument for GATKTool.

- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/WellformedReadFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
READLENGTH_EQUALS_CIGARLENGTH was not used at all - I added it to WellFormedFilter.
In GATK3 that check (checking if read length is the same as cigar length) is done in BadCigarFilter but that's a bogus place for it because BadCigarFilter should only for malformed cigars - the problem here is that cigar disagrees with the rest of the read (but it's otherwise a wellformed cigar)
this should close #348
> add READLENGTH_EQUALS_CIGARLENGTH to well formed read filter

- src/main/java/org/broadinstitute/hellbender/utils/baq/BAQ.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
getBaseQualities is expensive because it allocates a new byte array every time
getSoftStart etc are also costly because they create many objects
getCigar creates a new Cigar object every time
all of those clearly show on the profiler when running BaseRecalibrator
this PR lifts these operations out of the loops they're in. 
@lbergelson please review -
> BQSR: improve runtime and memory allocation by lifting a few operations out of loops

- src/main/java/org/broadinstitute/hellbender/engine/FeatureContext.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java
- src/main/java/org/broadinstitute/hellbender/utils/baq/BAQ.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ReadClipper.java
- src/main/java/org/broadinstitute/hellbender/utils/read/AlignmentUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/covariates/QualityScoreCovariate.java
- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
2 commits - one for Cigars and one for bases/quals
@lbergelson please have a look
> BQSR optimization - reduce object churn by not creating as many Cigar objects and less bases/quals

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/MiniClusterUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/metrics/MetricsUtilsTest.java
- src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsTest.java
- fixup for problem with fully specified `file:///` names that I introduced in #1450 
- adding test for fully specified `file:///` url
- adding additional tests to `ReadSparkSink` for HDFS
- tests for writing to HDFS using `MiniDFSCluster`
- tests for overwriting existing HDFS paths
- fixed instance of Wrong FileSystem exception in `ReadSparkSink`
- refactored `ReadSparkSink` to remove duplication
- adding `MiniClusterUtils`
- revising existing code using `MiniDFSCluster` to go through `MiniClusterUtils`
- had to make the minicluster dependency a compile time instead of test dependency so downstream projects can make use of MiniClusterUtils.
> updates to ReadSparkSink

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceWindowFunctions.java
- src/test/java/org/broadinstitute/hellbender/engine/ReferenceMultiSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordSerializerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkTestUtils.java
This PR fixes an exception that was thrown when trying to serialize a ReferenceMultisource object.
I was attempting to broadcast a 2bit reference in a Spark tool and found that I received a serialization error of the form:
...
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: ReferenceWindowFunctions$$Lambda$1/1599771323
Along with some related error reports (https://github.com/npgall/mobility-rpc/issues/12), this allowed me to track this down to the use of a Lambda function in the ReferenceWindowFunctions class. Replacing it with an explicitly defined function class solves the problem.
Added a unit test which used to fail but now passes.
> Fix reference serialization

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/ValidateSamFile.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareBaseQualitiesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadConstants.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/SortSamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUnitTest.java
Requires upgrades to Hadoop-BAM (not yet released) and htsjdk.
Fixes https://github.com/broadinstitute/gatk/issues/1346, https://github.com/broadinstitute/gatk/issues/1261, https://github.com/broadinstitute/gatk/issues/1175, https://github.com/broadinstitute/gatk/issues/1326, https://github.com/broadinstitute/gatk/issues/1259, and much of the underlying code for https://github.com/broadinstitute/gatk/issues/1270, which will be enabled in a separate PR.
> Hadoop-BAM and htsjdk upgrades, Spark tool changes.

- README.md
We found (the hard way) that simple `gradle` sometimes fails (eg when a dotkit is broken) and `gradlew` should be the uniformly recommended way.
@lbergelson please have a look
> Update README.md - recommend gradlew and use in all examples

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSparkIntegrationTest.java
adding tests for NPR when there's no output specified
this effects CountBasesSpark, CountReadsSpark, FlagStatSpark, and CountVariantsSpark
fixes #1523
fixing an error in CountVariantsSpark where the vcf input was optional
adding some convinience functions to ArgumentsBuilder
> fixing nprs in spark tools where no output file was specified

- src/main/java/org/broadinstitute/hellbender/engine/spark/SAMRecordSerializer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/ReorderSam.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/ReplaceSamHeader.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/mergealignment/AbstractAlignmentMerger.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MeanQualityByCycleSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/HeaderlessSAMRecordCoordinateComparatorUnitTest.java
Use setHeaderStrict, which validates the record's reference and mate reference against the new header. Requires disabling the ADAM test in MeanQualityByCycleSparkIntegrationTest due to  https://github.com/broadinstitute/gatk/issues/1540.
> Switch to SAMRecord setHeaderStrict.

- gatk-launch
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
removing spark.executor.userClassPathFirst=true seems to fix the problems encountered when running using spark-submit and sparkMaster local
this fixes #1315 and also fixes #1386
Removing it doesn't seem to cause any problems when running under yarn on the cluster.  I tested with a reasonable size file using the ReadSparkPipeline so that should cover most of our bases.
I'm not certain why we added spark.executor.userClassPathFirst=true in the first place.  I assumed it was necessary, like spark.driver.userClassPathFirst=true is.  
It seems plausible that it was only added for symmetry and it was never actually needed in the first place.
> fixing spark-submit not running with local[*]

- src/main/java/org/broadinstitute/hellbender/utils/test/SamAssertionUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
Fixes https://github.com/broadinstitute/gatk/issues/1087 now that https://github.com/samtools/htsjdk/pull/487/files is in.
> Use non-lenient comparison for CRAM.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineParser.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineParserTest.java
- src/test/java/org/broadinstitute/hellbender/tools/SplitNCigarReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/FilterReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/VariantsToTableIntegrationTest.java
previously CommandLineParser would accept non-ambiguous abbreviations for longopts
this caused issues where -v would have different meanings in different tools
I patched joptSimple to add an option to disallow abbreviations, and updated to 5.0-beta-1 which incorporates the necessary changes.
fixes #1347
> stop CommandLineParser from recognizing abbreviations

- README.md
- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
Switch to using async IO by default. It's an out-of-the-box win for almost everybody because almost everyone has more than 1 CPU. Difference is write speed is at least 20%.  
Also added a line to the output that indicates what IO we're using (a'la deflater)
On single processors it is slower than syncIO, so you can turn it off by running like this:
```
JAVA_OPTS="-Dsamjdk.use_async_io=false" ./gatk-launch PrintReads .....
```
@lbergelson can you review and test?
> use async IO by default

- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
One of the non-cloud tests in BQSRSparkIntegrationTest tries to use the API key when its not required; as a result the test fails when the key isn't set even though it should pass. Introduced in the test refactoring that was part of https://github.com/broadinstitute/gatk/pull/1533.
> Fix test in BQSRSparkIntegrationTest.

- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java
- src/test/java/org/broadinstitute/hellbender/utils/pairhmm/VectorPairHMMUnitTest.java
Fixing an issue where AVX tests would fail if AVX was supported by the computer but the library hadn't been built for some reason.  
Fixes #1575
> fixing test failures when AVX is supported but the library doesn't exist

- README.md
- src/main/java/org/broadinstitute/hellbender/Main.java
setting property GATK_STACKTRACE_ON_USER_EXCEPTION=true will cause UserExceptions to emit stacktraces
the default behavior is to hide the stacktrace on a user exception
> adding an option for stacktraces on UserExceptions

- build.gradle
fixes #1585 - getting IntelDeflater from htsjdk zipfile (it's not part of the jar!) and then putting the path to it as a default JVM argument.
@lbergelson can you review? this is a bit of a hack, improvements welcome
Do check that, out of the box (on linux) you get the IntelDeflater. I run this:
```
./gradlew clean installDist
./gatk-launch CountReads -I src/test/resources/large/NA12878.RNAseq.bam
```
and check output for `IntelDeflater`
> Use IntelDeflater (libIntelDeflater.so) by default

- scripts/install_git_lfs.sh
his version includes a fix for the issue we were seeing which required multiple pulls
removed the workaround (fixes #1404)
The problem was that we were using an ssh git remote.  git-lfs fails in this case because it can't authenticate.  (unclear to me if this is a bug or not, I don't know if github requires authentication for ssh access to public repos).  In versions <= 1.1.0 git-lfs was falling back to trying over an http connection.  They removed this fallback mechanism in 1.1.1.  See github/git-lfs#1090 for discussion.
> updating git-lfs on travis to v1.1.2

- gatk-launch
gatk-launch wasn't exiting with the same exit code that GATK did
this causes problems for testing infrastructure that expects non-zero exit codes from failures
fixes #1599
> propagating exit codes from GATK through gatk-launch

- .travis.yml
travis support recommended that we move to travis with sudo since the capacity problems have been fixed
the travis nodes with sudo are more powerful now and there shouldn't be long startup delays like there used to be
also moving to the newer ubuntu image
> moving to sudo enabled travis

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/KBestHaplotypeFinder.java
- src/main/java/org/broadinstitute/hellbender/utils/collections/CountSet.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2178 - Short-circuit logic should be used in boolean contexts
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2178
M-Ezzat
> squid:S2178 - Short-circuit logic should be used in boolean contexts

- build.gradle
all JVM args should be on 1 line to not get lost
> build script: all JVM args should be on 1 line to not get lost

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/markduplicates/EstimateLibraryComplexity.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/TargetCollectionUnitTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2184 - Math operands should be cast before assignment
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2184
M-Ezzat
> squid:S2184 - Math operands should be cast before assignment

- src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureSupportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
> Bug fix: do not interpret contigs with periods in their names as files in the interval parsing system

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/Kmer.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/KmerUnitTest.java
came up in recent profiling - hashCode computation on KMer was very inefficient and wasteful in String creation 
> fix inefficient hashcode computation and added tests to 100%

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/Path.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/PathUnitTest.java
This came up during profiling - containsVertex was creating full lists for vertices all the time only to check membership. Using a scan now (no caching but that's possible too if needed later)
Tests for Path at 100% now.
> check containsVertex faster and added tests to 100%

- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareBaseQualitiesSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/validation/CompareBaseQualitiesSparkIntegrationTest.java
Fixes https://github.com/broadinstitute/gatk/issues/1321. Also added some CRAM tests. I started to fix https://github.com/broadinstitute/gatk/issues/1593 as part of this but there are several code paths that need to change so I'll do a separate PR.
> Fix CompareBaseQualitiesSpark reference handling.

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/tools/ApplyBQSRUniqueArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/ApplyBQSRSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/AnalyzeCovariates.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSR.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationArgumentCollection.java
making constants BQSR_TABLE_LONG_NAME and BQSR_TABLE_SHORT_NAME in StandardArgumentDefinitions
fixing outdated references to -BQSR -> -bqsr in documentation and error messages
fixes #1631
> making BQSR table input parameter names constants

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
Came in in profiling - findNumberOfRepetitions was creating lots of byte arrays that were discarded right away after comparing of a small range. This PR makes the comparison work on arrays directly.
@lbergelson can you have a look?
> findNumberOfRepetitions makes fewer useless arrays

- build.gradle
Our launch script gatk-launch now uses a bunch of system properties for things like compression, async reading, deflater. Our testing infrastructure must use the same settings.
for @lbergelson
> tests must use same JVM system properties as gatk-launch

- README.md
delete asyncO from README until tribble is fixed
@lbergelson, we're not doing async now so let's excise it from readme.
> delete asyncO from README until tribble is fixed

- gatk-launch
dataproc is no longer beta, so this is not needed anymore
> removing beta from our gcloud dataproc script

- src/main/java/org/broadinstitute/hellbender/utils/baq/BAQ.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationArgumentCollection.java
this PR adds a hidden option to skip BAQ. This is used in the ongoing investigation of BAQ removal in https://github.com/broadinstitute/gatk/issues/1557
@droazen have a look. I could add a test but the recal table would need to be taken on faith.
> remove BAQ - provide an option to skip BAQ

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/BaseGraph.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/LowWeightChainPruner.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
All comments are now consistent with actual behavior in `LowWeightChainPruner`.  No actual code was changed except for which parts of the graph are given dotted lines in the debugging output.  This change,  from `<=` to `<` is also to make everything consistent with `LowWeightChainPruner`.
> fixed comments about low weight pruning

- build.gradle
previously avx code was sometimes included if installDist had been run prior to running sparkJar, now sparkJar will always contain the native code
fixes #1576
also changing download of inteldeflator.so to only happen if it doesn't exist already
> packaging avx code during spark and shadowJar

- README.md
- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
fixes #1653
ok, results are in, with asyncIO GATK4 out of the box beats GATK3 4.53x on PrintReads and 1.48x on BaseRecalibrator!
PrintReads
syncTribble, asyncSamtools, IntelDeflater: 1x baseline (this is the out-of-the box GATK4 config)
syncTribble,  syncSamtools, IntelDeflater:  1.32x baseline
syncTribble, asyncSamtools, JDKDeflater: 1.68x baseline 
syncTribble,  syncSamtools, JDKDeflater:  2.32x baseline
For comparison, GATK3 out of the box is 4.53x baseline on PrintReads
BaseRecalibrator
syncTribble, asyncSamtools, IntelDeflater: 1x baseline (this is the out-of-the box GATK4 config)
syncTribble,  syncSamtools, IntelDeflater:  1x baseline
asyncTribble, asyncSamtools, IntelDeflater:  2.14x baseline
syncTribble, asyncSamtools, JDKDeflater: 1.04x baseline
syncTribble,  syncSamtools, …
> asynch IO back on

- build.gradle
also updating build to extract the intelDeflater from the jar instead of downloading it
removed the htsjdkVersion property I had recently added since it was no longer necessary with the update to include the .so in the jar
> updating htsjdk to current snapshop for asynch fix

- build.gradle
Also added a check that extractIntelDeflator extracts exactly 1 file.  It will kill the build if it's missing.
> bump to newer htsjdk snapshot and fix spelling of libIntelDeflater.so

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/AbstractMarkDuplicatesCommandLineProgram.java
This was debugged while testing https://github.com/samtools/htsjdk/pull/576. Readers allocated in `AbstractMarkDuplicatesCommandLineProgram.openInputs` were never closed. In the asyncIO realm (if we switch to async reading) this is a big problem because one worker thread is then created and abandoned (it keeps living after its master is long gone - unless the master is closed which will inform the worker to finish).
The diffs are much more trivial than it looks in github gui - essentially 2 things were put in try-with-resources (two lines like this) and lot of white-space shifting followed.
`final SamHeaderAndIterator headerAndIterator = openInputs();`
> fix resource leaks in MarkDuplicates

- gatk-launch
This makes gatk-launch work with gatk-protected.  It doesn't work without these changes since the folder names it's looking of are different.  Now it looks up the project name from the settings.gradle and uses that to construct the path to the launch script.
> updating gatk-launch to be compatible with gatk-protected

- .travis.yml
- build.gradle
Before this change you can run tests only once before gradle decides that the task is "UP-TO-DATE". I want to be able to rerun tests multiple times (bonus: guess what I'm testing) and so this caching got in the way. With this change, tasks are always rerunnable.
Test it by running this twice:
```
./gradlew test --tests *VariantFiltrationIntegrationTest*
```
> Update build.gradle to make sure that tests are always rerunable.

- gatk-launch
fixes https://github.com/broadinstitute/gatk/issues/1702
Speed up in writing - from 3.1 minutes down to 2.4 minutes in MarkDuplicatesSpark
> using IntelDeflater and igzip on Spark

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
registering PairedEnds for Kryo. The reason is that Kryo serializes each object graph separately (for us, ther's a object graph for reach read pair, so there're billions of them). Now, for unregistered classes, the first encounter of such a class means that Kryo must serialize the class's full name (it uses an ID for subsequent uses of this class in the same object graph). For us, that means that the string "org.broadinstitute.hellbender.utils.read.markduplicates.PairedEnds" gets serialized billions of times. If this class is registered, then it's always referred to by ID not by name. This PR does not change the serializer used, just forces Kryo to always refer to this type by ID.
It saves ~2% of shuffle volume (99.7 GB vs 97.9 GB) and saves some time: 7.2 mins vs 7.4 mins on …
> Add PairedEnds to GATKRegistrator for Kryo

- build.gradle
https://issues.apache.org/jira/browse/COLLECTIONS-580
credit goes to @gmlewis  who alerted us on https://github.com/broadgsa/gatk/pull/17. Thanks Glenn
@lbergelson any objections?
> update to 4.1 - apache collections 4.0 had a serialization exploit 

- .travis.yml
- build.gradle
- src/test/java/org/broadinstitute/hellbender/IntelDeflaterIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/IntelDeflaterTest.java
the first commit adds a test, which should fail
the second should fix the test.  It's currently failing though, so I'm not sure what's happening yet.  It works on gsa5.
> fix lib intel deflater extraction

- src/main/java/org/broadinstitute/hellbender/engine/ContextShard.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkOptimized.java
- src/main/java/org/broadinstitute/hellbender/utils/collections/IntervalsSkipList.java
- src/main/java/org/broadinstitute/hellbender/utils/collections/IntervalsSkipListOneContig.java
- src/test/java/org/broadinstitute/hellbender/utils/collections/IntervalsSkipListOneContigUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/collections/IntervalsSkipListUnitTest.java
there was some not nice code in IntervalsSkipList (using Hashtables (sic! we had Hashtables in 2016), declaring things as ArrayList, verbose comparators etc). This is a small cleanup
> small cleanup in IntervalsSkipList and friends

- src/main/java/org/broadinstitute/hellbender/utils/activityprofile/ActivityProfileState.java
Turns out that the BandPassActivityProfile can generate probabilities
that slightly exceed 1.0 when moving probability mass around. We should
eventually cap at 1.0, but first we must evaluate the effect of such a
cap on the HaplotypeCaller
> Remove the range check in ActivityProfileState.setIsActiveProb()

- src/main/cpp/VectorLoglessPairHMM/org_broadinstitute_hellbender_utils_pairhmm_VectorLoglessPairHMM.cc
this solves a nasty precision issue in the HaplotypeCaller integration tests where tests would pass or fail depending on the order in which they ran!
> set FTZ always on jniComputeLikelihoods

- src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
our tests used to fail when run a root (because root can create files that others can't etc). This is a fix for it. Tested on a docker vm running gatk as root.
> make tests run as root

- src/test/resources/large/.gitattributes
- src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram
- src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram.bai
- src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram.crai
adding cram version of our main test bam
@lbergelson, ok?
> add cram to testresources

- scripts/build_pair_hmm_so_in_clean_repo.sh
- scripts/upload_artifact_with_both_lib_and_dylib.sh
adding a pair of scripts to help build both the dylib and so into a single jar, and then upload that jar to sonatype
these can only be run at broad
they should be temporary and removed / exported to a new repot when we resolve the native code question
> helper scripts to build jar with .dylib and .so

- gatk-launch
- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
fixes #1784  and #1780  which both caused problems with the intel deflater
note: this incorporates the changes in https://github.com/broadinstitute/gatk/pull/1717 because without them it fails with
```
java.lang.UnsupportedOperationException: Directory size listing not supported on GCS.
at org.broadinstitute.hellbender.utils.gcs.BucketUtils.dirSize(BucketUtils.java:301)
at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.getRecommendedNumReducers(GATKSparkTool.java:255)
at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:237)
at org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark.runTool(PrintReadsSpark.java:35)
at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:313)
at …
```
> fix intel deflater on dataproc

- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SWPairwiseAlignment.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/smithwaterman/SWPairwiseAlignmentUnitTest.java
#1629 @akiezun @droazen @lbergelson
Added a substring search to `SWPairwiseAlignment.align `to avoid running the full Smith-Waterman when the query is found in the reference without any indels. The performance benefit of this code will be data dependent. In the current HaplotypeCaller test, >80% of the Smith-Waterman calls are filtered by the substring search.
Added tests to cover all of the overhang strategies.
**Note:** The substring search only works for the `SOFTCLIP `and `IGNORE `overhang strategies. The `INDEL `and `LEADING_INDEL `can result in more complicated CIGAR strings. See the `SWPairwiseAlignmentUnitTest.testSubstringMatchIndelLong` and `SWPairwiseAlignmentUnitTest.testSubstringMatchLeadingIndelLong` tests for examples.
> add substring search to smith-waterman and new tests

- src/main/java/org/broadinstitute/hellbender/utils/pileup/PileupElement.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
PileupElement: save memory and time by accessing bases and quals directly without copying. Showed up on profile in HC
> PileupElement : save memory and time by accessing bases and quals directly without copying. 

- src/main/java/org/broadinstitute/hellbender/engine/AlignmentContext.java
- src/test/java/org/broadinstitute/hellbender/engine/AlignmentContextUnitTest.java
`AlignmentContext.splitContextBySampleName` should be a no-op if we assume that there's 1 sample. Saves a few percent of HC. Requires a change to HaplotypeCaller to take advantage of this.
```
diff --git a/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java b/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
index 97fe54a..c2f58d9 100644
--- a/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
+++ b/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
@@ -440,7 +440,14 @@ public final class HaplotypeCallerEngine implements AssemblyRegionEvaluator {
final int ploidy = …
```
> save time if assuming 1 sample

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/main/java/org/broadinstitute/hellbender/utils/NativeUtils.java
- src/test/java/org/broadinstitute/hellbender/IntelDeflaterIntegrationTest.java
1. User can define the number of Spark cores in gradle test by environmental variable GATK_TEST_SPARK_CORES. If the variable is not defined, or the value is bogus, will fall back to default of "local[\*]"
2. Skip intelDeflator test on PPC platforms.
> user-specified spark core num; disable intelDeflator testing on PPC

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/ClipReads.java
- src/main/java/org/broadinstitute/hellbender/tools/FixMisencodedBaseQualityReads.java
- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
- src/main/java/org/broadinstitute/hellbender/tools/PrintReads.java
- src/main/java/org/broadinstitute/hellbender/tools/SplitReads.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleIntervalWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithReference.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleVariantWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/RevertBaseQualityScores.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/UnmarkDuplicates.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSR.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
fixes https://github.com/broadinstitute/gatk/issues/1741 by closing the writer regardless of success. Added an `onTraversalDone` template method to `GATKTool` to take care of this. Otherwise we'll always leak resources on exceptions.
> close all resources regardless of success

- build.gradle
- src/main/cpp/VectorLoglessPairHMM/common_data_structure.h
- src/main/cpp/VectorLoglessPairHMM/org_broadinstitute_hellbender_utils_pairhmm_VectorLoglessPairHMM.cc
- src/main/cpp/VectorLoglessPairHMM/utils.cc
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java
Changes to enable multi-threaded native AVX PairHMM using OpenMP. Also includes a performance improvement in the native C++ `Context` class.
`VectorLoglessPairHMM.java` is hardcoded to set the maximum number of PairHMM threads (`maxNumberOfThreads`) to 100. This is the maximum number of threads **allowed** by GATK, not the number of threads **requested**. C code in the native library will query OpenMP for the number of threads available on the platform, and use min(OpenMP threads available, `maxNumberOfThreads`) threads.
**Measured Speedup**
Command
```
./gatk-launch HaplotypeCaller -R src/test/resources/large/human_g1k_v37.20.21.fasta -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O out.g.vcf -ERC GVCF
```
1 thread
INFO  PairHMM - Total compute time in PairHMM …
> Enable multi-threaded AVX PairHMM

- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
- src/main/java/org/broadinstitute/hellbender/tools/SplitNCigarReads.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ReadClipper.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/PileupElement.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/MergeBamAlignmentIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/AlignmentStateMachineUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LIBS_position.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/PileupElementUnitTest.java
addresses #1797 
some small speedup and less object allocation when using BAMs
> use getCigarLength() rather than getCigar().numCigarElements() 

- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationArgumentCollection.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkShardedIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BothStepsOfBQSRIntegrationTest.java
I want to skip indels by default in BQSR. We know if does not affect results but it's faster and we want speed out of the box.
> no indel tables in BQSR tables by default

- build.gradle
- src/main/cpp/VectorLoglessPairHMM/common_data_structure.h
- src/main/cpp/VectorLoglessPairHMM/org_broadinstitute_hellbender_utils_pairhmm_VectorLoglessPairHMM.cc
- src/main/cpp/VectorLoglessPairHMM/utils.cc
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java
Reverts broadinstitute/gatk#1813 for now.
We have to revert this because there's no fallback to lack of OMP or incompatible libraries:  https://github.com/broadinstitute/gatk/issues/1819
What happens then is that we build the so file on a one machine and the protected repo uses a different machine and blows up with ```java.lang.UnsatisfiedLinkError: /tmp/libVectorLoglessPairHMM.4842381956752440752.so: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /tmp/libVectorLoglessPairHMM.4842381956752440752.so)```
> Revert "Enable multi-threaded AVX PairHMM"

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
saves memory in time in HaplotypeCaller - the protected part of this PR coming next (such a pain with 2 repos). The actual savings will come from the protected part because it'll be able to pass in a big array and have this method operate on subarrays (thus saving memory and time)
> GATKVariantContextUtils.findNumberOfRepetitions operate on sub arrays 

- build.gradle
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
@tomwhite can you review? We have CHD 5.7 running now and 1.6 is available on the cloud so no reason to not upgrade AFAIK
For some reason, the lists returned from `.collect` are no longer mutable so i have to make copies in 1 test
> upgrade spark to 1.6.1 and a few more upgrades

- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSparkIntegrationTest.java
fixes #1506 : re-enable test for blocked vcfs on spark
@tomwhite can you have a look?
> re-enable test for blocked vcfs on spark

- src/main/java/org/broadinstitute/hellbender/utils/pileup/PileupElement.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/ReadPileup.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/PileupElementUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/ReadPileupUnitTest.java
those came up clearly on HaplotypeCaller profiles and allocated many megabytes of objects for now reason
> faster PileupElement.isBefore and isAfter queries with no linked list allocation.

- src/main/java/org/broadinstitute/hellbender/utils/test/SparkTestUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/ReferenceMultiSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordSerializerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java
SparkTestUtils contains a useful method that tests whether a class is
serializable/deserializable in Kryo. This method is needed by the
gatk-protected test suite, but is not currently packaged in the gatk-public
jar. Moving to utils/test so that it will be packaged.
> Move SparkTestUtils to utils/test so that gatk-protected can use it

- build.gradle
- scripts/publish_jbwa.gradle
- src/main/java/org/broadinstitute/hellbender/utils/NativeUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java
- src/test/java/org/broadinstitute/hellbender/IntelDeflaterIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/JBWAIntegrationTest.java
-Published a jbwa snapshot to the Broad artifactory, which we now depend on
via gradle. This snapshot contains builds of the native jbwa code for both
Mac and Linux.
-Added utility methods to NativeUtils to load this library at runtime,
and a test proving that it can be loaded successfully. Also switched
to the new NativeUtils methods for loading the PairHMM, and confirmed
that it loads successfully with the HaplotypeCaller in protected
-Included a gradle script to publish a new jbwa snapshot, should it
become necessary, along with instructions on how to do so.
Resolves #1838
> Add dependency on jbwa snapshot, script to release future jbwa snapshots, and method to load the library at runtime

- gatk-launch
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
improvement proposed by folks at Intel - in my tests it improves performance of MarkDuplicatesSpark by >10% 
@gspowley can you review and/or ask Eric+Lucy ?
> use snappy and 512k blocks

- build.gradle
these are moved over from protected to public. Without them, even count reads does not work after we added mllib.
> moved dependency fixes from protected to here

- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByState.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateBaseTest.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateUnitTest.java
In #1774 I added to LIBS the possibility to keep reads with Ns. This is a simple commit to allow `LocusWalker` implementations to use this behaviour (switch off by default).
> LocusWalker with the possibility of include reads with Ns

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/ExternalCommandlineProgramModule.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/RunBWAMEMViaCommandLine.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/RunSGAViaProcessBuilderOnSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/RunSGAViaProcessBuilderOnSparkUnitTest.java
This affects `RunBWAMEMViaCommandLine.java` and `RunSGAViaProcessBuilderOnSpark.java`, where stdio are always captured.
Capturing BWA MEM's stdout is a must because the result is piped to stdout.
For SGA, this helps debugging. But this also slows down the performance.
Hence an option would be useful.
> Provide option for not capturing stdio of programs launched via ProcessBuilder

- src/main/java/org/broadinstitute/hellbender/utils/pileup/PileupElement.java
- src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
reduced memory consumption: identified by profiling HC. 
+ added a bunch of tests while I was there.
note: the equals/hashcode changes are just for clean code - no perf improvements
@lbergelson can you have a look?
> less memory allocation in GATKRead operations

- src/main/java/org/broadinstitute/hellbender/tools/SplitNCigarReads.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
- src/test/java/org/broadinstitute/hellbender/tools/SplitNCigarReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManagerUnitTest.java
- src/test/resources/large/.gitattributes
- src/test/resources/large/K-562.duplicateMarked.chr20.bai
- src/test/resources/large/K-562.duplicateMarked.chr20.bam
- src/test/resources/large/expected.K-562.splitNCigarReads.chr20.bam
which is used by SplitNCigarReads.
> Fixes null pointer exception in OverhangFixingManger

- src/main/java/org/broadinstitute/hellbender/engine/ReadContextData.java
- src/main/java/org/broadinstitute/hellbender/utils/genotyper/PerReadAlleleLikelihoodMap.java
This pull request is focused on resolving occurrences of Sonar rule pmd:InefficientStringBuffering - Inefficient String Buffering
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:InefficientStringBuffering
M-Ezzat
> pmd:InefficientStringBuffering - Inefficient String Buffering

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/markduplicates/EstimateLibraryComplexity.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java
- src/main/java/org/broadinstitute/hellbender/utils/read/mergealignment/BestEndMapqPrimaryAlignmentStrategy.java
- src/main/java/org/broadinstitute/hellbender/utils/read/mergealignment/HitsForInsert.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2063 - Comparators should be "Serializable"
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2063
M-Ezzat
> squid:S2063 - Comparators should be Serializable

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/BuildBamIndex.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/FastqToSam.java
This pull request is focused on resolving occurrences of Sonar rule pmd:UseIndexOfChar - Use Index Of Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseIndexOfChar
M-Ezzat
> Cleanup - pmd:UseIndexOfChar - Use Index Of Char

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSparkIntegrationTest.java
- src/test/resources/large/dbsnp_138.b37.20.21.vcf.blockgz.gz
- src/test/resources/large/dbsnp_138.b37.20.21.vcf.blockgz.gz.tbi
Fixes #1651.
Thanks to @droazen for suggesting the use of `-R` as a source for the sequence dictionary.
> Enable query-by-interval of VCFs (including blockgzipped VCFs) on Spark.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculators.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/Haplotype.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculatorsUnitTest.java
Most changes are trivial, except `computeMaxAcceptableAlleleCount `, which is exactly the same code as in the GATK3 fix.
The part that's missing is changes made to `HaplotypeCallerGenotyingEngine`, which is in GATK-protected, which in turn depends on these classes in GATK. So these changes have to go in first.
> Porting same fix from GATK3 for issue 1357

- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
https://github.com/broadinstitute/gatk/issues/1673 was fixed with the htsjdk update; this re-enables the test.
> Enable previously broken and disabled CRAM index query test.

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
such as hdfs://local/print_reads.sorted.bam (double slash) instead of
hdfs:///local/print_reads.sorted.bam (triple slash).
Fixes #1257
> Throw a UserException when an HDFS URI has an unknown host,

- build.gradle
- gatk-launch
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
fixes https://github.com/broadinstitute/gatk/issues/1903
also updated the system properties in build.gradle and gatk-launch
> use IntelDeflaterFactory from the GKL

- src/test/java/org/broadinstitute/hellbender/utils/pileup/PileupElementUnitTest.java
PileupElementUnitTest.testBadOffsetWithinBounds was being skipped because the data provider name was wrong.
> PileupElementUnitTest no longer skipping a test

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculators.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/IndependentSampleGenotypesModel.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/GeneralPloidyExactAFCalculator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/IndependentAllelesDiploidExactAFCalculator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/ReferenceDiploidExactAFCalculator.java
- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculatorUnitTest.java
part of work tracked here https://github.com/broadinstitute/gatk/issues/1608
@lbergelson please review. The corresponding protected branch is https://github.com/broadinstitute/gatk-protected/tree/ak_ggvcf_performance
> performance optimizations for GenotypeGVCFs

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureInput.java
- src/main/java/org/broadinstitute/hellbender/engine/TaggedInputFileArgument.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleVariantWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSpark.java
- src/test/java/org/broadinstitute/hellbender/cmdline/TestProgramGroup.java
- src/test/java/org/broadinstitute/hellbender/engine/TaggedInputFileArgumentUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithVariantsIntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/examples/expected_ExampleReadWalkerWithVariantsIntegrationTest_output.txt
this enables users to give symbolic names to input files (read files). Essentially expands the functionality we had for feature files to read files. This functionality exists in gatk3 and is used for example in ContEst and M2 (in gatk3 you specify -I:tumor file1.bam -I:normal file2.bam, in gatk4 you specify -I tumor:file1.bam -I normal:file2.bam).
> symbolic names for sources of reads

- .travis.yml
this aims to fix https://github.com/broadinstitute/gatk/issues/1993
@lbergelson can you look at it?
the command i see on travis now is 
```
git clone --depth=9999999 --branch=ak_deep_clone https://github.com/broadinstitute/gatk.git
```
(the `depth` option is documented [here](https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth))
> clone deep to fix continuous snapshots

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISource.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
We got an email complaining that we were the only users in the world still using the beta API.
This updates to the most recent version, they changed the api from `List<String> -> List<Object>`, but the documentation still says it has to be a `String`, so I've just added some explicit casts.  
Fix for #2009
> updating google-api-services-genomics off of the beta api

- build.gradle
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReadsIntegrationTest.java
adding snappy.disable=true to prevent htsjdk from using snappy
this is a temporary solution for #2026 until we can patch htsjdk to fix incompatibilities with more modern snappy
fixes #2026
> disabling htsjdk snappy

- build.gradle
no reason to depend on spark when we depend on spark ML lib anyway. Simpler to update 1 dependency than two
@lbergelson wdyt?
> remove direct spark dependency and use ML lib

- src/main/java/org/broadinstitute/hellbender/metrics/MultiLevelMetrics.java
- src/main/java/org/broadinstitute/hellbender/metrics/PerUnitInsertSizeMetricsCollector.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/AlignmentSummaryMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/HsMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/RnaSeqMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/RrbsCpgDetailMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/RrbsSummaryMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetedPcrMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectInsertSizeMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectQualityYieldMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/InsertSizeMetricsCollectorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MetricsCollectorSparkTool.java
- src/test/java/org/broadinstitute/hellbender/metrics/MultiLevelCollectorTest.java
- src/test/java/org/broadinstitute/hellbender/metrics/MultiLevelReducibleCollectorUnitTest.java
This mostly consists of added "implements Serializable" to MultilLevelMetrics and it's subclasses, which wasn't needed for the existing metrics collectors but affected the Example collectors I'm adding. Also contains some miscellaneous reductions of method/field scope that were unnecessarily broad.
> Metrics code serialization fix for sample collectors.

- .travis.yml
- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/utils/nio/GcsNioIntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/utils/nio/private_file.txt
- src/test/resources/org/broadinstitute/hellbender/utils/nio/private_file_2.txt
Add a dependency to the official NIO jar and include tests for gcloud-java-nio.
This is based on the earlier NIO example. Now that NIO support is official we can move this test to our main branch.
I'm resubmitting this as a branch from broadinstitute/ directly so (hopefully) the Travis cloud tests will run.
CC: @lbergelson @droazen
> Add official nio and test (with Travis test this time hopefully)

- build.gradle
adding htsjdk.version and hadoopBam.version system properties to specify the versions on the command line when building
ex:
```
./gradlew test -Dhtsjdk.version=2.6.0 -DhadoopBam.version=7.5.0
```
this will make testing against different htsjdk versions easier
fixes #2076
> htsjdk and hadoopBam versions settable on CLI

- README.md
- build.gradle
- gatk-launch
-Will now look for both shadow and spark jars in the same directory
as the gatk-launch script, and use them if found. Also checks
BIN_PATH for jars.
-Environment variable overrides GATK_SHADOW_JAR and GATK_SPARK_JAR
take precedence over everything
-Wrapper script is used if found and GATK_SHADOW_JAR is not set.
Resolves #1693
> Patch gatk-launch to allow it to run with standalone packaged GATK jars

- build.gradle
We forgot to take this out when we removed native code compilation
> removing gcov references from build.gradle

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/test/GenomicsDBTestUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/GenomicsDBIntegrationTest.java
this includes the new VCF2TileDB java API
replacing process builder calls to GenomicsDB binaries with usage of VCF2TileDB api in GenomicsDBTestUtils
these tests will likely now fail on power systems since GenomicsDB doesn't bundle a power library, power users should build genomics db and specify it's path on the LD_PATH
> updating GenomicsDB from 0.2.1 -> 0.3.0

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollection.java
- src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollectionTest.java
addresses issue https://github.com/broadinstitute/gsa-unstable/issues/1280 from GATK3 (issue was originally found in GATK3 but same issue was present in GATK4) now interval padding works for exclude intervals
> addresses issue #1280 from GATK3 (issue was originally found in GATK3)

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_RankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java
- src/main/java/org/broadinstitute/hellbender/utils/read/AlignmentUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/read/AlignmentUtilsUnitTest.java
Implements #2059.
Ignore loci inside spanning deletions in Rank Sum tests.
> Ignore spanning deletions in Rank Sum tests

- src/test/java/org/broadinstitute/hellbender/JBWAIntegrationTest.java
previously jbwaIntegrationTest was being skipped if running on ppc
this was a hold over from when we didn't yet have a ppc library for it
now it will always run and fail if it's on an unsupported system
it should be compatible with most linux, osx, and power systems now though
> fix jbwaIntegrationTest so it doesn't skip on ppc

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/FindBreakpointEvidenceSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/FindBreakpointEvidenceSparkUnitTest.java
Rather than finding all over-represented kmers among the reads.  Halves run time, but increases the size of a few assemblies.
> Find promiscuous kmers only among those being used to pull reads for assembly.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AFCalculator.java
AFCalculator.getLog10PNonRef() was throwing a confusing error due to a typo.
> fix typo in AFCalculator error message

- src/main/java/org/broadinstitute/hellbender/CommandLineProgramTest.java
- src/main/java/org/broadinstitute/hellbender/utils/test/CommandLineProgramTestInterface.java
- src/main/java/org/broadinstitute/hellbender/utils/test/CommandLineProgramTester.java
- src/main/java/org/broadinstitute/hellbender/utils/test/IntegrationTestSpec.java
This is a very minimal change of the testing framework to allow users of the framework to use `IntegrationTestSpec` with their own classes.
It solves the problem of a custom  `Main` class to run the command line test in programs using the framework (through overriding default behavior), and the loading of `GenomeLocParser` by the `BaseTest` if the test is simply extending `CommandLineProgramTest`. More details for this issue in #2033.
Now API users could implements and modify default behavior of `CommandLineProgramTestInterface` and use this test classes in `IntegrationTestSpec`.
> CommandLineProgramTestInterface for API users

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionaryIntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary/basic.fasta.dict
Fix #2093: `CreateSequenceDictionary` now generates a plain-text dictionary as expected by tools that use it.
> Fix CreateSequenceDictionary (issue #2093)

- src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java
adding a warning to TwoPassReadWalker that authors should probably prefer other traversal patterns if they can
updating documentation for the walker methods
@jamesemery Could you review my changes?
> updating documentation for TwoPassReadWalker

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
Splitting-bai files are used to find split points in BAM files so they can be read in parallel without having to heuristically find suitable split points.
Note that for this change splitting-bai files are only written in non-sharded mode, since sharded mode has issues with the splitting files being read accidentally by the input format. Also, typically each has one split (typically), so there's less need for the splitting index.
> Write splitting-bai files when writing (non-sharded) BAM files from Spark

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/AlignmentRegion.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/BreakpointAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/BreakpointAllele.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/BreakpointEvidence.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/CallVariantsFromAlignedContigsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/GATKSVVCFHeaderLines.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/BreakpointAlleleTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/CallVariantsFromAlignedContigsSparkTest.java
This PR primarily fixes a bug in the hashCode method of BreakpointAllele that was causing Spark's groupByKey() method to not group identical inversion events together, resulting in duplicate variant calls in the output VCF. 
All changes:
- Fix hashCode of BreakpointAllele to use the ordinal of the InversionType enum, which is consistent across executors
- Added Kryo Serializers to several SV classes
- Made the INSERTED_SEQUENCE_MAPPINGS VCF annotation include the assembly id and contig name for each mapping, which is necessary to read them.
> Fix a bug responsible for creating duplicate inversion calls

- src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
AssemblyRegionWalker didn't override getPluginDescriptors() and didn't have a ReadFilterPluginDescriptor
this caused an NPR on every invocation of the haplotype caller
> adding ReadFilterPluginDescriptor to AssemblyRegionWalker

- .coveralls.yml
- .travis.yml
- README.md
- codecov.yml
wanted to see how codecov.io works.  don't merge this.  It looks like they fixed all the problems we have with coveralls though and actually generate a useful report.  They have a browser extension that lets you view which lines are covered by tests in github.  It seems like it would actually be pretty useful in code reviews.
> replacing coveralls with codecov

- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
- src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/OverclippedReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadLengthReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadStrandFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/WellformedReadFilter.java
- src/main/java/org/broadinstitute/hellbender/metrics/InsertSizeMetricsArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/metrics/InsertSizeMetricsCollector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectMultipleMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterPluginUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectInsertSizeMetricsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/InsertSizeMetricsCollectorSparkUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/2148, https://github.com/broadinstitute/gatk/issues/2142, and a bug where we were honoring command line order of read filters but not tool default order. Also contains a few TODOs with questions about the suitability of names and/or implementations of some existing read filters.
> Remove and replace custom tool filter args with standard read filters.

- src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java
The current error handling swallows the detailed part of the error string that gets reported to the user, i.e., without this change you see:
A USER ERROR has occurred: Badly formed genome unclippedLoc: Failed to parse Genome Location string: 20:10000000-10010000
With this change:
A USER ERROR has occurred: Badly formed genome unclippedLoc: Parameters to GenomeLocParser are incorrect:The genome loc coordinates 10000000-10010000 exceed the contig size (200000)
I originally removed the entire try/catch block, but there is downstream code that throws IllegalArgumentException, which can benefit from being decorated with the context info.
> Fix GenomeLocParser error reporting.

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
@takutosato can you review this fix of the bug we were discussing with @droazen?  For comparison, `AlleleSubsettingUtils` uses `GenotypeLikelihoodCalculators` in a similar way.
> Fix bug making HaplotypeCaller fail for non-diploid samples.  Closes #2214.

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
The quality score sum (QSS) format field reports the sum of base qualities for ref and alt allele, and its correct format field count type is 'R' (see 1.2.2 in the [vcf spec](http://samtools.github.io/hts-specs/VCFv4.2.pdf)). We used to use the wrong count type of 1 and that caused a parsing error in the dream challenge evaluation script.
> change qss's count type to R

- src/main/java/org/broadinstitute/hellbender/Main.java
Simple patch to allow passing specific tool classes to `Main.instanceMain` instead of whole packages to solve #2140.
This will allow clients that want their own command line with their tools to include only `IndexFeatureFile` for their own codecs and/or bundle tools like `CreateSequenceDictionary` to pre-process input files.
> Main.instanceMain support for passing CommandLineProgram without a package

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
* Include custom validation in try-catch block to handle custom `UserException.CommandLineException` (solves #2225)
* Unchanged behaviour for the rest of the tools.
> parseArgs catch CommandLineException thrown by customCommandLineValidation

- src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegion.java
- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/CheckPileup.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/Pileup.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByState.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/ReadPileup.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateBaseTest.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/ReadPileupUnitTest.java
This PR tries to solve several issues:
* Refactoring constructors for LIBS (#1879)
* Adding maximum depth per sample argument to `LocusWalker` to avoid memory overload
* Fixing `Pileup`/`CheckPileup` tools for command line read filters
* Method for fix overlaps in `ReadPileup` in the same way as samtools (#2034)
> Pileup-related changes (LIBS/LocusWalker/ReadPileup)

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerAlleleBySample.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHC.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerAlleleBySampleUnitTest.java
Two annotations, allele depth and total depth, consider whether reads are informative relative to the alleles in the output `VariantContext`, which is in general a subset of the alleles contains in the `ReadLikelihoods`.  In PR #2185 I overlooked this and forgot to subset the likelihoods' alleles to those of the vc, which was the previous behavior (see the diff from that PR for the two annotations in this PR).  This PR duplicates the old behavior.  This fixes failures in the HaplotypeCaller integration tests introduced by the previous PR.
> Fix an oversight in recent refactoring of annotation code

- .travis.yml
they seem to have changed the gcloud cli to use --key-file instead of
--key in authentication
this was causing travis to fail on the cloud tests
> updating gcloud command on travis

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/GaussianMixtureModel.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/MultivariateGaussian.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorModelOutputUnitTest.java
A handful of simple optimizations for VariantRecalibrator:
- Preallocate arrays when the size is known
- Eliminate unnecessary boxing of doubles
- Lift some loop invariants with unnecessary allocations (this eliminates millions of array allocations on the full SNP test used by GATK3)
The current GATK4 (multi-variant walker) implementation is about 3% faster than GATK3 without these; these bring it to about 6% faster.
> VariantRecalibrator optimizations

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureInput.java
- src/main/java/org/broadinstitute/hellbender/engine/ShardBoundary.java
- src/main/java/org/broadinstitute/hellbender/engine/ShardBoundaryShard.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/CoalescedRDD.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/CoalescedRDDPartition.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JoinStrategy.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/LocusWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/PartitionCoalescer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/RangePartitionCoalescer.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkSharder.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/PileupSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/downsampling/DownsamplingMethod.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/LIBSDownsamplingInfo.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/RangePartitionCoalescerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkSharderUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/PileupSparkIntegrationTest.java
This addresses #1558 by using an implementation of #1988.
Running on a 6.6GB BAM file:
- PileupSpark with a shuffle took 4.35 minutes on a 6 node cluster
- PileupSpark with no shuffle (using the overlaps partitioner) took 2.96 minutes (30% faster)
- Pileup took 39.2 minutes (on a single node)
@droazen, please take a look and let me know what you think.
> Pileup on Spark

- .travis.yml
these should no longer be necessary and were causing problems because
one of the URL's no longer exists
> removing GenomicsDB dependencies from travis.yml

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/ReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceHadoopSource.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleNioCountReads.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/nio/NioBam.java
- src/main/java/org/broadinstitute/hellbender/utils/nio/ReadsIterable.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/engine/AssemblyRegionUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/LocalReadShardUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/ReadsContextUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/ReadsDataSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/ConvertHeaderlessHadoopBamShardToBamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadCoordinateComparatorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/spark/SparkUtilsUnitTest.java
As a result, every walker that takes a BAM as input can now read it from
the cloud directly.
Sample use: ./gatk-launch CountReads -I
"gs://.../CEUTrio.HiSeq.WGS.b37.ch20.4m-12m.NA12878.bam"
(...)
Tool returned:
7275701
Note that this CL doesn't add a prefetcher or multithreading, so the
performance is inferior to that of the NIO proof of concept which was
using both.
cc: @droazen
> Convert ReadsDataSource to use Paths, so it can read inputs from the cloud

- src/main/java/org/broadinstitute/hellbender/Main.java
Simple patch to improve the `Main` usage in the same direction as previous PRs to finer control by API user:
* Added `handleNonUserException(final Exception exception)` to handle custom exceptions.
> Allow custom exception handling to API users

- src/test/java/org/broadinstitute/hellbender/MainTest.java
removing MainTest.printReadsVersionTest because it was causing the test
suite to exit early.
it wasn't a very good test to begin with so it's not much of a loss
> remove bad test that was causing tests to abort

- build.gradle
since we've switched to spark 2.0 we now have to use new dataproc images
these images use spark compiled against scala 11 instead of scala 10
updating gatk to use spark with scala 11 to fix #2073
> use spark compiled for scala 11

- gatk-launch
2 changes to gatk-launch
- gcloud now requires arguments to the spark job to be separated from arguments to gcloud by `--`
- `--sparkMaster yarn-client` has been replaced with `--sparkMaster yarn --deploy-mode client`
this only requires the sparkMaster to be changed in gatk-launch gcs because the client mode is set by gcloud
> updating gatk-launch for spark 2.0 on gcloud

- src/main/java/org/broadinstitute/hellbender/utils/LoggingUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
kryo uses com.esotericsoft.MinLog which is a yet another logger
making LoggingUtils.setLoggingLevel() set MinLog's level
> making kryo respect our log level

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineParser.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineParserTest.java
- src/test/java/org/broadinstitute/hellbender/tools/examples/ExampleCollectMultiMetricsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectInsertSizeMetricsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectRnaSeqMetricsTest.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/RevertSamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectInsertSizeMetricsSparkIntegrationTest.java
Also reject 'null' for collection arguments when used as one of several values for the same option.
Fixes https://github.com/broadinstitute/gatk/issues/2274.
> Change command line collection argument behavior from "append" to "replace". 

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
Very simple patch to extract arguments that may be useful for other toolkits into `StandardArgumentDefinitions` and some in-class changes.
> Extracting some args names in GATKTool to static values

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java
- src/test/java/org/broadinstitute/hellbender/utils/pairhmm/VectorPairHMMUnitTest.java
Update to GKL 0.3.1 which provides the following features compared to GKL 0.1.2 currently used by GATK:
1. Improved performance for Level 1 compression.
1. OpenMP AVX PairHMM with fallback to non-OpenMP support logic in GATK.
1. Individual shared library objects for each native binding.
1. Flush-to-zero get/set support.
Updated `VectorPairHMMUnitTest` to test all supported implementations of `VectorLoglessPairHMM` and skip the test if no implementations are supported.
**Note**
The default number of threads used by OpenMP AVX PairHMM is set to 1, and the command line argument to change the number of threads is not connected yet (see #1946). So, the OpenMP and non-OpenMP PairHMM currently have the same performance.
Resolves #1819
First step for #1946
> Update to GKL 0.3.1

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
this seems to fix an issue with serializing Genotypes in haplotype caller
updating kryo-serializers:0.37 -> 0.41 just in case
I couldn't come up with a test case that fails when run locally.  It only seems to fail when run with spark-submit.
> changing nCopies registration to use FieldSerializer

- build.gradle
addressing https://github.com/broadinstitute/gatk/pull/2264#issuecomment-261062024
we were importing the wrong version of adam to go with spark 2.0
> fixing adam import to be the spark 2.0 version

- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/test/java/org/broadinstitute/hellbender/engine/ReadsDataSourceUnitTest.java
Tests and fix for https://github.com/broadinstitute/gatk/issues/1674.
> Fix for ReadsDataSource queries that intersect a subset of inputs.

- src/main/java/org/broadinstitute/hellbender/utils/FisherExactTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/FisherStrandUnitTest.java
Even though the Fisher Exact Test here is based on the R implementation, there was an edge case when the hypergeometric distribution we're getting the probabilities from only has one possible value. The difference in resulting p-value was coming from the fact that the apache Math3 HypergeometricDistribution behaves differently at this edge case than dhyper in R. 
Adresses #2292
> Handles edge case of Fisher Exact Test

- src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentCollection.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/ReadPileup.java
- src/test/java/org/broadinstitute/hellbender/utils/fragments/FragmentCollectionUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/ReadPileupUnitTest.java
`FragmentCollection.create(ReadPileup)` assumes a `ReadPileup` sorted by start position and thus it throws an exception (#2245) while trying to fix a multi-sample `ReadPileup` constructed with an stratified one (like in LIBS).
For solving the issue, I just implemented a simple fix from the constructor (sorting the stratified pielup) and a simple test for check if #2245 is solved.
> Fixing ReadPileup constructor for multiple samples

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java
- src/test/java/org/broadinstitute/hellbender/utils/pairhmm/VectorPairHMMUnitTest.java
Reverting the update to gkl 0.3.1 for now because we've encountered some downstream errors that are making it impossible to update gatk-protected.
This reverts commit 9e3c6e3d7370c503d2a57be0c662fb1016d8b764, reversing
changes made to 767974906e91c90079cefa4512b463138ca09f68.
> Revert "Merge pull request #2259 from broadinstitute/gp_gkl_updates"

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTestUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AlleleSpecificReadPosRankSumTestUnitTest.java
Implement https://github.com/broadinstitute/gatk/issues/2147.
```
Change ReadPosRankSumTest.isUsableRead to take deletions into account. Previously, reads were skipped because the variant location was considered downstream from the read. 
```
The same fix was done to `AS_ReadPosRankSumTest`.
> Make ReadPosRankSumTest.isUsableRead() account for deletions

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/AddOrReplaceReadGroups.java
I would like to keep in some of my tools the read group arguments in sync with the `AddOrReplaceReadGroup` in picard, but currently there is no way of access them.
This is a very simple and trivial patch to extract the short/long names to a static String variable to be able to use them. In addition, I refactored the variable names to the camel-case java convention.
> Argument names for AddOrReplaceReadGroup to static

- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/artifacts/Transition.java
Would like to make the Transition enum a public enum.
> Making public Transition

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java
Implements #2193.
This is a port of https://github.com/broadinstitute/gsa-unstable/pull/1417. Unit tests were added since the GATK3 version was tested with GenotypeGVCFs, which is in `gatk-protected`. There is a new internal class, `GenomeLocation` is used instead of `GenomeLoc` to store the deletions. This is because `GenomeLocParser`, which is used to create  `GenomeLoc` is not passed into `GenotypingEngine` in GATK4. I could not find a clean way to add it.
> Remove spanning deletions if the deletion was removed

- build.gradle
No longer needed due to Barclay dependency.
> Remove obsolete dependency on JOpt.

- src/main/java/org/broadinstitute/hellbender/engine/FeatureWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/ShuffleJoinReadsWithRefBases.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVKmerizer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVKmerizerWithLowComplexityFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/ApplyBQSRSparkFn.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/ExactAFCalculator.java
- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableColumnCollection.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableReader.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureManagerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/covariates/StandardCovariateListUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
Because calling `StreamSupport.stream(iterable.spliterator(false))` is really ugly.
> Utils methods to stream Iterable/Iterator

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary.java
- src/main/java/org/broadinstitute/hellbender/utils/fasta/CachingIndexedFastaSequenceFile.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionaryIntegrationTest.java
This solves partially #2177, although generating the _.fai_ is not implemented yet.
* Use `IOUtil.DICT_FILE_EXTENSION` as dictionary extension in `CachingIndexedFastaSequenceFile.checkAndCreate`
* No required output argument for `CreateSequenceDictionary`, using as default the name that is used internally in the GATK framework (e.g., __basic.dict__ for __basic.fa__).
> CreateSequenceDictionary default output file name

- src/main/java/org/broadinstitute/hellbender/exceptions/GATKException.java
this seems to be outdated now that we have barclay
> deleting GATKException.CommandLineParserInternalException

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
changing from GATKException to the more appropriate UserException.CouldNotCreateOutputFile
updating user exceptions that take an exception to properly pass the exception on as their cause so they don't show incomplete stack traces
> improving error message in GATKSparkTool.writeReads

- src/main/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilter.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilterUnitTest.java
Found in https://github.com/broadinstitute/gatk/pull/2195:
* `getSummaryLineForLevel` fix for indentLevel = 0 (including tests)
* `resetFilterCount` now is propagated to lhs/rhs
> Minor fixes for CountingReadFilter

- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/ASEReadCounter.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/ReadPileup.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/ReadPileupUnitTest.java
@lbergelson Sorry, you were too fast for me! This now handles multiple samples in the ReadPileup filter and cleans up that StringBuilder.
> Handling samples and cleaning in ASEReadCounter and ReadPileup

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramUnitTest.java
fixes the issue where CommandLineExceptions produced no error message
added a public getUsage() method to CommandLineProgram
added a catch for these in instanceMain(), where the CommandLineProgram is in scope for printing the usage message
added a protected accessor getCommandLineParser to CommandLineProgram which guards against having an uninitialized CommandLineParser
moved the "A USER ERROR HAS OCCURRED" text out of the actual user exception and into the pretty printing
> CommandLineException is no longer silent #2324

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVUtils.java
@tedsharpe please kindly review.
The skip interval that has the corresponding format lives here:
gs://sv-data-dsde-dev/reference/GRCh38.kill.intervals
and was generated by 
gs://sv-data-dsde-dev/extra_input_generator_scripts
> Trivial formatting update for skip interval file parser

- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterPluginUnitTest.java
Only for no default filters. If not, the composed filter will contain twice the filter one after the other.
> Throw CommandLineException for enabling twice the same read filter

- .travis.yml
- README.md
- build.gradle
tests will now run as cloud, integration, and unit on travis
this reduces our wallclock time from 30ish -> 20ish minutes
cleaned up some wierdness in the way things were specified as well
> splitting tests on travis

- src/test/java/org/broadinstitute/hellbender/engine/VariantWalkerGCSSupportIntegrationTest.java
The entire test suite aborts if HELLBENDER_TEST_INPUTS isn't set because an exception is thrown when loading the VariantWalkerGCSSupportIntegrationTest class.
With this change, the tests will still fail, but the rest of the test suite will run. Depending on what the intent for these tests is, another possibility would be to add a dependsOn method with a hard dependency so the tests would be skipped in the case of no env variable.
> Allow tests to fail gracefully if HELLBENDER_TEST_INPUTS isn't set.

- .travis.yml
This would publish master-SNAPSHOT on every commit to master.  It would give people a single moving snapshot to build off of if they wanted to be on the bleeding edge.
Fixes #1995 
It's hard to test that it pushes only on commits to master without committing to master... but I think it should work.
> publishing a master-snapshot update on every push to master

- src/main/java/org/broadinstitute/hellbender/tools/SplitReads.java
As described in #2383, to avoid clash with Picard arguments for add read groups and point out that they are meant to split.
> Modify SplitReads argument names

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
this seems to resolve the extremely slow runtimes when using large interval lists #2356
> enabling bam index caching in memory for GATKTool

- scripts/sv/alignAssembly.sh
- scripts/sv/assembly.sh
- scripts/sv/callVariants.sh
- scripts/sv/create_cluster.sh
- scripts/sv/delete_cluster.sh
- scripts/sv/scanBam.sh
- scripts/sv/svCall.sh
@cwhelan @tedsharpe @vruano @mwalker174 , I've organized the scripts for running the whole sv pipeline as it exists right now. There used to be a PR (if I recall correctly) but since that's outdated, why not an up-to-date one.
Here's how to run it
1. To create the cluster
```
./create_cluster.sh broad-dsde-methods sv-methods-1 broad-dsde-methods/sv
```
where the 1st argument is the project name, 2nd argument is the cluster name, and the 3rd name is the place where input data lives.
2. To run the whole pipeline
```
./svCall.sh /Users/shuang/GATK/gatk sv-methods-1 /user/shuang/NA12878_PCR-_30X
```
where the 1st argument is the location of my GATK directory and the 3rd argument is the location of all outputs on the cluster. So change them as necessary. The different stages called by the …
> Scripts running the whole sv-pipeline as exists now from birth to termination

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
*before*: GATK crashes with a stack trace. The stack trace contains useful
info, but:
* it's hard to read
* it doesn't include the name of the file we cannot access
*now*, a better message that addresses both issues:
> A USER ERROR has occurred: Couldn't read file gs://(...). Error was:
> 401: Anonymous users does not have storage.objects.get access to object (...).
Additional information (including a stack trace) is displayed if the
user specifies `--verbosity=DEBUG`
> Improve error message for no-access and disabled-account cases

- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterPluginUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
- Disable default read filter with arguments does not longer blows up  but log a warning (fixes #2357)
- Improved help message for read filter (fixes #2358 and #2398)
- `--disableAllReadFilters` changed to `--disableToolDefaultReadFilters` and `isDisabledFilter()` honor this behavior (fixes #2361 and #2363)
- Add test for exercise the path of logging a warning when disabling a  not enabled filter (as proposed in #2377)
- Disabling a non-existent read filter throws a `CommandLineException`  (fixes #2397)
> GATKReadFilterPluginDescriptor fixes

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/InsertSizeMetricsCollectorSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/FindBreakpointEvidenceSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUnitTest.java
> Fix NPE due to GCS auth not being passed in when reading BAM header.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
Implements https://github.com/broadinstitute/gatk/issues/2099.
Remove the `-stand_emit_conf` argument from `GenotypeCalculationArgumentCollection.java` and set as a static value in `GenotypingEngine.java`
> Remove -stand_emit_conf argument

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/nio/GcsNioIntegrationTest.java
Main motivation: it includes fixes we need for writing to
Google Cloud Storage buckets via NIO.
However this comes with some API changes too so we must agree
on what to do there.
> Move to the latest version of google-cloud-java

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RankSumTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQualityRankSumTestUnitTest.java
previously RankSumTest disallowed null likelihoods in it's annotate method
this was different from GATK3 and causes problems in GenotypeGVCFs
relaxing this constraint so annotate will now return Collections.emptyMap() if likelihoods is null
> allow null-likelihoods in  RankSumTest annotate

- gatk-launch
previously system properties were set by the wrapper script but not by gatk-launch when running with a local jar
now both local jar and wrapper script get the same properties
more properties are now explicitely set for spark tools as well
fixes #2316
> gatk-launch launch now sets properties for local jars correctly

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
GenotypeCalculationArgumentCollection.STANDARD_CONFIDENCE_FOR_CALLING now defaults to 10.0 instead of 30.0
> setting STANDARD_CONFIDENCE_FOR_CALLING = 10.0 to match gatk3

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/AlignmentRegion.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/GATKSVVCFHeaderLines.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVVariantConsensusCall.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/NovelAdjacencyReferenceLocationsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/SVVariantConsensusCallUnitTest.java
> fix for issue 2502 "SV called variants.vcf ASSEMBLY_IDS and CONTIG_IDS uses % rather than , to separate elements"

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java
* changes to GenotypingEngine.calculateGenotypes in #2528 introduced a regression that caused IndexOutOfBoundsException
* fixes #2530 by preventing the exception and adding tests
@davidbenjamin Note that I also changed the condition from "first alt allele is NON_REF" to "any alt allele is NON_REF".  This more accurately matches what the comment says, but let me know if you think it's not the right thing.
> fixing IndexOutOfBoundsException in GenotypingEngine

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHet.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeff.java
- src/main/java/org/broadinstitute/hellbender/utils/GenotypeCounts.java
- src/main/java/org/broadinstitute/hellbender/utils/GenotypeUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHetUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeffUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/GenotypeUtilsUnitTest.java
* changing GenotypeCounts to be doubles instead of ints, this is weird but it's how gatk3 is
* adding an additional boolean parameter to computeDiploidGenotypeCounts that controls rounding behavior
ExcessHet needs rounding on
InbreedingCoeff needs it off
* adding a new GenotypeUtilsUnitTest class
these tests are not exhaustive and leave most conditions untested
* updating InbreedingCoeffUnitTest with a test that checks that we match gatk3 output for a previously divergent case
> fixing InbreedingCoeff calculation to match GATK3

- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/DefaultGATKReadFilterArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterPluginUnitTest.java
I would like to use the implementation of `GATKReadFilterPluginDescriptor` with some minor changes, but the current design of the class does not allow it. In this PR I include the following changes (divided in commits):
- Argument collection to apply to `GATKReadFilterPluginDescriptor` added on construction. This allow to modify the argument descriptions/behaviour depending on the usages.
-  Make fields protected, and a couple of final keywords to methods that are not expected to be modified.
> Make GATKReadFilterPluginDescriptor extensible

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/TandemRepeat.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/TandemRepeatUnitTest.java
It was assuming that the `ReferenceContext`'s interval has the same start as the `VariantContext` being annotated, which is often not true.  I tested this in Mutect and it seems to work correctly now.
@LeeTL1220 This will improve indel specificty in M2 by 75% or so.  Can you review?
> Fixed a bug in TandemRepeat annotation

- build.gradle
- src/test/java/org/broadinstitute/hellbender/IntelInflaterDeflaterIntegrationTest.java
* Bump GKL version to 0.4.3 which addresses some GC and memory leak issues.
* Remove DEBUG verbosity setting in `IntelInflaterDeflaterIntegrationTest`, which caused subsequent tests to generate huge amounts of debug info and run out of memory on some systems.
Resolves #2490 and resolves #2535.
> Bump GKL to 0.4.3 and fix IntelInflaterDeflaterIntegrationTest

- src/main/java/org/broadinstitute/hellbender/tools/spark/ParallelCopyGCSDirectoryIntoHDFSSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/MiniClusterUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/ParallelCopyGCSDirectoryIntoHDFSSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsTest.java
This tool copies single large files or directories from GCS into HDFS using Spark. Spark parallelization allows each task to copy a chunk in the size of the blocks of the target HDFS system simultaneously.
When copying a directory containing a 120GB WGS bam and its index, this takes approximately 1 minute on a 10 worker / 160 core cluster, as opposed to approximately 20 minutes using Hadoop distcp.
This may eventually be superseded by the NIO GCS integration work if that ends up performing comparably.
@lbergelson would you like to review? Or feel free to nominate someone else.
> Tool to read data in parallel from GCS to HDFS with Spark

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java
Fix "no alleles" case in GenotypingEngine.calculateGenotypes() boolean expression
> Fix "no alleles" case in GenotypingEngine.calculateGenotypes() boolean expression

- scripts/sv/create_cluster.sh
- scripts/sv/default_init.sh
This PR removes the use of hadoop distcp to copy reference and sample data into HDFS, and replaces it with the new ParallelCopyGCSDirectoryIntoHDFSSpark tool.
Based on initial tests, cluster creation with reference and a 110GB sample BAM file now takes ~8 minutes with SGA installation on the worker nodes and ~5 minutes without SGA installation.
@SHuang-Broad can you review?
> Modify cluster creation scripts to use ParallelCopyGCSDirectoryIntoHDFSSpark

- build.gradle
Exclude htsjdk and protobuf from genomicsdb dependency
> Exclude htsjdk and protobuf from genomicsdb dependency - Issue 2578

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSR.java
- src/test/java/org/broadinstitute/hellbender/engine/LocusWalkerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/ReadWalkerUnitTest.java
In the same way as `makeReadFilter()`, I implemented a function to include read transformers in `ReadWalker` and `LocusWalker` to use already transformed reads in `apply` (as requested in #1886).
This function could be added to the `GATKSparkTool` too, and include it in `getReads()`.
> GATKTool pre/post ReadTransformers methods + ReadWalker/LocusWalker integration 

- src/main/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtilsUnitTest.java
Surgical changes to the VariantContextTestUtils to allow the GenomicsDB importer to tests to compare variants coming from a BCF stream with variants coming from a VCF stream.
> Minor changes to variant comparator test utility for GenomicsDB tests.

- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculatorUnitTest.java
The version of testNG that we're using has some [inconsistencies](https://github.com/cbeust/testng/pull/790) in how nested arrays/collections are handled, and they've resolved them in newer versions by implementing changes that are not backward compatible. The AlleleFrequencyCalculatorUnitTest tests fail with newer versions of testNG that have these changes, since they were wrapping an array in a single element List (not sure if that was intentional or not).
The testNG issues seem to suggest using assertEqualsDeep for [some cases](https://github.com/cbeust/testng/issues/1342) but even the newest version doesn't seem to have an overload for Collections. For AlleleFrequencyCalculatorUnitTest though, the collection wrapping was unnecessary anyway, so the array comparisons can be made …
> Fix test assertion that fails on newer versions of testNG.

- build.gradle
And remove unnecessary dependencies introduced for GenomicsDB.
> Upgrade testNG to 6.11, use force dependency resolution for testNG

- build.gradle
We were seeing failures on spark clusters that manifested as being
unable to find the Main class while running spark submit.
The caused was the accidental introduction of a jar signature file
and key from the transitive gnu.getopt dependency. This was causing
signature validation failures since our uber jar did not match the
expected hashes.
Fixed by excluding .SF and .RSA files from our jars.
> fixing the spark failures introduced by #2389

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RankSumTest.java
- src/main/java/org/broadinstitute/hellbender/utils/MannWhitneyU.java
- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQualityRankSumTestUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ClippingRankSumTestUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/LikelihoodRankSumTestUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/MappingQualityRankSumTestUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTestUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/MannWhitneyUUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTest.java
MannWhitneyU was re-written from scratch in 2016 in GATK3,
but these changes never got ported to GATK4. This new version
produces significantly different results from the version
currently in GATK4, resulting in VERY different values for the
RankSumTest annotations in HaplotypeCaller output.
@meganshand informs me that the updated GATK3 version has been
validated in R, and has much better tests than the old version.
This is a straightforward port of that version with minimal changes:
-Merged "MWUnitTest" and "RankSumUnitTest" from GATK3 into a single
test class MannWhitneyUUnitTest
-Ported MathUtils.binomialCoefficient() and wrote new test for it
-Updated RankSumTest class and tests as appropriate
I've confirmed that with this change, the RankSum annotations produced
by the GATK4 …
> Replace MannWhitneyU with updated version from GATK3

- src/main/java/org/broadinstitute/hellbender/engine/spark/RangePartitionCoalescer.java
This is needed for recent versions of Spark 2; see https:/issues.apache.org/jira/browse/SPARK-18051.
> Implement scala.Serializable for the PartitionCoalescer 

- src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java
After all, there's no point in having a larger buffer than that.
> Limit NIO buffer size to file size

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ValidateVariants.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/ValidateVariantsIntegrationTest.java
> ValidateVariants is smarter about when a reference is and is not required. Closes #2509.

- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriter.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriterUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/utils/variant/writers/small.g.vcf
Finish porting https://github.com/broadinstitute/gsa-unstable/pull/1440.
* Changed the last band from [lastValue,  Integer.MAX_VALUE) to [lastValue,  MAX_GENOTYPE_QUAL) .
* Changed the expected test data and compare against the output partition (value) rather than the input (key).
* Changed GVCFBlock in a test gvcf file.
> Change the last GCVF partition band upper bound from strictly less than Integer.MAX_VALUE to MAX_GENOTYPE_QUAL

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/GenomicsDBImportIntegrationTest.java
build will break because genomicsdb-0.6.0 hasn't been released yet and dependence on protobuf-java-format needs to be fixed!
@droazen, remember now that I added the dependence on protobuf-java-format to use protobuf.JsonFormat.printToString() method which converts a protobuf structure to JSON string. I want to use import configuration protocol buffers in this code which means this dependence will be back to bite us! Need to fix this cause I don't want to break the Spark build again
> Added batchsize and consolidation parameters to GenomicsDBImporter

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQuality.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQualityUnitTest.java
Removing the error check in RMSMappingQuality.getNumReads which was causing a crash when depth was being reported as 0 or less.
It will now return -1 which should match gatk3 behavior.
Fixes #2658
> prevent GenotypeGVCFs crash due to RMSMappingQuality #2658

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
GenomicsDBImport now specifies default NIO buffer sizes of 2 MB, rather than the
default 40 MB. The smaller size is due to the large number of inputs this tool
typically has.
Resolves #2670
> Make it possible for individual tools to override the default NIO buffer sizes

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportUnitTest.java
Adding an advanced option --sampleNameMap to GenomicsDBImport which can be specified instead of -V
* This allows providing a file mapping samples to their vcf uri which is used instead of loading each header and checking the sample names.
* The first file in the mapping is chosen to act as the header template.
If the headers are not consistent there may be data corruption.
A mapping file is a tab seperated file with no header in the format
Sample1	file1
Sample2 file2
Sample3 file3
...
> Allowing GenomicsDBImport to skip header merging

- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlock.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlockUnitTest.java
This fixes an explosion in the HaplotypeCaller in protected caused by
the recent change in public to cap the last GVCF band.
> HomRefBlock: when doing bounds checking in add(), treat GQs > 99 as 99.

- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSPairedUnpairedSplitterSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSPairedUnpairedSplitterSparkTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSUtilsTest.java
@cwhelan @tedsharpe please review.
Miscellaneous utility functions used by two or more PathSeq tools.
Note pathseqGetRecommendedNumReducers is needed because some tools read 2 BAMs - one with paired reads one with unpaired reads - and the GATKTool's version will only let you call it on the BAM specified by --input.
> PathSeq common utilities class

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
We were dumping all HTSJDK defaults to our logger, even though many settings are not
really relevant to GATK
Resolves #2691
> Print a curated set of important HTSJDK settings at startup, instead of all HTSJDK defaults

- src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/IntervalWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ProgressMeter.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalkerBase.java
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
-Tools can now customize the progress meter to use a different word than
"records" in its output (eg., "reads", "regions", etc.)
-Updated standard walker classes to specify appropriate labels
-Hooked up GenomicsDBImport to the progress meter (it was always reporting
"Processed 0 records" at traversal end)
Resolves #1943
Resolves #2683
> ProgressMeter: allow labels to be configurable per-traversal/tool, and hook up to GenomicsDBImport

- build.gradle
Fixes https://github.com/broadinstitute/gatk/issues/2693.
> Move generated online docs into the build directory.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java
@lbergelson I believe this change is the only difference, but I would appreciate if you check whether this branch's likelihood sums match those of GATK 3.
> Eliminate allele count weighting in AlleleSubsetting likelihood sum to match GATK 3

- src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegion.java
- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/LocusWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/downsampling/LevelingDownsampler.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/IntervalAlignmentContextIterator.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/IntervalLocusIterator.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/IntervalOverlappingIterator.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/ShardedIntervalIterator.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/LIBSDownsamplingInfo.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByState.java
- src/test/java/org/broadinstitute/hellbender/engine/LocusWalkerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/iterators/IntervalAlignmentContextIteratorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/iterators/IntervalLocusIteratorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/iterators/IntervalOverlappingIteratorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/iterators/ShardedIntervalIteratorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateUnitTest.java
- Changes LocusWalker to emit uncovered loci if requested.  Default is previous behavior.
- Needed when there needs to be differentiation between "we do not care about this locus" versus "this locus has no coverage".
> Ll emit empty loci

- .travis.yml
Adding tests on openJDK since it seems like we're going to have to support it.
> adding openjdk to our tests

- src/main/java/org/broadinstitute/hellbender/tools/picard/vcf/GatherVcfs.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/vcf/GatherVcfsUnitTest.java
This only works for the conventional gather.  adding useConventionalGather argument to force using conventional gather.
adding --ignoreSafetyChecks to skip pre-validating the headers
continuing the tradition of having no tests for this tool
> updating gathervcfs to work with paths

- .travis.yml
removing redundant builds:
we will now have:
openJDK builds for cloud, integration, and unit tests
docker builds for integration and unit tests
an oracleJDK build for integration tests
> reducing size of travis build matrix

- src/main/java/org/broadinstitute/hellbender/tools/exome/GetBayesianHetCoverage.java
The doc generation system was abruptly stopping the docs at the `@` signs in the example data header. Solution is to use `{@literal @}`.
> CNV GetBayesianHetCoverage: format at signs in example header so javadocs can represent literally

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
I've completely rewritten the documentation portion to be more helpful to users (and to reflect the new M2 rather than gatk3's M2), and I have updated the example commands.
---
- `--af_of_alleles_not_in_resource`: is this allele frequency used only in certain contexts, e.g. with matched normal analyses, or towards tumor sample variant alleles, etc.? I need to add to the doc details how this argument factors into calculations.
- I need a sentence or two describing the new algorithmic improvement on the new Mutect2 integration over uncertainty. 
- The WDLs do not include use of a contamination.table and so I did not include it in the commands. Is this something we want to nudge users to use, i.e. should I put in a sentence in the documentation section about the new tool …
> Document Mutect2: revamp documentation and example commands to reflect algorithmic changes

- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
- Given the output is described to contain population allele frequencies, I made the conjecture that the input -V resource file must also contain population allele frequencies. Is this really a requirement?
> shl GetPileupSummaries tag doc, limit and flesh out example command, include note on default -maxAF

- src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java
- Not clear if SplitIntervals actually divides by the count of intervals or by genomic territory covered. Specifically, what is the difference between --subdivision_mode INTERVAL_SUBDIVISION and BALANCING_WITHOUT_INTERVAL_SUBDIVISION? The argument description is unclear.
- What is the point of having the default scatter count 1? For future reference, can we change this default.
> shl SplitIntervals tag doc, give example command, clarify some details

- src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java
Now throws a UserException.MalformedFile if the resulting header has no
dictionary.
Added testLoadFastaDictionaryWithFastaFile to test this case.
resolves #2609
> Check for bad sequence dictionaries in ReferenceUtils.loadFastaDictionary

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java
- src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java
This also includes:
* Added FPGA to ```Implementation``` enum of ```VectorLoglessPairHMM```
* Added FPGA to ```Implementation``` enum of ```PairHMM```
* Updated ```FASTEST_AVAILABLE``` value to try FPGA first (then AVX+OMP, then AVX, then regular)
> Added FPGA support to PairHMM via GKL

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVVCFWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsTest.java
- src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java
Those options are used to carry auth for the ReferenceAPISource,
so we can't remove all instances without changing those.
This work is part of #963.
> Remove some uses of dataflow.sdk.options.PipelineOptions

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkSharder.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkSharderUnitTest.java
This gives better errors in the case of sequence dictionary mismatches.
> Add validation to SparkSharder to get better information about sequence dictionary errors

- gatk-launch
Options only used when running locally.
Internally options are passed either by appending to java invocation directly with
command-line options or using the JAVA_OPTS environment variable.
Also added environment variable printout with --dryRun
Other minor formatting / whitespace changes.
resolves #2694
> Adding in ability to pass options to the Java JVM in gatk-launch via --javaOptions flag

- src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java
> SplitIntervals output argument made required, as it should be.  Closes #3409

- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadLengthReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/WellformedReadFilter.java
Using character entities in javadoc to correct HTML formatting.
> Fix javadoc HTML in ReadLengthReadFilter and WellformedReadFilter

- src/main/java/org/broadinstitute/hellbender/metrics/InsertSizeMetricsCollector.java
- src/main/java/org/broadinstitute/hellbender/metrics/MetricsUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/metrics/multi/ExampleCollectMultiMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/metrics/multi/ExampleMultiMetricsCollector.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/metrics/multi/ExampleMultiMetricsCollectorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/metrics/single/ExampleCollectSingleMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/metrics/single/ExampleSingleMetricsCollectorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectInsertSizeMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectBaseDistributionByCycleSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectInsertSizeMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectMultipleMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectQualityYieldMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/InsertSizeMetricsCollectorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MeanQualityByCycleSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MetricsCollectorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MetricsCollectorSparkTool.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/QualityScoreDistributionSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/QualityYieldMetricsCollectorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/metrics/MetricsUtilsTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectMultipleMetricsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/InsertSizeMetricsCollectorSparkUnitTest.java
Also remove imports and update comments.
Metrics are saved using NIO so we don't need authHolder.
This work is part of #2402.
> Remove authHolder from metric-related classes

- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/CoverageModelArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/CoverageModelEMComputeBlock.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/CacheNode.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ComputableCacheNode.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ComputableGraphStructure.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ComputableNodeFunction.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/Duplicable.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/DuplicableNDArray.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/DuplicableNumber.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ImmutableComputableGraph.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ImmutableComputableGraphUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/PrimitiveCacheNode.java
- src/main/java/org/broadinstitute/hellbender/utils/MathObjectAsserts.java
- src/test/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/CacheNodeUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ComputableGraphStructureUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ImmutableComputableGraphUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/coveragemodel/cachemanager/ImmutableComputableGraphUtilsUnitTest.java
- reviewed and restricted the access modifiers of all ICG-related classes
- got rid of the functionality to hold on to old caches: whenever a cache goes out of date, the reference is immediately made null in the new ICG
- completely rewrote ComputableGraphStructure in a functional style
- got rid of unused and unnecessary methods
- Created an ImmutableComputableGraphUtils and factored out the builder and other common methods
- math equality asserts for NDArray
- unit tests for ComputableGraphStructure
- unit tests for ImmutableComputableGraph
- unit tests for ImmutableComputableGraphUtils
- keys and tags have their own classes now
> ImmutableComputableGraph code improvement + unit tests.

- src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java
- src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
Not sure if there is a better way to do this. UserException seems wrong since its displays USER Error.
> Temporarily disable IndexFeatureFile and tests to avoid creation of bad indices.

- .travis.yml
- build.gradle
update the artifactory url to point to the new artifactory
update the travis build with another environment variable called UPLOAD which determines if that build should upload a snapshot or not
fixes #3068
> fixing problems with artifactory uploads

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
Empirical testing has shown that this tool performs best at scale with cloud buffering
disabled. With cloud buffering on and thousands of concurrent GenomicsDBImport tasks,
we do too many simultaneous GCS accesses (since the prefetcher spawns a new thread for each
reader upon a query) and start seeing intermittent failures, even with aggressive retries.
> Disable NIO prefetching in GenomicsDBImport

- README.md
Hi, I was reading README.md and found the following minor bugs:
- s/instructins/instructions/
- s/convinience/convenience/
- remove a whitespace between [these instructions] and (https://...
Thanks!
> Fix minor typos and a format error in README.md

- src/main/java/org/broadinstitute/hellbender/Main.java
(The variable was renamed to GATK_STACKTRACE_ON_USER_EXCEPTION)
There are no mentions left of STACK_TRACE_ON_USEREXCEPTION.
Thanks to David who reported this bug on gatk-dev-public.
> Fix mention of STACK_TRACE_ON_USEREXCEPTION

- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/KnownSitesCache.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
This is needed to get BQSR running on an exome with a 10GB known sites VCF. See https://github.com/broadinstitute/gatk/blob/tw_spark_eval/q4_spark_eval/test_case_exome_pipeline.sh
> Use a per-JVM cache of known sites (variants) rather than broadcast which fails for >2GB

- build.gradle
from snapshots to released versions.
> Upgrade barclay, htsjdk, gatk-fermilite-jni and gatk-bwamem-jni

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
I also removed the obsolete errorProbability variable line of code in the SomaticGenotypingEngine.java and noted this argument is deprecated in the M2ArgumentCollection.
Somewhat relatedly, see request in #3123.
> Shl Correct and expand the M2ArgumentCollection documentation

- scripts/sv/create_cluster.sh
- scripts/sv/default_init.sh
- scripts/sv/runWholePipeline.sh
rather than the default boot HDD.
Thanks to @mwalker174 for discovering this.
In terms of runtime, this didn't change runtime for the SV pipeline much.
> modified init script to put ref idx img in local ssd

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
Implements the GVCFGQBands documentation for https://github.com/broadinstitute/gatk/issues/2981.
Port from https://github.com/broadinstitute/gsa-unstable/pull/1451.
> GVCFGQBands documentation

- src/main/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMEmissionProbabilityCalculator.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMModel.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMSegmentGenotyper.java
- src/main/java/org/broadinstitute/hellbender/utils/hmm/segmentation/HMMPostProcessor.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMSegmentCallerBaseIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMSegmentCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/germlinehmm/xhmm/XHMMSegmentGenotyperIntegrationTest.java
- src/test/resources/large/cnv/truncated-realistic-targets.tab
Still not sure why the tests failed randomly! all XHMM-related tests use their own RNG with fixed seeds and there are no RNG calls in any parallel streams. Therefore, the randomly generated test data must be identical and fully deterministic across all runs. However, it did not appear to be the case! some test runs triggered a bug in HMMPostProcessor (see below) and some runs didn't. I removed a few unnecessary RNGs and the issue is not reproducible anymore. In particular, both XHMMModel and XHMMEmissionProbabilityCalculator had their own RNG but then again, if the tests are run in a deterministic order, it shouldn't matter. The good news is the bug in HMMPostProcessor is fixed; the bad news is, I still don't know why the tests were not deterministic. I bet the failing issue is …
> Fix for randomly failing XHMM-related tests

- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/common.html
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/gatkDoc.css
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.index.template.html
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.template.html
This PR updates the Freemarker templates so that the resulting pages will work with the current state of the website code. Most of the changes have to do with functionality I put in to enable hosting multiple doc versions and easy switching between them via a dropdown menu. 
I had already done some retrofitting on older tooldocs so the versioned tool docs go back to 3.5, and we can add beta versions of 4 without changing the "latest supported version". 
The only remaining problem is that I couldn't figure out how to output php instead of html. To test the web integration, I just renamed all *.html to *.php with `for f in *.html; do mv -- "$f" "${f%.html}.php"; done` but that doesn't take care of internal links, which are of course broken as a result. @cmnbroad please let me know if I …
> Updated templates to fit current website logic

- src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java
I'd mistaken the two meanings of RAW in the CNV workflow and have clarified with @samuelklee and on behalf of our users.
> Clarify two uses of "Raw" in CNV workflow

- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
Currently, the GATKRead.getAttributeAsByteArray for a `String` attribute use the default CharSet, but it will be nice if the method sticks to a common representation by using a default charset. This PR adds a UTF-8 default encoding for this case in the GATKRead implementations to retrieve the bytes.
> Add default CharSet for retrieve bytes from String in GATKRead

- .travis.yml
- build_docker.sh
- scripts/m2_cromwell_tests/run_m2_wdl.sh
Previously we had an issue where our travis builds would use the wrong
commit for the docker builds in the travis pull-request builds but not for the push
builds.
This caused the tests from master to run and usually pass.  However,
since we are mounting the test data from the correct commit into the
docker, this would result in confusing mismatches where old tests would
try to run on new test data.
Fixing the problem by using the $TRAVIS_COMMIT environment variable
instead of the TRAVIS_BRANCH.
fixes #3216
> travis PR builds now use the correct commit in docker

- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/CountFalsePositives.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/FalsePositiveRecord.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/CountFalsePositivesIntegrationTest.java
- src/test/resources/wgs_calling_regions.v1.interval_list
With a large interval file e.g. WGS intervals it would return garbage as target territory and 0 as false positive rates. Now it's fixed
> Fix CountFalsePositives

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
This simplifies the code and didn't affect specificity in our validations.  @takutosato can you review this?
> No more prepareReadLikelihoodsForAnnotation in Mutect

- scripts/sv/runWholePipeline.sh
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/ReadClassifier.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/ReadClassifierTest.java
This PR fixes two problems I noticed relative to how we are treating cross-contig evidence that comes from the alt contigs:
- The cross-contig exclusion rule in `ReadClassifier` was incorrect. Due to the structure of the `if`-`else if` logic in `checkDiscordantPair()`, `SameStrandPair` or `OutiesPair` evidence was still being created for cross-contig pairs based on the strand configuration of the two reads (even though they were aligned to different contigs).
- The `runWholePipeline` script we've been using was not actually setting the cross-contig kill list parameter, meaning no cross-contig evidence was being filtered out.
The change makes the number of intervals for CMHMIX WGS1 drop from 31962 to 27645.
> [SV] Fix cross-contig exclusion issues

- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/LocusWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/AlignmentContextIteratorBuilder.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/IntervalAlignmentContextIterator.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/IntervalAlignmentContextIteratorUnitTest.java
Introducing the IntervalLocusIterator which will traverse every locus in intervals, regardless of coverage.
Minor changes
Removed imports.
AlignmentContextLocusIterator first cut.  Still needs unit tests.
Putting in the walker.  Still needs unit tests
Adding tests (and fixes) so that we can get AlignmentContexts.
Adding tests (and fixes) so that we can get AlignmentContexts.
Working tests.  Beginning migration to a LocusWalker change rather than a separate walker.
Merging the emit empty loci into locus walker.  Still need warnings and validation of parameters.
Next step is the LocusWalker testing.
Simple test of the new LocusWalker when it emit empty loci
Addressing PR requests and added ShardedIntervalIterator to save RAM on big intervals.
Addressing the rest of the PR comments
Rolling …
> Supporting empty loci emission for Spark tools

- scripts/sv/create_cluster.sh
Avoid spark crash by switching from preview to latest supported Dataproc image.
> sv/create_cluster.sh uses Dataproc image 1.1

- src/main/java/org/broadinstitute/hellbender/engine/AlignmentContext.java
Hi, I found the following minor comment bug while looking into code.
REVERSE  = reads on forward strand
-> REVERSE  = reads on reverse strand
Thanks!
> Fix a minor comment mistake in AlignmentContext

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/AlignedAssemblyOrExcuse.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
Now the assemblies file will be sorted by coordinates by default.... one can indicate the sorting order using an additional option (-sort coordinate|queryname|...). The assemblies sam/bam output format will depend on the file name extension: .bam -> binary BAM, .sam -> text SAM and anything else will result in an exception.
> Addresses #3242.

- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/test/java/org/broadinstitute/hellbender/engine/ReadsDataSourceUnitTest.java
Currently, if `ReadsDataSource` comes from several files, the `getHeader()` method is always returning a coordinate sorted header. Thus, it is difficult to assume that the input is pre-sorted or not for other sorting orders.
This PR implements a method to obtain the consensus between the files (ignoring the unknown sort order), and if there is no consensus falls back in the previous behavior (coordinate). In addition, it logs a warning with the current assumptions.
> Add SortOrder to ReadsDataSource.SamFileHeaderMerger based on inputs

- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
For `byte[]` attributes, the `GATKSAMRecordToGATKReadAdapter.getAttributesAsString()` uses the default `Object.toString()` (className@hashCode). This is something unexpected for my point of view, because the following code may fail:
```java
public void testGATKReadGetAttributeAsString(final GATKRead read) {
read.setAttribute("BC", new byte[]{'A', 'C', 'T', 'G'});
// this will fail with the current implementation
Assert.assertEquals(read.getAttributesAsString("BC").getBytes(Charset.forName("UTF-8")),
read.getAttributeAsByteArray("BC"));
}
```
This PR fixes the issue by identifying `byte[]` attributes and converting them to Strings by using the default GATKRead charset (UTF-8).
> Fix GATKSAMRecordToGATKReadAdapter.getAttributeAsString for byte[]

- src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java
- src/main/java/org/broadinstitute/hellbender/utils/UniqueIDWrapper.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFiltererUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
Closes #3291 
- Detects the issue earlier and fails with a better error message that is local (in code) to the problem.
- Removes the spew of warnings that are not useful except in debug.
- Fixes an issue where filter values were being replaced instead of appended.
- Implemented a wrapper to always guarantee sorting never collides.
> Fixing hash collision issue when adding filter value to the variant context

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
This moves us to a snapshot of google-cloud-java based off of a branch in my fork here: https://github.com/droazen/google-cloud-java/tree/dr_retry_CloudStorageReadChannel_fetchSize. This patch wraps many more operations within retries, and in our tests resolves the intermittent 503/SSL errors completely when running at scale.
This PR also migrates us from setting retry settings per-Path to setting it globally, using a new API from that google-cloud-java branch. This fixes an issue where the number of reopens was getting set to 0 deep in the google-cloud-java library.
Resolves #2749
Resolves #2685
Resolves #3118
Resolves #3120
Resolves #3253
> Move to google-cloud-java snapshot with more robust retries, and set number of retries/reopens globally

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/UniqueAltReadCount.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedVariantContextUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/UniqueAltReadCountUnitTest.java
Migrated from broadinstitute/gatk-protected#1109
> Filter Mutect2 artifacts that arise from apparent-duplicate reads

- src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java
This seems to address issue #2885.  @cmnbroad @samuelklee
> undid override of CalculateTargetCoverage.GroupBy::toString

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/ApplyVQSR.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/GatherTranches.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/Tranche.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/TrancheManager.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/TruthSensitivityTranche.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VQSLODTranche.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantDataManager.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/report/GATKReportTable.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/GatherTranchesIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/TruthSensitivityTrancheUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantGaussianMixtureModelUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorModelOutputUnitTest.java
- src/test/resources/large/VQSR/expected/snpRecal.scattered.vcf
- src/test/resources/large/VQSR/expected/snpRecal.scattered.vcf.idx
- src/test/resources/large/VQSR/expected/snpSampledRecal.vcf
- src/test/resources/large/VQSR/expected/snpSampledRecal.vcf.idx
- src/test/resources/large/VQSR/expected/snpSampledTranches.txt
- src/test/resources/large/VQSR/expected/snpTranches.gathered.txt
- src/test/resources/large/VQSR/snpTranches.scattered.2.txt
- src/test/resources/large/VQSR/snpTranches.scattered.txt
New functionality to limit the amount of memory needed to read in all the data, intended for use with large WGS callsets.  (VQSR downsamples training data if there are more than 2.5M variants anyway.)
Also contains port of broadinstitute/gsa-unstable#1608 and broadinstitute/gsa-unstable#1575
Addresses #3230
> Port VQSR model serialization and add data sampling

- src/main/java/org/broadinstitute/hellbender/Main.java
When an error occurs, we currently print this:
> Use -DGATK_STACKTRACE_ON_USER_EXCEPTIONto print the stack trace.
In addition to missing a space, this doesn't work with gatk-launch. Replace this with:
> Use the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--javaOptions '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
> Fix stack trace error message.

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportUnitTest.java
This adds the option to use multithreading to load multiple headers at the same time when initializing FeatureReaders.  
Empirically this speeds up large runs of GenomicsDBImport over GCS by 20-30%.
> multithreaded vcf header loading for GenomicsDBImport

- .travis.yml
- Dockerfile
Also reduced the overall number of tests to execute by eliminating non-docker unit and integration tests from the travis.yml.
I would suggest checking that the docker tests in this travis execution actually uploaded to where it says they do on gcloud.
> Added functionality for travis tests to upload reports from a docker image 

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
This includes the fix for the position overflowing in CloudStorageReadChannel
(https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2283), as well
as the fix for the intermittent 503 errors we've already been depending on
(https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2281)
> Update google-cloud-nio dependency to 0.20.4-alpha-20170727.190814-1:shaded

- src/main/java/org/broadinstitute/hellbender/tools/exome/copyratio/CopyRatioModeller.java
Just a patch to make the change suggested in the review of broadinstitute/gatk-protected#1001.  @asmirnov239 your comment was correct, not sure what I was thinking back then!
Closes #3372.
> Increased maximum copy-ratio variance slice-sampling bound.

- .travis.yml
There is a second and perhaps more proper method for accomplishing the same thing commented out in the travis.yml which I could not get to work immediately. I invite suggestion as to whether this should be our approach, It would still require separate code in order to remove older zips from the repository.
fixes #3168
> Added support for uploading the zipped gatk file on a nightly basis to google buckets

- AUTHORS
Updating the AUTHORS file to include authors who contributed to gatk-protected who's work has been integrated into GATK by the merger.
I need to find out the preferred emails for the newly listed authors.
Anders Peterson
Ayman Abdel Ghany <aymana.ghany@devfactory.com>
Kenji Kaneda 
Nils Homer
@apete @AymanDF @kkaneda @nh13 Would you like to be included here and if so, what email address would you like listed?  Have I spelled your name correctly?
Resolves #3048
> updating AUTHORS to include gatk-protected authors

- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContamination.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/ContaminationRecord.java
@takutosato This corrects the math error you pointed out in your code review of the docs.  While we're at it, it also outputs the error bars according to the formula given in the docs.  I have tested it on an in silico contamination series and it improves results slightly.
> fixed contamination calculation, added error bars to output

- build.gradle
This release fixes (among other issues) a bug that could cause the
AVX compatibility check to hang on CentOS machines.
> Update to Intel GKL version 0.5.3

- scripts/sv/copy_sv_results.sh
- scripts/sv/create_cluster.sh
- scripts/sv/manage_sv_pipeline.sh
- scripts/sv/runWholePipeline.sh
Add new scripts to gatk/scripts/sv/ folder, and alter action (but not
passed parameters) of older scripts to make running sv spark jobs
more convenient.
Added:
-copy_sv_results.sh: copy files to time and git-stamped folder on
google cloud storage
-> results folder on cluster
-> command line arguments to SV discover pipeline
-> console log file (if present)
-manage_sv_pipeline.sh: create cluster, run job, copy results, and
delete cluster. Manage cluster naming, time and git-stamping,
and log file production.
Altered:
-create_cluster.sh: control GCS zone and numbers of workers via
environmental variables. Defaults to previous hard-coded values.
-runWholePipeline.sh: accept command-line arguments for sv
discovery pipeline, work with clusters having NUM_WORKERS != 10
> Add scripts to manage SV spark jobs and copy result

- .travis.yml
The nightly builds weren't working due to a race condition with the travis build status indicator, so the checks were removed.
> Removed checks for build status of master for nightly builds

- build.gradle
GKL 0.5.5 fixes a critical bug in the FPGA PairHMM implementation. The bug produces a segmentation fault when FPGA PairHMM is invoked in 'private' mode. GKL 0.5.5 is otherwise identical to 0.5.3.
> Update to Intel GKL version 0.5.5

- src/main/java/org/broadinstitute/hellbender/transformers/BaseQualityClipReadTransformer.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
- src/test/java/org/broadinstitute/hellbender/transformers/BaseQualityClipReadTransformerTest.java
The earlier version of BaseQualityClipReadTransformer clipped bases by just removing them from the bases and base qualities arrays, but did not adjust the cigar, coordinate, etc. (thanks to @SHuang-Broad for catching this in #3354).
This commit fixes this behavior by invoking the ReadClipper class and adds cigar checking to the unit test. It also makes some minor style changes to the transformer and test code.
> Use ReadClipper in BaseQualityClipReadTransformer

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectAllelicCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContamination.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
Addresses issue #3173 
I'd welcome advice from @cmnbroad on how to deal with the issue in CalculateContamination where the `@` starting the header lines in the example of Picard interval list breaks the docgen.  My hacky workaround is to add a dot before the @ but it's icky.
> Minor doc fixes - addresses issue 3173

- src/main/java/org/broadinstitute/hellbender/Main.java
this fixes the yarn early termination bug reported in #2666 and #3166
> removing the explicit System.exit(0) from Main

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
The MuTect2 headers ECNT, TLOD and NLOD are currently strings. It is more accurate to describe these fields as integer, float and float.
> Fix MuTect2 INFO field types in the VCF header

- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilterArgumentCollection.java
The PathSeq filter repartitioning the reads directly before the BWA host filtering step to even out the load on each partition. This is helpful for typical samples with low pathogen abundance, when ~90% of the reads are filtered before this step. 
However, in some sample types such as stool, saliva, or environmental samples, one can have a large number of reads (i.e. ~10M) at this stage so the cost of the repartition shuffle outweighs the benefit of load balancing for the slow BWA step. 
This PR exposes a tool argument to skip the repartitioning.
> Add option to skip pre-Bwa repartitioning in PSFilter

- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSPathogenTaxonScore.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSScorer.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSScorerTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqTestUtils.java
Upgrades PathSeqScoreSpark to perform abundance score calculations on the executors rather than the driver. This was crashing on inputs with a lot of pathogen reads. 
This also required some minor changes to the `PSPathogenTaxonScore` class to be able to keep track of abundance score contributions that come directly from hits to that taxon and those that are from the taxon's descendents.
As a result, some of the test output changed when using bitwise, exact checks on the output. So the tests now check for output equivalence, meaning parsing the scores table, checking that all the taxa are the same, and that the scores are equal to within some defined epsilon.
> Implement PathSeq taxon hit scoring in Spark

- .dockerignore
- Dockerfile
- build_docker.sh
This reduces the size of the docker image from ~9GB when LFS tests were being run to 2.74GB
fixes #3414
> Added a .dockerignore file to the gatk

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/codecs/TargetCodec.java
- src/test/java/org/broadinstitute/hellbender/utils/codecs/TargetCodecUnitTest.java
TargetCodec is dependent on the old htsjdk indexing scheme whereby the indexer called readActualHeader on the codec first (for the side effect of initializing the codec header state), and then manually processed the feature file contents by:
- re-creating the input SOURCE/stream a second time
- NOT calling readActualHeader
- extracting and passing the features one at a time to the codec's decode method, using the stream position to find the feature file offsets
Although this scheme worked with TargetCodec, it had several other failure modes (see https://github.com/samtools/htsjdk/pull/906). With https://github.com/samtools/htsjdk/pull/906, the SOURCE/stream is only opened once for indexing. However, TargetCodec uses an underlying CSVReader that automatically buffers input, which confounds …
> Upgrade to htsjdk 2.11.0. Make TargetCodec indexable.

- scripts/sv/manage_sv_pipeline.sh
This fixes a bug in handling the defaults for setting and using our default cluster initialization script for the SV pipeline. The master version will error if no init script parameters are specified.
> fix SV pipeline default init script handling

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AFCalculator.java
profiling of GenotypeGVCFs showed a lot of wasted time in VariantContext.toString() which can be tracked to computing an error message we never display in `AFCalculator.getLog10PNonRef`
fixing it so we only compute the message when we the error occurs
> prevent accidental toString call during validation

- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
MathUtils was using the log4j1 logger, fixed to use the log4j 2 logger
> use correct logger class in MathUtils

- .travis.yml
- README.md
- hooks/README.md
- hooks/post_push
These changes are needed for dockerhub automatic builds so that they will be triggered when we do our nightly builds.
> Adding in the necessary hooks to make the nightly builds automatic

- .gitignore
Building with Intellij 2017.2 generates an /out directory instead of using the build/ folder from gradle, that is show as untracked but can be committed by error.
This folder cannot be changed, even if the compiler output is changed (see CrazyCoder comment in https://stackoverflow.com/questions/45174989/building-with-intellij-2017-2-out-directory-duplicates-files-in-build-director).
> Add out/ to .gitignore

- build.gradle
Picks up VCF header performance fix.
> Upgrade htsjdk to 2.11.0-4-g958dc6e-SNAPSHOT.

- src/test/resources/large/.gitattributes
Only the top-level .gitattributes is needed these days, as it includes
all of large recursively via a wildcard.
> Remove extra .gitattributes file that got checked into large via an SV PR

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQualityRankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_BaseQualityRankSumTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java
Closes #1882.
Normally I assign the author of the issue for this kind of stuff, but Adam is no longer with us.  @ldgauthier would you mind looking and/or suggesting anything else on your wish list for the annotations code?
> fix code duplication in ReadPosRankSumTest and its allele-specific version

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
Not ready for merge as this relies on https://github.com/HadoopGenomics/Hadoop-BAM/pull/136, hence a new Hadoop-BAM release.
Addresses https://github.com/broadinstitute/gatk/issues/2572 and https://github.com/broadinstitute/gatk/issues/2571
> Support unmapped reads in Spark.

- scripts/spark_eval/exome_pipeline_single_gcs.sh
- scripts/spark_eval/small_pipeline_single_gcs.sh
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintVariantsSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintVariantsSparkIntegrationTest.java
Writing reads was fixed in https://github.com/broadinstitute/gatk/commit/73f2a62bee52518b57a985717770ed3a64d83243, but unfortunately the same problem occurs with variants.
This commit (https://github.com/broadinstitute/gatk/commit/a861a23b544012fb8f69358a3999dd587d343547) fixes the problem for variants, when deployed with a Hadoop-BAM fix (https://github.com/HadoopGenomics/Hadoop-BAM/pull/143).
> Fix writing variants to GCS buckets

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/test/java/org/broadinstitute/hellbender/MainTest.java
Tools with omitFromCommandLine=true can be run after this commit, but
they do not appear in the CLI help (they are hidden).
Related with https://github.com/broadinstitute/barclay/issues/92
> Add support for running tools with omitFromCommandLine=true

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SimpleStrandSwitchVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SvDiscoverFromLocalAssemblyContigAlignmentsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/experimental/FindSmallIndelRegions.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSparkUnitTest.java
but still runnable if knowing their existence
> hide prototyping tools in sv package

- src/test/java/org/broadinstitute/hellbender/BwaMemIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/coveragemodel/germline/GermlineCNVCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculatorsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AFCalculationUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/GeneralPloidyAFCalculationModelUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PairHMMLikelihoodCalculationEngineUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/recalibration/QualQuantizerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
There is quite a bit of code annotated with @BeforeSuite that should probably just be @BeforeClass. @BeforeSuite code can run even when no methods in the class are selected in the current suite. Most of it is harmless, but some of it is painfully slow, i.e., using gradle to run a single test method always causes the BwaMemIntegrationTest code to create an index image for the large test reference, which takes 1-2 minutes, before the selected test even starts.
We should probably reserve @BeforeSuite for test-infrastructure setup code; most test classes should use @BeforeClass instead.
> Fix @BeforeSuite usages to prevent excessive code execution

- src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
Randomly noticed this test that was disabled long ago. Between https://github.com/samtools/htsjdk/pull/704 and https://github.com/samtools/htsjdk/pull/906, it now works.
> Re-enable BED test in IndexFeatureFile.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/CalculateGenotypePosteriors.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/FamilyLikelihoods.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/CalculateGenotypePosteriorsIntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/CalculateGenotypePosteriors/CEUtriMixedPloidyTest.vcf
Implements https://github.com/broadinstitute/gatk/issues/3320.
Was throwing a ArrayIndexOutOfBoundsException because the number of PLs is set to 3. This is only true for diploid biallelics.
> Make error informative for non-diploid family likelihoods

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/optimization/PersistenceOptimizer.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/utils/optimization/PersistenceOptimizerUnitTest.java
This bit of code will be used for the new segmentation method, but could be more generally useful as well.  I put it in a utils package within the copynumber package for now, but we can put it somewhere else if more appropriate.
> Implemented watershed algorithm for finding local minima in 1D data based on topological persistence.

- build.gradle
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithRefBasesSparkUnitTest.java
I've had several Travis test failures (on my picard removal branch) that appear to be failures during kryo serialization of a mocked ReferenceMultiSource object (based on the failing class name, (org.broadinstitute.hellbender.engine.datasources.ReferenceMultiSource$$EnhancerByMockitoWithCGLIB$$b0dc631f, which looks like the CGLIB names mentioned [here](https://github.com/mockito/mockito/issues/319)).
We're on an ancient version of mockito anyway, and newer versions no longer use cglib, so it seemed like a good time to upgrade. To do so I also had to replace usage of the method getArgumentAt, which has been [deprecated](https://github.com/mockito/mockito/pull/373) in favor of getArgument.
> Upgrade Mockito from 1.10.19 -> 2.10.0.

- scripts/sv/create_cluster.sh
- scripts/sv/manage_sv_pipeline.sh
cluster timed self-termination (beta) feature.
Fixes #3574 considering that several people are suggesting beta from gcloud is safe enough.
> updates sv manager and cluster creation scripts to utilize dataproc

- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
- src/test/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptorTest.java
* Repackage and rename `org.broadinstitute.hellbender.engine.filters.ReadFilterPluginUnitTest` to `org.broadinstitute.hellbender.cmdline.GATKPlugin.GATKReadFilterPluginDescriptorTest`.
* Add `BaseTest` to `GATKReadFilterPluginDescriptorTest`.
* Make the filed `GATKReadFilterPluginDescriptor.userArgs` package-private now that it is possible. 
Closes #2532
> Repackage ReadFilter plugin tests

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceMultiSource.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
I've had ConcurrentModificationExceptions several times when mocked ReferenceMultiSource objects are both mocked and broadcast ([for example](https://travis-ci.org/broadinstitute/gatk/jobs/275982454)). Mocks appear to be mutated, even when the mocked object is immutable, so serialization can fail. This replaces the mock object with a faked one.
> Use a handmade TestReferenceMultiSource in tests instead of a mock.

- scripts/sv/manage_sv_pipeline.sh
manage_sv_pipeline checks version from gatk-spark.jar and compares it
to the current git hash (to ensure the correct version is run). Newer
gatk versions had a slightly different file name format and caused
errors parsing the hash. This updates the hash check and produces
more comprehensible error messages when it fails.
Resolves: #3593
> Fix bad version check in manage_sv_pipeline.sh

- README.md
Updating the README.md to fix the R installation instructions which were out of date.
scripts/install_R_packages.R -> scripts/docker/gatkbase/install_R_packages.R
fixes #3601
> update README with correct path to install_R_packages.R

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
This reverts commit b47838c9a5fa172ed6669ed4872b04d91c962a85.
This commit introduced a major issue for spark https://github.com/broadinstitute/gatk/issues/3591.
> Revert "Move to google-cloud-java:0.23.1-alpha. (#3576)"

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriter.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriterUnitTest.java
updating to a new htsjdk snapshot and updating our VariantContextWriters to compile
test may fail on this....
> updating to newer htsjdk snapshot

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtilsUnitTest.java
Thanks to the work already done by @lbergelson, I added the ability to compare two variant contexts for equality by sorting them and remapping their attributes to the correct value and then comparing the sorted variant contexts for equality. 
Fixes #2599
> Added allele order independent VariantContext equality comparison

- build.gradle
Changes include: AVX-512 on non-Mac Skylake + ISA-L 2.19 for level 1 compression. AVX-512 support for OS X is planned for the near future.
> Upgrade to GKL 0.7

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/optimization/PersistenceOptimizer.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/segmentation/KernelSegmenter.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/utils/segmentation/KernelSegmenterUnitTest.java
Some of the posts in #2858 might be helpful in reviewing this PR.
> Added KernelSegmenter.

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVContext.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVContextUnitTest.java
This is more in-line with other SV class names.
Also SVContext.create is renamed to SVContext.of
> Renames StructuralVariantContext to SVContext.

- .travis.yml
I asked about a status update on the travis image space issue in the travis ticket, and based on feedback I tried moving to the new image. It seems to work now. Fixes https://github.com/broadinstitute/gatk/issues/3559.
> Revert use of deprecated travis image.

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/VariantAnnotationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQuality.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/Coverage.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerAlleleBySample.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/FragmentLength.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/MappingQuality.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/OxoGReadCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosition.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StandardMutectAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StandardSomaticAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandArtifact.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/TandemRepeat.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/UniqueAltReadCount.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
Fixes #3618
Fixes #3292 
Fixes #3123
> Created VariantAnnotationArgumentCollection and StandardM2Annotation classes

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/AlignedAssemblyOrExcuse.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/KmerCounter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/QNameIntervalFinder.java
- src/main/java/org/broadinstitute/hellbender/utils/spark/SparkUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignedContigGeneratorUnitTest.java
Here's a tiny commit that's mostly just code cleanup.  @SHuang-Broad -- I sprinkled some "final"s around.
> add elapsed time to assembly info in intervals file

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AnnotatedVariantProducer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SimpleSVType.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/InsDelVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SimpleStrandSwitchVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointEvidence.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/EvidenceTargetLink.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/EvidenceTargetLinkClusterer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/LibraryStatistics.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/sga/DiscoverVariantsFromContigAlignmentsSGASpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFConstants.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFHeaderLines.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/PairedStrandedIntervalTree.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVContext.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVInterval.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalTree.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVVCFWriter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/StrandedInterval.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AnnotatedVariantProducerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/DiscoverVariantsFromContigAlignmentsSAMSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVContextUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/spark/sv/integration/hg19_DEL.vcf
This PR adds logic to use imprecise evidence (gathered from discordant read pair mappings and split reads with supplementary alignments) to:
- Annotate events that we are calling from assembled breakpoints with the number of discordant read pairs and split reads that support those events.
- Call new variants when an imprecise evidence link supporting a deletion is supported by a minimum number of pieces of evidence (set to 7 by default in this PR; parameters can be tuned later).
In an initial run on the CHM mix this uses 3500 evidence-target clusters to annotate our existing deletion calls and makes an additional 670 IMPRECISE deletion calls. Initial visual evaluations against the CHM truth set looks good on visual inspection; more detailed evaluations will follow.
> Imprecise deletion evidence annotation and variant calling

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/OxoGReadCounts.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
@LeeTL1220 you were right.  Fortunately the fix is very simple.
> fixed bug in which F1R2 and F2R1 annotation kept discarded alleles

- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilter.java
- src/main/java/org/broadinstitute/hellbender/transformers/StripMateNumberTransformer.java
- src/test/java/org/broadinstitute/hellbender/transformers/StripMateNumberTransformerTest.java
Adds a read transformer that removes the "/1" and "/2" from read names to the PathSeq filter phase. This seems to be the way TCGA RNA-seq BAMs are formatted.
> Have PSFilter strip mate number from read names

- src/main/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSparkEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BwaAndMarkDuplicatesPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaAndMarkDuplicatesPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSparkIntegrationTest.java
This removes the need to use the Spark `--files` argument and the `BwaSpark` `--bwaMemIndexImage` argument, since instead the `.img` file will be distributed for the user based on the reference argument (`-R`).
> Automatically distribute the BWA-MEM index image file to executors for BwaSpark

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVFastqUtils.java
there is a read with the cigar 44I107S, which is complete gibberish, in the NA12878 bam.
it's nonsense, but we can't afford to blow up.
> quick fix for broken read (mapped to no ref bases)

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportUnitTest.java
the sample swap issue seems to have been caused by the fact that the callset.json files had the sample names globally sorted
the actual data was entered in the order the sample names were input, but each bactch was sorted within the batch
this produced a mismatch between data and samplename mapping
fixing it by using sorted map everywhere sample names are handled
modifying our tests to use an out of order sample map file and multiple batches
> fixing sample name reordering in GenomicsDBImport

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AnnotatedVariantProducer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SimpleSVType.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVContext.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSparkUnitTest.java
This PR fixes a critical error that was causing an "invalid interval" exception to be thrown while calling imprecise deletion intervals. The problem was a mismatch between the sequence dictionary in the reference and the read metadata's contig ID - contig name mapping. I've modified the code to always use the read metadata when translating the contig ID in `EvidenceTargetLink` intervals into contig names.
> fix bug causing error finding ref base for imprecise deletions

- build.gradle
- gatk-launch
htsjdk has updated to a newer version of snappy (https://github.com/samtools/htsjdk/pull/872) which makes it compatible with the rest of the world's snappy
this means we can re-enable snappy usage in htsjdk which should give performance improvements in tools that use `SortingCollection`
this is a permanent solution to #2026 that replaces the changes we made in #2028
> re-enable snappy use in htsjdk

- scripts/sv/manage_sv_pipeline.sh
- scripts/sv/runWholePipeline.sh
- scripts/sv/stepByStep/discoverVariants.sh
- scripts/sv/stepByStep/scanBam.sh
- scripts/sv/stepByStep/svDiscover.sh
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/InsDelVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SimpleStrandSwitchVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SvDiscoverFromLocalAssemblyContigAlignmentsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/VariantDetectorFromLocalAssemblyContigAlignments.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVVCFWriter.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/DiscoverVariantsFromContigAlignmentsSAMSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/StructuralVariationDiscoveryPipelineSparkIntegrationTest.java
(for its dict) for sorting variants in output VCF, now using header in input SAM/BAM
> removing required FASTA reference input in SV discovery pipeline

- src/test/java/org/broadinstitute/hellbender/utils/nio/ExtremeReadsTest.java
This was a very useful debug tool when working on issue #2685. It sends many parallel reads for a long time. This makes sure that the combination of the cloud provider's throttling and our own retry parameters allows us to eventually read everything to completion and not fail with disconnection errors.
This test is disabled by default, because it takes too long to be run every time. But if there's a doubt about retries we can dust it off and run it.
> Add ExtremeReadsTest

- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleAssemblyRegionWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleAssemblyRegionWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleFeatureWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleIntervalWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleIntervalWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleNioCountReads.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExamplePostTraversalPythonExecutor.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithReference.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithReferenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleVariantWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleVariantWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/metrics/multi/ExampleCollectMultiMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/metrics/single/ExampleCollectSingleMetricsSpark.java
Example tools are not documented features, and are provided for being examples for developers to build their own traversals and for testing purposes. Thus, it is unnecessary to show them in the command line help, which already contains a huge list of tools (GATK, Picard, etc).
Although they can still be run from the command line if you know its existence, they won't be shown after #3486.
> Add omitFromCommandLine=true for example tools

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointEvidence.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadMetadata.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointDensityFilterTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointEvidenceTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadMetadataTest.java
* Added new option --unfilteredBreakpointEvidenceDir
When set, this option dumps all evidence (even evidence that is
ultimately rejected) in an easy to parse text format. Some additional
info (cigarString, mappingQuality) is stored in ReadEvidence to output
information related to read quality.
* Updated option --readMetadata
When set, will additionaly output the map from contig number to contig
name. Added non-null ParitionBounds to readMetadata in
ReadMetadataTest::testEverything to prevent crash.
> Dump more evidence info for SV pipeline debugging

- Dockerfile
- scripts/docker/gatkbase/build_docker_base.sh
- scripts/docker/gatkbase/install_R_packages.R
Oops, looks like they just updated the URL last week.  Perhaps another reason why we should host these dependencies or have some simple contingencies for testing them other than manually building the base image.
> Update data.table R dependency.

- build.gradle
This change suppresses about 600k of output from the gatkTabComplete task, which should fix #3710 and allow the nightly cron job to complete. Note that this doesn't actually suppress the excessive "backtrace" messages we're seeing with the addition of Picard tools when running javadoc using openjdk (see the note in #3710), which we'll need to do separately in Barclay.
To test this change, I added a temporary travis matrix entry that runs the target that is causing the cron job to fail (./gradlew bundle). That branch [fails](https://travis-ci.org/broadinstitute/gatk/builds/289636845) the same way as the cron job does without this change, and [succeeds](https://travis-ci.org/broadinstitute/gatk/builds/289569595) with it. But that doesn't guaranty that the cron job will succeed, since cron …
> Turn off verbose for gatkDoc/gatkTabComplete tasks.

- build.gradle
This fixes a memory leak caused by a bug BwaMemIndex.close()
Resolves #3723.
> Updates gatk-bwamem-jni dependency to 1.0.3

- src/test/java/org/broadinstitute/hellbender/utils/read/CigarConversionUtilsUnitTest.java
Because the data provider was failing while constructing a cigar with negative length...
> Fix skipped CigarConversionUtilsUnitTest.testHandleInvalidCigarElement

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignedContig.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AnnotatedVariantProducer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakEndVariantType.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/GappedAlignmentSplitter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/NovelAdjacencyReferenceLocations.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SimpleSVType.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/ContigAlignmentsModifier.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/InsDelVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SimpleStrandSwitchVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SuspectedTransLocDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SvDiscoverFromLocalAssemblyContigAlignmentsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/RDDUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVVCFWriter.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AnnotatedVariantProducerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignmentUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/GappedAlignmentSplitterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/NovelAdjacencyReferenceLocationsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SVDiscoveryTestDataProvider.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SVTypeUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/ContigAlignmentsModifierUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSparkUnitTest.java
This PR deals with long reads with exactly two alignments (no other equally good alignment configuration), mapped to 
* the same chromosome with reference order switch but without strand switch, or
* different chromosomes
This brings us (unfiltered) ~6000 mated BND records, half of which are on canonical chromosomes.
> PR series for complex SV, part 5

- build.gradle
Picks up https://github.com/broadinstitute/picard/pull/875, which was a backport from GATK.
> Upgrade Picard to 2.14.0.

- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureInput.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureInputUnitTest.java
Propose to reduce redundantly cracking open a path/stream to discover the correct feature codec. We do this twice for each feature input, which for multi-variant walkers with large # of inputs can be a lot. This caches the codec class in a FeatureInout the first time we find it. Ideally FeatureManager would remember it, but not all of the FeatureDataSources are created by Feature Manager (and fixing that is a bigger refactoring).
> Cache the codec class used for a FeatureInput so we only have to discover it once.

- build.gradle
previously we dependend on com.github.fommil.netlib:netlib:all which is a pom only dependency that includes a number of jars containing native code
this caused problems when importing GATK using maven, see #3724
to fix this, I've added the exact versions of the transitive dependencies that we want
an added bonus is that it means we are no longer including  native code for systems we don't support, like arm, 32 bit systems, and windows
> specifying com.github.fommil native dependencies explicitly

- src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java
Noticed some compile warnings in the Travis logs, looks like a funky apostrophe is to blame?
:compileJava/gatk/src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java:511: error: unmappable character for encoding ASCII
// if there???s more than 1 DEL allele then we need to use the best one
^
> Fixing an ASCII warning.

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java
an edge case where "==" is to be distinguished from "<=" or ">=".
The reason is that when two quantities are equal, the value to be deduced from their difference is simply zero and an expensive computation could be avoided (the method performing the expensive computation has a check for such optimization opportunity and caught this).
> fix a bug in alt haplotype sequence extraction for inv dup

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/CombineSegmentBreakpoints.java
- src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
- expanding unit tests to actually replicate the error if we have a regression.
- applied fix that sorts the output.
> Fixing contig ordering issue when calling CombineBreakpoints

- Dockerfile
- build_docker.sh
This will not affect our nightly build naming patterns as that is generated manually by the script.
Fixes #3700
> Removed "SNAPSHOT" from the gatk jar in the docker images

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
We've been encountering transient 403 errors when using GCS NIO.
It seems that some GCS-related service is incorrectly returning 403 in
certain cases where we do actually have permission to access a resource.
This commit moves us to a google-cloud-java snapshot that retries upon
403 errors:
https://github.com/droazen/google-cloud-java/commit/6d11bef1c81f885c26b2b56c8616b7a705171e4f
Resolves #3735
> google-cloud-java: switch to a snapshot that retries on 403 errors

- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/nio/GcsNioIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadUtilsIntegrationTest.java
The GCS ReadUtils tests are failing intermittently on the Barclay upgrade branch, probably due to filename collision when tests are running in parallel on Travis because the tests don't use unique temporary filenames.
> Change tests to not clobber GCS files being used by other tests.

- src/test/java/org/broadinstitute/hellbender/engine/GATKToolUnitTest.java
- src/test/resources/picard_intervals.list
Test to verify that picard interval lists are handled properly by GATK tools. Validates the fix for https://github.com/broadinstitute/gatk/issues/3555.
> Add GATKTool unit test for picard interval lists.

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
it seems like the only change necessary was in our code
removing pointless asserts
adding tests the deal with renaming
> fix to allow sample renaming to work correctly in GenomicsDBImport

- build.gradle
GKL 0.8.2 version has a bugfix that resolves Intel-HLS/GKL#81.
> Update GKL to 0.8.2

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/AssemblyContigAlignmentSignatureClassifier.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/AssemblyContigWithFineTunedAlignments.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SvDiscoverFromLocalAssemblyContigAlignmentsSpark.java
for multiple alignment fine tuning for 
* sending back some contigs back to the 2 alignment logic tree, as handled by #3752 , and 
* capturing more incomplete picture assemblies, and 
* sending the assembly contig seemingly has a complete picture down the multiple alignment logic tree, which is being finalized.
To be merged after #3752 is reviewed.
Code for hooking it up exists and is minimal.
> Cpx SV PR series, part-7: Finetune multiple/chimeric alignment of a single assembly contig

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandArtifact.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngineUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/StrandArtifactUnitTest.java
Before it was throwing a NullPointerError.
Fixes #2797
> Changed StrandArtifact to warn and not annotate if the 'TLOD' attribute is missing from the VariantContext

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/unsupported/mutect2_opt.wdl
- src/main/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBias.java
So as to avoid a conflict with -A for annotations.
closes #3875
> Making -A become -AM in FilterByOrientationBias.

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/utils/help/GATKDocWorkUnit.java
- src/main/java/org/broadinstitute/hellbender/utils/help/GATKHelpDoclet.java
- src/main/java/org/broadinstitute/hellbender/utils/runtime/RuntimeUtils.java
Consolidate program GATK program groups with Picard, and identify Picard tools in doc and help output:
> Identify Picard tools in help/doc using " (Picard)" suffix.

- src/main/java/org/broadinstitute/hellbender/engine/filters/LibraryReadFilter.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
Part of https://github.com/broadinstitute/gatk/issues/3144, maintaining the usage as before but allowing multiple `--library` arguments to provide more than one library...
> Support several libraries in LibraryReadFilter

- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/test/java/org/broadinstitute/hellbender/utils/StringSplitSpeedUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
Based on timing results (see below), we should do two things:
1) Switch to the HTSJDK `ParsingUtils::split` method for all
cases where we split a string using a single character.
2) Switch to the `Utils::split` method for all cases where
we split a string by another string of length > 1.
A quick stopgap that will reduce splitting time by ~1/2 is to just
replace all calls to Java's `String::split` with `Utils::split` (since
they both take two Strings as arguments, it should be very easy).
Also, I have disabled the test so that it doesn't slow down testing cycles.
Fixes #3759
| Method | Benchmark | Total Time (ns) | Total Time (ms) | Time Per Split Operation (ns) | Time Per Split Operation (ms) |   
| --- | --- | --- | --- | --- | --- |
| Java String::split | Split on Words | 131867865203 | …
> Added Utils::split (and tests).  Added performance test for string splitting.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHet.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeff.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/PedigreeAnnotation.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHetUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeffUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeff/testtrio.ped
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/testPedigree.ped
Currently there is no way to supply the pedigree file, but that is dependent on #3287 but this is a first step to implementing the pedigree annotations. 
The current plan is still to have the pedigree file be an argument on the tool but to reconcile them using the pluginDescriptor since there is currently one tool which takes a ped file that doesn't have annotations.
Fixes #3939 
Fixes #2542
> Added pedigree file support for InbreedingCoeff and ExcessHet

- .travis.yml
- Dockerfile
- README.md
- build.gradle
- scripts/gatkcondaenv.yml
- src/test/java/org/broadinstitute/hellbender/utils/python/PythonEnvironmentIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/python/PythonScriptExecutorUnitTest.java
- Adds the “gatk” conda environment, with dependencies defined by the file scripts/gatkcondaenv.yml.
- Updates the docker image to include the activated conda environment.
- Adds a new entry to the travis test matrix for running tests that depend on Python and the conda environment.
- Adds a “python” test group. Any tests for tools or functionality that are dependent on Python should be put into this group. Tests in this group will be executed in a docker container on travis in the python build matrix entry only.
- The existing WDL tests are unchanged; so although they execute in the context of the docker container and conda environment, there are no tests (yet) that are actually dependent on the conda environment and run through cromwell.
> Create a conda-based Python environment.

- .travis.yml
Travis [updated](https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/) the trusty images last night (seems to be ok so far). They also added a new update schedule and a new [group](https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images) declaration. The default appears to be "stability ensured", but this adds an explicit declaration for that.
> Use "stability ensured" trusty image on travis.

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
This should prevent the confusing case of accidentally corrupting an existing GenomicsDB.  The next genomicsDB update is supposed to make this unnecessary, but until it happens lets avoid this problem.
> throw if GenomicsDBImport tries to import into existing directory

- src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/main/java/org/broadinstitute/hellbender/utils/downsampling/MutectDownsampler.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
This greatly reduces wall clock time in M2 scatters without affecting sensitivity.  It is decoupled from HaplotypeCaller's downsampling.
> Mutect downsampler that recognizes and skips bad mapping regions

- src/test/java/org/broadinstitute/hellbender/utils/runtime/AsynchronousStreamWriterServiceUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/4024. The timeout for this test was relatively short, and we hit it once in travis, so lengthen it a lot to ensure we don't get random failures. Also removed a couple of unreferenced lines of code.
> Update AsynchronousStreamWriterService unit test timeouts.

- scripts/cnv_wdl/somatic/cnv_somatic_oncotate.wdl
This WDL change is needed for two reasons:
- keep formats the same as previous CNV oncotator outputs
- remove any sequence dictionary that might be prepended to the incoming seg file, which oncotator cannot handle.
> Getting rid of '@' from lines when generating the oncotated outputs.

- Dockerfile
- build.gradle
- scripts/gatkcondaenv.yml
- src/main/python/org/broadinstitute/hellbender/gatkpython/__init__.py
- src/main/python/org/broadinstitute/hellbender/setup.py
- src/test/java/org/broadinstitute/hellbender/utils/python/PythonEnvironmentIntegrationTest.java
We need a way to install GATK Python modules onto the docker image, from repo source, in a way that doesn't assume a repo clone is present on the docker image (there currently is one, but we want to remove it to recover space), and that also doesn't make the conda environment dependent on a repo clone.
This PR adds a build task that creates a zip archive of the GATK Python source; propagates that to the docker image, and then pip installs the contents of the archive into the conda environment on the docker. Since we don't have an actual python module in the repo at the moment, there is a second, temporary, commit that contains a dummy python module used only to trigger and test that the installation works.
> Install GATK Python packages.

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotModeledSegments.java
> Added missing fullName for sequence dictionary in PlotModeledSegments.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/mcmc/GibbsSamplerCopyRatioUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/runtime/ProcessControllerUnitTest.java
this bring our version of commons-io from 2.4 -> 2.5 and removes use of
deprecated functions
it unblocks updating the adam version which relies on commons 2.5
unblocks #4044
> update apache commons-io 2.4->2.5

- build.gradle
* gatk-native-bindings
0.1.0-rc1 -> 1.0.0
these versions are identical
* gatk-bwamem-jni
1.0.3 -> 1.0.4
this includes a new method to get the name of the default image	file
* gatk-fermilite-jni
1.0.0-rc6 -> 1.1.0
these versions should be identical, the rc6 tag is missing from the repo so it's hard to be perfectly sure though
it's going to 1.1.0 because we already have a 1.0.0 version ofmysterious provenance in central
closes #4030
> updating some of our libraries to 1.0+ versions

- src/main/java/org/broadinstitute/hellbender/engine/ReferenceContext.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
- Deprecated FuncotatorUtils.getCodingSequence (until its fixed).
- Added a more descriptive error message when the reference does not contain sequence information for a given position.
- Fixed all args to be kabob case.
- Fixed high-level Funcotator documentation.
Fixes #4021
> Adding in new, better documentation for Funcotator.

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BwaAndMarkDuplicatesPipelineSpark.java
We seem to have introduced a dumb regression in our spark tools when we added support for a gcs reference.  This should fix it.
> fix reference bug

- src/main/java/org/broadinstitute/hellbender/tools/BwaMemIndexImageCreator.java
- src/main/java/org/broadinstitute/hellbender/tools/ClipReads.java
- src/main/java/org/broadinstitute/hellbender/tools/ConvertHeaderlessHadoopBamShardToBam.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/CreateHadoopBamSplittingIndex.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/ClipReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/ConvertHeaderlessHadoopBamShardToBamIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSparkIntegrationTest.java
Documentation update for the following tools:
BwaMemIndexImageCreator
ClipReads
CompareDuplicatesSpark
ConvertHeaderlessHadoopBamShardToBam
CreateHadoopBamSplittingIndex
> Update documentation for various tools (MW)

- src/main/java/org/broadinstitute/hellbender/utils/help/GATKHelpDocWorkUnitHandler.java
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.template.html
- src/test/java/org/broadinstitute/hellbender/utils/test/DocumentationGenerationIntegrationTest.java
GATK tools use the tool javadoc for the summary details, but Picard tools rely on the summary line, so special-case Picard tools so the details aren't stranded.
> Use Picard-style doc summaries when generating doc for Picard tools.

- build.gradle
`com.google.cloud:google-cloud-nio:0.20.4-alpha-20171031.194208-5:shaded` -> `org.broadinstitute:google-cloud-nio-GATK4-custom-patch:0.20.4-alpha-GCS-RETRY-FIX:shaded`
This artifact should be functionally identical to our previous artifact but it's hosted in maven central instead of our artifactory.
closes  #4008
> updating to use our google-cloud-nio build from central

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
@lbergelson Does this look reasonable to you?
> made min-base-quality-score argument actually do something. Closes #4126.

- build_docker.sh
This fixes an issue in build_docker.sh where the script was
rebuilding the image from scratch when creating the "latest"
tag.
> build_docker.sh: don't rebuild the image when tagging latest

- scripts/sv/create_cluster.sh
- scripts/sv/manage_sv_pipeline.sh
does two small things:
1. bump the image version so that we don't get the annoying "org.bdgenomics.adam.serialization.ADAMKryoRegistrator: Did not find Spark internal class. This is expected for Spark 1." message
2. name of cluster created with manage_sv_pipeline.sh now post-fixed with "master" or "feature" depending on if running master or a feature branch.
@TedBrookings can you please review?
> Sh sv cluster image ver upgrade and custom name

- src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/CNVPlottingLibrary.R
I didn't add a regression test because the most naive implementation of one would require adding a large test file.
Closes #4140.
> Changed CNV plotting to grep to temporary file when using fread to avoid Docker tmpfs issues.

- build.gradle
* moved a log message about creating the python bundle during build so it only triggers when the python bundle is actually being built
* previously it was emitted on every build
> prevent log message from triggering incorrectly

- src/test/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
* disables tests that use the now defunct google genomics reference API
* update BaseRecalibratorSparkIntegrationTest.testBQSRFailWithIncompatibleReference to not use the reference API
* fixes #4163
* these tests should be revisted and removed or replaced in #4166
> disabling tests that use google reference API

- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
* adding back GenomicDBImportIntegrationTest.testYouCantWriteIntoAnExistingDirectory that was accidentally deleted
* fixing spacing issues introduced in the same pr
* removing unused parameter from internal method
> re-add GenomicsDBImport test that was deleted

- src/main/resources/log4j.properties
- src/main/resources/log4j2.xml
- src/test/java/org/broadinstitute/hellbender/engine/PipelineSupportIntegrationTest.java
Tested that piping seems to work by running `$ ./gatk SortSam -I file.bam -O /dev/stdout -SO coordinate | ./gatk SetNmMdAndUqTags -I /dev/stdin -O testSorted.bam --CREATE_INDEX true -R reference.fasta`
Fixes https://github.com/broadinstitute/gatk/issues/4135
Fixes https://github.com/broadinstitute/gatk/issues/4133
> Changed logging output to stderr

- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java
- src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
> IndexFeatureFile: more informative error message when trying to index a malformed file

- .travis.yml
- scripts/m2_cromwell_tests/test_m2_wdl_multi.json
- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_multi_sample.wdl
- scripts/mutect2_wdl/mutect2_pon.wdl
- scripts/mutect2_wdl/mutect2_template.json
- scripts/mutect2_wdl/unsupported/README.md
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity_all_plexes.wdl
- scripts/mutect2_wdl/unsupported/m2_basic_validation.wdl
- scripts/mutect2_wdl/unsupported/mutect2-replicate-validation.wdl
- scripts/mutect2_wdl/unsupported/mutect2_compare_tumors.wdl
- scripts/mutect2_wdl/unsupported/mutect2_multi_sample_concordance.wdl
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
Closes #2962 (clean M2 wdl)
Closes #2949 (hardcoded memory)
Closes #2970 (optional user-supplied sequencing artifact metrics)
Closes #3341 (comments from FC wdl)
Closes #3270 (smarter disk requirements)
Closes #3625 (remove picard jar)
Closes #4142 (merge improvements from mutect2_opt wdl)
@takutosato This ought to be the last significant change to the M2 wdl for a while.  I hope.
> Lots of updates to the Mutect2 wdl

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary.java
- src/main/java/org/broadinstitute/hellbender/utils/test/SimpleIntervalTestFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionaryIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
> updating to htsjdk 2.14.1

- src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureDataSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
Add a test that validates than an ambiguous interval query can be disambiguated by the user by providing the interval in a bed file; changes the error message to recommend this alternative; fixes an issue where the error message was displaying the entire interval query multiple times, rather than the specific contigs which make the query ambiguous.
> Use BED files as a way to resolve ambiguous queries.

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
Some code cleaning for `StandardArgumentDefinitions`
> Remove unused StandardArgumentDefinitions

- README.md
- build.gradle
Fixes the Python part of https://github.com/broadinstitute/gatk/issues/4209. Also updated the README with more specific instructions based on previous feedback from another user. This was tested manually.
> Change conda environment creation to work with release distribution.

- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CallCopyRatioSegments.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/caller/SimpleCopyRatioCaller.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/formats/records/AlleleFractionSegment.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotDenoisedCopyRatios.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/caller/SimpleCopyRatioCallerUnitTest.java
Although identification of the copy-neutral state is still relatively manual, this will at least make the tool usable for samples with high ploidy until @MartonKN finishes up the new caller.
> Exposed bounds for copy-neutral segments in CallCopyRatioSegments.

- build.gradle
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
- src/test/resources/large/NA24385.vcf.gz
- src/test/resources/large/NA24385.vcf.gz.tbi
This PR adds:
- Allele Annotation Support #3707 (w/ changes requested in [4047](https://github.com/broadinstitute/gatk/pull/4047))
and fixes:
- [4160](https://github.com/broadinstitute/gatk/issues/4160)
- [4106](https://github.com/broadinstitute/gatk/issues/4106)
- [3736](https://github.com/broadinstitute/gatk/issues/3736)
- [3745](https://github.com/broadinstitute/gatk/issues/3745)
- Bug fix - Resize LUTs when dealing with spanning deletions
> GenomicsDB Allele-specific Annotation Support and Bug Fixes

- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
This PR:
- Increases workspace to 256+ character path for `GenomicsDBImportIntegrationTest.testLongWorkspacePath()`
- Fixes whitespace inconsistency introduced in previous PR
@droazen I can also confirm that the two unit tests introduced in the last PR - `GenomicsDBImportIntegrationTest.testLongWorkspacePath()` and `GenomicsDBImportIntegrationTest.testGenomicsDBImportWithoutDBField()` pass with the latest version of GenomicsDB (0.9.2-\*) and fail with the previous version (0.8.1-\*) as expected
> GenomicsDB unit test fix

- Dockerfile
- scripts/docker/gatkbase/build_docker_base.sh
- scripts/docker/gatkbase/install_R_packages.R
Adding a note to developers that if they change the install_R_scripts script they must rebuild gatkbase and test with clean caches.
> add warning message to install_R_scripts

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalIntervalArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredIntervalArgumentCollection.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/GATKToolUnitTest.java
This is currently using a Barclay snapshot, and should not be merged until the released version is up.
> Upgrade Barclay, suppress file expansion for interval arguments.

- scripts/m2_cromwell_tests/test_m2_wdl_multi.json
- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_multi_sample.wdl
Closes #4188.
@sooheelee This wraps up the wish list in #4188.
@takutosato Although funcotator is off in the Travis test, I *did* test it locally. Also, I have tested with and without compressed vcf output.  The funcotator command is simply copied from @jonn-smith's funcotator.wdl.  Subworkflows are a pain in Firecloud, which is why I don't `import` it.
> Compressed vcf output and Funcotator options in Mutect2 wdl

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSparkIntegrationTest.java
* this is currently broken, see https://github.com/broadinstitute/gatk/issues/4274
* add a check to HaplotypeCallerSpark and VariantSparkSink and throw a clear exception in this case
* added test for GVCF writing in VariantSparkSink which previously didn't exist
* added new UserException.UnimplementedFeature class
* closes https://github.com/broadinstitute/gatk/issues/4275
> prevent users from requesting g.vcf.gz in Spark

- src/main/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBias.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContamination.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/Concordance.java
Tools touched:
Mutect2
CreateSomaticPanelOfNormals
GetPileupSummaries
CalculateContamination
FilterMutectCalls
Picard CollectSequencingArtifactMetrics
FilterByOrientationBias
Concordance 
The Mutect2 (How to) tutorial and various supporting documents are now public and so I've cleaned up now redundant information we temporarily placed in the tool docs. I also made a pass at unifying this set of tool docs in terms of presentation elements.
> Shl Update somatic short variants tool docs

- build.gradle
removing hamcrest and junit test dependencies
these were necessary for dataflow tests but are no longer used
> removing unecessary test dependencies

- scripts/mutect2_wdl/mutect2.wdl
@bshifaw found this bug in the M2 wdl where it requests eg 3500 GB of RAM instead of 3500 MB, causing disastrous "no machines available" errors.  @LeeTL1220 any way to get this into a release?
> fixing memory GB/MB inconsistency in M2 wdl

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SvDiscoverFromLocalAssemblyContigAlignmentsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/FilterLongReadAlignmentsSAMSpark.java
replacing overrides of `makeReadFilter` with `getDefaultReadFilters`
This way they these tools will obey read filter command line options correctly.
@SHuang-Broad I think you accidentally used the wrong method here, which is very reasonable because it's super confusing.  I think this is an improvement, but feel free to reject this is you disagree, I may be misunderstanding.
> replacing inappropriate overrides of makeReadFilter

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/ImpreciseVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/EvidenceTargetLink.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadClassifier.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/ImpreciseVariantDetectorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadClassifierTest.java
This PR removes the cap on insert size for calling an 'innie' read pair SV evidence. Previously this was set to a max Z score of 100, which worked out to be around 10kb for some libraries. This was causing us to not gather read-pair based evidence around deletions of over 10kb. The motivation for this limit was to exclude very long read pairs as evidence since they are predominantly mapping errors. I believe that a) this limit was set too low, causing us to miss real events and b) the reads with very long insert sizes likely cover many instances of real variation, even if the actual mappings locations are incorrect, and that the assembly process, variant filters, and correlation with coverage data should be able to filter out assemblies triggered by reads with long mappings. 
Removing the …
> Remove min crazy zish score for template size evidence

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/unsupported/mutect2_opt.wdl
This is the bug fix for @eitanbanks's pon.  @LeeTL1220 can you review if tests pass?  If they fail I will fix ASAP.
> Passing vcf indices correctly in M2 wdls

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
@chandrans Can I give this one to you?
> Removed BetaFeature tag from Mutect2 and FilterMutectCalls

- scripts/cnv_cromwell_tests/somatic/cnv_somatic_pair_wes_no-gc_tumor_only_workflow.json
- scripts/cnv_cromwell_tests/somatic/cnv_somatic_pair_wgs_do-gc_tumor_only_workflow.json
- scripts/cnv_cromwell_tests/somatic/run_cnv_somatic_workflows.sh
- scripts/cnv_wdl/somatic/README.md
- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
Fixes #3983 
- Added two tumor-only tests to the CNV WDL test.  I did not add all four possible combinations, since I did not see the value.  I just wanted to make sure that the WGS and WES cases were covered.
> CNV Tumor only WDL

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/CalculateGenotypePosteriors.java
refactoring code to remove confusion and unnecessary call to calculateChromosomeCounts
> refactoring in CalculateGenotypePosteriors to remove confusion

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDDenoisingUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/formats/records/CopyRatio.java
@LeeTL1220 This should fail earlier in situations like the one you ran into with the low coverage test data.  I don't *think* there should be any unintended side effects.  I'm fine if this doesn't make it in before the point release if you want to run some sanity checks on real data with it (since users should be able to figure out what is going on relatively quickly if they run into the issue), but I'll leave it up to you.
> Added check for non-finite copy ratios in ModelSegments pipeline.

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/test/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/4367. Includes a sleep for 5 seconds; not sure thats a good idea, although the warning message scrolls off the screen pretty quickly, especially with Spark apps. This will need to be replicated in Picard as well.
Experimental:
Beta:
> Display a warning message for Beta and Exerimental tools.

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortSamSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortSamSparkIntegrationTest.java
For consistency with the non-Spark version of this tool.
> Rename SortReadFileSpark to SortSamSpark

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSource.java
This reverts commit 8a366c7ba570c61338f7109b86c3284b80d5cf47.
We noticed a major performance regression in `BaseRecalibratorSpark` and `HaplotypeCallerSpark` after we upgraded our ADAM dependency (see https://github.com/broadinstitute/gatk/issues/4376). This PR reverts that upgrade for now until we understand the underlying cause.
> Revert "Bump to ADAM 0.23.0 release. (#4044)"

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
* some classes were missing registration in kryo which causes less efficient serialization
* adding registrations for a number of classes that MarkDuplicatesSpark needs that weren't registered yet
* notably, BAMRecord wasn't registered to use the correct serializer which could cause major inefficiencies
* it's not clear what circumstances we're serializing BAMRecord instead of SAMRecordToGATKReadAdapter so how much this will help is not obvious
> adding missing registrations in kryo

- README.md
- build.gradle
- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/utils/config/ConfigFactory.java
- src/main/resources/org/broadinstitute/hellbender/utils/config/GATKConfig.properties
- src/test/java/org/broadinstitute/hellbender/utils/config/ConfigIntegrationTest.java
> Config file no longer overrides system properties 

- scripts/sv/runWholePipeline.sh
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ExtractSVEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/IntervalCoverageFinder.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/QNameFinder.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadClassifier.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/SVReadFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVInterval.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/IntervalCoverageFinderUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/QNameFinderTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadClassifierTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVKmerLongUnitTest.java
This PR attempts to eliminate long-running, useless assemblies that significantly extend runtime on some samples:
- Conducts a scan over the genome to find intervals of excessive depth, defined as an interval where coverage is greater than a lower factor times the average coverage of the sample and containing a coverage peak greater than an upper factor times the average coverage.
- Nearby high-coverage regions within one read-length of each other are merged together.
- Excludes reads that map exclusively inside high coverage regions from evidence gathering.
- Excludes reads that map exclusively inside high coverage regions from QName finding for seeding assemblies.
In addition, after observing that many long-running assemblies occur on non-primary reference contigs, we also exclude reads …
> Add a scan for intervals of high depth and excludes reads from those regions from evidence

- Dockerfile
There is currently an issue with spark stderr output if running through the wrapper script, this is a workaround to that.
> Fixed the Docker build to run using the jar

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/DenoiseReadCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDDenoisingUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/DenoiseReadCountsIntegrationTest.java
> Allowed use of zero eigensamples in DenoiseReadCounts.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/LikelihoodEngineArgumentCollection.java
previously it was a hidden argument, now it's a visible advanced argument
> exposing pair-hmm-implementation

- scripts/sv/create_cluster.sh
- scripts/sv/default_init.sh
- scripts/sv/manage_sv_pipeline.sh
- scripts/sv/runWholePipeline.sh
The current initialization action for dataproc workers puts the reference image in different places depending on whether or not an SSD is mounted. Preemptible dataproc workers don't have SSDs, so a mixed cluster will have references mounted on different paths depending on the worker. This change symlinks the SSD mount point onto the HDD so that paths can be consistent. 
Also increases several cluster configuration parameters relating to retries, which I saw recommended if using preemptible workers.
> Make the SV cluster creation scripts work with preemptible workers

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
Because the sorting order makes it difficult to know if the reads you are holding are in the grouped properly at the front of a shard, we must serialize all the starting reads grouped by their name and append them at the backs of shards appropriately. 
Fixes #4441
> Changed spark sharding of queryname sorted bams to better handle secondary and supplementary reads

- scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity_all_plexes.wdl
- scripts/mutect2_wdl/unsupported/mutect2_multi_sample_concordance.wdl
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/Concordance.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/FilterAnalysisRecord.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/ConcordanceIntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/concordance/filter-analysis-eval.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/concordance/filter-analysis-truth.vcf
@takutosato This adds an option to report counts of false negatives, true negatives, and false/true negatives not flagged by any other filter for each filter.  Gives a rough picture of how valuable (or harmful) each filter is.
> Option to analyze contributions of different filters in Concordance

- README.md
There have been several users confused that the sources zip file is not
buildable. Clarify that a full git clone is required for building GATK.
> Add a note to the GATK README that a git clone is required to build GATK

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticLikelihoodsEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
@takutosato I made sure that when the new option is turned off, as it is by default, nothing changes.  Also, the new option surprisingly only added 30% or so to runtime because M2 already calls so many 
false active regions.
@chandrans @sooheelee This is the feature we have been discussing.
> Option to emit (but still filter) all germline sites in Mutect2

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/cmdline/DeprecatedToolsRegistry.java
- src/test/java/org/broadinstitute/hellbender/cmdline/DeprecatedToolsRegistryTest.java
We should be able to use this single implementation to satisfy both https://github.com/broadinstitute/gatk/issues/4347 and https://github.com/broadinstitute/gatk/issues/4351.
Questions: @vdauwera What other tools that were dropped from GATK3 should be added to the list now? GATK3 also has a deprecated annotations list, which is included here, but is empty. Are there any annotations that should be listed ? I can't really implement/test that part unless I populate it with something.
Also, trying to run a missing tool is currently handled as an error, and surfaces in the context of a usage message. Perhaps that hides it too much:
> Add registry for deprecated tools and annotations.

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
GenomicsDBImport.getReaderFromPath() could fail with an uncaught TribbleException
Convert the TribbleException to a UserException
fixes #4526
> wrapping TribbleException in GenomicsDBImport

- build.gradle
- gatk
- src/main/java/org/broadinstitute/hellbender/utils/config/GATKConfig.java
- src/main/resources/org/broadinstitute/hellbender/utils/config/GATKConfig.properties
I'm honestly not sure which of the various settings take precedence, so I set them all...  We should remove the irrelevant ones.  I assume that that includes the ones in the `gatk` launch script as well as the defaults in build.gradle?
> setting default compression level to 2

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
@takutosato Can you review this?
@sooheelee This closes #4552.
> Made number of samples to put variant site in M2 pon adjustable

- build.gradle
Adds a folder called gatkdoc to the bundle. Fixes https://github.com/broadinstitute/gatk/issues/4345.
> Include user docs in distribution bundle.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/report/GATKReportColumn.java
This bumped some transitive dependencies which required a minor update in unrelated classes
We shouldn't merge this until we get a 👍 from the SV team as well as running the jenkins spark tests.
I think the SV team is already using 2.2.0 since they've gone to dataproc image 1.2.
This will prevent the annoying adam log spam, closes #4186 
closes #2555
> upgrading to spark 2.2.0

- .gitattributes
- README.md
- build.gradle
- build_docker.sh
- src/main/java/org/broadinstitute/hellbender/utils/NativeUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/R/RScriptLibrary.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/io/Resource.java
- src/main/resources/large/testResourceFile.txt
- src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/utils/io/testResourceFile.txt
This adds a new folder for large runtime resources to git-lfs. Unlike the large test resources, which are only accessed via a volume mount when tests are run on the Docker image, the runtime resources need to be accessible to the GATK build during the Docker build process, since they're included in the jar. AFAICT there is no `docker build` equivalent to `docker run -v`. So for now the runtime resources are git pulled into the Docker staging area, and thus onto the Docker image. We need this for @lucidtronix 's CNN branch (and possibly for @TedBrookings) if we're going to load models for resources, but longer term, we need a better solution.
> Add large runtime resource directory to lfs, and expose it to the Docker build.

- build.gradle
This changes the GCS batch request endpoint to the new per-api endpoint
(https://github.com/GoogleCloudPlatform/bigdata-interop/blob/branch-1.6.x/gcs/CHANGES.txt),
as the old endpoint is being deprecated
(https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html).
> Update GCS connector from 1.6.1 to 1.6.3.

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
> Fixing calculation of GC content to be correct.

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AlignmentInterval.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/ChimericAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/CpxVariantInducingAssemblyContig.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/NovelAdjacencyAndAltHaplotype.java
Calling `hashCode` directly on an instance of a Java enum produces a value that depends on the object's memory location and is therefore not stable across machines in a distributed environment. This causes issues when using these objects (or objects that contain them) as keys in Spark RDDs, which by default use `HashPartitioner` to parition by hash code. See this blog post for a summary:
http://dev.bizo.com/2014/02/beware-enums-in-spark.html
This PR modifies all places within the sv tools where we call `hashCode` on an enum, instead computing the hash of the ordinal of the enum value.
For @SHuang-Broad
> switch away from calling hashCode directly on enums

- src/main/java/org/broadinstitute/hellbender/tools/spark/ParallelCopyGCSDirectoryIntoHDFSSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/ParallelCopyGCSDirectoryIntoHDFSSparkIntegrationTest.java
This gives `ParallelCopyGCSDirectoryIntoHDFSSpark` the ability to subset the files in a GCS directory to be copied to HDFS using a wildcard glob. Useful in cases where the bucket directory contains files that you don't want to copy or data from multiple samples.
> allow the parallel copy tool to take a filename glob to subset files to copy

- build.gradle
So we don't accidentally pick up a different version via Picard. Fixes https://github.com/broadinstitute/gatk/issues/4556.
> Add a force resolution strategy for google-cloud-nio.

- scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CreateReadCountPanelOfNormals.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/HDF5SVDReadCountPanelOfNormals.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/HDF5Utils.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/utils/HDF5UtilsUnitTest.java
This enables PoNs to be built with a number of intervals greater than 16777216, which lets us push down to bin sizes <175bp if really necessary.  At some point, it is better to scatter and build a separate PoN for each contig so we don't run into memory issues.  However, the official WDL is not set up to do the scatter, so one would have to write a custom WDL.
@mwalker174 Do you mind taking a look?
Closes #4365.
> Exposed maximum chunk size in CNV panel of normals.

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CreateReadCountPanelOfNormals.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDDenoisingUtils.java
This will require less tuning of `minimum-interval-median-percentile` to filter out completely uncovered intervals, which will avoid e.g. https://gatkforums.broadinstitute.org/gatk/discussion/11461/gatk-4-0-1-2-no-non-zero-singular-values-were-found-in-creating-a-panel-of-normals-for-somatic-cnv
For example, currently if 10% of my intervals are completely uncovered and I set the relevant parameter to 5%, the 5th percentile is then equal to zero.  However, because no intervals are strictly less than zero, none are filtered.  Changing this to filter on equality then gets rid of all 10% of the intervals as one would want to do in practice.
> Changed CNV PoN to filter on equality to interval median percentile.

- scripts/m2_cromwell_tests/test_m2_wdl_multi.json
- scripts/mutect2_wdl/mutect2.wdl
Closes #4606.
@takutosato Another little one for you.  This works on SGE and in Travis.
> fixed M2 wdl bamout bug on scatters with overlapping assembly regions

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AlignmentInterval.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/BreakpointComplications.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/ChimericAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/CpxVariantInducingAssemblyContig.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/NovelAdjacencyAndAltHaplotype.java
in `BreakpointComplications`
After this fix, the duplicated records disappear.
> More fix enum hashCode 

- scripts/mutect2_wdl/mutect2.wdl
Closes #4596.
@TedBrookings Could you review this PR for an issue we saw earlier today, once tests pass?
> Fixed extra filtering args being deactivated in M2 wdl due to typo

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
Closes #4625.
@takutosato Could you review this?  It's a one-liner.
> restored explicit PASS (as opposed to empty) filter in Mutect2

- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSR.java
- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/SamAssertionUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSRIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/test/SamAssertionUtilsUnitTest.java
> NIO output support for ApplyBQSR

- build.gradle
upgrading picard dependency from 2.18.1 -> 2.18.2
this way we'll be on the latest release when we start doing MarkDuplicates tieout
> updating picard to 2.18.2

- src/main/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMergerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/ReducibleAnnotationBaseTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/spanningDeletionBaseExtensionTest1.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/spanningDeletionBaseExtensionTest2.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/spanningDeletionBaseExtensionTestExpected.g.vcf
Fixes for https://github.com/broadinstitute/gatk/issues/4525 and https://github.com/broadinstitute/gatk/issues/4633. Longer term we should do a more significant rewrite/refactoring.
> ReferenceConfidenceVariantContextMerger fixes for spanning deletions, attribute merging.

- scripts/sv/copy_sv_results.sh
- scripts/sv/create_cluster.sh
- scripts/sv/delete_cluster.sh
- scripts/sv/manage_sv_pipeline.sh
- scripts/sv/runWholePipeline.sh
- scripts/sv/run_whole_pipeline.sh
This PR makes four changes to the SV pipeline management scripts:  First it uses the new glob argument for copying data into HDFS to only copy the requested BAM file and its index, rather than everything in the GCS bucket directory (this is useful when the bucket directory contains multiple samples, as is the case with our HGSV trios). Second, the scripts now respect the project argument at each phase of the pipeline. Third, the output directory will include the name of the cluster so that if multiple samples are being processed by the same branch in parallel it's easier to figure out which results directory contains which sample and the results won't collide if two runs happen to start at the same timestamp. Finally, if the user requests not to copy the FASTQ files from the main …
> update sv scripts to only copy a single bam file and index, and respect project parameter

- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadGroupBlackListReadFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariants.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriter.java
- src/main/python/org/broadinstitute/hellbender/vqsr_cnn/vqsr_cnn/inference.py
- src/main/resources/org/broadinstitute/hellbender/tools/walkers/vqsr/training.py
- src/test/resources/large/VQSR/expected/cnn_1d_chr20_subset_expected.vcf
- src/test/resources/large/VQSR/expected/cnn_2d_chr20_subset_expected.vcf
This PR brings pure python inference and java-python streaming inference into much better agreement. also a transpose bugfix.
> Numerical consistency between python and java, transpose fix

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
@takutosato The first commit gives tumor-normal the old default AF.  The second commit is a more intelligent STR contraction filter that improves both sensitivity and precision.
> Better default AF for M2 tumor-normal mode; improved M2 STR filter

- src/main/java/org/broadinstitute/hellbender/tools/ClipReads.java
- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/RevertBaseQualityScores.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/UnmarkDuplicates.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java
These tools can now write bam files to Google Buckets: ClipReads, LeftAlignIndels, RevertBaseQualityScores, UnmarkDuplicates, SplitNCigarReads
> NIO output support for multiple tools

- src/main/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFsUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs/gvcfWithTrailingReferenceBlocksBandedExpected.g.vcf
Fixes https://github.com/broadinstitute/gatk/issues/4672.
> Fix and test for calculating CombineGVCFs intermediate band interval start locations.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
Barclay can't currently handle immutable collections in `@Argument` values due to
https://github.com/broadinstitute/gatk/issues/4702
Tests for these arguments are coming in a separate, larger branch, but I
wanted to get the fixes in first since it's such a simple fix.
> Fix two instances of immutable collections being used to initialize List arguments

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/MarkDuplicatesSparkArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OpticalDuplicatesArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/validation/validate-reads-spark-pipeline.sh
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/AbstractMarkDuplicatesCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/OpticalDuplicateFinder.java
- src/main/java/org/broadinstitute/hellbender/utils/test/testers/AbstractMarkDuplicatesTester.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaAndMarkDuplicatesPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/MarkDuplicatesGATKIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/MarkDuplicatesSparkTester.java
* some of the arguments to MarkDuplicatesSpark were still using Picard style uppercase names
* the following arguments in MarkDuplicatesGATK and MarkDuplicatesSpark have changed
--METRICS_FILE -> --metrics-file
--DUPLICATE_SCORING_STRATEGY -> --duplicate-scoring-strategy
--READ_NAME_REGEX -> --read-name-regex
--OPTICAL_DUPLICATE_PIXEL_DISTANCE -> --optical-duplicate-pixel-distance
* this fixes an accidental change to ReadsPipelineSpark which was introduced when we added MarkDuplicatesSparkArgumentCollection
> kabobifying MarkDuplicatesSpark arguments

- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCalls.java
- src/main/java/org/broadinstitute/hellbender/utils/R/RScriptExecutor.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/runtime/ProcessControllerUnitTest.java
Two commits here:
- The first is to fix a no longer accurate message in `UserException.BadTmpDir`
- The second is a few improvements to IOUtils.  
1.  Rename and simplify `tmpDir` -> `createTempDir` and make it automatically scheduled for deletion
2. Add documentation to the confusing `absolute` method so that I stop wondering what it's for
> minor improvements to code in IOUtils and UserException.BadTmpDir

- src/main/java/org/broadinstitute/hellbender/utils/read/ReadQueryNameComparator.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadQueryNameComparatorUnitTest.java
* this should match the results of SAMRecordQueryNameComparator exactly
* it operates on GATKRead instead of SAMRecord
> adding new ReadQueryNameComparator

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
- src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfCodec.java
- src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfFeature.java
* improving slow String handling
* enabling feature caching
> making optimizations to funcotator

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BwaAndMarkDuplicatesPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
This should allow for the .parts whiteout to live elsewhere which is needed for using LOCAL disks with spark. 
Fixes #4636
> Added an argument to specify the parts directory for ReadsSparkSink

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadQueryNameComparator.java
- src/main/java/org/broadinstitute/hellbender/utils/spark/SparkUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadQueryNameComparatorUnitTest.java
Added a global sort to the beginning of the tool to ensure we are always working with name grouped bams. In the future we should evaluate if alternatives that avoid sorting are necessary.  
Fixes  #4701
> Fixed MarkDuplicatesSpark handling of unsorted bams

- src/test/resources/large/NexPond-377866.NA12878.WEX.20.21.with.unmapped.bam
- src/test/resources/large/NexPond-377866.NA12878.WEX.20.21.with.unmapped.bam.bai
- src/test/resources/large/whole_exome_illumina_coding_v1.Homo_sapiens_assembly19.targets.interval_list
This is a ~130 MB snippet of the NexPond-377866 NA12878 bam from
https://github.com/broadinstitute/palantir/wiki/Gold-Standard-Datasets
with:
-all reads from chromosomes 20 and 21
-50,000 unmapped reads added to the end
It can be used with the existing human_g1k_v37.20.21.fasta reference in
src/test/resources/large
Tests that use this new file will be coming in a future branch.
> Added a new WEX test bam to src/test/resources/large, with a companion target interval list

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
Fixes #4274 and #4303. Relies on https://github.com/HadoopGenomics/Hadoop-BAM/pull/194, so this won't pass (and shouldn't be merged) until a new release of Hadoop-BAM is available.
> Support g.vcf.gz, g.bcf and g.bcf.gz files in Spark.

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
Fixes #4295.
Relies on https://github.com/HadoopGenomics/Hadoop-BAM/pull/195.
> Fix Spark tools to write SAM files when a .sam suffix is specified.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
This is from https://github.com/broadinstitute/dsde-docs/issues/2967#event-1504632768. Users find the -tranche argument difficult to use. I hope this extra sentence with example will help.
> minor doc change for -tranche argument

- scripts/sv/copy_sv_results.sh
The SV copy results script has to figure out the total number of workers including standard and preemptibles. The current version of the script had an error in parsing the `gcloud compute dataproc clusters list` command, which left a blank field when no preemptibles were used that couldn't be parsed because it was displayed in fixed-width format. This switches to the CSV format option for the cluster list command, making it easier to parse.
> Fix bug in sv copy script

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/DataprocIntegrationTest.java
* register the variants of ImmutableMap that we use in MarkDuplicatesSpark with appropriate serializers
* fixes #4775
> fix MarkDuplicatesSpark serialization crash

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/EmptyFragment.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Fragment.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Pair.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/PairedEnds.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/PairedEndsUnitTest.java
Fixes #4730 
Blocked by https://github.com/broadinstitute/gatk/pull/4732
> Added a distinction between PCR orientation and Optical Duplicates orientation in MarkDuplicatesSpark

- scripts/funcotator/data_sources/getGencode.sh
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfCodec.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/DataProviderForMuc16IndelData.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
Added in a script to pull down the latest Gencode data source.
Fixed an issue in 5' UTR processing that would cause variant alleles with length > 1 to throw an exception (issue 4712).
Added three test cases to prevent regression of issue 4712.
Updated Gencode codec to be compatible with latest Gencode release (v28).
Fixed a bug in the version detection for Funcotator data sources that would prevent newer data source versions from being detected as compatible (date comparison error).
> Addressing issue #4712

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/spark/SparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/spark/SparkUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/test/ReadTestUtils.java
* fix partitioning bug by moving edge fixing from coordinateSortReads -> querynameSortReads
* refactor methods to reduce code duplication
* renaming and moving some methods
* disallow duplicate sort order on spark because it doesn't work with headerless reads
> fixes and refactoring methods in SparkUtils

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/DetermineGermlineContigPloidy.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/ModelSegments.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/arguments/CopyNumberArgumentValidationUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/ModelSegmentsIntegrationTest.java
Unfortunately, projects like TCGA with BAMs from different sequencing centers do not use the exact same sequence dictionary across them.  I've relaxed validation in cases where dictionaries are checked across different BAMs so that only a warning is thrown; however, cases where dictionaries should arise from the same BAM still throw an exception.
> Validation of sequence dictionaries from multiple BAMs now throws warning instead of exception in CNV workflows.

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/SequenceDictionaryValidationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BwaAndMarkDuplicatesPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/SequenceDictionaryValidationArgumentCollectionTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaAndMarkDuplicatesPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSparkIntegrationTest.java
previously, tools that align reads required you to manually disable sequence dictionary validation
if you didn't, they would fail because the unaligned bam didn't have the required sequence dictionary
extracting out a SequenceDictionaryValidationArgumentCollection and providing a method for GATKSparkTools to configure it
ReadsPipeline couldn't easily make use of this, so instead it overrides the method that does validation
BwaSpark / BwaAndMarkDuplicatesPipelineSpark now do not require or allow dictionary validation
fixes #4131
> prevent sequence dictionary validation when aligning reads

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/SAMFileDestination.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriterUnitTest.java
HaplotypeCaller's bamOutputPath is no longer internally converted to a File so "gs://" paths can now be passed for the optional "bam output" parameter.
> NIO output support for HaplotypeCaller

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
@takuto The problem was, if there were two alt alleles, A and B, (both most likely PCR slippage artifacts) and A had a higher tumor lod and higher normal lod, then M2 (not the filtering engine) could remove A leaving only B, which has less of the normal artifact signature.  The solution is to emit both A and B, thereby allowing it to be filtered.
> Fixed M2 bug where triallelic normal artifacts were sometimes hidden from filtering

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculator.java
- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculatorUnitTest.java
@ldgauthier The new qual was not doing the right thing for spanning deletions.  This fixes it.  Would you mind reviewing?  And would you like me to re-run those GVCFs just in case before going ahead with #4614?
> New qual doesn't count spanning deletions as support for variant qual

- build.gradle
this fixes the use of pipes with the Path api.
> upgrading htjsdk to 2.15.1

- .gitignore
- Dockerfile
- README.md
- build.gradle
- scripts/gatkcondaenv.yml.template
Several changes:
- Fix https://github.com/broadinstitute/gatk/issues/4741, where newer versions of conda appear to treat relative references in the environment yml as being relative to the yml file instead of relative to the cwd (based on observation).
- Add a second conda yml file (`gatkcondaenv.intel.yml`) for environments that use Intel hardware acceleration and Intel Tensorflow package (based on https://github.com/broadinstitute/gatk/pull/4735).
- Add a gradle task (`condaEnvironmentDefinition`) to generate the conda yml files from a single template to ensure that all the environment definitions remain in sync. This task also generates the Python package archive.
- Add a gradle task (`localDevCondaEnv`) to create or update a local (non-Intel) conda environment. This is a shortcut for …
> Update the conda environment and build.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
@takutosato Here's another little one.  This didn't affect sensitivity in Hapmap or DREAM and in DREAM it reduced indel false positives by about half.  Not a bad short-term improvement for MC3, although deep learning will handle it better.
> M2 STR filter also looks at insertions

- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/common.html
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.index.template.html
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.template.html
- matches the bootstrap updates for formatting 
- minor text tweaks, displays version clearly
- adds version switching menu
These changes will make it easier to upload new version docs quickly. This should definitely go in before the next version release. 
Resulting docs are live at https://software.broadinstitute.org/gatk/documentation/tooldocs
> Updated doc templates to match website updates

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
@takutosato this fixes a bug that came up this morning when I was trying to make a bamout for one of Junko's samples.
> Gave SortSam lenient validation in M2 wdl

- .github/ISSUE_TEMPLATE.md
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculatorUnitTest.java
Text edits are welcome.  I tried to split the difference between being a pushover and fully expressing my frustration.
> Add slightly modified version of GATK3 github issue template

- src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
- src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureManagerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
* expand -L support for Feature Files to work with Paths
* previously interval files could be read from Paths, but not feature
files like vcf and bed
* fixes #4852
> enable -L to read Feature Files from Paths

- scripts/sv/copy_sv_results.sh
Simple fix to remove trailing slash in GCS_SAVE_PATH to avoid double slashes in GCS_RESULTS_DIR.
Without this, if the `manage_sv_pipeline.sh` is launched with `-s gs://custom/path/to/save/` having the trailing slash, log file and cmd line info will be saved to a strange place.
> Simple fix to copy_sv_results.sh

- src/main/java/org/broadinstitute/hellbender/engine/AbstractConcordanceWalker.java
This is a very simple change to allow subclasses of `AbstractConcordanceWalker` to use NIO for their truth callset.
> Allow concordance tools to use NIO for truth call set

- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBuildReferenceTaxonomy.java
Trivial correction that uses the correct tool name in the usage example. See ticket #4284
> Correct PathSeqBuildReferenceTaxonomy doc usage example

- src/main/java/org/broadinstitute/hellbender/utils/codecs/xsvLocatableTable/XsvTableFeature.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java
- src/test/java/org/broadinstitute/hellbender/utils/test/FuncotatorReferenceTestUtils.java
- src/test/resources/large/funcotator/b37.2.tar.gz
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/clinvar/hg19/clinvar_hgmd.config
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/clinvar/hg19/clinvar_hgmd.tsv
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/clinvar/hg19/clinvar_hgmd.tsv.idx
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/gencode_pik3ca/hg19/gencode.config
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/gencode_pik3ca/hg19/gencode.v19.PIK3CA.gtf
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/gencode_pik3ca/hg19/gencode.v19.PIK3CA.gtf.idx
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/gencode_pik3ca/hg19/gencode.v19.PIK3CA_transcript.dict
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/gencode_pik3ca/hg19/gencode.v19.PIK3CA_transcript.fasta
- src/test/resources/large/funcotator/small_ds_clinvar_hg19/gencode_pik3ca/hg19/gencode.v19.PIK3CA_transcript.fasta.fai
- src/test/resources/org/broadinstitute/hellbender/tools/funcotator/clinvar_hg19_column_test.vcf
Fixes #4193
`XsvTableFeature` no longer removes an extra column if start and end in
the config file for a `LocatableXsv` data source are the same.
> XsvTableFeatures now always put out the right number of columns.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/GatherVcfsCloud.java
- src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/FilterVariantTranches.java
- src/main/java/org/broadinstitute/hellbender/utils/codecs/sampileup/SAMPileupCodec.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/codecs/sampileup/SAMPileupCodecUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadUtilsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadUtilsUnitTest.java
Update to htsjdk 2.16.0.  This only updates gatk to fix the compile warnings from deprecations.  An additional PR is needed in order to support fasta.gz files.
fixes #4039
> update htsjdk 2.15.1 -> 2.16.0

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactoryUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/funcotator/clinvar_hg19_multihit_test.vcf
LocatableXsv data sources now produce at most 1 funcotation per allele pair.
Fixes #4929
> LocatableXsv data sources now produce at most 1 funcotation

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/TranscriptSelectionMode.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfFeature.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
- User defined transcripts were being used as a filter rather than a priority order.  The filtering step has been eliminated.  Closes #4918 
- Fixed previously unidentified issue where locus level ranking was being reversed.  Updated tests.  This was identified thanks to the thousands of tests in Funcotator (only one failed, but that was all it took).
> Eliminated the filtering by user transcripts and fixed locus level issue

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/ExtractOriginalAlignmentRecordsByNameSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/ExtractOriginalAlignmentRecordsByNameSparkIntegrationTest.java
> add option to invert logic in ExtractOriginalAlignmentRecordsByNameSpark

- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutationsIntegrationTest.java
With this addition, summarizing the results of the MC3 validation will use more GATK, less scripting.
> Add optional summary table output to ValidateBasicSomaticShortMutations

- .travis.yml
- build.gradle
- src/test/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormalsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
> Created "variantcalling" test group and split them off from the rest of the integration tests for runtime purposes

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBConstants.java
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/engine/GenomicsDBIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportUnitTest.java
- src/test/resources/large/gvcfs/.gitattributes
- src/test/resources/large/gvcfs/HG00096_after_combine_gvcfs.g.vcf.gz
- src/test/resources/large/gvcfs/HG00096_after_combine_gvcfs.g.vcf.gz.tbi
- src/test/resources/large/gvcfs/HG00268_after_combine_gvcfs.g.vcf.gz
- src/test/resources/large/gvcfs/HG00268_after_combine_gvcfs.g.vcf.gz.tbi
- src/test/resources/large/gvcfs/NA19625_after_combine_gvcfs.g.vcf.gz
- src/test/resources/large/gvcfs/NA19625_after_combine_gvcfs.g.vcf.gz.tbi
- src/test/resources/large/gvcfs/combined.gatk3.7_sites_only.g.vcf.gz
- src/test/resources/large/gvcfs/combined.gatk3.7_sites_only.g.vcf.gz.tbi
- src/test/resources/large/gvcfs/combined_multi_interval.gatk3.7.g.vcf.gz
- src/test/resources/large/gvcfs/combined_multi_interval.gatk3.7.g.vcf.gz.tbi
- src/test/resources/large/gvcfs/combined_with_genotypes.g.vcf.gz
- src/test/resources/large/gvcfs/combined_with_genotypes.g.vcf.gz.tbi
This PR addresses required changes in order to use latest version of GenomicsDB which exposes new functionality such as:
- [Multi interval import and query support](https://github.com/broadinstitute/gatk/issues/3269):
- We create multiple arrays (directories) in a single workspace - one per interval. So, if you wish to import intervals ("chr1", [ 1, 100M ]) and ("chr2", [ 1, 100M ]), you end up with 2 directories/arrays in the workspace with names chr1$1$100M and chr2$1$100M. The array names depend on the     partition bounds.
- During the read phase, the user only supplies the workspace. The array names are obtained by scanning the entries in the workspace and reading the right arrays. For example, if you wish to read ("chr2", [ 50, 50M] ), then only the second array is queried.
- In the …
> GenomicsDBImport: Modifications in order to address GATK issue #3269

- .dockerignore
- .travis.yml
- Dockerfile
- README.md
- build.gradle
- build_docker.sh
- scripts/docker/dockertest.gradle
- scripts/docker/gatkbase/Dockerfile
- scripts/docker/gatkbase/build_docker_base.sh
- scripts/docker/gatkbase/install_R_packages.R
- src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotModeledSegments.R
> Refactored the docker build script to only only include the gatk bundle in order to shrink the docker image size

- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
The GenomicsDBTests are long running (~6.5 minutes) and are at least tangentially related to variant calls.
Fixes #4990
> Move genomicsDB tests into variantcalling test group

- src/main/java/org/broadinstitute/hellbender/tools/FlagStat.java
- src/main/java/org/broadinstitute/hellbender/tools/GetSampleName.java
- src/main/java/org/broadinstitute/hellbender/tools/SplitReads.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSpark.java
A few of the example commands in the documentation used a forward slash as the line continuation character rather than a backslash - this PR fixes that.
> Fix line continuations in example commands

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java
Fixes that:
- the docs for VariantFiltration still referred to old spellings of command-line arguments (e.g. `--filterExpression` rather than `--filter-expression`) in a couple of places
- the examples for FilterMutectCalls and ReadsPipelineSpark were missing a dash in front of a long argument
> Correct a couple of arguments in the documentation

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformer.java
- src/test/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformerUnitTest.java
@takutosato Here it is.  The failure has nothing to do with this branch -- every branch is failing in the same way currently.  I have tested and debugged this thoroughly and I am deliberately not writing unit tests for now because we're too busy with MC3 and the M2 paper.  I intend to come back to these later.
> Mutect2 ReadTransformer to hard clip inverted tandem repeats insertion artifacts

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
- M2 WDL will now default to having the orientation bias filter (`FilterByOrientationBias`) turned on.  Closes #5016 
- Empty artifact modes parameter will no longer cause failure in `FilterByOrientationBias`.  Instead the task `FilterByOrientationBias` will not run.  Closes #5025
> Making OB filtering default to true

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/main/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformer.java
Closes #5036.
@meganshand This fixes the bug you found.
> Fix an edge case bug in PalindromeArtifactReadTransformer

- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/BasicSomaticShortMutationValidator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutationsIntegrationTest.java
@takutosato This lets `ValidateBasicSomaticShortMutations` optionally annotate the `eval` vcf with validation `INFO` fields in addition to the standard output of a tsv.  Having a vcf is more convenient for some things in MC3.
> added option for ValidateBasicSomaticShortMutations to output a vcf

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AssemblyContigAlignmentsConfigPicker.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/ContigChimericAlignmentIterativeInterpreter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVInterval.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AssemblyContigAlignmentsConfigPickerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalUnitTest.java
fixes #4951 
And another alignment edge case illustrated below (SAM records)
```
asm017280:tig00000	0	chr18	77371711	60	1447M50D184M980S	*	0	0	AATCAGATTTTCAGAACAGAGCTTCTTAGGGAGATGGTTGGACCACCATAGTCCTGCATCTTCAGGGAGCTGCTCACCATCCCCACTACTGCAGGCACCACTGATCCCTGAGTGAGACCCAGGCACTAACAAGACATGAAGAAGGTGCTGGGTTCCTGGCCGGTCCTTTTGACCCATAAGTGTGGTTCAGTTCTTGGCACTGATGGGCTGGTCGGATGGTGGTGAGGTCAAGCACTCCTTCAGTGCCTGAGGCGTGGCGAGTGGACTTTGGGACCTCTTCCTGAGATGATGATTGCTTCTCAAGGGTGGGAATGAGTTCTTCCAGGGGTCAGCGGTGTGTCATAGGCAAGCACAGCACATTACTAGAAAGCATACGTTTTATTAAGTAGAAGGTATCTTTAATTCCCTGAATAGTAAGACATCTTTGGATTGATGGAAAGGTTGCCCTGGGAAAGGTGGAATATTTGTTGTCATGACCTAAAGCAGCATGCCTAACACCATGTTTGCCAGAGCTCATGCCCACACTGCCATCTCAGGGTTTTCTAAGGGAGAGGAAGCAAGAGGAGGCCCTCGAATTTCTAACCGATTGCTGCAGTCAAAAAATTGCTAAGAAGGACTCGGTGGAAAAGGGAAAACTCAAAAGTGAAGTATGCTGTG …
```
> (SV) more alignment edge cases

- scripts/cnv_wdl/cnv_common_tasks.wdl
- scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
- scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl
- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
- scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl
This is a relatively simple change, but has not been tested.  The reviewer should make sure I haven't screwed it up!
> Exposed ability to blacklist intervals in CNV WDLs.

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
- scripts/mutect2_wdl/mutect2_pon.wdl
@takutosato This is really important for overcoming transient errors in Firecloud, especially as long as we don't have call-caching for NIO.
> Added maxRetries to runtime in M2 WDLs

- Dockerfile
- scripts/docker/gatkbase/build_docker_base.sh
- scripts/docker/gatkbase/install_R_packages.R
- src/main/resources/org/broadinstitute/hellbender/utils/recalibration/BQSR.R
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/AnalyzeCovariatesIntegrationTest.java
The ggplot2 R dependency was not installed correctly in the gatkbase-2.0.0 Docker image.  It appears that this resulted from a recent ggplot2 update that has broken dependencies (perhaps for the version of R that we use).  This missing ggplot2 dependency was the root cause of #5022.
I updated the install_R_packages.R script, which should now fail if any package fails to install, and pushed an updated gatkbase-2.0.1 image.  The second commit addresses #5022.
This should be considered a temporary fix until #5026 is in.
Closes #5022.
> Updated install_R_packages.R to fix broken ggplot2 dependency in gatkbase Docker image.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
This value is more correct. I didn't use it earlier because it was protecting against some false positives, but those were not contamination or germline (i.e. default AF was filtering them for the wrong reasons) and we can instead filter them by catching variants on the same haplotype as filtered variants.
This improves sensitivity in MC3.
> changed default AF for Mutect2 tumor-only

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingGivenAllelesUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
Closes #4182.  Note the duplicate method in `ReadThreadingAssembler`. @droazen Let me know if I should bother someone outside the engine team for things like this.
> Deleted an unused duplicated method in GenotypeGivenAllelesUtils

- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/BasicSomaticShortMutationValidator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/BasicValidationResult.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/PowerCalculationUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
- src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutationsIntegrationTest.java
- `ValidateBasicSomaticShortMutations` will now provide a count of supporting alt alleles in the validation normals.  This value does not affect the validation status.  Closes #5059 
- Note that there are indels that will not be caught by this functionality.  See #5061
> Providing counts for supporting alt reads in the validation normal.

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_multi_sample.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
- scripts/mutect2_wdl/mutect2_pon.wdl
@LeeTL1220 The unfiltered vcf has no additional information and I don't want to give users a chance to shoot themselves in the foot.
> M2 wdl doesn't emit unfiltered vcf, which is redundant

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
- src/main/java/org/broadinstitute/hellbender/engine/AbstractConcordanceWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummariesIntegrationTest.java
@LeeTL1220 The first commit makes all concordance tools and MC3/M2 vcf merge much faster in Firecloud -- tasks that have been taking an hour will take a few minutes.  The second commit makes `GetPileupSummaries`, hence the contamination task much faster.  Previously that tool has cached all reads for the 100,000 bases around each site, so basically it had to do a whole bam's worth of I/O just to get ~60,000 pileups.
> Optimize some Mutect-related tools

- src/main/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformer.java
> fixed edge case for M2 palindrome transformer

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVVCFWriter.java
turned off temporarily long time ago but slipped attention after implementation stablelized
> turn back on checking variant info fields against header in SV vcf writing 

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
@takutosato This change doesn't hurt sensitivity in our validations and made M2 25% faster.  We were getting a lot of active regions based on single substitution errors in overlapping reads.
> handle overlapping mates in M2 isActive

- src/test/java/org/broadinstitute/hellbender/tools/walkers/readorientation/ReadOrientationModelIntegrationTest.java
One of the variants is no longer emitted in vcf, potentially due to #5078. Somehow this was not caught by the remote test for #4895.
> Read Orientation Model test case where the variant is no longer emitted in the vcf

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Fragment.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Pair.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/TransientFieldPhysicalLocation.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
Tests ported from picard: https://github.com/broadinstitute/picard/pull/1195
Fixes #4707
> Updating MarkDuplicatesSpark tiebreaking to reflect changes in picard

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
Fixes https://github.com/broadinstitute/gatk/issues/5066
> Display warning when using large interval lists with GenomicsDBImport.

- build.gradle
Some speedup by eliminating a ls operation - however, having 10K small arrays will still be slower than 100 large arrays.
> Fix the file handles issue discussed in #5066

- src/main/java/org/broadinstitute/hellbender/tools/FixCallSetSampleOrdering.java
- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/ApplyBQSRSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilterArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSScorer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBuildReferenceTaxonomy.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithExpectedAlleleFraction.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/CalculateGenotypePosteriors.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/ApplyVQSR.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantTrain.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantWriteTensors.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
Updating a few more old spellings of arguments.
I also noticed some references to `-scatterTranches` and `-sampleEvery`, but as far as I can tell they're not currently valid arguments to anything, so I didn't touch the references to those.
> Update references to old-style arguments

- .travis.yml
the first commit is the fix, the second is a deliberate test failure so we can validate that the fix works when the tests fail
> update publishing for failed tests

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/MarkDuplicatesScoringStrategy.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/EmptyFragment.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Fragment.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Pair.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/PairedEnds.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/MarkDuplicatesGATKIntegrationTest.java
After delving into picard and MarkDuplicates I have found two more sources of inconsistencies, first we were preserving the original mapped start position which we used for tie-breaking. This was unnecessary and caused problems at sites with very high depth. Additionally, our scoring code was out of step with the equivalent code in htsjdk which packed its results into shorts rather than ints.
> Updated MarkDuplicates Scoring and Comparison code to reflect mismatches to picard

- README.md
the homebrew/science tap has been merged into core so it's no longer necessary to tap it to get R
> No longer refer to homebrew/science in README

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/FilterVariantTranches.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantPipelineTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/FilterVariantTranchesIntegrationTest.java
- src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_95_99_99.9.vcf
- src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_99.vcf
- src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_99_99.5.vcf
- src/test/resources/large/VQSR/expected/g94982_20_1m_10m_tranched_99_with_old_filters.vcf
This addresses: https://github.com/broadinstitute/gatk/issues/4928
@cmnbroad care to review?
> Filter variant tranches removes old filters by default

- jitpack.yml
- scripts/prepareJitpackEnvironment.sh
> Add jitpack support for SNAPSHOTS

- src/test/java/org/broadinstitute/hellbender/utils/python/StreamingPythonScriptExecutorUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/5065. This test verifies that we receive output written to Python's stderr, but it fails occasionally due to an inherent race condition in the assert (occasionally the assert executes before the data is received and the test fails). I added a Python statement that explicitly flushes stderr first, and ran the test 1000 times and it still failed once for the same reason. Since I don't see any way to have a reliable test condition (that doesn't involve polling inside a loop and a long timeout), I'm just removing the test.
> Remove StreamingPythonExecutor testStderrOutput unit test.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
The google-cloud-java maintainers have merged a fix for the longstanding issue
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2453 that prevented us
from running on a modern version of the library, and forced us to run off of a fork.
This PR updates us to the latest release, which incorporates the fix.
Resolves #3591
Resolves #3500
Resolves #4986
> google-cloud-java: update to the official 0.59.0 release, and move off of our custom fork

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariants.java
- src/main/java/org/broadinstitute/hellbender/utils/python/StreamingPythonScriptExecutor.java
- src/main/python/org/broadinstitute/hellbender/gatktool/tool.py
- src/test/java/org/broadinstitute/hellbender/utils/python/StreamingPythonScriptExecutorUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/4766. We might want to do a similar thing for the non-streaming executor, in a separate PR.
> Enable Python profiling for StreamingPythonScriptExecutor.

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectAllelicCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/PreprocessIntervals.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/formats/collections/AllelicCountCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/AltSiteRecord.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/CollectF1R2Counts.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/DepthOneHistograms.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/F1R2FilterConstants.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModel.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModelEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/Nucleotide.java
- src/main/java/org/broadinstitute/hellbender/utils/reference/FastaReferenceWriter.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModelEngineUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/NucleotideUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/RandomDNA.java
- src/test/java/org/broadinstitute/hellbender/utils/RandomDNAUnitTest.java
Change method names `valueOf` and `toBase` for `decode` and `encodeAsByte`. Reason is that `valueOf` (taking an string for example) has a bit of a meaning in Java Enums (e.g. it should result in a NotSuchElementException if such a constant does not exist and we don't do that here (returns Nucleotide#X).
Apart from that I added a few more methods to cover for functionality that I need as part of a larger pull-request for SV.
> Improvements and refactoring of Nucleotide.java

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2TestingUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/readorientation/CollectF1R2CountsIntegrationTest.java
This unintended change crept in with #4895.
@meganshand @davidbenjamin
> Restore base quality filter code that got reverted in #4895

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtilsUnitTest.java
Now looks at manifest file, not readme.
Now supports version decorators (e.g. `somatic`) after version numbers in manifest file.
Added in a unit test to check the version regex.
Fixes #4582 
Fixes #4692
> Updated datasource version parsing

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/utils/config/GATKConfig.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsTest.java
Google Cloud Storage has "requester pays" buckets. When reading from
those buckets, the requester is billed for the bandwidth (normally, it's
the bucket owner who is billed).
This pull request enables this feature with GATK. By default it is
turned off (so there are no unexpected charges). To turn it on, use the
command line argument "--project-for-requester-pays" (or
"--requester-project") to indicate which project to bill.
Example:
$ ./gatk PrintReads --input $INPUT --output=/tmp/reads.bam
fails with: com.google.cloud.storage.StorageException: Bucket is requester pays bucket but no user project provided.
$ ./gatk PrintReads --input $INPUT --output=/tmp/reads.bam --requester-project=$PROJECT
works
This PR also removes the argumentless version of
setGlobalNIODefaultOptions() because it …
> Enable Requester Pays support

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AlignmentInterval.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/inference/SegmentedCpxVariantSimpleVariantExtractor.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/XGBoostEvidenceFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVInterval.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalTreeTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalUnitTest.java
@tedsharpe 
not sure if the args checking would significantly affect performance.
> Add documentation and args check for SVInterval

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/NonStandardMutectAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/OrientationBiasMixtureModelAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadOrientationArtifact.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReferenceBases.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReferenceBasesUnitTest.java
(Reported in #5130)
We had a user report that when a variant is within 10 base pairs from the end of the chromosome (as defined by the reference dictionary), `ReferenceBases` throws a String index out of range error. This bug was in the annotation prior to #4895. What #4895 did was that it made the `ReferenceBases` annotation part of `StandardMutectAnnotation,` which turned on `RefernceBases` by default, and that led to the user getting the error.
> Fix Edge Cases in Reference Bases

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactoryUnitTest.java
Now the COSMIC data source produces counts of each protein change found in the COSMIC database.
That is, rather than a raw count of the total number of protein changes (e.g. `2` or `7`), it produces a count of each specific protein change found in the COSMIC database that overlaps a variant (e.g. `p.E545K(2)` or `p.E545K(2)|p.E542K(2)|p.H1047R(2)|p.N345K(1)`).
Fixes #4400
> Updated COSMIC to annotate protein change strings with their counts.

- .travis.yml
- scripts/check_for_pull_request
testing if this skips the push builds.
> Skip push builds if there is a pull request

- src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegion.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ReadClipper.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/covariates/ContextCovariate.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingGraphUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReadsUnitTest.java
* Fixed an issue where OverhangFixingManger did not handle empty reads correctly resulting in an NPE
* Checked every codepath that could result in an empty read in readClipper and ensured that it handles empty reads.
Resolves: https://github.com/broadinstitute/gatk/issues/4204
> Added documentation warnings about empty clipped reads from readClipper where they can occur

- build.gradle
* updating google-cloud-java 0.59.0 -> 0.62.0
* this includes retries on 502 errors see https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3557
> updating google-cloud-java nio to 0.62.0

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureContext.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureInput.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/DataSourceFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationMap.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/vcf/VcfFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/utils/codecs/xsvLocatableTable/XsvLocatableTableCodec.java
- src/test/java/org/broadinstitute/hellbender/engine/DummyPlaceholderGatkTool.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/DummyPlaceholderGatkTool.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationMapUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngineUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/vcf/VcfFuncotationFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/CustomMafFuncotationCreatorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRendererUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/test/FuncotatorTestUtils.java
- src/test/resources/org/broadinstitute/hellbender/tools/funcotator/PIK3CA_SNPS_engine_test_chr3.vcf
- Added a `FuncotationEngine` class.  This is meant to decouple the CLI from the funcotation generation.
- Moved the querying of datasources into the funcotation factories.  This means that the funcotation factory generates the funcotations using a feature context, instead of a map of feature inputs.
- Funcotation factories now encapsulate the feature input of the source file.  Non-locatable funcotation factories will have a `null` for this attribute.
> Funcotation Engine Refactoring

- build.gradle
* fixing two issues that prevented us from publishing to maven central
- fixing sourceJar typo -> sourcesJar
- configure the pom for all artifact filters
* partial fix for https://github.com/broadinstitute/gatk/issues/5212
> fixing pom issues that prevented publishing

- scripts/cnv_wdl/cnv_common_tasks.wdl
- scripts/cnv_wdl/germline/cnv_germline_case_scattered_workflow.wdl
- scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
- scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl
Closes #5217.
@vruano, I've verified that cohort and scattered-case mode WDLs run correctly on FC (to be precise, I tested the WDLs from my sl_filter branch rebased on this branch, but this branch alone should be fine as well).
However, #4397 should still be addressed at some point in the future.  This can wait until we have v1 of the FC evaluation in place.
> Revert gCNV WDLs to tar calls from all samples.

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotation.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/OutputRenderer.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotation.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationBuilder.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRenderer.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotationUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/vcf/VcfFuncotationFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRendererUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRendererUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/test/FuncotatorTestUtils.java
- Added support for `--exclusion-list` parameter, which can be specified multiple times.  This will remove some rendered fields from the output.  The field should appear exactly as written in the output MAF or VCF (e.g. ClinVar_ALLELEID). Closes #4359. 
- Does basic cleaning of field values for MAF.  I.e. cleaning tabs and \n.  Fixes #4693
> Adding command line exclusion lists, so that users can prune fields from output. 

- src/main/java/org/broadinstitute/hellbender/utils/python/StreamingPythonScriptExecutor.java
- src/main/java/org/broadinstitute/hellbender/utils/runtime/ProcessControllerAckResult.java
- src/main/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessController.java
- src/main/java/org/broadinstitute/hellbender/utils/runtime/StreamingToolConstants.java
- src/main/python/org/broadinstitute/hellbender/gatktool/tool.py
- src/main/python/org/broadinstitute/hellbender/gatktool/toolconstants.py
- src/test/java/org/broadinstitute/hellbender/utils/python/StreamingPythonScriptExecutorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessControllerUnitTest.java
This adds a new message to the StreamingProcessController ack FIFO protocol to allow additional message detail to be passed as part of a negative ack. Fixes https://github.com/broadinstitute/gatk/issues/5100.
> Add nck with message to StreamingProcessController for passing fatal error messages.

- scripts/mutect2_wdl/mutect2.wdl
In particular, do not call the old orientation bias filter deprecated
> Reword comments in Mutect2.wdl

- AUTHORS
* adding new contributors Tim Fennell and Jake VanCampen
* adding a line break between companies and individuals for readability
* closes https://github.com/broadinstitute/gatk/issues/5238
@tfenne @jakevc Could you proofread this / provide any  corrections if you're not represented the way you would like to be.
> updating AUTHORS file

- src/main/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformer.java
- src/test/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformerUnitTest.java
The palindrome artifact read filter wasn't checking for an edge case.  Now it is.
@takutosato Could you review?  And if you approve and it's Monday or Tuesday, could you merge before the release?
> Fix an M2 bug

- Dockerfile
- scripts/docker/gatkbase/Dockerfile
- scripts/docker/gatkbase/build_docker_base.sh
* including tabix in base image
* updating base image from 2.0.1 -> 2.0.2
> adding tabix to docker base image

- README.md
- scripts/spark_eval/exome_reads-pipeline_hdfs.sh
- scripts/spark_eval/genome_reads-pipeline_hdfs.sh
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/ApplyBQSRSparkFn.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java
- src/main/java/org/broadinstitute/hellbender/utils/collections/AutoCloseableCollection.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/CloseAtEndIterator.java
- src/main/java/org/broadinstitute/hellbender/utils/spark/JoinReadsWithVariants.java
- src/test/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSparkIntegrationTest.java
... for BaseRecalibratorSpark, BQSRPipelineSpark, ReadsPipelineSpark, and to localise reference for HaplotypeCallerSpark.
As a consequence of this change, the reference can be a standard fasta file for Spark
tools (indeed 2bit is no longer supported, since htsjdk does not have support for it).
Also:
* Add AutoCloseableCollection to automatically close all objects in a collection.
* Add CloseAtEndIterator to call close on an object at the end of the iteration.
* Don't materialize all reads in memory in ApplyBQSRSparkFn.
See #5103
> Use SparkFiles to localize reference and known sites

- src/main/java/org/broadinstitute/hellbender/engine/spark/AssemblyRegionWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/IntervalWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/LocusWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/ReadWalkerSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/VariantWalkerSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSparkIntegrationTest.java
Using the technique in #5127, this change uses Spark files to distribute the reference for all of the Spark Walker classes. This makes Spark tools run faster and use less memory.
(Note that this PR includes #5127, since it hasn't been merged yet, so only the last commit should be reviewed here.)
>  Use Spark files to distribute the reference for Spark Walker classes

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
- scripts/mutect2_wdl/unsupported/funcotator.wdl
- M2 WDL has explicit optional parameter for a list of fields that should be excluded from the output.
- Both M2 WDL files are updated.
Manually tested mutect2.wdl on local backend.
Closes #5141
> Added Funcotator excluded fields option explicitly to the M2 WDL.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/tools/FixCallSetSampleOrdering.java
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportUnitTest.java
Sample code to show how to modify INFO field combine operation while querying GenomicsDB using the Protobuf API
#4541 
ping @ldgauthier @droazen @lbergelson @jamesemery
> sample code snippet showing how to specify combine operations for annotations

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculators.java
Fixes #4661.
I managed to run `genome_reads-pipeline_hdfs.sh` with this change, whereas before it was failing (see details in #4661).
No unit test since it is very difficult to write a test for the effect of adding synchronization.
> Synchronize update of shared genotype likelihood tables.

- src/main/java/org/broadinstitute/hellbender/engine/TwoPassVariantWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalkerBase.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/VariantFilterLibrary.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariants.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/VariantFilterUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/4747.
> Integrate CountingVariantFilter.

- build.gradle
* simplifying a few line in build.gradle and making all JavaCompile tasks apply the same compiler arguments
* previously this didn't apply to compileJavaTestUtils
> set the same flags for all JavaCompile gradle tasks

- src/test/java/org/broadinstitute/hellbender/engine/FeatureInputUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceFileSparkSourceUnitTest.java
- src/testUtils/java/org/broadinstitute/hellbender/testutils/SparkTestUtils.java
* adding in a new SparkTestUtils.roundTripThroughJavaSerialization method
* updating existing code to use the new method
> adding SparkTestUtils.roundTripThroughJavaSerialization

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectAllelicCountsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/datacollection/AllelicCountCollector.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/formats/metadata/SimpleSampleMetadata.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalkerSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/CollectAllelicCountsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalkerSparkIntegrationTest.java
This PR fixes #3823 opened by @LeeTL1220 
There are several series of commits applied here:
1. The first set of commits rebase `ll_CollectAllelicCountsSpark` on `master`.
2. Then there's a commit (https://github.com/broadinstitute/gatk/commit/21e1dcfb88fc6543f6ba3e6095eba512a33f9f8d) to fix up some changes to make `CollectAllelicCountsSpark` work on `master`.
3. The next set of commits applies the changes from  #5127 and #5221 (since they have not yet been merged) to make passing the reference in Spark more efficient. These changes are needed for the fix below to work.
4. The actual fix is in https://github.com/broadinstitute/gatk/commit/3326b9093246ff6fb51ad5537951b4646411d80f.
5. There's also a new test for `ExampleLocusWalkerSpark` in addition to the one for …
> LocusWalkerSpark drops intervals with no reads

- scripts/unsupported/combine_tracks_postprocessing_cnv/aggregate_combined_tracks.wdl
- scripts/unsupported/combine_tracks_postprocessing_cnv/combine_tracks.wdl
- scripts/unsupported/combine_tracks_postprocessing_cnv/multi_combine_tracks.wdl
There are no Java code changes in this PR.  Tests were done manually.  As a reminder, the modified files are still considered experimental.
Changes:
- combine_tracks.wdl:  Fixes bug where string was compared to a float.  Closes #5284 
- combine_tracks.wdl:  Converts the processed seg file into a format for GISTIC2.  This is a trivial conversion.  Closes #5283 
- Other changes in `aggregate_combine_tracks.wdl` to support the above, including aggregation of individual GISTIC2 seg files into a single GISTIC2 seg file.
- Added gs urls for necessary auxiliary files in the documentation.
- Added multiple output types for the ABSOLUTE skew parameter to support heterogeneous execution configurations.  File, Float, and String.  All are the same value.
> combine_tracks.wdl supports GISTIC2 conversion (and bugfix)

- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManagerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReadsIntegrationTest.java
Before we were limiting the edge fixing from trimming to large a percentage of the reads, but we computed this percentage based on the reference length of the read, not the number of bases. This resulted in cases where we might check more than the number of bases in the read for mismatches. 
Fixes #5230
> Fixed SplitNCigarReads ArrayIndexOutOfBounds error for short reads with deletions

- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManagerUnitTest.java
> Fixed exception in SplitNCigarReads for non-reference consuming reads

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandArtifact.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandBiasTest.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2TestingUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/readorientation/CollectF1R2CountsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtilsUnitTest.java
This PR includes two changes:
1. Provide a command line argument to toggle the overlapping base quality correction (i.e. min(bq, 20)) before reassembly, which happens in FragmentUtils. I've found, however, that by the time SomaticGenotypingEngine runs, those the quality of these bases get bumped up to what they used to be, so this may be a no-op. I included it in case I missed something, and to be consistent with the branch @fleharty and @madduran have been using.
2. Provide a command line argument to count the two reads in an overlapping pair separately in StrandArtfiact and StrandBiasBySample. This feature is only available in Mutect i.e. it won't affect other tools that use StrandBiasBySample
> Strand based annotations will use both reads in an overlapping read pair

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriter.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java
Adds three annotations to reads in bamout produced by HaplotypeCaller and Mutect2:
1.  AR (Alignment Region)- The reference region over which a read is aligned to a haplotype
2. CR (Callable Region)- The reference region over which the caller is using this read to call variants
3. SG (Supported Genotypes)- A list of the genotypes supported by this read for variants called in the callable region
> Add bamout read annotations for alignement and callable regions, and supported genotypes

- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
> handle normal reads in validation sample in BasicSomaticValidator

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSpark.java
I have been burned one too many times by the fact that this count silently filters reads for you. Since there is no logging output printing the number of filtered reads in spark it makes more sense to remove filtering from the tool altogether.
> Removing WellformedReadFilter from CountReadsSpark

- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
- scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl
- scripts/unsupported/combine_tracks_postprocessing_cnv/combine_tracks.wdl
- scripts/unsupported/combine_tracks_postprocessing_cnv/multi_combine_tracks.wdl
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/utils/annotatedinterval/AnnotatedIntervalUtilsUnitTest.java
- Fixed automated test for that was being skipped.  When re-enabled, it passed without code changes.
- Added automated test.  Passed without any other code changes.
- Added documentation for blacklisting when running the PoN and case sample/pair workflows (as opposed to using the postprocessing combine_tracks.wdl).
- Added hard num het filter.  This helps guard against oversegmentation skewing MAF estimates.  For WGS, `10` is a reasonable value.
- Changed default maf threshold for calling balanced segments.  The previous value was too sensitive.
> More tooling of combine_tracks.wdl

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
> Updated top-level class documentation for Funcotator.

- scripts/cnn_variant_wdl/cnn_variant_common_tasks.wdl
- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
- src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervalsIntegrationTest.java
* This matches what picard expects an interval list to be named.
* Added a new --extension argument to allow changing the extension.
* Fixes https://github.com/broadinstitute/gatk/issues/5390
@ldgauthier
> ScatterIntervals produces interval_list instead of intervals

- README.md
The [Google Java Style guide](http://google-styleguide.googlecode.com/svn/trunk/javaguide.html) links are dead and give a 404 error.
References were changed to [Google Java Style guide](https://google.github.io/styleguide/javaguide.html).
> Fixed dead links - Google Java Style guide

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
In #5215 the SA tag was used to add a "supported alleles" tag to the bamout from HaplotypeCaller and Mutect2.  However, SA is a standard tag reserved for other canonical alignments in a chimeric alignment (http://samtools.github.io/hts-specs/SAMtags.pdf).  This PR changes the tag for "supported alleles" in the bamout from SA to XA.
> Changing SUPPORTED_ALLELES_TAG from SA to XA in bamout

- README.md
- build.gradle
- scripts/gatkcondaenv.yml.template
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariants.java
CNNScoreVariant relies on a computationally demanding operation - a deep neural network.  Using an Intel-optimized version of TensorFlow gives a 10X improvement in performance (e.g. 50 hours to 5 hours for a typical input).  However, these improvements mean that we now have a minimum hardware requirement - the availability of AVX.
> AVX present?

- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
> Added setUnplaced() to the GATKRead api to distinguish reads with no mapping information

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQuality.java
- src/main/java/org/broadinstitute/hellbender/utils/GATKProtectedVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQualityUnitTest.java
Updated RMS Mapping quality annotations to be of type long/Long instead
of int/Integer. With int types, a large cohort could overflow
Integer.MAX_VALUE when handling sum of squared mapping qualities. With
long types this should not be a problem until we have off-world
colonies. This resolves issue 5433.
> Fix integer overflow bug in RMSMappingQuality

- gatk
Resolved the issue of adding gs:// to the beginning and / to the end of the environment variable GATK_GCS_STAGING. Tested it locally.
> Resolved issue: gatk-launch appends as needed to GATK_GCS_STAGING #1338

- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKAnnotationPluginDescriptor.java
* Fixing an obscure error in an error message in GATKAnnotationPluginDescription.
* entrySet was called instead of values as a result everything was always filtered from the error message.
Noticed this one completely by chance.
> fix message in GATKAnnotationPluginDescription

- src/main/java/org/broadinstitute/hellbender/metrics/MetricsUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java
* PrintWriter doesn't throw exceptions on write failures and might therefore lead to unexpectedly trunacated data being produced without any notification
* replacing it's use in MetricsUtils and MafOutputRenderer where it might cause problems
* partial fix for https://github.com/broadinstitute/gatk/issues/5458
> Replacing some uses of PrintWriter

- src/main/java/org/broadinstitute/hellbender/engine/filters/VariantIDsVariantFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/complexExample1.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_KeepSelectionID.vcf
Changed SelectVariants so that it can handle multiple rsIDs separated by ';' in a VCF file.
The corresponding entry gets removed if any of those rsIDs has been set by the user to be deleted.
I also changed testExcludeSelectionIDFromFile() in SelectVariantsIntegrationTest to check this case.
> Completes #5260 on GitHub.

- src/main/java/org/broadinstitute/hellbender/engine/filters/CountingVariantFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyResultSet.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
The debug variable of AsseemblyResultSet wasn't set anywhere, and therefore the command line argument debug didn't propagate to the function buildEventMapsForHaplotypes in EventMap.java. I added the function setDebug to AssemblyResultSet, and set its value in HaplotypeCallerEngine.
> The debug command line argument is now passed correctly in Haplotype caller -- fixed issue #4943

- src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java
Closes #5459.
This change speeds up Mutect2 and HaplotypeCaller by ~5% when not using hardware Smith-Waterman acceleration.  In order to show that the shortcut is only triggered when Smith-Waterman would have given the same result, I modified this branch to throw an exception whenever the shortcut condition is met but Smith-Waterman doesn't agree and ran Mutect2 using this modified version on 60 extremely deep (1000x - 20,000x) mitochondria bams using minimal pruning in order to yield a lot of very thorny haplotypes, as Laura suggested.  Over the several hundred thousand haplotypes in these bams the exception was never thrown.  Therefore, we can be quite confident that this change has no effect on outputs.
@ldgauthier do you mind taking a look?
> optimization in CigarUtils to shortcut to M-only CIGAR when provably optimal

- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
Closes #5072.
@cmnbroad Personally, I'm in favor of making the command line consistent with the rest of the GATK, regardless of backward compatibility.  @vdauwera what do you say?
> gave LeftAlignIndels the usual command line for output
