broadinstitute/gatk

- README.md
> Edits to README: general guidelines

- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTests.java
I deleted our custom gamma function implementation and replaced it with apache math. 
@yfarjoun please have a look. should be trivial
> use apache math libraries. delete custom gamma function computations

- src/main/java/org/broadinstitute/hellbender/engine/filters/InsertSizeReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/LibraryReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/MappingQualityReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/PlatformReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/PlatformUnitReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadGroupBlackListReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadGroupReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadLengthReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadNameReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadStrandFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/SampleReadFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/recalibration/BQSRGatherer.java
- src/main/java/org/broadinstitute/hellbender/utils/commandline/Gatherer.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialSAMUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/text/XReadLines.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadGroupBlackListReadFilterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BQSRGathererTest.java
- src/test/resources/readgroupblacklisttest.txt
- src/test/resources/readgroupblacklisttestlist.txt
ported all filters requested by @vdauwera in #429 
and added tests for all of them.
> ported remaining read filters and added tests

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/ReadsSource.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipeline.java
This class is now needed by other pipelines, so let's make it generally available
in the engine.
> Extract ReadsSource from DataflowReadsPipeline into a public class in the engine

- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
small tweaks to a few bqsr classes. It was intended to solve #189 but I don't know what the answer is. @droazen please review. Unless someone else figures out the LEFT_TAIL mystery, I'll assume it's a stale comment and let's delete it.
> bqsr small tweaks

- AUTHORS
- LICENSE.TXT
@eitanbanks please review and merge if OK
> copyright and authors

- build.gradle
updating htsjdk and dataflow
adding vfs2 to resolve dataflow warning
should close #467
> updating dependencies to current version

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataFlowSAMFn.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/PTransformSAM.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/WordCount.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/CountBasesDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/CountReadsDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipeline.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/FlagStatDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/PrintReadsDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountBasesDataflowTransform.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountReadsDataflowTransform.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/FlagStatusDataflowTransform.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/PrintReadsDataflowTransform.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipelineTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountBasesTransformUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/CountReadsTransformUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/FlagStatTransformUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/transforms/PrintReadsTransformUnitTest.java
@lbergelson please review. minor edits
> small edits while reading the code

- build.gradle
- src/test/java/org/broadinstitute/hellbender/utils/interval/IntervalUtilsUnitTest.java
This fixes a data loss bug with `VCFHeader`
> Bump htsjdk version to 1.132

- Dockerfile
Creating a basic dockerfile so we can build containers of hellbender.
> Adding a Dockerfile to build a hellbender container

- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/SmallBamWriter.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/SmallBamWriterTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorDataflowIntegrationTest.java
PCollection\<Read\> -\> BAM file. With tests.
> few reads writer

- AUTHORS
> add Cloudera to AUTHORS

- src/test/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgramUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtilsUnitTest.java
a few instances of TestPipeline were being used instead of GATKTestPipeline still
> Switching over remaining usages of TestPipeline

- src/main/java/org/broadinstitute/hellbender/tools/dataflow/WordCount.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/vcf/SortVcfTest.java
I made the minor changes requested.
> Modified usage strings

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionaryIntegrationTest.java
Fixed the NPE from #273 and added a test for it.
> Fixing NPE

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/coders/GATKReadCoder.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/coders/GATKReadCoderUnitTest.java
Added a unit test to verify that GATKReads are being coded correctly
regardless of backing implementation.
> Unit test for GATKReadCoder

- build.gradle
> Fix the jat-jar problem

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/DataflowUtils.java
> Upgrade to Spark Dataflow 0.2.3, which has scalability and performance

- src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java
> fix for AlleleListUtilsUnitTest

- build.gradle
- spark.md
I've done this as a markdown document in the top-level directory, but I can move it somewhere else if there's a better place for it.
> Document how to run on Spark

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/transforms/composite/AddContextDataToRead.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ReadsPreprocessingPipeline.java
Profiling is easier when the stages have names and output logging information. Keeping my branch as close as possible to 'master' means merges are easier, both ways.
> Adding names and logging

- build.gradle
run cloud and non cloud tests together with gradle testAll!
> Adding a gradle testAll task to run all the tests

- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorDataflowIntegrationTest.java
We would have noticed this a long time ago were it not for #656.
> Fix for test-breaking typo

- build.gradle
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testClusteredSnps.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testDeletions.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testFilter1.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testFilter2.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testFilterWithSeparateNames.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testFilteringDPfromFORMAT.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testFilteringDPfromINFO.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testGenotypeFilters1.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testGenotypeFilters2.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testInvertFilter.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testInvertGenotypeFilterExpression.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testInvertJexlFilter.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testInvertJexlGenotypeFilterExpression.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testMask1.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testMask2.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testMask3.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testMaskReversed.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testNoAction.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testSetFilteredGtoNocall.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testUnfilteredBecomesFilteredAndPass.vcf
This brings in an important fix for auto-detection of indices
for CRAM files.
> Rev htsjdk to 1.138

- .gitignore
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
this adds a shutdown hook to delete a directory and its contents and works even on directories that didn't exist at call time
> Add deleteRecursivelyOnExit()

- build.gradle
- src/main/java/org/broadinstitute/hellbender/dev/pipelines/bqsr/BaseRecalibratorDataflowUtils.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/ApplyBQSRDataflow.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/ApplyWholeBQSRDataflow.java
- src/main/java/org/broadinstitute/hellbender/dev/tools/walkers/bqsr/BaseRecalibratorDataflow.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReadsDataflowSource.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/DataflowReadsPipeline.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReadsDataflowSourceTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/SmallBamWriterTest.java
Plus small code changes to accommodate the API changes.
This should fix issue #791.
> genomics-dataflow-java at version 0.15. 

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/RefAPISource.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/RefAPISourceUnitTest.java
Fixes issue #816 and improves performance. Marking those tests as mandatory since they pass now.
> Fix RefAPISource test and improve performance

- README.md
Clarified testing and code review policy
> Update README.md on testing

- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ApplyBQSRDataflow.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ReadsPreprocessingPipeline.java
- src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/bqsr/ApplyBQSRTransform.java
- src/main/java/org/broadinstitute/hellbender/utils/logging/BunnyLog.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/ApplyBQSRDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/dataflow/pipelines/BaseRecalibratorDataflowIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/logging/BunnyLogTest.java
This includes the workaround for https://github.com/google/google-http-java-client/issues/293
> ApplyBQSRDataflow, with passing tests.

- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/PileupElement.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/ReadPileup.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialReadUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/PileupElementUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/ReadPileupUnitTest.java
Pileup is going to be needed for variant annotations. Ported over the new read interface.
> porting of pileups infrastructure.

- build.gradle
This should fix the build (see #866).
> Remove guava-jdk5 dependency to fix "stopWatch" error

- src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java
Quick fix of an incorrect comment.
> Fixing comment

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/RefAPISource.java
- src/main/java/org/broadinstitute/hellbender/utils/SimpleInterval.java
- src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceBases.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/datasources/RefAPISourceUnitTest.java
We can now fetch over a million reference bases without crashing.
> RefAPISource support for multiple pages, with corresponding test code.

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/DataflowCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/RefAPISource.java
> Serialize auth onto pipeline

- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
A simple change with a big impact.
> Remove randomUUID for 100x speedup

- .travis.yml
- README.md
- scripts/install_git_lfs.sh
- src/test/java/org/broadinstitute/hellbender/GitLfsTest.java
- src/test/resources/large/.gitattributes
- src/test/resources/large/exampleLargeFile.txt
adding a test for large files existance in the "large" test group
large files should be available for tests on travis after this pull request
> installing git-lfs and downloading large files on travis

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUnitTest.java
Fixes #906.
This will be useful for benchmarking. Can you have a look when you have time @davidadamsphd?
> Write sharded output from MarkDuplicatesSpark.

- src/main/java/htsjdk/samtools/reference/HadoopReferenceSequenceFileFactory.java
- src/test/java/org/broadinstitute/hellbender/engine/dataflow/ReferenceHadoopSourceUnitTest.java
This fix is needed to read references from HDFS for BaseRecalibrator.
> Use the sequence dictionary when reading from HDFS if one's available.

- gradle/wrapper/gradle-wrapper.properties
- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/RequiredReadInputArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSparkIntegrationTest.java
the simplest example, for sanity checking of instalations
> count reads in spark + integration test

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSparkIntegrationTest.java
> count bases on spark

- scripts/binary_search.sh
This script will look for a small input that trips BaseRecalibrator. However, it can be adapted for debugging pretty much anything else, so long as you have two versions of the code: a "known good" one to compare against, and a "under test" one that has the bug you're trying to generate a minimal input for.
> binary search script

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/ApplyBQSRSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortBamSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
I want to be able to specify the name of the app as it appears in the Spark monitoring GUI.
> pull up programName method and add CLI argument to override it

- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/ReferenceShard.java
- src/main/java/org/broadinstitute/hellbender/engine/dataflow/datasources/VariantShard.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariants.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java
- src/main/java/org/broadinstitute/hellbender/utils/dataflow/BucketUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariantsSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/ReadsPreprocessingPipelineSparkTestData.java
change shards `hashCode` to fix bad distribution to partitions
fix NPE
adding uri's change from distinct to aggregate
reduce shard size by half
> Making changes to improve bqsr scaling

- .travis.yml
- README.md
- gradle/wrapper/gradle-wrapper.properties
we've been recommending a very old version, might as well upgrade
> updating gradlew wrapper to newer gradle, 2.7

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/FisherStrand.java
this used to lead to complaints when building on some machines "error: unmappable character for encoding ASCII"
for @davidadamsphd
> removed non-ASCII character

- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
This test was failing to clean up its output directory, because it
was calling File.deleteOnExit() instead of IOUtils.deleteRecursivelyOnExit().
Also changed the tests to write their output to temp locations instead of
the hellbender root.
Resolves #977
> Make ReadSparkSinkUnitTest clean up after itself

- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
fixes #672 
for @davidadamsphd
> Uses proper types for fields (enabled by htsjdk fix)

- .travis.yml
testing to see if external pull request testing is fixed
> fix external pull requests

- README.md
> Update Readme, added info on how to contribute.

- README.md
> readme - gradle 2.7

- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
> exposing bam partition size to GATKSparkTool

- src/main/java/org/broadinstitute/hellbender/engine/filters/MetricsReadFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectBaseDistributionByCycleSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MeanQualityByCycleSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/QualityScoreDistributionSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/MetricsReadFilterUnitTest.java
A very tardy follow up on #1053
> Metrics read filter

- AUTHORS
Add Eugene Wolfson to AUTHORS
@yegeniy please have a look - if you have an email address you'd like to put in there that'd be great
> Add Eugene Wolfson

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISource.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/test/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISourceUnitTest.java
> test query off the contig

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISource.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/test/java/org/broadinstitute/hellbender/engine/datasources/ReferenceAPISourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkOptimizedIntegrationTest.java
> lookup references by assemblyID

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssemblerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingGraphUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/runtime/ProcessControllerUnitTest.java
quick fix for #762 
added `BaseTest.createTempDir()`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/gatk/1083)
> fix dot files from being created in working dir by test

- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
Modified FeatureCache to track the number of cache hits/misses over the
lifetime of each FeatureDataSource. Upon close, output these statistics
to logger.debug().
Tracking this information introduces almost zero overhead, but should be
useful on an ongoing basis as we add new tools to GATK4 and profile them.
> FeatureDataSource: output cache hit rate to logger.debug() upon close

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
as seen in #1092 this improves the performance of variant walkers (at least SelectVariants)
fixes #1092 
quick one for @droazen
> feature cache increased to 100k for variant walkers

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
Fixes a gsa-unstable ticket broadinstitute/gsa-unstable#1194
and fixes #1095
> Fix two SelectVariants issues

- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
> broadcast is default

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceMultiSource.java
- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceSource.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSparkIntegrationTest.java
> broadcast requires 2bit

- src/main/java/org/broadinstitute/hellbender/utils/read/BDGAlignmentRecordToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
> GATKRead.toString

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
This addresses https://github.com/broadinstitute/gatk/issues/1015 and https://github.com/broadinstitute/gatk/issues/1094.
The idea is to remove the single reducer sort (which doesn't scale), by performing a totally ordered parallel sort on the reads, then writing each partition as a (headerless) BAM file. Finally, the BAM files are concatenated together after writing an initial header. This is very similar to the approach that Hadoop-BAM takes, but adapted to work on Spark.
I haven't done extensive benchmarking, but when I ran MD on a ~75MB BAM the runtime dropped from >30 mins to around 8 mins. This is still worse than the walker equivalent for small files, but it's an improvement that means many jobs that didn't finish before now do.
Note that this includes the changes from …
> Improvements to writing a single BAM from Spark

- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkShardedIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BQSRTestData.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java
fixes #1140 (extracts file names to name constants to avoid errors and indicate where same outputs are expected)
for @droazen
> more tests for broadcast on bqsr

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSource.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSourceUnitTest.java
The TwoBit API can't handle queries beyond the ends of contigs (we get
an assertion failure). This changes ReferenceTwoBitSource to truncate query
intervals at contig ends as necessary.
Resolves #1214
> Truncate queries in ReferenceTwoBitSource at contig ends when necessary

- src/main/java/org/broadinstitute/hellbender/utils/baq/BAQ.java
- src/test/java/org/broadinstitute/hellbender/utils/baq/BAQUnitTest.java
fixes #1234 
i checked that the original error goes away
@droazen can you have a quick look?
> fix for IAE in BAQ

- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
Fix for https://github.com/broadinstitute/gatk/issues/1200.
> Clone header in createCommonSAMWriterFromFactory.

- src/main/java/org/broadinstitute/hellbender/utils/read/HeaderlessSAMRecordCoordinateComparator.java
Instead of calling setHeader() to temporarily give headerless reads
a header and then calling into htsjdk's SAMRecordCoordinateComparator,
adapt the htsjdk code directly to work with headerless reads. This should
be safer (especially in a multithreaded context), as mutating the objects
being compared within a comparator is a violation of contract.
> Make HeaderlessSAMRecordCoordinateComparator safer

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSpark.java
> Fix NPE in FlagStatSpark when -O is not specified

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
fixes #https://github.com/broadinstitute/gatk/issues/1312
> remove justReads from SelectVariants

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/DownsampleSam.java
fixes https://github.com/broadinstitute/gatk/issues/1303
> resolve parameter collision

- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CompareSAMs.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/CompareSAMsIntegrationTest.java
fixes #https://github.com/broadinstitute/gatk/issues/1290
> consistent exception for compare SAMs

- .travis.yml
this should stop the timeout errors
> adding timeout protection

- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
fixes https://github.com/broadinstitute/gatk/issues/1285
> mention --help in error message

- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
> Improve the wording of UserException.CouldNotReadInputFile messages slightly

- README.md
- gatk-launch
> Rename --sparkRunner SUBMIT to --sparkRunner SPARK, and --sparkRunner DIRECT to --sparkRunner LOCAL

- README.md
- gatk-launch
The script help output now mentions --list.
Resolves #1331
> Add gatk-launch --list, make ./gatk-launch, ./gatk-launch --help, and ./gatk-launch -h all print help for the script itself

- src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureManagerUnitTest.java
> FeatureManager: allow clients to more tightly control codec selection by considering only codecs that produce a specific type of Feature

- build.gradle
- src/main/java/htsjdk/samtools/DumpBAMFileIndex.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/FindBadGenomicKmers.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/GatherSplitReadsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/Kmer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/Kmerizer.java
note that this PR is onto sv_master, not onto master
> tools to find breakpoints and to find ubiquitous reference kmers

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
also changing the tmp file name to be more random to make races less likely
> fix #1265 delete tmp files after writing single bam

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/ApplyBQSRSparkFn.java
fixes https://github.com/broadinstitute/gatk/issues/1381
@tomwhite please review
> reuse heavy object BQSRReadTransformer for whole partition

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
fix for https://github.com/broadinstitute/gatk/issues/1389
@tomwhite i think we need to revert pull request https://github.com/broadinstitute/gatk/pull/1344
> revert crc fix because it's causing CCE

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_maxNOCALLnumber1.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_maxNOCALLnumber2.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/vcfexample.forNoCallFiltering.vcf
> added maxNOCALLfraction and maxNOCALLnumber to SelectVariants

- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
fixes #914 
@lbergelson please have a look
> make log cached immutable after creation

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
> Change number to fraction in maxNOCALLfraction doc

- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/bqsr/BaseRecalibratorEngineSparkWrapper.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/QuantizationInfo.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkShardedIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java
> Ak bqsr always sort all columns

- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlock.java
- src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlockUnitTest.java
Porting the GVCFWriter and tests
the first commit includes the original gatk classes modulo some import statements and package names
the next commit is my changes on top of it
closes #736
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/gatk/859)
> port GVCFWriter

- src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java
- src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
> tabix requires TBI + writing TBI uses BlockCompressedOutputStream

- build.gradle
> upgrade to spark 1.5.0

- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlock.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlockUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/utils/variant/writers/small.g.vcf
> adding a GVCFWriter test against a sample GVCF

- src/main/java/org/broadinstitute/hellbender/tools/ClipReads.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ReadClipper.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/EventType.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/covariates/ReadGroupCovariate.java
Leaving as 3 separate commits for review. Will squash before merge.
@lbergelson can you have a look?
> BQSR time and memory optimizations - mostly object allocation

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
fixes #1313 
@vdauwera does it look ok?
> better error message for JEXL

- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssemblerUnitTest.java
fixes #1081 
@lbergelson easy one for you
> remove duplicated test

- src/main/resources/log4j.properties
> provide log4j.properties to eliminate adam.log

- src/main/java/org/broadinstitute/hellbender/engine/spark/ShuffleJoinReadsWithRefBases.java
- src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/SimpleInterval.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/SimpleIntervalUnitTest.java
coverage now at 100% 
fixes https://github.com/broadinstitute/gatk/issues/1405 by moving getSpanningInterval as private to ShuffleJoinReadsWithRefBases
> more tests for SimpleInterval. 

- src/main/java/org/broadinstitute/hellbender/engine/ContextShard.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadContextData.java
- src/main/java/org/broadinstitute/hellbender/engine/datasources/VariantsSource.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkOptimized.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/BroadcastJoinReadsWithVariants.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/ShuffleJoinReadsWithVariants.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/bqsr/BaseRecalibratorEngineSparkWrapper.java
- src/main/java/org/broadinstitute/hellbender/utils/collections/IntervalsSkipList.java
- src/main/java/org/broadinstitute/hellbender/utils/test/ReadsPreprocessingPipelineTestData.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariant.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/MinimalVariant.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/VariantContextVariantAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/VariantUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/JoinReadsWithVariantsSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/ReadsPreprocessingPipelineSparkTestData.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/VariantContextVariantAdapterTest.java
> renamed Variant to GATKVariant

- build.gradle
> add a comment to build.gradle

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
> make MD5s for BAM/SAM/CRAM

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
> Hadoop-BAM: add support for efficiently loading a subset of a BAM

- src/main/java/org/broadinstitute/hellbender/utils/recalibration/QuantizationInfo.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/utils/report/GATKReport.java
- src/main/java/org/broadinstitute/hellbender/utils/report/GATKReportTable.java
- src/test/java/org/broadinstitute/hellbender/utils/report/GATKReportUnitTest.java
fixing a bogus test that never worked (fixes #1465)
changing functions that generate simple GATKReports to require a sort order
renaming GATKReportTable.TableSortingWay -> Sorting
not directly to master this time...
> fixing GATKReportUnitTest.testSortingByColumn

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineParser.java
- src/main/java/org/broadinstitute/hellbender/tools/ClipReads.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/KBestHaplotypeFinder.java
- src/main/java/org/broadinstitute/hellbender/utils/read/GoogleGenomicsReadToGATKReadAdapter.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ConsecutiveAppendsShouldReuse
M-Ezzat
> pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse

- AUTHORS
@m-ezzat  Is this the correct email address / spelling of your name?
> adding Mohammed Ezzat to contributors list

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSRIntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/print_reads_withPG.sam
fixes #1527
added a bunch of small doc to GATKTool and made some methods final
@droazen can you review?
> add PG to SAM/BAM/CRAM files

- .travis.yml
the old one has been invalidated
> updating our travis key

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHet.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeff.java
- src/main/java/org/broadinstitute/hellbender/utils/GenotypeCounts.java
- src/main/java/org/broadinstitute/hellbender/utils/GenotypeUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHetUnitTest.java
fixes #1484 
I also refactored the  code duplication between ExcessHet and InbreedingCoef 
@droazen please have a look
> ExcessHet + tests

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/IntervalWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/ClipReads.java
- src/main/java/org/broadinstitute/hellbender/tools/CountBases.java
- src/main/java/org/broadinstitute/hellbender/tools/CountReads.java
- src/main/java/org/broadinstitute/hellbender/tools/FixMisencodedBaseQualityReads.java
- src/main/java/org/broadinstitute/hellbender/tools/FlagStat.java
- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
- src/main/java/org/broadinstitute/hellbender/tools/PrintReads.java
- src/main/java/org/broadinstitute/hellbender/tools/SplitReads.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleIntervalWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithReference.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleReadWalkerWithVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleVariantWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/CalculateTargetCoverage.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/CountVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/RevertBaseQualityScores.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/UnmarkDuplicates.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/ApplyBQSR.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
fixed #358 
for @droazen 
I don't see why #358 depends on @121 btw.
> rename onTraversalDone to onTraversalSuccess

- src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
- src/main/java/org/broadinstitute/hellbender/engine/ProgressMeter.java
- src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java
- src/main/java/org/broadinstitute/hellbender/utils/codecs/ProgressReportingDelegatingCodec.java
- src/test/java/org/broadinstitute/hellbender/engine/ProgressMeterUnitTest.java
fixes #1307 
@droazen can you review?
> track progress in IndexFeatureFile

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
is this how a gradle update is done?
> gradle 2.12

- src/main/java/org/broadinstitute/hellbender/utils/iterators/ReadFilteringIterator.java
- src/test/java/org/broadinstitute/hellbender/utils/iterators/ReadFilteringIteratorUnitTest.java
This was extracted from the HaplotypeCaller branch currently under review,
as it's potentially useful for the LocusWalker branch.
> ReadFilteringIterator: an iterator that filters reads from another iterator

- build.gradle
we don't test on windows and I doubt gatk would work on windows so let's not generate the windows startup to avoid confusing people
@lbergelson can you look at it?
> remove Windows starting script

- src/main/java/org/broadinstitute/hellbender/Main.java
fixes #1598 
Yoda to the rescue!
> fixing #1598

- README.md
adding a "how to profile" info. fixes #1088
> Update README.md - adding profiling documentation

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/MultiDeBruijnVertex.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/MultiDeBruijnVertexUnitTest.java
came up on profiling - computing the hashcode over and over is expensive to we precompute it
> precompute hashcode in MultiDeBruijnVertex and added a bunch of tests

- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SWPairwiseAlignment.java
came up in profiling - SmithWaterman is a hotspot. This PR lifts some field lookups up from tight loops.
@lbergelson can you look?
> Smith Waterman performance - small tweaks

- README.md
- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
> use compression level 1 by default, for speed

- build.gradle
turning off async until until we can separate tribble async from bam async
see #1638
> turning async off async until tribble is fixed

- README.md
document better test selection by gradle test filtering
> document better test selection by gradle test filtering

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/FilterReads.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/RevertSam.java
- src/main/java/org/broadinstitute/hellbender/utils/read/mergealignment/AbstractAlignmentMerger.java
- src/main/java/org/broadinstitute/hellbender/utils/read/mergealignment/MultiHitAlignedReadIterator.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testUnfilteredBecomesFilteredAndPass.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_AlleleTrimming.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_InvertMendelianViolationSelection.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_KeepOriginalDP.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MendelianViolationSelection.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MultiAllelicAnnotationOrdering.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MultiAllelicExcludeNonVar.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_NoGTs.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_UnusedAlleleCCCT.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_UnusedAlleleCCCTEnv.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_UnusedAlleleCCCTTrim.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_UnusedAlleleCCCTTrimAltEnv.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_UnusedAlleleHardLeft.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_UnusedAlleleHardLeftTrim.vcf
- src/test/resources/org/broadinstitute/hellbender/utils/variant/writers/small.g.vcf
adding an htsjdkVersion property since we rely on the version in 2 places in the build
> updating htjsdk to 2.2.0

- src/test/resources/large/.gitattributes
- src/test/resources/large/human_g1k_v37.20.21.fasta.amb
- src/test/resources/large/human_g1k_v37.20.21.fasta.ann
- src/test/resources/large/human_g1k_v37.20.21.fasta.bwt
- src/test/resources/large/human_g1k_v37.20.21.fasta.pac
- src/test/resources/large/human_g1k_v37.20.21.fasta.sa
@SHuang-Broad this is one for you
> add fasta bwt index to repo for bwa

- README.md
fixes to dataproc section after i set it up on current dataproc
> README - fixes to dataproc section

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/GenotypeAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/InfoFieldAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngineUnitTest.java
fixes https://github.com/broadinstitute/gatk/issues/1713
the tests fail unless the 1 line in `GATKVCFHeaderLines` is added
> Adding ExcessHet to GATKVCFHeaderLines and future-proofing

- README.md
added info about dynamic allocation on YARN (I tested it on Google and it works nicely)
> Update README.md to add info about dynamic allocation on YARN

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceMultiSource.java
- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceWindowFunctions.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilter.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkOptimized.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/ShuffleJoinReadsWithRefBases.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/transformers/ReadTransformer.java
- src/main/java/org/broadinstitute/hellbender/utils/SerializableFunction.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
ongoing effort to reduce dependency on dataflow packages.
@lbergelson please have a look
> don't use dataflow SerializableFunction

- build.gradle
packaging gatk-launch in our jar so that it's available to downstream projects
some build.gradle refactoring
> adding gatk-launch to the jar

- AUTHORS
add IBM
@frank-y-liu please review (I can't assign to you because you need write access for that)
> add IBM to AUTHORS

- README.md
better sections, clarified that you can run dataproc from laptop (which I did not know until Louis told me)
> Update README.md - clarified that you can run dataproc from laptop

- build.gradle
this is necessary for sonatype to accept our releases, I forgot to commit it last time i did a release
> adding a developer section to our pom

- src/main/java/org/broadinstitute/hellbender/engine/TraversalParameters.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
@droazen has reviewed (over my shoulder) and says it looks good.
> Added ability to edit intervals in GATKSparkTool subclasses

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/CollectInsertSizeMetricsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/InsertSizeMetricsCollectorSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/CollectInsertSizeMetricsSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/InsertSizeMetricsCollectorSparkUnitTest.java
Hi Chris,
Would you please review this?
And @tedsharpe, feel free to look at the getters in `InsertSizeMetricsCollectorSpark.java` and see if you need more access functions.
Thank you.
Steve
> Tool rewritten to allow different levels

- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/RunBWAMEMViaCommandLineTest.java
@droazen , would you please review, before I go out and get enough beer (I hope I won't have to buy another round with this fix)?
Thanks!
> Fix Jenkins blowup caused by hacking tests involving external programs

- src/main/java/org/broadinstitute/hellbender/utils/baq/BAQ.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/test/java/org/broadinstitute/hellbender/utils/baq/BAQUnitTest.java
fixes #1239 
@droazen please review this alpha-1 ticket
I also deleted the unused option to includeClippedBases (it was always false in all cases)
> add BAQ unit tests, ported from gatk3

- build.gradle
- src/test/java/org/broadinstitute/hellbender/engine/SequenceDictionaryValidationSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineArgumentCollectionTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/ApplyBQSRSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkShardedIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortReadFileSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectBaseDistributionByCycleSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectQualityYieldMetricsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MeanQualityByCycleSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/QualityScoreDistributionSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/CollectInsertSizeMetricsSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/InsertSizeMetricsCollectorSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSparkIntegrationTest.java
adding "spark" tag to additional spark tests
> adding spark group to many spark tests

- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalker.java
- src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/IntervalOverlappingIterator.java
- src/test/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalkerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/iterators/IntervalOverlappingIteratorUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/examples/expected_ExampleLocusWalkerIntegrationTest_output.txt
Porting `LocusWalker` as described in #1464. This is a cleaner PR derived from #1526
> Implemented LocusWalker

- .travis.yml
- README.md
too much noise, too little control
@droazen
> remove sputnik

- src/main/java/org/broadinstitute/hellbender/engine/AlignmentContext.java
- src/main/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByState.java
- src/main/java/org/broadinstitute/hellbender/utils/pileup/ReadPileup.java
- src/test/java/org/broadinstitute/hellbender/utils/pileup/ReadPileupUnitTest.java
Solves #1752 and some changes:
* Adding all the reads overlapping a region, independently of the sample, in `LocusIteratorByState`
* Helper method to get a stratified `Map<String, ReadPileup>` by sample
* Use the previous implementation in the `AlignmentContext` split by sample method
* Adding the possibility (switch off by default) of tracking Ns in the `LocusIteratorByState`
> Multi-sample handling in LIBS

- src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalker.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/IntervalOverlappingIterator.java
> removing unmappable character for encoding ASCII

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/spark/SparkConverter.java
- src/main/java/org/broadinstitute/hellbender/utils/svd/ApacheSingularValueDecomposer.java
- src/main/java/org/broadinstitute/hellbender/utils/svd/OjAlgoAdapter.java
- src/main/java/org/broadinstitute/hellbender/utils/svd/OjAlgoSingularValueDecomposer.java
- src/main/java/org/broadinstitute/hellbender/utils/svd/SVD.java
- src/main/java/org/broadinstitute/hellbender/utils/svd/SimpleSVD.java
- src/main/java/org/broadinstitute/hellbender/utils/svd/SingularValueDecomposer.java
- src/main/java/org/broadinstitute/hellbender/utils/svd/SparkSingularValueDecomposer.java
- src/test/java/org/broadinstitute/hellbender/utils/svd/SingularValueDecomposerUnitTest.java
Pushing MLLib down to public to make it easier for people to use with GATK4. Took SVD along for the ride (to test that it works).
> MLLib + svd calculations

- README.md
Add license badge to the README
@vdauwera wdyt?
> add license badge to README

- gatk-launch
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
Reverts broadinstitute/gatk#1861
> Revert "use snappy and 512k blocks"

- src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
-properly override requiresFeatures() and onStartup()
-documentation fixes
> Minor cleanup in the VariantWalker class

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/FeatureWalker.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleFeatureWalker.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/DataLine.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableColumnCollection.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableReader.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/package-info.java
- src/test/java/org/broadinstitute/hellbender/tools/examples/ExampleFeatureWalkerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/tsv/DataLineUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/tsv/TableColumnUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/tsv/TableReaderUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/tsv/TableUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/tsv/TableWriterUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/engine/example_features.bed
- src/test/resources/org/broadinstitute/hellbender/tools/examples/expected_ExampleFeatureWalkerIntegrationTest_output.txt
partially addressed https://github.com/broadinstitute/gatk/issues/1427 (let's do this in a few steps to minimize risk)
@droazen have a look
(will remove them from protected when this is merged and we're reved up)
> moved FeatureWalker and TSV code from protected

- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReadsUnitTest.java
- src/test/resources/large/NA12878.RNAseq.bai
- src/test/resources/large/NA12878.RNAseq.bam.bai
- src/test/resources/large/expected.NA12878.RNAseq.splitNcigarReads.subSequenceTest.bam
I refactored SplitNCigar reads to use the ReadWalker interface
> SplitNCigar reads walker refactor 1864

- scripts/anonymizeSampleNames.py
- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/GeneralPloidyFailOverAFCalculatorProvider.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/main/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/FisherStrandUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/GeneralPloidyFailOverAFCalculatorProviderUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
These are the changes to public necessary to support my initial port of genotypeGVCFs.
> public changes to support GenotypeGVCFs

- src/main/java/org/broadinstitute/hellbender/tools/validation/validate-reads-spark-pipeline.sh
I checked that it runs now with picard 2.0.1 and GATK3.5 (validation fails though)
> fix the script to validate-reads-spark-pipeline 

- .travis.yml
trying to fix the coveralls insanity about coverage dropping to 12% all the time. I think it may be because we send results from the cloud tests which are tiny
> no coveralls for cloud only tests

- src/test/resources/large/.gitattributes
these 2 files were missing from #1936
@lbergelson ok to merge?
> add blocked gvcf to attributes

- README.md
closes https://github.com/broadinstitute/gatk/issues/1609
@davidbernick does this look OK?
> added info about performance tests to README

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHet.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHetUnitTest.java
Port from [broadinstitue/gsa-unstable#1426](https://github.com/broadinstitute/gsa-unstable/pull/1426)
@akiezun Could you please take a look since there were some changes to ExcessHet between GATK3 and 4?
> Changes max value output for ExcessHet

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSource.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSparkIntegrationTest.java
a .gz suffix), see https://github.com/HadoopGenomics/Hadoop-BAM/pull/106.
Also remove spurious debug.
> Add support for block gzipped files with a .bgz suffix (as well as

- build.gradle
Checks for AVX support on the CPU. Fixes #1985
> Bump GKL version to 0.1.2

- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/tsv/TableWriter.java
- src/test/java/org/broadinstitute/hellbender/utils/tsv/TableColumnCollectionUnitTest.java
@lbergelson can you review and make a snapshot with those? It will allow me to cleanup https://github.com/broadinstitute/gatk-protected/pull/610 and delete 2 more classes from there
> backport 1 method from protected and renamed 1 file

- src/main/java/org/broadinstitute/hellbender/utils/svd/SVD.java
- src/test/java/org/broadinstitute/hellbender/utils/svd/SingularValueDecomposerUnitTest.java
added some better svd checking code 
@davidbenjamin this is pretty much straight from your comments in https://github.com/broadinstitute/gatk-protected/pull/609
can you review?
> a bit better asserts to check SVD

- README.md
> remove mention of AVX or GCC from README

- src/main/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSparkEngine.java
fixes #2050 
@tomwhite can you have a look?
> fix for race condition in BwaSparkEngine

- src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationArgumentCollection.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkShardedIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BQSRTestData.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java
(to make it off by default, ie no BAQ)
fixes #2060 
@droazen for you
> rename skipBAQ to enableBAQ and reverse the logic

- src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
- src/test/java/org/broadinstitute/hellbender/utils/clipping/ClippingOpUnitTest.java
> Fixed ClippingOP.getNewAlignmentStartOffset() to handle N cases properly and added unit tests

- src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/GenomeLocParserUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
> Throw an exception for invalid Picard intervals

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/bwa/BWANativeLibrary.java
moving from jbwa 1.0.0 -> 1.0.0_ppc64
updating the BWANativeLibrary loader to be ppc aware
> adding support for jBWA on power

- README.md
- build.gradle
> Add gradle distArchive to create a zip containing a standalone GATK distribution + launcher + README

- build.gradle
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testFilteringDPfromFORMAT.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testGenotypeFilters1.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testGenotypeFilters2.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testInvertGenotypeFilterExpression.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testInvertJexlGenotypeFilterExpression.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/expected/testVariantFiltration_testSetFilteredGtoNocall.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration/filteredSamples.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MaxFilteredGenotypesSelection.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MaxFractionFilteredGenotypesSelection.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MinFilteredGenotypesSelection.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MinFractionFilteredGenotypesSelection.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_SetFilteredGtoNocall.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/filteredSamples.vcf
updating test files due to change in VCF FT field from htsjdk
> updating to htsjdk 2.5.0 -> 2.6.0

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceFileSource.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/utils/fasta/CachingIndexedFastaSequenceFile.java
- src/main/java/org/broadinstitute/hellbender/utils/spark/SparkUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureDataSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/GATKToolUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/ReadsDataSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/ReferenceDataSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/ReferenceFileSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/ReferenceMultiSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/fasta/CachingIndexedFastaSequenceFileUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/samples/SampleDBUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/spark/SparkUtilsUnitTest.java
Fix for https://github.com/broadinstitute/gatk/issues/1593.
> Error handling for non-existent reference files.

- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java
- src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java
> Changed twoPassReadsWalker to reinitialize the reads to ensure equivalent behavior across SAM formats

- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/VcfUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/GATKToolUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
Common VCFWriter creation, and fix for https://github.com/broadinstitute/gatk/issues/365 (for non-Spark tools).
> Common VCFWriter and honor index/md5 arguments.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSinkUnitTest.java
Addresses #1989. Note that this requires https://github.com/HadoopGenomics/Hadoop-BAM/pull/111 from Hadoop-BAM, so it's not ready to be merged yet.
@lbergelson would you like to take a look to see if the direction looks OK to you?
> VariantsSparkSink

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/IndependentAllelesDiploidExactAFCalculator.java
@vruano Can you take a look at this plagiarism of your work in GATK3?
> Backport a bug fix, closes issue #2040

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
Triallelic site, strand artifact and clustered read position filters.
> Added VCF constants for Mutect2 filters

- src/main/java/org/broadinstitute/hellbender/engine/datasources/ReferenceFileSource.java
This class was leaking file handles badly on Spark
> Close readers in ReferenceFileSource

- src/main/java/org/broadinstitute/hellbender/Main.java
* No change in the actual behaviour of GATK
* Several protected methods for customize some parameters of the toolkit:
- `String getCommandLineName()`: returns the name from the command line toolkit
- `void handleResult(Object)`: handle the output of the tool
* `main(String[] args)` code moved to a non-static final method (`mainEntry(String[])`) called inside the static one. This allow that the changes from override the customization methods could be apply with custom instances.
With this changes a custom main could be simplify a lot. As an example:
```java
public class Main extends org.broadinstitute.hellbender.Main {
@Override
protected String getCommandLineName() { return "MyCustomName"; }
@Override
protected List<String> getPackageList() {
return Arrays.asList("org.custom.tools");
} …
```
> Main improvements for custom toolkits

- src/main/java/org/broadinstitute/hellbender/utils/collections/CountSet.java
- src/test/java/org/broadinstitute/hellbender/utils/collections/CountSetUnitTest.java
> Fixed CountSet::MyIterator

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/RevertSam.java
- src/main/java/org/broadinstitute/hellbender/utils/read/mergealignment/AbstractAlignmentMerger.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSinkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
* Update htsjdk to 2.7.0
* Remove usage of deprecated `SAMRecordUtil`
* Remove usage of deprecated `IndexFactory.writeIndex(index, indexFile)`
* Cleaning `IndexFeatureFile`
> Update htsjdk to 2.7.0

- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadUtilsUnitTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/BQSR/expected.overlappingRead.recal.txt
> Fix adapter bounday for positive strand

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
> Update stand_call_conf doc string

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/picard/sam/SamToFastq.java
Fix deprecation-related errors.
> Update htsjdk to 2.8.1-17-g19bd848-SNAPSHOT

- src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java
- src/test/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcherTest.java
- add missing null check for reads a whole block past EOF
- correct handling for seek just past EOF + read
- fix reuse of caching buffer when near EOF
- add tests that reproduce(d) the problems
> Fix EOF handling in prefetcher

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureInput.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureInputUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/examples/ExampleAssemblyRegionWalkerSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/PileupSparkIntegrationTest.java
This change allows features to be loaded using a NIO file, rather than just a local file.
> Support Path URIs for features.

- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
- src/main/java/org/broadinstitute/hellbender/engine/FeatureWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
- src/main/java/org/broadinstitute/hellbender/engine/IntervalWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/MultiVariantDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/MultiVariantWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/ReadsDataSource.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/VariantWalkerBase.java
- src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java
this duplicates work done for the Reads
> hooking up tools so they take path wrappers for Features

- src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterPluginUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
Fixes one of the cases described in #2377.
> Repeated disabled filters throws CommandLineException

- src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java
These measurement are useful when tuning performance (or hunting down performance anomalies), but they have a measurable overhead (10% difference on a test with 1000 intervals, 5x the standard deviation on 10 runs). So turn them off by default.
Also refactor a few of those into a try-finally to avoid repetition and its associated risks on correctness.
> Turn off fine-grained timing of prefetching by default

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/CustomAFPriorProvider.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AFPriorProviderUnitTest.java
Implement https://github.com/broadinstitute/gatk/issues/2413.
> Total ploidy does not have to equal to the number of priors

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/AlignmentRegion.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/AssemblyAlignmentParser.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/GATKSVVCFHeaderLines.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/NovelAdjacencyReferenceLocations.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVConstants.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVVariantCallerUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SVVariantConsensusCall.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/SvType.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/AlignmentRegionUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/AssemblyAlignmentParserUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/SVTypeUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/SVVariantCallerUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/SVVariantConsensusCallUnitTest.java
@cwhelan , this is the code for turning the edge case where an operator 'I' is the beginning or ending operator in the CIGAR of the contig alignment.
Please kindly review. Thanks!
> terminal 'I' to 'S' in gapped alignment breaker in SV-calling step

- src/main/java/org/broadinstitute/hellbender/engine/filters/MappingQualityReadFilter.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
> Add --maximumMappingQuality to MappingQualityReadFilter

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
> Update to Barclay 1.0.0-24-g87c3fa2-SNAPSHOT

- README.md
Via a VM, your account, or a service account.
> Document how to authenticate to Google Cloud Storage

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/VariantsToTable.java
> Document how VTT orders samples in output table

- README.md
The headings in our README were not rendering properly on github.
This fixes the rendering issue.
> Fix markdown headings in README to satisfy github

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AFCalculatorProvider.java
> Fixed javadoc. Closes #1945.

- src/main/java/org/broadinstitute/hellbender/tools/BwaMemIndexImageCreator.java
- src/test/java/org/broadinstitute/hellbender/tools/BwaMemIndexImageCreatorIntegrationTest.java
@droazen please take a look. Should be quick. Thanks!
> Move BwaMemIndexImageCreator to tools package from utils package

- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQuality.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQualityUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngineUnitTest.java
this allows you to convert RAW_MQ -> MQ 
this is not a general port of the reducible annotation's reducers
> adding RMSMappingQuality.finalizeRawMQ

- scripts/sv/create_cluster.sh
- scripts/sv/default_init.sh
> fix mistake in regex testing if a string ends with slash

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java
> Unit test for AlelleSubsettingUtils.calculateLikelihoodSums. Closes #2178.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHC.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/QualByDepth.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerAlleleBySampleUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHCUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/QualByDepthUnitTest.java
> Set AD and DP to zero if no read coverage

- src/main/java/org/broadinstitute/hellbender/engine/spark/AddContextDataToReadSparkOptimized.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java
Use NIO and htsjdk instead.
This belongs under issue #2402.
It's all gone:
```
$ grep -r BAMIO src/*
$
```
> Remove dependency on BAMIO

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/nio/ReadsIterable.java
- src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java
(these are all cloud-specific)
> Set channel reopen option and retry options for robustness

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/nio/GcsNioIntegrationTest.java
Also uncomment getAuthenticatedGcs test and update
code to new way of setting retry params.
> Update to latest gcloud, uncomment getAuthenticatedGcs

- src/main/java/org/broadinstitute/hellbender/tools/BwaMemIndexImageCreator.java
getFullPath is similar to dirname -- it's not the right method to call
> default output name was not being set correctly

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlock.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/HomRefBlockUnitTest.java
Implements the gatk part of https://github.com/broadinstitute/gatk-protected/issues/602.
> Limit GQ to fix GVCF block merging, throw exception for GQB > MAX_GENOTYPE_QUAL

- src/main/java/org/broadinstitute/hellbender/utils/FisherExactTest.java
- src/test/java/org/broadinstitute/hellbender/utils/FisherExactTestUnitTest.java
> Fixes rounding errors in FS using the same solution as R

- src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
@samuelklee Can you review this?
> deleted redundant method lnToLog10. Closes #2166.

- src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java
Addresses issue #2652 with the added bonus that we distinguish between different prefetcher instances (they each only have one thread, so the thread index won't help all that much besides checking they don't have too many threads).
> Name prefetching thread

- src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
@samuelklee This fixes another of your issues.
> unify two methods for checking readable files and let multiple files be passed. Closes #2145.

- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/GenomicsDBImportIntegrationTest.java
Closes #2583.
@lbergelson one more for you.
> added a constant for the path to the b38 reference in BaseTest

- src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
> improved an error message for missing sequence dictionary. Closes #1305.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/ApplyVQSR.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
Closes #2589.
@lbergelson since you raised the issue can you review?
> unified check for current and deprecated spanning deletion allele

- Dockerfile
- README.md
- build.gradle
- build_docker.sh
- scripts/docker/README.md
- scripts/docker/gatkbase/Dockerfile
- scripts/docker/gatkbase/build_docker_base.sh
- src/test/java/org/broadinstitute/hellbender/engine/FeatureInputUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSUtilsTest.java
- src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsTest.java
- src/test/java/org/broadinstitute/hellbender/utils/nio/GcsNioIntegrationTest.java
- Create a GATK4 Dockerfile
- Added a script to create the docker image for the GATK4 Dockerfile.  This will create a staging directory if desired.
- Created a GATK Base Dockerfile that other GATK4 Dockerfiles can use in ``FROM``
- Added a script to create the GATK Base image
- Documentation
- Fixed unit tests that fail in the docker image.
- docker images based on OpenJDK 8
Closes #2457 
Closes #2708 
Closes #2700
> Issue 2457 docker updates

- .travis.yml
> Issue 2697 docker testing

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportUnitTest.java
Added validateSampleNameMap command line parameter
Added a unit test
Updated genomicsdb version to 0.6.3
> Changes for issue #2713, #2714 and #2715

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.index.template.html
- src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.template.html
Fixes https://github.com/broadinstitute/gatk/issues/2744. Depends on Barclay upgrade.
> Integrate BetaFeature annotation with help/doc.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PairHMMNativeArgumentCollection.java
Also updated GKL version to 0.5.2, since it adds some output with information about num threads
> Changed default cores (threads) to 4 in OpenMP PairHMM; addresses #2717

- src/main/java/org/broadinstitute/hellbender/tools/picard/vcf/GatherVcfs.java
With this argument, we still check start positions to make sure they're increasing within a given contig
during a conventional gather, but we don't enforce relative ordering of contigs using the ordering of
the sequence dictionary in the VCF header.
> Add a --disableContigOrderingCheck argument to GatherVcfs to disable the comparison of relative contig ordering during a conventional gather

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
Fixes https://github.com/broadinstitute/gatk/issues/2240.
> Remove gatk3Compatibility argument from VQSR.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
Along with minor changes needed to track the moved classes
and changed interfaces.
This is related to issue #2822
> Update to gcloud NIO 0.19.0

- README.md
- build.gradle
- gatk-launch
> Remove gatk-launch dependency on settings.gradle, update gatkZipDistribution target

- gatk-launch
> Fixing bug in arg parsing for spark arguments in gatk-launch

- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortReadFileSpark.java
> Fix logger message in SortReadFileSpark

- src/main/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBias.java
Please see <https://github.com/broadinstitute/gatk/issues/3030> for the errors I encountered when running this tool. I have not been able to run the tool successfully and so ask what are we missing in the documentation that will help users get this tool running.
Otherwise, I recommend labeling this tool experimental as well as in BETA.
> shl FilterByOrientationBias tag doc, flesh out example command, introduce tool

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java
Placed a call to forceJVMLocaleToUSEnglish in Main.runCommandLineProgram so that integration tests can take advantage of this.
Fixes #2557
> Porting forceJVMLocaleToUSEnglish from GATK3.

- scripts/mutect2_wdl/README.md
- scripts/mutect2_wdl/mutect2-replicate-validation.wdl
- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_multi_sample.wdl
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl
> edited Mutect wdl README to reflect recent changes

- .travis.yml
cleaning up some old lines that are no longer necessary
adding additional directories to cache
> minor improvements to the .travis.yml

- src/main/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriter.java
- src/test/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriterUnitTest.java
Implements the gatk public part of https://github.com/broadinstitute/gatk-protected/issues/1029.
> Changed maximum allowed GQB value to 100

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
Added some websites with tool information and updated the command
> ChangedHaplotypeCallerDoc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
Added some minor changes for easier reading. Should insert some docs for CombineGVCFs when we know where the doc lives.
> ChangedGenotypeGVCfsDoc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
For GATK4 docs. Should add in ApplyVQSR webpage when available.
> ChangedVariantRecalibratorDoc

- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
> ChangedLeftAlignIndelsDoc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/Pileup.java
> ChangedPileupDoc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/AnalyzeCovariates.java
> ChangedAnalyzeCovariatesDoc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/VariantsToTable.java
> Changed VariantsToTable Doc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
Explanation of GATK4 SelectVariants
> ChangedSelectVariantsDoc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ValidateVariants.java
> Changed ValidateVariants Doc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
> Changed VariantFiltrationDoc

- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSparkIntegrationTest.java
This is a port from protected of https://github.com/broadinstitute/gatk-protected/pull/1004, with all comments addressed.
> Use VariantsSparkSink to write variants in parallel

- src/main/java/org/broadinstitute/hellbender/tools/exome/ReadCountCollectionUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/pon/coverage/pca/HDF5PCACoveragePoNCreationUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/pon/coverage/pca/HDF5PCACoveragePoNCreationUtilsUnitTest.java
Green light from devs to change this. However, perhaps more discussion is warranted. Please see #3163 for details leading to this PR.
> Do not round to integer during CreatePanelOfNormals filtering (addresses #3163).

- build.gradle
Depends on https://github.com/broadinstitute/gatk/pull/3165.
> Copy gatkDoc CSS file in doc build.

- src/main/java/org/broadinstitute/hellbender/tools/exome/NormalizeSomaticReadCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/PerformSegmentation.java
@samuelklee's request described in #3156.
> Shl doc explicate log2 for PerformSegmentation and NormalizeSomaticReadCounts

- scripts/mutect2_wdl/unsupported/calculate_sensitivity.py
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity.json
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity_all_plexes.wdl
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity_truth.json
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity_truth.wdl
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity_truth_all_plexes.wdl
- scripts/mutect2_wdl/unsupported/mutect2_multi_sample_concordance.wdl
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java
@takutosato These are the changes I made for the most recent GP validation.
> Polishing hapmap M2 validation

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java
> If null likelihoods, don't add to likelihoods sums

- scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity_all_plexes.wdl
@takutosato These are the finishing touches on autoval.  After this it will be ready to hand off to the TAG team.
> Enhance M2 hapmap sensitivity wdl

- scripts/mutect2_wdl/mutect2.wdl
> Added automatic extraction of sample name from the bam file.

- scripts/mutect2_wdl/mutect2.wdl
This corrects an issue where an incorrect number of variants would be filtered.
Closes #3288
> Making FilterByOrientationBias come after all other filtering.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandArtifact.java
due to recursive implementation of Legendre abscissas in Apache Commons.
@vdauwera @takutosato this is very simple; it just caps the number of subdivisions of the integral to avoid the recursive stack overflow.  I tested it on absurdly high coverage (100,000) and reproduced the error with the old code.  Whichever one of you gets to this first should review.
While this isn't the most beautiful thing in the world, it will work reasonably while new integration code is pending.
> Fix stack overflow at high depths in strand artifact annotation

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
MEDIAN_BASE_QUALITY_DIFFERENCE_FILTER and MEDIAN_MAPPING_QUALITY_DIFFERENCE_FILTER may be reported as MEDIAN_CLIPPING_DIFFERENCE_FILTER.
> correct filter names

- .travis.yml
Fixed issue were the travis script would fail to upload test reports because gsutils was not being found.
> Fixed Travis issue where test reports were not being uploaded

- scripts/mutect2_wdl/mutect2.wdl
@LeeTL1220 can you review this if tests pass?
> gave ProcessOptionalArguments in M2 wdl a leaner docker

- scripts/docker/gatkbase/install_R_packages.R
- scripts/mutect2_wdl/mutect2.wdl
- src/main/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBias.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java
- src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBiasIntegrationTest.java
Closes #3344 
Closes #3343 
Closes #3309
> Fixes for FOB being too generous, broken FOB summary table, oncotator MAF override values, and updating tests.

- Dockerfile
- README.md
> Changed the landing directory for the docker image to be /gatk

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_multi_sample.wdl
@LeeTL1220 as discussed today.
> M2 wdl outputs the contamination

- scripts/mutect2_wdl/mutect2_multi_sample.wdl
- scripts/mutect2_wdl/mutect2_pon.wdl
> Wrote wdl for making Mutect pon

- AUTHORS
adding Byunggil Yoo to the AUTHORS file
closes #3391
> update AUTHORS file

- build_docker.sh
Also deletes the staging directory when finished.
fixes #3191
> Changed the build_docker.sh to run git LFS dependent tests

- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriter.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/SAMFileDestination.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngineUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriterUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/2849.
> Honor index/MD5 creation for HC/Mutect2 bamouts.

- src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollection.java
- src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/IntervalArgumentCollectionTest.java
As well as some tests to the test suite.
> Added command line argument for IntervalMerging based on GATK3

- README.md
- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
since @jean-philippe-martin is away I'm responding to my own comments on https://github.com/broadinstitute/gatk/pull/3159
> responding to my own comments on jp's branch

- README.md
> Add link to GATK4 release instructions to README

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/test/testers/AbstractMarkDuplicatesTester.java
- src/test/java/org/broadinstitute/hellbender/tools/picard/sam/MergeBamAlignmentIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/MarkDuplicatesTester.java
> updating to htsjdk snapshot 2.10.1-26-g9c6c364-20170731.190658-1

- AUTHORS
adding new contributor Don Freed to AUTHORS
closes #3435
> add Don Freed to AUTHORS

- scripts/docker/gatkbase/install_R_packages.R
> changing cran repo for R installation -- sol. 2

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignedContig.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignmentInterval.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AnnotatedVariantProducer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/GappedAlignmentSplitter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/NovelAdjacencyReferenceLocations.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/StrandSwitch.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SvType.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SvTypeInference.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFConstants.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SvCigarUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AnnotatedVariantProducerUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignmentUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/GappedAlignmentSplitterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/NovelAdjacencyReferenceLocationsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SVTypeUnitTest.java
Some code cleanup, some existing class extension, some new utility classes.
All made to prepare for complex sv detection. This is the beginning.
Related changes are put into the same commit for easier review.
Test coverage is expected to drop slightly, but will be take care of in later commits.
> PR series for complex SV, part 0

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadMetadata.java
that shouldn't have been possible.
> Fixes #3462.  Eliminate possibility of a negative fragment length

- src/main/java/org/broadinstitute/hellbender/engine/ShardBoundaryShard.java
Or should we remove `serialVersionUID`?
> Make ShardBoundaryShard implement Serializable

- hooks/post_checkout
> Fixed the git version for the output jar on docker automatic builds

- README.md
> Added in documentation in the README.md file for bash tab completion.

- build.gradle
> Modifying build.gradle to include tab completion script in bundle.

- src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
> Fix MissingReferenceDictFile exception constructor.

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSink.java
- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
Fixes #2738, and is based on #3106 (which should be merged first). Also, requires a Hadoop-BAM release.
@lbergelson you mentioned something about changes you made to `HaplotypeCallerEngine` for GVCF - is that relevant to this PR do you think?
> Add GVCF support to VariantsSparkSink

- .travis.yml
to see if the build issues go away.
> Revert to the previous travis image.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
@sooheelee This is the issue you brought to my attention, and the fix is the method you suggested.  Would you mind reviewing?
> clip M2 alleles before emitting in case some alleles were dropped

- src/main/java/org/broadinstitute/hellbender/utils/codecs/table/TableFeature.java
- src/test/java/org/broadinstitute/hellbender/utils/codecs/table/TableFeatureUnitTest.java
> TableFeature javadoc and more tests

- src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/PileupSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/CheckPileup.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/Pileup.java
- src/test/java/org/broadinstitute/hellbender/engine/AssemblyRegionUnitTest.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
Solves #2165 without breaking previous behavior
> PrimaryAlignmentReadFilter change

- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSpark.java
In PathSeqPipelineSpark, the reads are repartitioned to ~5k per partition (by default) just prior to the pathogen BWA alignment step (to ensure an even distribution of work). Currently, some samples with a lot of non-host reads cause 10,000's of sharded BAMs to be written at the end of the pipeline.
This PR reduces the number of partitions in the read RDD just before writing to disk in the PathSeqPipelineSpark tool. It exposes a command-line option for the number of reads per partition, with a default value that results in a much more reasonable number of sharded BAMs in even the worst cases.
> Reduce number of output partitions in PathSeqPipelineSpark

- build.gradle
* Non-diploid genotypes: https://github.com/broadinstitute/gatk/issues/3342
* Phasing information in genotypes: https://github.com/broadinstitute/gatk/issues/3345
* Bug fixes and incremental improvements
> Upgrade GenomicsDB to version 0.7.0

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
Fixes https://github.com/broadinstitute/gatk/issues/3500.
> Move to google-cloud-java:0.23.1-alpha.

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_multi_sample.wdl
- scripts/mutect2_wdl/unsupported/mutect2_opt.wdl
- Added option to produce bamouts (assembled haplotypes in bam form) from M2
- Added WDL file for our specops team (@jsotobroad @meganshand )
> BamOut in M2 WDL

- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
- src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.testGVCFMode.gatk4.alleleSpecific.g.vcf
Corrects a couple of allele-specific annotations.
> Correct gVCF header lines

- build.gradle
upgrading to the newest htsjdk so we're not on a snapshot anymore
> upgrading to htsjdk 2.12.0

- README.md
User brought up that Broad's google-cloud-sdk is not up to date, so I added a note telling people to upgrade regularly.
> Added note on updating sdk frequently

- src/main/java/org/broadinstitute/hellbender/utils/test/SamAssertionUtils.java
Fixes https://github.com/broadinstitute/gatk/issues/3664.
> Fix SamAssertionUtils SortSam call.

- src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
Since we already have the CRAM files.
> Add CRAM integration tests for HaplotypeCaller.

- src/main/java/org/broadinstitute/hellbender/utils/param/ParamUtils.java
> Added a missing newline in ParamUtils method.

- scripts/docker/gatkbase/install_R_packages.R
Adding an R dependency for a package that improves performance and memory usage for reading large TSV files.  This is convenient for generating CNV plots from WGS data.
Note: The current CNV plotting code has other issues that make it unsuitable for WGS data; these are addressed in the sl_wgs_acnv dev branch for the new pipeline by new versions of the plotting tools.  However, I do not plan on making these fixes to the old versions of the plotting tools.  The real purpose of this PR is just to get the additional R dependency merged into master so I can build a new docker for the dev branch.
> Adding data.table R package.

- scripts/mutect2_wdl/unsupported/mutect2_opt.wdl
Adds dynamic sizing to m2 wdl as well as standardization of each task in terms of what control a user can have over it.  This is the first step pegging spec ops to a commit and then merging with the mutect.wdl proper once a release is to be made.
> updates to mutect2_opt wdl

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadMetadata.java
Fixes https://github.com/broadinstitute/gatk/issues/3717
> use clipped alignment start and end for computing partition boundaries

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/InsDelVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SimpleStrandSwitchVariantDetector.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplicationsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignmentUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/NovelAdjacencyReferenceLocationsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/SVDiscoveryTestDataProvider.java
partially cleanup, partially reminiscent of PR series part 5.
Broke into 3 commits, with the first two having no logic change and the last with logic changes.
> Improve ChimericAlignment in SV pipeline

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVContext.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalTree.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVVCFReader.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignedContigGeneratorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSparkUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVIntervalTreeTest.java
for now, just prints a false positive rate for intervals, and a false negative and false positive rate for novel adjacencies.  we can beef up the reporting later if it seems useful.
> compare to truth data

- Dockerfile
- scripts/docker/gatkbase/install_R_packages.R
Assuming the URL @lbergelson put in https://github.com/broadinstitute/gatk/issues/3772 is the correct one.
> Update repo location in install_R_packages.R.

- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplicationsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/GappedAlignmentSplitterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/EvidenceTargetLinkClustererTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/TextMDCodecTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/PairedStrandedIntervalTreeTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVFastqUtilsUnitTest.java
@magicDGS here you go. All unit tests in SV package now.
> adds "extends GATKBaseTest" to all SV unit tests

- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSink.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSinkUnitTest.java
> Write VCF files with .gz extension in block gzip format.

- src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
improving gatk, one error message at a time
> better error message

- scripts/mutect2_wdl/unsupported/calculate_sensitivity.py
- scripts/mutect2_wdl/unsupported/hapmap_sensitivity.wdl
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithExpectedAlleleFraction.java
As requested by Alyssa Macbeth.  @LeeTL1220 can you review?
> Add raw total counts to M2 autoval tables

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java
On 30x WGS samples FilterMutectCalls runs out of memory, even the node has 128GB of RAM. We believe this is because we store all variant contexts in a list. We can fix this by writing to vcf as we go.
> FilterMutectCalls: write to vcfs as we go

- build_docker.sh
> build_docker.sh: push to GCR repo in addition to dockerhub repo

- src/main/java/org/broadinstitute/hellbender/Main.java
Fixes https://github.com/broadinstitute/gatk/issues/3816.
> Send command line output to the correct stream.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SWNativeAlignerWrapper.java
- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanAligner.java
- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanIntelAligner.java
- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanJavaAligner.java
- src/test/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanAlignerAbstractUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanIntelAlignerUnitTest.java
Added support for the Native Intel SmithWaterman Aligner. Added the unitTest for the same. 
Closes #1812.
> Added the support for Native Intel SmithWaterman Aligner

- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SWNativeAlignerWrapper.java
- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanJavaAligner.java
going from debug -> info so that we'll always get timing information
> changing log level of SmithWaterman timing output

- src/main/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs.java
- src/test/java/org/broadinstitute/hellbender/engine/MultiVariantWalkerGroupedOnStartUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFsIntegrationTest.java
It looks like the HTSJDK update branch changed a few engine constants and that wasn't pulled into the combineGVCFs branch before merging.
> Fixed an incompatibility with the HTSJDK update branch

- src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
Fixes https://github.com/broadinstitute/gatk/issues/3534. @droazen I was planning to do https://github.com/broadinstitute/gatk/issues/2102 at the same time as this, but I'm submitting just this bug fix since it sounded like you wanted it soon.
> Honor VCF output index/md5 arguments in HC.

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/AssemblyContigWithFineTunedAlignments.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/InsDelVariantDetector.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignmentUnitTest.java
This fixes #3874 .
The detail is explained in the ticket and the self-review comments in code change below.
> fix 3874 by using the correct predicate

- .travis.yml
I'm sick of scrolling to the bottom to find the test report uri.
This saves the pain of having to scroll all the way down.
> putting a link to travis results at the top

- scripts/sv/runWholePipeline.sh
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignmentInterval.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/AssemblyContigAlignmentSignatureClassifier.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/AssemblyContigWithFineTunedAlignments.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SvDiscoverFromLocalAssemblyContigAlignmentsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/AlignedAssemblyOrExcuse.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignedContigGeneratorUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/AlignmentIntervalUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/DiscoverVariantsFromContigAlignmentsSAMSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/StructuralVariationDiscoveryPipelineSparkIntegrationTest.java
resolves #3890
Broken into commits for easier review
> merge prototyping SV breakpoint and type inference tool into SV spark pipeline

- build_docker.sh
- scripts/docker/gatkbase/build_docker_base.sh
> Removed SUDO from the docker build script

- src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionWalker.java
- src/main/java/org/broadinstitute/hellbender/engine/LocalReadShard.java
- src/main/java/org/broadinstitute/hellbender/utils/iterators/ReadTransformingIterator.java
- src/test/java/org/broadinstitute/hellbender/engine/LocalReadShardUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/iterators/ReadTransformingIteratorUnitTest.java
@droazen Is this what you had in mind?
> AssemblyRegionWalker now hooked up to pre- and post-filter read transformers

- build.gradle
updating htsjdk and picard dependencies
htsjdk 2.13.1 -> 2.13.2
picard 2.14.0 -> 2.16.0
> update htsjdk 2.13.2 and picard 2.16.0

- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummariesIntegrationTest.java
@LeeTL1220 can you review this?
> GetPileupSummaries throws exception if AF field missing from vcf. Closes #3955.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotation.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactory.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactoryUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/XSVFuncotationUnitTest.java
- src/test/resources/large/funcotator/dataSources/CosmicTest.db
> Implemented COSMIC reader for Funcotator.

- src/main/java/org/broadinstitute/hellbender/tools/exome/FilterByOrientationBias.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQuality.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/FragmentLength.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/MappingQuality.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/OxoGReadCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/PerAlleleAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosition.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReferenceBases.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandArtifact.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/UniqueAltReadCount.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContamination.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FilterMutectCalls.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContaminationIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummariesIntegrationTest.java
@sooheelee The first commit here is pure javadoc, which you can review.  The second involves some code, but it's just switching some arguments to kebab case.  Would you like to review the second, or should I assign a developer?
> Lots of Mutect-related javadoc

- src/main/java/org/broadinstitute/hellbender/tools/spark/ParallelCopyGCSDirectoryIntoHDFSSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/DiscoverVariantsFromContigAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/FilterLongReadAlignmentsSAMSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/prototype/SvDiscoverFromLocalAssemblyContigAlignmentsSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/CalcMetadataSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBadGenomicKmersSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/FindBreakpointEvidenceSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/ExtractOriginalAlignmentRecordsByNameSpark.java
Addresses requests for improvements to documentation by @sooheelee.
> Improvements to documentation

- src/test/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessControllerUnitTest.java
Fixes https://github.com/broadinstitute/gatk/issues/4014. This test uses python to test the controller, and was not properly synchronizing on all commands before asserting the results, leading to intermittent timing-dependent failures.
> Fix intermittent failure in StreamingProcessControllerUnitTest code.

- scripts/cnv_cromwell_tests/somatic/cnv_somatic_pair_wes_do-gc_workflow.json
- scripts/cnv_cromwell_tests/somatic/cnv_somatic_pair_wes_no-gc_workflow.json
- scripts/cnv_cromwell_tests/somatic/cnv_somatic_panel_wes_do-gc_workflow.json
- scripts/cnv_cromwell_tests/somatic/cnv_somatic_panel_wes_no-gc_workflow.json
- scripts/cnv_cromwell_tests/somatic/run_cnv_somatic_workflows.sh
- scripts/cnv_wdl/somatic/cnv_somatic_oncotate.wdl
- scripts/m2_cromwell_tests/run_m2_wdl.sh
Fixes and reverts some test-breaking changes made in #3985.
Closes #4012.
> Fixed broken WDL tests.

- LICENSE.TXT
> Update copyright date in license

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/VariantsToTable.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/VariantsToTableIntegrationTest.java
@sooheelee will you review or assign someone else to review?
> Variants to table doc

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormalsIntegrationTest.java
@sooheelee Closes #3510.  Thanks for finding these bugs.
> addressed a few issue with pon creation. Closes #3510.

- scripts/cnv_wdl/somatic/cnv_somatic_oncotate.wdl
- Error that was missed in testing.
> Adding boot disk for CNV WDL.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/CountVariants.java
Documentation for CountVariants
> Updating docs

- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/ModelSegments.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/models/MultidimensionalModeller.java
Placeholders for now.  We can tweak the actual values once @LeeTL1220 checks effect on validation.
Closes #4032.
> Changed default values for ModelSegments segmentation parameters.

- build.gradle
> Use GenomicsDB jar with OSX libuuid statically linked in

- src/main/java/org/broadinstitute/hellbender/tools/PrintReads.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
This takes @takutosato's first commit in https://github.com/broadinstitute/gatk/pull/4035 and adds my updates to the PrintReads document, and uses the latest master branch.
> shlee redo ts_print_reads_docs and make more doc updates

- scripts/spark_eval/exome_md-bqsr-hc_hdfs.sh
- scripts/spark_eval/exome_reads-pipeline_gcs.sh
- scripts/spark_eval/exome_reads-pipeline_hdfs.sh
- scripts/spark_eval/genome_md-bqsr-hc_hdfs.sh
- scripts/spark_eval/genome_reads-pipeline_hdfs.sh
- scripts/spark_eval/small_md-bqsr-hc_gcs.sh
- scripts/spark_eval/small_md-bqsr-hc_hdfs.sh
- scripts/spark_eval/small_reads-pipeline_gcs.sh
- scripts/spark_eval/small_reads-pipeline_hdfs.sh
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSpark.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/DataprocIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/bwa/BwaSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortReadFileSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
updating `SparkCommandLineProgram` and `GATKSparkTool` to use kebab case.
> kebab SparkCommandLineProgram and GATKSparkTool

- scripts/gatkcondaenv.yml
Just removed it -- unnecessary module.
> Python environment on OSX module dependency fix (libgcc-ng)

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSource.java
CC @droazen RE https://github.com/bigdatagenomics/adam/issues/1762
> Bump to ADAM 0.23.0 release.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
As of yet, this only works if you launch gatk from the jar or the gatk launch script.
> Added statement to the stderr output stating the HTSJDK and Picard versions

- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSBwaArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilterArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSScoreArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSScorer.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBuildKmers.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBuildReferenceTaxonomy.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqFilterSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBuildKmersSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBuildReferenceTaxonomyIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqFilterSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreIntegrationTest.java
- Moved tools to "Metagenomics" program group
- Updated tool docs
- Changed tool arguments to kebab-case
- Defined argument strings as static variables that are cross-referenced in integration tests
> PathSeq documentation update

- AUTHORS
adding Frank Nothaft to the AUTHORS list
> add Frank Nothaft to AUTHORS

- scripts/mutect2_wdl/mutect_resources.wdl
@LeeTL1220 Your call if this is worth merging pre-release.
@sooheelee @chandrans In case some users want to know how to generate the M2 resources for themselves.
> wdl script for generating M2's gnomad-based resources

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
Closes #4134.
@droazen Do you want someone on the engine team to review this?
> Moved HC-only arguments out of AssemblyBasedCallerArgumentCollection

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotation.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotation.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotationUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationUnitTest.java
Added map-style accessors to all concrete Funcotation classes (Funcotation.`getField`).
Fixes #3919
> Funcotator - Added map-style accessor for fields.

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectFragmentCounts.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/models/MultidimensionalModeller.java
- src/test/java/org/broadinstitute/hellbender/utils/mcmc/PosteriorSummaryUtilsUnitTest.java
Just some minor instances that slipped through during the rewrite.
> Removed references to ACNV.

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/HDF5SVDReadCountPanelOfNormals.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/CreateReadCountPanelOfNormalsIntegrationTest.java
Original behavior during development relied on Spark mllib's computeSVD to return something sensible even if a PoN was built with only one sample; typically this would yield a singular value of 0 and an eigenvector of NaNs (although it can also result in miscellaneous exceptions, depending on how many zeros are contained in the single-row matrix on which we perform SVD).  At one point, I added a check that at least one non-negligible singular value was returned (even when building a PoN with multiple samples).  This spoiled the ability to build single-sample PoNs (which is useful if you only have a matched pair).
I've added more explicit logic about how single-sample PoNs are built.  Now we explicitly set both the singular value and eigenvector to zero.
> Restored ability to make single-sample ModelSegments PoN.

- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
Closes #4136.
@droazen Here you go.
> integration tests to check min-bq argument is hooked up to HC and M2

- AUTHORS
closes https://github.com/broadinstitute/gatk/issues/4177
> adding new contributor Axel Verdier to AUTHORS

- Dockerfile
- scripts/docker/gatkbase/build_docker_base.sh
- scripts/docker/gatkbase/install_R_packages.R
I also updated the gatkbase Docker image to 1.2.2.
See comments in #4209.
> Restored getopt R dependency.

- src/main/java/org/broadinstitute/hellbender/tools/examples/ExamplePostTraversalPythonExecutor.java
- src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleStreamingPythonExecutor.java
- src/main/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessController.java
- src/test/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessControllerUnitTest.java
These are changes we made in order to get the NeuralNetInference branch integration tests to pass, and some example program updates..
> Python script executor updates required for NeuralNetInference branch.

- scripts/pathseq/wdl/README.md
- scripts/pathseq/wdl/pathseq_pipeline.wdl
- scripts/pathseq/wdl/pathseq_pipeline_template.json
WDL for running PathSeq pipeline with a readme and example json input.
> Add PathSeq WDL

- scripts/cnv_wdl/cnv_common_tasks.wdl
- scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
- scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl
- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
- scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCalls.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVPostprocessingEngine.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCallsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVPostprocessingEngineUnitTest.java
Note that I renamed PostProcessGermlineCNVCalls -> PostprocessGermlineCNVCalls.  I also fixed up some minor WDL typos and added some outputs.
Closes #4281.
> Added WDL for PostprocessGermlineCNVCalls.

- scripts/mutect2_wdl/mutect2.wdl
Closes #4285.
@LeeTL1220 Here you go.  Note the additional changes besides those mentioned in #4285.  I'm going to head out before finding out whether tests pass.  If they fail I will try to address tonight.
> m2 wdl works with cram

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/test/java/org/broadinstitute/hellbender/MainTest.java
> Fix printing of stacktrace with unknown command

- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
@ruchim @LeeTL1220 Can you confirm that this works before we merge and cut a release?  @droazen 
Closes #4319.
> Added missing Oncotator optional arguments to CNV pair WDL.

- scripts/sv/manage_sv_pipeline.sh
- scripts/sv/sanity_checks.sh
more sanity checks and grouping the work by what they are trying to do
> a bit of cleanning work for the "sv/manage_sv_pipeline.sh"

- build.gradle
Use the latest GKL 0.8.3 release which includes optimizations for Level 2 compression
> update to GKL_0.8.3 with compression improvments

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect_resources.wdl
- scripts/mutect2_wdl/unsupported/mutect2_opt.wdl
@jsotobroad Would you mind reviewing this?  Earlier I brought aspects of your mutect2_opt wdl into the public m2 wdl.  Now I am bringing all the changes from the public wdl into the opt wdl while keeping your NIO-dependent code.
> Bring changes in main M2 wdl into unsupported m2_opt wdl

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_pon.wdl
- scripts/mutect2_wdl/unsupported/mutect2_opt.wdl
- src/main/java/org/broadinstitute/hellbender/tools/GetSampleName.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/AnnotatePairOrientationIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/GetSampleNameIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
- src/test/resources/large/mutect/dream_synthetic_bams/tumor_1.bam
- src/test/resources/large/mutect/dream_synthetic_bams/tumor_1.bam.bai
- src/test/resources/org/broadinstitute/hellbender/tools/test_no_pair_orientation_info.vcf
@LeeTL1220 This fixes the issue.  I tested it on SGE and the M2 integration tests now have a DREAM bam where I switched the sample to "tumor sample".
> M2 wdl handles sample names with space

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/unsupported/mutect2_opt.wdl
@LeeTL1220 This should fix it.
> oncotator docker uses default docker if not specified

- scripts/sv/copy_sv_results.sh
- scripts/sv/manage_sv_pipeline.sh
- scripts/sv/runWholePipeline.sh
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointEvidence.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/ReadMetadata.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/BreakpointDensityFilterTest.java
I've tried to organize these changes into three separate commits with one issue per commit.
1) Running the new ExtractSVEvidenceSpark tool via manage_sv_pipeline.sh
2) Dumping more useful info for machine learning
3) Reinstating option to not copy fastq files.
Hopefully this is sensible, it's my first time trying to organize a PR this way.
This should resolve issue #4332
> Tb sv help dump evidence

- .travis.yml
- scripts/cnv_cromwell_tests/germline/run_cnv_germline_workflows.sh
- scripts/cnv_cromwell_tests/somatic/run_cnv_somatic_workflows.sh
- scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
- scripts/m2_cromwell_tests/run_m2_wdl.sh
> Upgrading automated WDL tests in this repo to cromwell 30 and making sure that CNV, gCNV, and M2 WDLs all work and call the correct cromwell jar.

- build.gradle
The earlier GKL release did not have all updates merged. Hence submitting another request to include the latest GKL.
> update to latest GKL with compression related optimizations

- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
- src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
Can you review this one @droazen - this would be for me a temporary solution for #3998. Thanks!
> Move CLP arguments to StandardArgumentDefinitions

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/PerAlleleAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContamination.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotator/expected/testWithAllAnnotations.vcf
> Scattered little improvements to Mutect2

- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java
> changed -o to -O

- build.gradle
> prevent uploadArchives from including distZip and distTar

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
> Fixed the refContext annotation.

- build.gradle
Fixes https://github.com/broadinstitute/gatk/issues/4619. We might also want to take https://github.com/broadinstitute/gatk/pull/4560.
> Upgrade to Picard 2.18.1.

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CreateReadCountPanelOfNormals.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/HDF5SVDReadCountPanelOfNormals.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDDenoisingUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDReadCountPanelOfNormals.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/CreateReadCountPanelOfNormalsIntegrationTest.java
> Enabled zero eigensamples to be specified for CreateReadCountPanelOfNormals.

- build.gradle
Update error message based on https://github.com/broadinstitute/gatk/issues/4669.
> Update git-lfs prerequisite message.

- src/main/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessController.java
Simple one liner to replace an errant println.
> Replace StreamingProcessController println with a logger info message.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/GermlineProbabilityCalculator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
> A bit of tidying Mutect2 code

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/ApplyVQSR.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
User pointed out --ts_filter_level does not work. https://gatkforums.broadinstitute.org/gatk/discussion/12040/errata-documentation-and-help-text-apparently-incorrect-for-applyvqsr-ts-filter-level
> Sheila apply vqsr quick fix

- src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
@droazen Here are a couple of unit tests for some heavily-uses and previously untested methods.
> Unit tests for two variant context utils methods

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariants.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantTrain.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantWriteTensors.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/FilterVariantTranches.java
These were in evaluation, but should be in filtering.
> Changed location of CNN tools in tool docs

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
@LeeTL1220 This is for Junko's issue.
> tweaked Mutect read position filter to better handle non-biological insertions

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
A forum user pointed this one out.
> took germline resource out of CreateSomaticPanelOfNormals javadoc example

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_nio.wdl
- scripts/mutect2_wdl/mutect2_pon.wdl
@LeeTL1220 For you if tests pass
> increased boot disk size on GATK tasks in M2 wdl to accommodate 4.0.5.0 docker

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
I noticed this message could be slightly more helpful in #4820.
> Added a slightly better debugging/error message to MarkDuplciatesSpark for duplicate readname issues.

- AUTHORS
adding a new contributor Kohl Kinning (@kohlkopf / @kohlk) to the AUTHORS file
> adding Kohl Kinning to AUTHORS file

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
User reported here: https://gatkforums.broadinstitute.org/gatk/discussion/12250/bug-in-docs
> Changed Incorrect Link

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculator.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculatorUnitTest.java
@droazen Can you review this once tests pass?
> fixes new qual regression in 4.0.5.0

- .travis.yml
- scripts/docker/dockertest.gradle
This should increase our code coverage by 20%!!! (from the place I unwittingly dropped it 20% to in the first place...)
Fixes #5001
> Fixed the Codecov coverage drop

- src/main/java/org/broadinstitute/hellbender/utils/Utils.java
- src/main/java/org/broadinstitute/hellbender/utils/test/VariantContextTestUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormalsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithBamDepthIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/AnnotateVcfWithExpectedAlleleFractionIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/ConcordanceIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/RemoveNearbyIndelsIntegrationTest.java
Closes #5006.
@TedBrookings May I assign you another little PR to review?
> extracted method for streaming a vcf

- src/main/java/org/broadinstitute/hellbender/engine/filters/OverclippedReadFilter.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
- src/main/java/org/broadinstitute/hellbender/utils/bwa/BwaMemAlignmentUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
- src/main/java/org/broadinstitute/hellbender/utils/clipping/ReadClipper.java
- src/main/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanJavaAligner.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/OverclippedReadFilterUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVFastqUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/clipping/ReadClipperUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/CigarUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/ReadsKeyUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/smithwaterman/SmithWatermanAlignerAbstractUnitTest.java
Closes #4946.
@TedBrookings Could you review this?
> Camel-cased some methods in ClippingOp

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PairHMMLikelihoodCalculationEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/genotyper/ReadLikelihoods.java
- src/test/java/org/broadinstitute/hellbender/utils/genotyper/ReadLikelihoodsUnitTest.java
Closes #4920.
@vruano would you mind reviewing?
> eliminated unused bestToZero argument in normalizeLikelihoods

- AUTHORS
@anowlcalledjosh and @bbimber Thanks for your contributions to GATK - I've updated the AUTHORs list with your names - can you verify that it looks correct ? (@bbimber not sure I got your name right, and let me know if you have an email address to include). Thx.
> Update AUTHORS with new contributors.

- scripts/spark_eval/run_gcs_cluster.sh
Simple update to use the correct version of Spark in the scripts.
> Use Dataproc 1.2 which supports Spark 2.2.1

- src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/ExtractOriginalAlignmentRecordsByNameSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/sv/integration/ExtractOriginalAlignmentRecordsByNameSparkIntegrationTest.java
read name mangling should use `replaceAll` instead of `replace`
Discovered in the process of creating test data for more comprehensive SV integration tests.
> Fix ExtractOriginalAlignmentRecordsByNameSpark

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSpark.java
- src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/ReadsKey.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/EmptyFragment.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Fragment.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/ReadUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/PairedEndsUnitTest.java
> Added better error messages around missing ReadGroups in MarkDuplicatesSpark

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
> Remove space in M2 vcf header field.  Closes #5183.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHC.java
> M2 emits DP format field. Closes #5158.

- build.gradle
upgrade Picard dependency from 2.18.13 -> 2.18.15
> upgrade Picard to 2.18.15

- build.gradle
* updating Intel-GKL from 8.5 -> 8.6
* this is a very minor update that only changes a log message
* fixes https://github.com/broadinstitute/gatk/issues/5393
> updating Intel-GKL dependency to 8.6

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/AlleleFraction.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/OriginalAlignment.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandArtifact.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/GermlineProbabilityCalculator.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
- src/test/resources/org/broadinstitute/hellbender/tools/mutect/mito/unfiltered.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotator/expected/testWithAllAnnotations.vcf
@takutosato This doesn't affect results but it makes debugging a bit easier.
> Cleaner Mutect2 VCF fields

- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
Fixing bad boolean to good value (false).
> Changing Funcotator large test boolean back to false where it belongs.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/GermlineProbabilityCalculator.java
@takutosato This came up recently.
> fix an edge case bug when M2 sees a variant with population AF = 1

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/KBestHaplotypeFinder.java
@takutosato The new `KBestHaplotypeFinder` algorithm implements the k shortest paths generalization of Dijkstra's algorithm as described in https://en.wikipedia.org/wiki/K_shortest_path_routing.  It was, however, missing the condition in the 6th-to-last line ` if count_u ≤ K`, which ignores a vertex if the k best paths through it have already been found.  This PR puts in that condition, reducing memory usage.
No need to review before January 2!
> optimize KBestHaplotypeFinder a bit more

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactoryUnitTest.java
> Funcotator: ignore transcript version number when matching on transcript ID

- Dockerfile
Fixes https://github.com/broadinstitute/gatk/issues/5550. Tested manually.
> Source tab completion script in Docker image.

- scripts/mutect2_wdl/mutect2_nio.wdl
@takutosato Unfortunately we still have to maintain two wdls.  Just a few weeks more.  I tested this on FC.
> Put new orientation bias model in M2 NIO wdl

- src/main/java/org/broadinstitute/hellbender/engine/spark/FindAssemblyRegionsSpark.java
- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkSharder.java
- src/test/java/org/broadinstitute/hellbender/engine/spark/SparkSharderUnitTest.java
> Get HaplotypeCallerSpark strict mode running on an exome

- scripts/funcotator/data_sources/createLiftoverForHg38ToB37.sh
This script is nearly identical to the `createLiftoverForB37ToHg38.sh`, with small changes to reverse the direction of the liftover.
> Add script to create Hg38 to B37 liftover chain

- build.gradle
Has updated optical duplicate finding code for MarkDuplicatesSpark.
> Updated Picard to version 2.18.25

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/QualityUtils.java
@LeeTL1220 Can you review?  This fixes your bug.  I'm not putting in a regression test yet because i the upcoming filtering refactoring it will become much easier to unit test for bugs like this.
@madduran Yours too.
> tweaking M2 germline filter

- scripts/mutect2_wdl/unsupported/funcotator.wdl
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorDataSourceDownloader.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java
- Added in new funcotator wdl.
- Added more documentation to Funcotator and FuncotatorDataSourceDownloader
- Added Gencode spec to the top-level funcotator tool doc.
Fixes #5611
> Updating Funcotator tool documentation for 4.1 release.

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorDataSourceDownloader.java
> Removed beta label from Funcotator and FuncotatorDataSourceDownloader.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/FilterVariantTranches.java
We forgot to remove the experimental tag.
> Filter variant tranches is not experimental

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/StandardCallerArgumentCollection.java
> Update two instances of '--genotyping_mode' with '--genotyping-mode'

- src/main/java/org/broadinstitute/hellbender/cmdline/ReadFilterArgumentDefinitions.java
- src/main/java/org/broadinstitute/hellbender/engine/filters/IntervalOverlapReadFilter.java
- src/test/java/org/broadinstitute/hellbender/engine/filters/IntervalOverlapReadFilterTest.java
- src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
I took over #5367 but since I don't have access to your fork @magicDGS I have created a second branch with my changes.
Closes #4860
> Created IntervalOverlapReadFilter

- src/main/java/org/broadinstitute/hellbender/Main.java
> Print the Picard/HTSJDK versions in addition to the GATK version when running with --version

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
Second approach to fixing master which was broken when we merged https://github.com/broadinstitute/gatk/pull/5808.
> Fix failing master build

- src/main/java/org/broadinstitute/hellbender/Main.java
- src/main/java/org/broadinstitute/hellbender/tools/AnnotatePairOrientation.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/MergeAnnotatedRegions.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/MergeAnnotatedRegionsByAnnotation.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/TagGermlineEvents.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
- src/test/java/org/broadinstitute/hellbender/MainTest.java
Fixes #5421. Picard updates are in https://github.com/broadinstitute/picard/pull/1259.
> Trim descriptions to shorten --list display width.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
> specified max-mnp-distance 0 in CreateSomaticPanelOfNormals javadoc

- src/main/java/org/broadinstitute/hellbender/engine/spark/AssemblyRegionArgumentCollection.java
> kebabified args in HaplotypeCallerSpark

- src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
* SparkContextFactory no longer always emits a warning about the GCS connector environment variables.
This should now only occur when running tests and missing the necessary environment variables.
I should have fixed this one a long time ago...
> Fix erroneous warning about GCS test configuration

- build.gradle
* Updating disq 0.3.1 -> 0.3.2
* This includes several important bug fixes
> Update disq to 0.3.2

- testsettings.gradle
maybe this will lower failure rates
> re-lower the xms value for the test jvm

- src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
Oversight leaving some hardcoded debug in with the tests...
> cleanup GenomicsDB test output

- .travis.yml
This shouldn't hurt anything and might help a bit with OOM type problems.
> free a bit of memory by disabling mysql and postgress on travis

- build.gradle
* Update htsjdk 2.20.1 -> 2.20.2
* This release fixes https://github.com/broadinstitute/gatk/issues/6091
> Update htsjdk to 2.20.2

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
> Updating to gradle 5.6

- build.gradle
* Update picard from 2.20.7 -> 2.21.1
> Updating picard to 2.21.1

- src/main/java/org/broadinstitute/hellbender/tools/GetSampleName.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GatherPileupSummaries.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/CollectF1R2Counts.java
@takutosato We don't want these tools to emit scary warnings any more.
> some things in M2 pipeline don't need to be beta any longer

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/FilterMutectCalls.java
@takutosato This seems worthwhile.
> Fixed random seed at beginning of FilterMutectCalls

- .travis.yml
Adding a cloud test for java 11.
> Adding cloud tests on java 11

- build.gradle
* Update picard 2.21.1 -> 2.21.2
> Update picard to 2.21.2

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/Mutect2FilteringEngine.java
@takutosato Not a huge difference, but makes output a bit more meaningful in some cases and reduces false positives by a bit.
> change filter output slightly in Mutect2

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCalls.java
Just fixing a typo.  @asmirnov239 can you review?
> Fixed shard index in PostprocessGermlineCNVCalls log message.

- build.gradle
* htsjdk 2.21.0 -> 2.21.1
* picard 2.21.2 -> 2.21.4
> update picard and htsjdk

- src/main/java/org/broadinstitute/hellbender/tools/LeftAlignIndels.java
This caught me off-guard until I read the source code.
> Update LeftAlignIndels documentation

- scripts/mitochondria_m2_wdl/AlignAndCall.wdl
> fixed force-calling mode in M2 mito WDL

- scripts/mutect2_wdl/mutect2.wdl
> pass ref to realignment filter in M2 WDL

- src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/Concordance.java
> Concordance is out of beta

- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltrationIntegrationTest.java
Invalidating filters didn't work and (guess what!) there were no tests
> Actually unfilter variants with VariantFiltration

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotator.java
> Bring VariantAnnotator out of beta

- src/main/java/org/broadinstitute/hellbender/tools/evoquer/Evoquer.java
- src/main/java/org/broadinstitute/hellbender/tools/evoquer/EvoquerEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHet.java
- src/main/java/org/broadinstitute/hellbender/utils/Histogram.java
- src/main/java/org/broadinstitute/hellbender/utils/bigquery/BigQueryUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantPipelineTest.java
- src/test/java/org/broadinstitute/hellbender/utils/HistogramUnitTest.java
- src/test/resources/large/integration_test_3_sample.vcf
See individual commit messages
- fix median bug
- parameterized sample_list and enable subsetting
- support pre-query bytes processed estimate
> Evoquer sample subset and estimates, Median bugfix

- src/main/java/org/broadinstitute/hellbender/tools/ApplyBQSRArgumentCollection.java
* Implemented a suggestion from an ancient TODO in ApplyBQSRArgumentCollection which was waiting for a now available barclay feature
> Add minValue/minRecommended value to ApplyBQSRArgumentCollection

- src/main/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibrator.java
Closes #6056.
@droazen This should take about a minute.
> Clarify mystery number in BaseRecalibrator stdout

- .travis.yml
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotDenoisedCopyRatiosIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotModeledSegmentsIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/CollectInsertSizeMetricsSparkIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/varianteval/AlleleFrequencyQCIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/utils/hmm/HMMUnitTest.java
- testsettings.gradle
Adds an R entry to the travis matrix. Note that some R tests were already in the "R" test group.
> Remove travis R install and only run R tests on the Docker.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java
> Don't call the non-ref allele in genotypes or ADs

- src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java
> Fix ignored test in GATKReadAdaptersUnitTest

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerReadThreadingAssemblerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/MutectReadThreadingAssemblerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/JTBestHaplotype.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/JunctionTreeKBestHaplotypeFinder.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/AbstractReadThreadingGraph.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/JunctionTreeLinkedDeBruijnGraph.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/JunctionTreeKBestHaplotypeFinderUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/JunctionTreeLinkedDeBruijnGraphUnitTest.java
* i before j except as in jin or when sounded as ji as in jingle or jink
> De bruin the De Bruijn graph

- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java
* I introduced a compile error because my branch wasn't rebased on the changes to ArgumentsBuilder
> Fix compile error in test.

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/DetermineGermlineContigPloidy.java
I think there's a typo in the docs.
> ploidy prior example is wrong?

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/NuMTFilterTool.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/NuMTFilterToolTest.java
> Test NuMT filtering thresholds

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDDenoisingUtils.java
@samuelklee Could you please review?
> Fixed an error message in SVD utils

- src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/DepthOfCoverage.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/coverage/DepthOfCoverageIntegrationTest.java
Remember kids, always check for empty files or you end up missing something important in the rebase.
> Fixed interval summary files being empty in DepthOfCoverage

- src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/DepthOfCoverage.java
> Adding a note as to how to filter on MappingQuality in DepthOfCoverage

- src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/DepthOfCoverage.java
> Removed incorrect logger from DepthOfCoverage.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
More carnage form the forum migration.
> Fixing a dead link in SelectVariants

- .travis.yml
> Upgrade cromwell to v51.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/FilterAlignmentArtifacts.java
@fleharty This fixes an old oversight.
> better javadoc for FilterAlignmentArtifacts

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
- src/test/java/org/broadinstitute/hellbender/engine/FeatureManagerUnitTest.java
Will fail until the Barclay upgrade.
> Upgrade to Barclay 3.0.0, with changes for FeatureInput discovery based on Barclay refactoring.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotator.java
* Cache the result of getBestAvailableSequenceDictionary instead of calling it on every variant.
> Fix VariantAnnotator performance bug

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/PossibleDeNovo.java
> Removing doc reference to gatk3 annotation that not longer exists

- README.md
> Add instructions for running Spark tools in LOCAL mode to the README

- scripts/mutect2_wdl/mutect2.wdl
Adds space for an extra argument in the M2 WDL for GetPileupSummaries.
> Mf m2wdl maxaf

- src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModel.java
Fixes https://github.com/broadinstitute/gatk/issues/6720.
> Enable DocumentedFeature for LearnReadOrientationModel.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
Its time to finally unhide our shame...
> Exposed Linked-Debrujin-Graph arguments to the help options

- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayMetadataTsvCreator.java
- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/CreateArrayIngestFiles.java
- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/RawArrayTsvCreator.java
- src/test/resources/org/broadinstitute/hellbender/tools/variantdb/arrays/array.vcf
- src/test/resources/org/broadinstitute/hellbender/tools/variantdb/arrays/metadata_001_testSample.tsv
- src/test/resources/org/broadinstitute/hellbender/tools/variantdb/arrays/probe_info.csv
- src/test/resources/org/broadinstitute/hellbender/tools/variantdb/arrays/raw_001_testSample.tsv
- src/test/resources/org/broadinstitute/hellbender/tools/variantdb/arrays/sampleMap.csv
@ahaessly Can you take a look please?
> Adding a test and small features to var store branch

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantDataManager.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorIntegrationTest.java
- src/test/resources/large/VQSR/bothRecal.vcf
- src/test/resources/large/VQSR/bothRecalWithAggregate.vcf
- src/test/resources/large/VQSR/expected/bothTranches.txt
- src/test/resources/large/VQSR/expected/bothTranchesWithAggregate.txt
- src/test/resources/large/VQSR/g94982_20_1m_10m_python_2dcnn.vcf.gz.tbi
New test for multi-input BOTH mode
Uniquify annotations to fix #2221
> CNN filtering should run for all-SNP VCF (#6411)

- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohort.java
- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohortEngine.java
- src/main/java/org/broadinstitute/hellbender/utils/bigquery/StorageAPIAvroReader.java
See https://github.com/broadinstitute/dsp-spec-ops/issues/185
> added support for probe_id ranges

- src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtils.java
> fix a bug in FragmentUtils where insertion quals were used instead of deletion quals

- src/main/java/org/broadinstitute/hellbender/tools/variantdb/CommonCode.java
- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohort.java
- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohortEngine.java
- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/ProbeQcMetrics.java
- src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/ProbeQcMetricsSchema.java
See https://github.com/broadinstitute/dsp-spec-ops/issues/189
> Ability to filter variants based on QC in ArrayExtractCohort 

- .dockerignore
- .travis.yml
- Dockerfile
> Added git-lfs to the build script to better support no-arg builds of gatk

- scripts/mitochondria_m2_wdl/Haplochecker/Dockerfile
update Dockerfile to reflect correct haplocheckCLI
> ah-mito-update

- build.gradle
Fixes https://github.com/broadinstitute/gatk/issues/6775.
> Upgrade to Barclay 4.0.1.

- src/test/java/org/broadinstitute/hellbender/utils/bigquery/BigQueryUtilsUnitTest.java
@droazen Here's the other test.
> Another test for BigQueryUtils

- src/main/resources/org/broadinstitute/hellbender/utils/wdlTemplates/wdlToolTemplate.wdl.ftl
- src/main/resources/org/broadinstitute/hellbender/utils/wdlTemplates/wdlToolTemplateAllArgs.wdl.ftl
- src/main/resources/org/broadinstitute/hellbender/utils/wdlTemplates/wdlToolTemplateAllArgsTest.wdl.ftl
Forward port of user-proposed changes in Barclay for WDL templates. See https://github.com/broadinstitute/barclay/issues/168 and https://github.com/broadinstitute/barclay/pull/170.
> Forward port Barclay WDL template fix for Debian dist.

- scripts/funcotator_wdl/funcotator.wdl
> Added in requester pays arg to funcotator wdl.

- scripts/mutect2_wdl/mutect2.wdl
- scripts/mutect2_wdl/mutect2_multi_sample.wdl
- scripts/mutect2_wdl/mutect2_pon.wdl
gnomAD VCFs are not currently requester pays nor are they expected to be
> Added requester pays option to Mutect2 tasks that access bams

- scripts/mitochondria_m2_wdl/AlignAndCall.wdl
remove the unused parameter from the Filter task
> ah_remove_param_mitofilter

- scripts/mitochondria_m2_wdl/AlignAndCall.wdl
@ahaessly I meant to do this a long time ago, but it slipped off my radar. This should work in Terra (the argument shows up as optional).
> Simplifying argument in mitochondria pipeline

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
- Creating PR for update to Funcotator documentation and to show off CARROT integration.
> Updated the link to the Funcotator info/tutorial page.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/AnnotationUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHC.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeff.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandBiasBySample.java
- src/test/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCallerIntegrationTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/AnnotationUtilsUnitTest.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
> Add loci to annotation warnings

- src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
The links to the jexl docs were broken.
> updating jexl doc website link

- build.gradle
- src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
> Print the current Spark version on GATK startup

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java
- src/main/java/org/broadinstitute/hellbender/utils/python/PythonScriptExecutor.java
- src/main/java/org/broadinstitute/hellbender/utils/runtime/ProcessOutput.java
- src/main/java/org/broadinstitute/hellbender/utils/runtime/ScriptExecutor.java
- src/main/python/org/broadinstitute/hellbender/gcnvkernel/__init__.py
- src/main/python/org/broadinstitute/hellbender/gcnvkernel/io/io_consts.py
- src/main/python/org/broadinstitute/hellbender/gcnvkernel/tasks/inference_task_base.py
- src/main/resources/org/broadinstitute/hellbender/tools/copynumber/case_denoising_calling.py
- src/main/resources/org/broadinstitute/hellbender/tools/copynumber/cohort_denoising_calling.py
- src/test/java/org/broadinstitute/hellbender/utils/python/PythonScriptExecutorUnitTest.java
This is intended to alleviate transient issues with GermlineCNVCaller inference in which the ELBO converges to a NaN value, by calling the python gCNV code with an updated random seed input.
> gCNV restarts inference with a new random seed in case ELBO converges to a NaN

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantDataManager.java
> Add locus info to ref allele mismatch exception

- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
- src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java
> Fixed a NPE when null ReadNameRegex provided to MDSpark

- src/test/java/org/broadinstitute/hellbender/utils/pairhmm/VectorPairHMMUnitTest.java
> Disable PairHMMUnitTest on Java 11.

- scripts/mutect2_wdl/mutect2.wdl
Closes #5896.  @fleharty more technical debt for your review
> eliminate obsolete cram to bam conversion in M2 WDL

- src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
- src/test/java/org/broadinstitute/hellbender/testutils/FuncotatorReferenceTestUtils.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/DataProviderForTroubleVariants.java
- src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
- src/test/resources/large/funcotator/GRCh37.p13.chr17.tar.gz
- src/test/resources/large/funcotator/small_ds_order_bugfix_7051_tests/gencode_tp53/hg19/gencode.config
- src/test/resources/large/funcotator/small_ds_order_bugfix_7051_tests/gencode_tp53/hg19/gencode.v34lift37.annotation.REORDERED.TP53.gtf
- src/test/resources/large/funcotator/small_ds_order_bugfix_7051_tests/gencode_tp53/hg19/gencode.v34lift37.annotation.REORDERED.TP53.gtf.idx
- src/test/resources/large/funcotator/small_ds_order_bugfix_7051_tests/gencode_tp53/hg19/gencode.v34lift37.pc_transcripts.TP53.dict
- src/test/resources/large/funcotator/small_ds_order_bugfix_7051_tests/gencode_tp53/hg19/gencode.v34lift37.pc_transcripts.TP53.fa
- src/test/resources/large/funcotator/small_ds_order_bugfix_7051_tests/gencode_tp53/hg19/gencode.v34lift37.pc_transcripts.TP53.fa.fai
> Added sorting by strand order for transcript subcomponents.

- src/test/java/org/broadinstitute/hellbender/engine/CRAMSupportIntegrationTest.java
Test will fail until htsjdk is updated. Fixes https://github.com/broadinstitute/gatk/issues/6475.
> CRAM test to verify proper stream management with multiple queries on remote files.

- build.gradle
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Fragment.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/Pair.java
- src/main/java/org/broadinstitute/hellbender/utils/read/markduplicates/sparkrecords/TransientFieldPhysicalLocation.java
* Update Picard 2.23.0 -> 2.25.0
* Add serialVersionUID to classes now marked as Serializable in picard.
> Update Picard to 2.25.0

- build_docker.sh
"gcloud docker" is no longer supported for the latest docker client versions
> Update gcloud docker commands in build_docker.sh

- .dockstore.yml
- scripts/variantstore/wdl/ngs_filter_extract.wdl
> Add model inputs to ngs_filter_extract

- .travis.yml
This authenticates us to dockerhub on travis builds that require docker.
> Authenticating to dockerhub in travis build

- .travis.yml
* Moving the artifactory key and username out of the .travis.yml and into the travis settings directly.
* This will make it easier to rotate passwords in the future without requiring a new commit and rebases.
> Updating to the new artifactory key.

- src/main/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyper.java
Docs should say how to generate necessary annotations -- namely with ReblockGVCF for Gnarly inputs
> Clarify Gnarly pipeline inputs

- build.gradle
We have received a request to incorporate some of the picard tool improvements in newer versions of picard. This is a bump in preparation of an eventual GATK release.
> Bump Picard Version

- scripts/variantstore/tieout/GIAB_TIEOUT.md
I added GATK to prereqs 
-- but should this be done through conda? 
--isn't gatk technically part of this repository anyway? wouldn't that be the easier way?
> add conda commands to GIAB readme

- scripts/variantstore/wdl/GvsImportGenomes.wdl
Closes https://github.com/broadinstitute/dsp-spec-ops/issues/310
> added default value to drop_state

- scripts/variantstore/wdl/GvsExtractCallset.wdl
Closes https://github.com/broadinstitute/dsp-spec-ops/issues/320
> Add timestamp check to ExtractTask call

- src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeatures.java
- src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeaturesBQ.java
- src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeaturesEngine.java
- src/main/resources/org/broadinstitute/hellbender/tools/gvs/filtering/feature_extract.sql
Closes https://github.com/broadinstitute/dsp-spec-ops/issues/261
> Remove training sites only param from ExtractFeatures

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
(I'll remove the branch from the dockstore yaml)
> add param for mem for indels

- src/main/java/org/broadinstitute/hellbender/tools/copynumber/CallCopyRatioSegments.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/DetermineGermlineContigPloidy.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java
- src/main/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCalls.java
- src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
Found updates for broken links in the tool docs and replaced them or removed them.
> Replace broken links in tool docs

- src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/ASEReadCounter.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/ASEReadCounterIntegrationTest.java
Adding a guard to hopefully answer forum questions.
> Added a warning for lacking GT fields in ASEReadCounter

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants.java
> fixed typo in tool documentation

- scripts/funcotator/data_sources/cosmic/GenericTsvReader.py
- scripts/funcotator/data_sources/cosmic/createCosmicGeneTsv.py
> removed embedded licenses from scripts 

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHC.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandBiasBySample.java
> fixed two noisy annotation loggers

- scripts/variantstore/bq/BQ_QUERY_STATS.md
Resolves https://github.com/broadinstitute/dsp-spec-ops/issues/383
See also notebook for visualization in [Spec Ops GVS Analysis](https://app.terra.bio/#workspaces/broad-dsp-spec-ops-fc/Spec%20Ops%20GVS%20Analysis)
> Instructions on how to download BQ Metadata and visualize results

- scripts/variantstore/wdl/GvsValidateVAT.example.inputs.json
- scripts/variantstore/wdl/GvsValidateVAT.wdl
Closes broadinstitute/dsp-spec-ops#371 by putting into SQL what is in English in those two bullets:
8. Every transcript_source is Ensembl or null
9. No row has AC of zero or AN of zero.
> Add task for VAT validation #8 & 9

- scripts/variantstore/wdl/GvsPrepareCallset.wdl
- scripts/variantstore/wdl/extract/Dockerfile
closes https://broadworkbench.atlassian.net/browse/VS-143
> added bcftools, upgraded gcloud version

- .dockstore.yml
- scripts/variantstore/wdl/GvsValidateVAT.wdl
Closes https://broadworkbench.atlassian.net/browse/VS-15 by adding SQL for
No non-nullable / required fields contain null values in the VAT.
AND
Closes https://broadworkbench.atlassian.net/browse/VS-14 by adding SQL for
Each key combination (vid+transcript) is unique--confirms that primary key is enforced.
> Add VAT validation rule #7 [VS-14] and validation rule #6 [VS-15]

- .dockstore.yml
- scripts/variantstore/wdl/GvsPrepareCallset.wdl
closes https://broadworkbench.atlassian.net/browse/VS-148
> fixing SA change from file to string [VS-148]

- scripts/variantstore/wdl/GvsImportGenomes.wdl
no longer loading sample info table in this wdl
> AH - fix bad merge

- src/main/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs.java
Already got RefConfVCMerger, but this one snuck past me
> Update annotation args to GATK4 names

- scripts/variantstore/wdl/GvsImportGenomes.wdl
fix partition end, add 1
VS-160
> fix partition

- src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF.java
> ReblockGVCF out of beta

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCallset.wdl
To finish up file size changes from https://github.com/broadinstitute/gatk/pull/7423
> Also changed file size from Int to Float in SumBytes task python

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateAltAllele.wdl
- scripts/variantstore/wdl/extract/populate_alt_allele_table.py
Closes https://broadworkbench.atlassian.net/browse/VS-194
> added job ID to alt_allele population call output [VS-194]

- scripts/variantstore/wdl/extract/create_cohort_extract_data_table.py
changes to put pet data directly into data table
> efficient queries for pet data into DATA table

- src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
Closes #7318.  @takutosato I need to find a new go-to reviewer with Mark F joining GP, and I do _not_ intend to dump it all on you.  This PR, however, will take about 30 seconds to review.
> genotype-germline-sites not called experimental

- scripts/variantstore/wdl/GvsPrepareCallset.wdl
ah_var_store was using an old, incompatible docker image
> fixed docker

- .dockstore.yml
- scripts/variantstore/wdl/GvsAoUReblockGvcf.wdl
tested here https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_ah_reblock0825/workflows
> bad param assignment in aou reblocking

- .dockstore.yml
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- `localization_optional` for indexes localization in `CreateImportTsvs`
- check to make sure there are more than 0 samples to load before going forward in `GetSampleIds`
> Small fixes to ImportGenomes (non-write api version)

- .dockstore.yml
- scripts/variantstore/TERRA_QUICKSTART.md
- scripts/variantstore/wdl/GvsAssignIds.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
- src/main/java/org/broadinstitute/hellbender/utils/bigquery/CommittedBQWriter.java
- src/test/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFilesIntegrationTest.java
Major changes:
- remove workspace datamodel updating from GvsAssignIds
- refactored GvsImportGenomes to remove all bq load code
- added new load status table append the load status of a sample
- changed SetIsLoaded and CheckForDuplicateData to read from the partitions AND the load status table
> Move to Sample Set based write-api

- AUTHORS
I'm not really a contributor to this project, I only once bumped a version number: https://github.com/broadinstitute/gatk/commit/bd5d37d0d35dcd8b8a950c2d7918543c252dc692.
> Remove janlugt from AUTHORS

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
Opportunistic cleanup. @cwhelan I think you last touched this so you get this difficult review :)
> Remove outdated javadoc line in AssemblyBasedCallerUtils

- build.gradle
> Upgrade log4j to 2.17.0 to mitigate another newly discovered issue

- src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_RMSMappingQuality.java
Fix for developer comments in finalize method
> Update AS_RMSMappingQuality.java comments

- build.gradle
> Update log4j to 2.17.1

- src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
> Mention acceptable compressed VCF file extension in GenomicsDBImport error message

- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
use updated jars---even in split intervals!
One less place to track the jars
> Clean up gatk jars -- looks like we are not passing them properly in the extract

- .github/workflows/gatk-tests.yml
- build.gradle
- scripts/cnv_wdl/germline/joint_call_exome_cnvs.wdl
- scripts/variantstore/tieout/legacy_wdl/JointGenotypingTasks.wdl
Renamed existing test for validating generated WDLs.
> Added a test to validate WDLs in the scripts directory. (#7826)

- src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotate.java
Added @DocumentedFeature to SVAnnotate tool class so that GATK tool docs will generated.
> add @DocumentedFeature to SVAnnotate

- src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/JointGermlineCNVSegmentation.java
> Add DocumentedFeature to JointGermlineCNVSegmentation

- .dockstore.yml
- scripts/variantstore/wdl/GvsAssignIds.wdl
- scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
- scripts/variantstore/wdl/GvsCreateAltAllele.wdl
- scripts/variantstore/wdl/GvsCreateVAT.wdl
- scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
- scripts/variantstore/wdl/GvsCreateVATFromAnnotations.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py
https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/824a088b-db39-4dae-be7f-3953ed975e3d
> Fix bug and update images

- build.gradle
- src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/StrandCorrectedAllele.java
- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
- src/main/java/org/broadinstitute/hellbender/utils/haplotype/Haplotype.java
This reverts commit ace782100afb24802c39c1be0e30c0f65de973a9. This is a necessary step in order for #7876 to be merged. We will re-instate this branch after that is merged.
> Revert "Upgrade htsjdk to v3.0.0. (#7867)"

- scripts/variantstore/AOU_DELIVERABLES.md
Minor update to AoU Documentation
Update to include link to Firecloud support script which can be used to upload sample sets without using the UI.
> VS-598 - Minor update to AoU Documentation.

- scripts/variantstore/beta_docs/gvs-quickstart.md
- scripts/variantstore/beta_docs/run-your-own-samples.md
Finishing updating the docs to reflect the added return values.
> Updating documentation to reflect the changed outputs [VS-565]

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
Gonna merge WDLs one at a time as they get changed then tested
> Updating references to old GATK for VS-620

- .dockstore.yml
- scripts/variantstore/wdl/GvsWithdrawSamples.wdl
Fix for bug in handling of control samples
> Fix bug in GvsWithdrawSamples.wdl

- build.gradle
* upgrade protobuf-java 3.19.4 -> 3.21.6
> Update protobuf to 3.21.6

- src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/CollectSVEvidence.java
Adds `@DocumentedFeature` annotation so the tool appears in documentation.
> Enable CollectSVEvidence docs

- build.gradle
this is now available on cran again
> Updating gsalib version to 2.2.1

- src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java
- src/test/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMergerUnitTest.java
Pulling in fixes to AD calculation from @RoriCremer's previous fixes in master branch
> Vs 665 re create vcf for cd 68 po 52339 with ad padding fixed

- .dockstore.yml
- scripts/variantstore/wdl/GvsAssignIds.wdl
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
successful runs here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Tiny%20Quickstart%20hatcher/job_history
successful extract, in particular, located here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Tiny%20Quickstart%20hatcher/job_history/18e07ed5-fef7-47ff-ae36-cb225aefdd24
> VS-665 and VS-620 updating code to use latest docker images containing Rori's AD calculation changes in extract

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/extract/create_genes_bqloadjson_from_annotations.py
- scripts/variantstore/wdl/extract/create_vt_bqloadjson_from_annotations.py
This PR uses Nirvana's JASIX parser to break the annotated output of Nirvana into a genes and positions json which are then parsed by the corresponding python methods. This improves performance significantly.
Successful workflow here:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/14d2d1cf-3a2a-42e0-8542-c70edd2133e5
> VS-757 - Use JASIX to make sub-jsons of annotated output of Nirvana

- scripts/variantstore/docs/aou/cleanup/cleanup.md
Hey, we deleted one of those VDSes, let's not pretend we didn't!
> Add note that we deleted a VDS!

- src/main/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyperEngine.java
If this ever happens it would be good to have some information.
> better Gnarly error message

- src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
> Re-adding --dont-use-softclipped-bases to the help output

- .dockstore.yml
- scripts/variantstore/variant_annotations_table/GvsCreateVATFilesFromBigQuery.wdl
- scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
- scripts/variantstore/wdl/GvsAssignIds.wdl
- scripts/variantstore/wdl/GvsBenchmarkExtractTask.wdl
- scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
- scripts/variantstore/wdl/GvsCallsetCost.wdl
- scripts/variantstore/wdl/GvsCallsetStatistics.wdl
- scripts/variantstore/wdl/GvsCreateTables.wdl
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsIngestTieout.wdl
- scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
- scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/Dockerfile
- scripts/variantstore/wdl/extract/build_base.Dockerfile
- scripts/variantstore/wdl/extract/build_build_base_docker.sh
- scripts/variantstore/wdl/extract/build_docker.sh
TBH I'm not sure what went wrong with the previous image, I just re-baked a new one with the current version of gcloud-sdk and that seems to be working (or at least gsutil does not immediately explode).
Test run here https://job-manager.dsde-prod.broadinstitute.org/jobs/016779a9-62d0-4195-9598-5f0eee559d99
> Fix broken gsutil in Variants Docker image [VS-888]

- .dockstore.yml
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
- scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
- scripts/variantstore/wdl/GvsCallsetCost.wdl
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
- scripts/variantstore/wdl/GvsPrepareBulkImport.wdl
- scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/hail_gvs_import.py
- scripts/variantstore/wdl/extract/import_gvs.py
Successful integration run
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/job_history/4caeb3e1-6c8f-4547-a334-b3264f2aed95
We initially changed the name of the method (since import_gvs is a bit misleading inside our repo) but because it looks like there are still external changes being made, we decided to keep the name consistent with Tim/Hail's chosen one.
> Update to the latest import_gvs() code

- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
quick pr to update the beta workflow to use the latest ploidy changes
> updating beta to use the latest code changes

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
- scripts/variantstore/wdl/GvsUnified.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
Mostly changing `use_classic_VQSR` to `use_VQSR_lite` with a couple of minor bugfixes thrown in. Successful integration run [here](https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/3e60bf43-5cc3-4e5b-97ad-1732b4c543be).
> VQSR Lite by default except for beta users [VS-700]

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/GvsWarpTasks.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
Passing workflow here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Exome%20Data%2049k/job_history/38d22351-33cd-4c2c-abf9-feccda71d40a
Mostly passing integration test here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/4a7e6628-6c19-442d-90b8-202da267d8bb
(the failure was a bq time out.)
> VS-987 out of date docker

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/GvsVQSRClassic.wdl
Updating dockers to include updates to Google cloud storage libraries
> VS-1001 update dockers for google storage library update

- build.gradle
* tiny fix to remove one of gradle's warnings.
> Fix one of the warnings in Gradle

- .dockstore.yml
- scripts/variantstore/wdl/GvsImportGenomes.wdl
Increasing max auto batch size to 25K to allow for larger beta sets.
> VS-1004. Increasing max auto batch size to 25K to allow for larger beta sets.

- .dockstore.yml
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
Running a joint calling [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/b38a46ad-00d1-46d7-bac7-9989cb4687bd)
> Update override jar in bulk ingest staging

- .dockstore.yml
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/66145614-7fe9-4c09-9864-2049e2c192bb
> pin hail version in the integration test

- .dockstore.yml
- scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
Found some issues trying to run P&S:
- TerminateWorkflow was using a cloud sdk Docker where a basic Docker should suffice
- Docker image wasn't being specified for TerminateWorkflow calls
- GOTC imputation Docker was still being hardcoded
- Lots of detritus left in .dockstore.yml
> Centralized Docker fixups

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsRescatterCallsetInterval.wdl
Integration run in progress https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/474c06f0-1c6a-41d0-bc1f-7a22054153fe
> Fix copy/paste errors with Docker image variable names

- src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantTrain.java
- src/main/python/org/broadinstitute/hellbender/vqsr_cnn/vqsr_cnn/arguments.py
- src/main/python/org/broadinstitute/hellbender/vqsr_cnn/vqsr_cnn/models.py
Added the following Adam optimization / learning parameters to the command-line:
- learning rate
- beta1
- beta2
- epsilon
- clipnorm
> Expose more CNN training parameters to the command line

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
successful run here:
https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20Echo%20RD/job_history/b6b3513e-0077-427c-a865-58c9e3a2f4c3
> Add more disk space to extract

- scripts/variantstore/beta_docs/gvs-workspace-description.md
In releasing bulk ingest I noticed a few places we could add some clarification to the workspace description. This has already been updated in the workspace and can go out in github in the next release.
> Update gvs workspace description [VS-1042]

- .dockstore.yml
- scripts/variantstore/beta_docs/gvs-overview.md
- scripts/variantstore/beta_docs/gvs-quickstart.md
- scripts/variantstore/beta_docs/gvs-workspace-description.md
- scripts/variantstore/beta_docs/run-your-own-samples.md
- scripts/variantstore/docs/CHANGELOG.md
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
Successful run [here](https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%203%20samples/job_history/38797783-5aaa-450e-b161-1a07921cc162).
> Improve Beta UX with a default `extract_output_gcs_dir` [VS-1040]

- scripts/variantstore/docs/aou/vds/Creating a VDS.md
Notebook documenting the _actual_ creation of this VDS here:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/analysis/launch/Make%20a%20VDS%20with%20Quickstart.ipynb?mode=edit
This VDS (well I made two, one with VQSR and one with VETS) can then be used for a tie out in the near future with the WDL pipeline for VDS creation
gs://fc-eada2674-7c2b-42a6-8db3-0246872596dc/quickstart-vds-for-wdl-tieout/VQSR-Classic/vds/
gs://fc-eada2674-7c2b-42a6-8db3-0246872596dc/quickstart-vds-for-wdl-tieout/VETS/vds/
> Make a VDS (how to / how do we even) for VS-1026

- .dockstore.yml
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
- scripts/variantstore/wdl/GvsIngestTieout.wdl
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
Simple copy/paste bug. Closing the header line creator fixes the hanging issues as seen in [this run](https://job-manager.dsde-prod.broadinstitute.org/jobs/21c1ec08-444e-4acd-8490-cc9640d9ea03) (requires PMI ops).
Integration run [in progress](https://job-manager.dsde-prod.broadinstitute.org/jobs/3b5129bb-b7fe-47db-abc4-dda5d7f5006a) (regular auth).
> Close header line creator once ingest is complete [VS-1045]

- .dockstore.yml
- scripts/variantstore/docs/CHANGELOG.md
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
* `JointVariantCalling` [does set](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/f3f98f0e-2a7f-460b-886f-3442551140a8) `tighter_gcp_quotas`.
* Integration tests [do not set](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/51213d40-7583-49f1-a101-1842180a6470) `tighter_gcp_quotas`.
> Restore Beta throttling [VS-1072]

- .dockstore.yml
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
Successful run here https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/3727848a-190a-43a8-8aa5-18d430cf005a
> Throttling integration test [VS-1076]

- .dockstore.yml
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
Successful run linked below, need confirmation from @koncheto-broad that this targets the task that was causing issues for him last week
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/dfcc1388-0dd9-4825-9e8b-a3e4bade12e7
> Turn off caching for workspace-data dependent task [VS-1075]

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/RefCreator.java
Link to Terra run and queries in ticket.
> Bitpacking fixup [VS-1104]

- scripts/variantstore/docs/CHANGELOG.md
Updating CHANGELOG.md for new behavior replacing missing ranges in ref_ranges_* tables.
> VS-1115 - Updating CHANGELOG.md for new missing behavior

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
- src/main/java/org/broadinstitute/hellbender/utils/gvs/bigquery/BigQueryUtils.java
Passing Integration test (using built-in dockers) [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/d2063e26-a22e-412e-ad91-aa2b14fbb7ec).
> VS-1119 remove unused call

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
VS-1092 - Fix for GvsCreateFilterSet OOD
Integration test ran [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/f2dc8eca-1fc2-4ab3-ac38-ab430fb1d60a).
One failure - in the Exome test on AssertCostIsTrackedAndExpected. Doesn't seem related to this code change, so am going to allow it.
> VS-1092 - Fix for GvsCreateFilterSet OOD

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
Heap Space error in PopulateFilterSetInfo
Passing Integration Test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/50d867c5-3f6f-405b-8e7b-a714ab7e806f).
> VS-1092. More memory for PopulateFilterSetInfo

- .dockstore.yml
- scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
Update AoU Documentation for GvsImportGenomes to reflect new behavior
> VS-1090 - Update AoU Documentation for GvsImportGenomes to reflect new behavior

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateVDS.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/hail_gvs_import.py
- scripts/variantstore/wdl/extract/import_gvs.py
- scripts/variantstore/wdl/extract/run_in_hail_cluster.py
- Preferentially puts phased genotyped into `LGT` entry, otherwise unphased [VS-1060].
- Drops `GT` [VS-1122].
- Drops any all-empty phasing fields in {`PS`, `PID`} [VS-1123].
[VS-1060]: https://broadworkbench.atlassian.net/browse/VS-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VS-1122]: https://broadworkbench.atlassian.net/browse/VS-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VS-1123]: https://broadworkbench.atlassian.net/browse/VS-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Phasing and GT removal in VDS [VS-1060] [VS-1122] [VS-1123]

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateVDS.wdl
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/run_in_hail_cluster.py
- scripts/variantstore/wdl/extract/vds_validation.py
Integration run:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/3aa1545f-7f11-4919-9ecf-8b3a5900441a
> VS 923 add validation to cluster creation

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/import_gvs.py
Revert some phasing changes that were unnecessary for AoU and broke our integration tests.
[Integration run](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/ba93baa2-9971-4c90-8ce3-635702a81eb6)
> Revert phasing changes [VS-1144]

- codecov.yml
> Disable line-by-line codecov comments

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
- scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
Test run here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/81030f0d-af0e-4f75-8350-0dfeabb5e4a3
> VS-1163 - Set default to enable TTL on prepare ranges tables.

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCallset.wdl
Links require PMI auth
- [Successful 100 wide extract](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%20Delta%20Callset%20v2/job_history/2cb983e9-84bc-43dc-8191-b7f9342bba30) with no explicit memory override
- [Successful 500 wide extract](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%20Delta%20Callset%20v2/job_history/7d143481-9e27-47d3-860f-b661a16d7299) with no explicit memory override
> Address ExtractTask OOMs [VS-1127]

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- src/main/java/org/broadinstitute/hellbender/tools/GatherVcfsCloud.java
Reduce the logging a bit.
Probably should make a PR directly into gatk master so that when we next merge gatk master changes we'll get this goodness?
Integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/f8c38f97-7945-414f-9432-13b2f12138bb) (note failed one of the subtests for a random docker pull error)
Example CreateFilterSet run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/b2e7eb86-e494-4891-885b-5a96cb1056b3)
> VS-1103 GatherVcfs logging too much

- .dockstore.yml
- scripts/variantstore/variant_annotations_table/GvsCreateVATFilesFromBigQuery.wdl
- scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
- scripts/variantstore/wdl/GvsAssignIds.wdl
- scripts/variantstore/wdl/GvsBenchmarkExtractTask.wdl
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
- scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
- scripts/variantstore/wdl/GvsCallsetCost.wdl
- scripts/variantstore/wdl/GvsCallsetStatistics.wdl
- scripts/variantstore/wdl/GvsCreateFilterSet.wdl
- scripts/variantstore/wdl/GvsCreateTables.wdl
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
- scripts/variantstore/wdl/GvsExtractCallset.wdl
- scripts/variantstore/wdl/GvsFindHailCruft.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- scripts/variantstore/wdl/GvsJointVariantCallsetCost.wdl
- scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
- scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/GvsVQSRClassic.wdl
- scripts/variantstore/wdl/GvsWithdrawSamples.wdl
Standardized bash options for all, successful workflow run here https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/54c01416-d3ff-4878-b844-92249d4f6a4c
> Standardize bash options [VS-460]

- .dockstore.yml
- scripts/variantstore/variant_annotations_table/README.md
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
- Successful [VAT creation](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/9503ad5e-676f-4e48-90ac-44022bc4d608)
- Reasonably successful [VAT validation](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/9b4dc893-cad5-4204-b40d-3d3f0a541db3)? Could use a check on this
> Minor changes for updated VAT reference testing [VS-1054]

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/GvsCreateVDS.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/hail_gvs_import.py
- scripts/variantstore/wdl/extract/run_in_hail_cluster.py
- run to create the VDS: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/6af5e497-7ee2-48de-9c35-79a586d7d0eb
- run to create the VAT: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/0c11d926-a0cc-40f7-83fd-ee37c69b67f5
- run to validate the VAT: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/926767be-fd29-4696-b341-bf9592d9e6e1
> Make run_in_hail_cluster.py more generic and use it to create the VAT [VS-1200]

- .dockstore.yml
- scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
Run in quickstart: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/588a50be-9e03-4e34-8f12-a61a26262763
Run on delta: https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%20Delta%20Callset%20v2/job_history/135f5cc3-4948-426b-a90c-8ced5ec9f1e6 (failed on the test that was added after Delta because the typo in the nfe column names)
> Only run certain VAT tests on larger callsets [VS-823]

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateVDS.wdl
Integration run with [all the tests here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/d6892c6d-0d1e-415b-819b-24a30ed08f0f)
> VDS optional args fixes [VS-1226]

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
Successful Integration Test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/d43ca844-632b-4737-962e-56369ac91e53)
> VS-1232 SelectVariants extension fix

- scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
- scripts/variantstore/docs/aou/workspace/CreateWriteStreamRequestIncreasedQuota.md
As John loads data into the Echo callset, he will certainly run into issues in the documentation, that should be addressed
> VS 1036 documenting quotas

- .dockstore.yml
- scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
- scripts/variantstore/docs/aou/vds/vds_validation.py
- scripts/variantstore/variant_annotations_table/README.md
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/GvsCreateVDS.wdl
- scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/hail_create_vat_inputs.py
- scripts/variantstore/wdl/extract/hail_gvs_import.py
- scripts/variantstore/wdl/extract/vds_validation.py
Generate Avro Files run: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/577e77f2-4174-46c0-9d8a-9fdbbd2a27ed
Generate VDS run: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/27299041-7779-49d7-b7d3-6c0349f5ffc3
Generate VAT run: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/ad1b2687-7df0-4e92-b4e2-b61fcb77cd19
Validate VAT run: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/dae4874f-a619-40d4-84b4-066295b76cb2
> Remove Unneeded Task and Update Docs [VS-817]

- scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
Added a note to AoU documentation describing possible need for more memory or disk on certain task.
> VS-1211. Update usage documentation

- .github/workflows/gatk-tests.yml
* update setup-gcloud@v0 -> v2 since v0 is deprecated
> Update the setup_cloud github action

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/GvsValidateVDS.wdl
- scripts/variantstore/wdl/extract/vds_validation.py
note I still need to update the docker image and utils
> Early Subset VDS during validation for validation check

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/run_in_hail_cluster.py
- scripts/variantstore/wdl/extract/vds_validation.py
successful run here:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/5b3529d7-10b9-4019-a898-23a7eb596585
> Add a loop to the validation

- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
This doesn't fix the integration test, but a bug in GvsBulkIngest
> VS-1291 fix integration test in ah var store

- scripts/variantstore/docs/CHANGELOG.md
Update changelog for Beta release
> VS-623 exclude as yng from vcf

- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
This migrates ONLY that part of the code from ah_var_store to EchoCallset branch (there are other changes in ah_var_store)
> VS-1190 - Update GvsCreateVATfromVDS.wdl to use new Nirvana reference.

- .dockstore.yml
- scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
- scripts/variantstore/wdl/extract/hail_create_vat_inputs.py
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/6f50b33b-3a44-49a9-8e43-d9752f8cb224
> export variant info for debugging

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/hail_create_vat_inputs.py
successful integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/802f9314-2b8b-4007-9c8d-6832a5687f22)
> add logging and validate vat to echo callset branch

- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/hail_create_vat_inputs.py
- scripts/variantstore/wdl/extract/run_in_hail_cluster.py
> Rc vs 903 tighten hail code

- .dockstore.yml
- scripts/variantstore/wdl/GvsTieoutPgenToVcf.wdl
Successful run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/3b8ec994-8b18-4bf8-bf43-c75e88073506)
> PGEN / VCF tieout [VS-1311]

- scripts/variantstore/wdl/extract/build_docker.sh
- scripts/variantstore/wdl/extract/build_docker_tag.py
- scripts/variantstore/wdl/extract/test_build_docker_tag.py
Make sure to run the following to be able to push to GAR from your machine:
```
gcloud auth configure-docker us-central1-docker.pkg.dev
```
> Docker image ID in tags [VS-1340]

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/hail_create_vat_inputs.py
[successful run here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/3f2a97af-80ec-48fb-98f6-7d84d5594df3)
> Add Konrad's changes

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCallsetPgenMerged.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/extract/plink_docker/Dockerfile
- scripts/variantstore/wdl/extract/plink_docker/build_plink_docker.sh
Successful PGEN extract [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/e59ff255-cfac-4c10-84ed-91d2331fa5b8), successful VCF / PGEN tieout [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/bc770f70-94f2-40ee-a561-1b6d2032e3cb).
> PLINK2 Docker [VS-1315]

- .dockstore.yml
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
Integration Test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/a795190c-dcc2-40a7-bfcc-84fa6a4ea0dc)
Two failed on ValidateVDS (or rather something upstream). I *don't* think this is an effect of this PR.
> Apply latest test changes to echo callset

- scripts/variantstore/wdl/GvsUtils.wdl
Fix mishmash of GCR path with GAR tag to be all GAR
> Fix Docker image tag bug

- scripts/variantstore/wdl/GvsUtils.wdl
* Compress the tarball saves a bit.
* Remove unused contigs from interval_list files by grepping.
> VS-1368 The tarball is too damn big (#8829) -- Echo Callset Version

- .dockstore.yml
- scripts/variantstore/wdl/GvsJointVariantCalling.wdl
- scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
- scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
Correct for newly non-optional inputs to `GvsJointVariantCalling`, plus fix an unrelated race condition between creating the dataset and running this workflow.
Integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/f8797021-f5d4-4003-92be-010001b7f6af).
> Fix integration tests [VS-1374]

- scripts/variantstore/wdl/GvsExtractCallsetPgenMerged.wdl
- scripts/variantstore/wdl/MergePgenHierarchical.wdl
* Fix Chromosome Encoding used in pgen merge.
> VS-1413 Fix Pgen merge chrom encoding - EchoCallset Version

- scripts/variantstore/beta_docs/gvs-outputs.md
- scripts/variantstore/beta_docs/gvs-troubleshooting.md
- scripts/variantstore/beta_docs/run-your-own-samples.md
1. Add a section about how to use data stored in other workspaces without copying it
2. Add a troubleshooting section at the top about generally how to re-run the workflow when it fails (clean up to do before etc)
3. Reorganized the outputs document
4. Added commands on how to filter the VCFs in bcftools following our recommendations
> Update GVS Docs to cover additional use cases and troubleshooting suggestions

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCallsetPgen.wdl
- scripts/variantstore/wdl/GvsExtractCallsetPgenMerged.wdl
- scripts/variantstore/wdl/MergePgenHierarchical.wdl
Successful run here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/7fe712ca-427a-4d67-b96c-fa270b1c33ae
> Put PGEN deliverable (instead of intermediate) files in output_gcs_dir [VS-431]

- .dockstore.yml
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
successful run here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/21fffc17-7ac3-4680-a1c0-ebdd99b05854
> Add integration test for BGE samples [VS-1225]

- .dockstore.yml
- scripts/variantstore/beta_docs/gvs-exome-workspace-description.md
- scripts/variantstore/docs/RUNNING_EXOMES_ON_GVS.md
- scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
Integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/8eadce08-04fa-447f-bbbc-934f52e79030), still working on testing this by hand
> Fix status writing edge case bug [VS-1456]

- .dockstore.yml
- scripts/variantstore/InputValidation.ipynb
- scripts/variantstore/wdl/GvsExtractCallsetPgen.wdl
- scripts/variantstore/wdl/GvsExtractCallsetPgenMerged.wdl
- scripts/variantstore/wdl/MergePgenHierarchical.wdl
Port over changes to `ah_var_store` to make input `output_gcs_dir` behave the same way for PGEN as VCF extract.
Successful run here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/4862a35d-7ac3-421e-9b91-86acaf2b8376
> bring PGEN output dir changes from ah_var_store

- scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
Instructions to create vid to mapping table
> VS-1461 Instructions to create vid to mapping table

- .dockstore.yml
- scripts/variantstore/wdl/GvsExtractCallsetPgen.wdl
test run here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/efc74c40-5e71-4252-8e5a-8526bad35ad4
> Don't Copy PGEN Interval Lists to Output Directory

- scripts/variantstore/docs/Build Docker from VM/building_gatk_docker_on_a_vm.md
Minor correct for new script location.
> Update docs for moved script [VS-1490]

- .dockstore.yml
- scripts/variantstore/wdl/GvsUtils.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
VS-1558. This PR modifies the ExtractCohortEngine code to have the Vet and RefRanges SortingCollections explicitly call the 'doneAdding' method when they are done having data added to them.
Passing Integration test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/78dfca26-6569-4635-baca-1cb0f79d2347)
> VS-1558 release the memory

- .dockstore.yml
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- [Failing ingest ](https://job-manager.dsde-prod.broadinstitute.org/jobs/6c8d516d-a322-419e-84d7-1f04b14feb60) without these highly sophisticated changes.
- Passing ingest [with](https://job-manager.dsde-prod.broadinstitute.org/jobs/6ec4410a-58cd-4e72-9d41-96fc68b016d6).
> Fix exomes bug for 200 < # samples < 400 [VS-1533]

- scripts/variantstore/docs/CHANGELOG.md
> GVS pre-release branch

- .dockstore.yml
- scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
- scripts/variantstore/wdl/GvsImportGenomes.wdl
- src/main/java/org/broadinstitute/hellbender/tools/gvs/common/ChromosomeEnum.java
- src/main/java/org/broadinstitute/hellbender/tools/gvs/common/SchemaUtils.java
- src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
- src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/RefCreator.java
First pass for supporting custom references.  Right now, we're just passing in the cat references as an argument and there's nothing cat-specific in there, but eventually we might want to hard-code the cat info.
The code as it stands passed Bulk Ingest and alt allele!
Successful bulk ingest run: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Tiny%20Quickstart%20for%20Felis%20catus%20adoribus/submission_history/49c59fff-5748-4c12-96c8-dbf4fb1bce29
Successful alt allele run: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Tiny%20Quickstart%20for%20Felis%20catus%20adoribus/submission_history/4435525c-4a69-473b-8ebf-f61b2732e1e5
Successful bulk ingest run including headers: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Tiny%20Quickstart%20for%20Felis%20catus%20adoribus/submission_history/1b …
> Vs 1611 - herding cats

- build.gradle
> update netty version

- build.gradle
> Update gradle sonatype plugin

- docs/funcotator/forum_info/forum_post_tutorial.md
- src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
* fix two links that weren't updated
> Fix funcotator links

- .dockstore.yml
- scripts/variantstore/aou/rwb/rwb_search_export.sh
- scripts/variantstore/scripts/check_vat_columns.py
- scripts/variantstore/scripts/create_ranges_cohort_extract_data_table.py
- scripts/variantstore/scripts/populate_alt_allele_table.py
- scripts/variantstore/scripts/process_sample_vcf_headers.py
- scripts/variantstore/scripts/run_avro_query.py
- scripts/variantstore/scripts/run_avro_query_for_sample_info.py
- scripts/variantstore/wdl/GvsCallsetStatistics.wdl
- scripts/variantstore/wdl/GvsUtils.wdl
- scripts/variantstore/wdl/test/GvsQuickstartIntegration.wdl
Passing Integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/submission_history/40e40641-773d-4be7-b85c-ce28d88262c2)
> VS-1654. Don't allow usage of legacy SQL.

- .github/workflows/gatk-tests.yml
> Update CI job matrix names so the interesting bits appear in the dashboard.
