broadinstitute/gatk

build.gradle

* Adding the dataproc-cluster-ui script to the release bundle so users can access it.
* Fixes #5400

Add scripts/dataproc-cluster-ui to bundle.

---

build.gradle

Noticed these when reviewing https://github.com/broadinstitute/gatk/pull/5401.

Remove remaining obsolete Intel Conda env references.

---

build.gradle

updating htjsdk 2.18.0 -> 2.18.1
this fixes an issue that prevents gatk from reading certain cram files

updating htsjdk to 2.18.1

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java

@takutosato I was checking the filter analysis outputs of every M2 validation and this filter hurts much, much more than it helps, probably because other developments have made it less necessary.  Let's essentially turn it off by default.

made Mutect2 read position filter default much less stringent

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervalsIntegrationTest.java

Changed FilterIntervals to operate on the intersection of intervals in all inputs.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java

@takutosato This works around #5492 and eliminates a handful of false negatives.

Deal with read position annotation bug in M2 filter

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java

@takutosato this will remove some confusing irrelevant arguments.

removed unnecessary inheritance of M2 filtering arguments collection

---

build.gradle
src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java

Fixes https://github.com/broadinstitute/gatk/issues/5362 and https://github.com/broadinstitute/gatk/issues/4637. Log messages from JEXL were being dropped because of https://github.com/broadinstitute/gatk/issues/4637, making the behavior described by https://github.com/broadinstitute/gatk/issues/5362 even more subtle to discern. Now, instead of seeing:
> log4j:WARN No appenders could be found for logger (org.apache.commons.jexl2.JexlEngine).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
the user will see:
> 11:51:06.321 WARN  JexlEngine - ![51,60]: 'QD < 2.0 || MQ < 40.0 || FS > 60.0 || SOR > 3.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0 || ExcessHet > 54.69;' undefined variable MQRankSum

Fix jexl logging and update VariantFiltration doc.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/FilterAlignmentArtifacts.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngineUnitTest.java

The more the best alignment mismatches its assigned reference location, the more stringent the filter becomes, that is, the lower the threshold for secondary alignments to constitute a multi-mapping becomes.  If the best mapping mismatches at one base and the second best mismatches at three, that is very different from the best mismatching at four bases and the second best mismatching at six.
@takutosato This corrects a failure to filter some very obvious clustered events mapping artifacts.  For example, there were 11 "events" within 150 bp in one MC3 sample that were all being called as false negatives for M2 and true positives for M1.  If these are real, I will eat dog food.

mismatch ratio option in realignment filter

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeAlleleCounts.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculator.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeAlleleCountsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/afcalc/AlleleFrequencyCalculatorUnitTest.java

Closes #4833.
This doesn't change the model, just the numerical implementation.  It addresses some of the issues holding up #4614.  From the discussion there, here is the essence of this PR:
>The general rule for avoiding finite precision problems with the qual score is: always calculate probabilities of alleles being absent.  The problem with working in terms of alleles being present is that for very good GQs this probability is so close to 1 that quals can become infinite. 
In this PR we add up the probabilities of genotypes that don't have the allele, which is small but non-zero and everything works fine.
@ldgauthier care to review?  Note that this does not close issue #4614, but it enables a subsequent PR to do so.

Improved implementation of allele-specific new qual

---

src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java

order to dramatically improve exome performance
This makes an 81X speedup in the 1000interval test I put back in.  Exomes are just about unrunnable without some sort of interval manipulation.  The 65 sample exome joint calling callset output was exactly the same with this version.  I also did a comparison for a chr1 and chr20 import (so that we were looking at two intervals that were far apart) and the runtime was the same.  This is a huge improvement for some typical use cases.

Definine GenomicsDB "partitions" over the span of the input intervals in

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/AdaptiveChainPruner.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2FiltersArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

This optimizes the defaults in mitochondria-mode for WGS mitochondria calling. It changes the `pruning-lod-threshold` in adaptive pruning and the `lod-divided-by-depth` threshold in `FilterMutectCalls`.

Changing defaults for mitochondria mode now that we have adaptive pruning

---

src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/OutputRenderer.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRenderer.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRendererUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRendererUnitTest.java

Funcotator used to override getVersion() with a custom version number.
Now it uses the toolkit-wide version number, like other GATK tools.
Also improved javadoc for OutputRenderer constructors, and deleted
some unused constructors.
Resolves #5128

Funcotator: remove hardcoded tool-level version, and use the GATK version instead

---

build.gradle
src/main/java/org/broadinstitute/hellbender/Main.java
src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
src/main/java/org/broadinstitute/hellbender/utils/runtime/RuntimeUtils.java
src/test/java/org/broadinstitute/hellbender/MainTest.java
src/test/java/org/broadinstitute/hellbender/utils/runtime/RuntimeUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessControllerUnitTest.java

making gatk --version print the version

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java

Fixes the gatk doc part of https://github.com/broadinstitute/gatk/issues/5509 now that the public doc has been updated.

Restore link in VariantFiltration to point to update online JEXL doc.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariants.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/LeftAlignAndTrimVariantsUnitTest.java

Fix for https://github.com/broadinstitute/gatk/issues/5511, intermittent LeftAlignAndTrimVariants unit tests failures.

Fix LeftAlignAndTrimVariants args.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/GermlineProbabilityCalculator.java

Closes #5553.
@takutosato This is a bug fix for the case `--default-af 0.0`.

fix edge case for Mutect2 germline resource

---

scripts/cnv_wdl/cnv_common_tasks.wdl
scripts/cnv_wdl/germline/cnv_germline_case_scattered_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl
src/main/java/org/broadinstitute/hellbender/tools/copynumber/DetermineGermlineContigPloidy.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/CopyNumberUtils.java

Reverts the reversion in #5225, this time addressing the lexicographical ordering issue in #5217 at the WDL level by simply renaming gCNV output at the command line.  If desired, we can eventually change gCNV itself to output filenames that are robust against lexicographic ordering, but this is low priority in my opinion.
@vruano this is what we discussed last week.  Tests pass on Travis, and I'm pretty sure this fix should work OK, but I have not done an actual run with enough samples to see the fix in action.  Can I assign you to review once I get a chance to do this?
EDIT: Also went ahead and rolled an older PR #5304 into this one so I can test both at the same time.
Closes #4724.

Restore array output in gCNV WDLs for efficient postprocessing.

---

scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
src/main/java/org/broadinstitute/hellbender/tools/copynumber/ModelSegments.java

Also fixed some minor style issues in argument variable names and the WDL.
This should help recover some deletions and might possibly clear up some issues with MAF estimation when the number of hets is small.  @LeeTL1220 can you run on some test cases to check the effect?  (Note that the changes to fix estimation of the posterior widths, which will in turn affect similar-segment smoothing, are in another branch; we should test those changes as well.)
Note that the default threshold of zero for the tumor in matched-normal mode should ensure that the sites genotyped as het should always match in the tumor and the normal.  (This will ultimately make multisample segmentation, as enabled by #5524, more straightforward.)  There was previously a check for this condition in the integration test; …

Added separate allele-count thresholds for the normal and tumor in ModelSegments.

---

src/main/java/org/broadinstitute/hellbender/engine/MultiVariantWalker.java
src/main/java/org/broadinstitute/hellbender/engine/VariantLocusWalker.java
src/main/java/org/broadinstitute/hellbender/engine/VariantWalker.java
src/main/java/org/broadinstitute/hellbender/engine/VariantWalkerBase.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java

Adding a new method `getVariantCacheLookAheadBases` to `VariantWalkerBase` which allows subclasses to set how far to look ahead when caching variants.  This may help reduce memory use in GenotypeGVCFs.
This also changes the side inputs to use FeatureDataSource.DEFAULT_QUERY_LOOKAHEAD_BASES which is `1000`, this is the value used by the other tools.  I'm not sure if that's the right thing to do, but it makes variant walkers more consistent with other tools.  Alternatively we could add a separate configuration method that lets tools change the side input value.  We could also expose an optional parameter in the feature input that lets you set that on a per input basis if we need it.  
This doesn't seem to have any negative effect on performance for genotypegvcfs, but it's hard to tell from …

allowing variant walkers to configure their caching behavior

---

build.gradle

The documentation date is currently displayed incorrectly, and nonsensically, and sometimes from the future, in the generated doc. See the bottom of the page at https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.12.0/#, for example.
Before:
`GATK version 4.0.11.0-92-gf9a2e5c-SNAPSHOT built at 09-10-2019 06:10:16`
After:
`GATK version 4.0.11.0-92-gf9a2e5c-SNAPSHOT built at Wed, 9 Jan 2019 18:13:38 -0500`
@bhanugandham Can you test this when you get a chance.

Put the actual date/time in the generated doc output.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2FilteringEngine.java

@takutosato Here's another bug fix.  After the big filtering refactor M2 filters will be unit-testable and these things will be easier to prevent.
This fixes the last edge case mentioned by @byoo in the discussion of #5563.

Fixed edge case of zero-depth in FilterMutectCalls germline filter

---

src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
src/main/java/org/broadinstitute/hellbender/utils/io/DeleteRecursivelyOnExitPathHook.java
src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsTest.java
src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java

* replacing existing deleteRecursivelyOnExit method with deleteOnExit
* closes https://github.com/broadinstitute/gatk/issues/5319

moving BucketUtils.deleteOnExit -> IOUtils

---

src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKAnnotationPluginDescriptor.java
src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java

Fixes https://github.com/broadinstitute/gatk/issues/4387. Tested manually.
Before (no default read filters in doc):
After (read filters included):

Fix inclusion of default read filters in doc (use valid freemarker property values).

---

src/main/java/org/broadinstitute/hellbender/utils/pairhmm/Log10PairHMM.java
src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java
src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java

Hello.
I believe there is an error in the description of the algorithm in the pairHMM alignment stage.
It states that it does **local** alignment, however the code implements a **global** alignment.
Therefore I fixed the comments and added the correct reference to Durbin's book. (The figure referenced is not the Finite State Machine implemented).
This was discussed on the GATK forum before I made the pull request.
See discussion here : [Discussion Thread](https://gatkforums.broadinstitute.org/gatk/discussion/23197/question-about-the-alignment-performed-in-the-haplotypecaller-pairhmm#latest)
I believe this is important,  because the difference between the two FSMs is as important as the difference between running the Needleman–Wunsch and Smith-Waterman algorithm (global vs local).
Regards. …

Pair-HMM alignment algorithm description fix

---

build.gradle
src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSinkUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java

* Updating htsjdk 2.18.1 -> 2.18.2
* Remove deprecated method use
* Changing IntervalUtilsUnitTest due to changes in IntervalList
* IntervalList now rejects certain invalid intervals that it previously didn't and throw IllegalArgumentException.
* This ends up changing which exceptions are thrown in some cases, updated some tests to accept both MalformedFile and MalforedGenomeLoc.

Update htsjdk to 2.18.2

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/RefVsAnyResult.java

This made a moderate difference in the `ReferenceModelForNoVariation` runtime as I have been profiling the HaplotypeCaller GVCF mode. 
Before: 
After:

Doing away with stream api call in place that showed up on the profile for GVCF mode

---

src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKAnnotationPluginDescriptor.java
src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngine.java
src/main/java/org/broadinstitute/hellbender/utils/ClassUtils.java
src/main/java/org/broadinstitute/hellbender/utils/config/GATKConfig.java
src/main/resources/org/broadinstitute/hellbender/utils/config/GATKConfig.properties
src/test/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKAnnotationPluginDescriptorUnitTest.java
src/test/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptorTest.java
src/test/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/testpluggables/TestAnnotation.java
src/test/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/testpluggables/TestReadFilter.java
src/test/java/org/broadinstitute/hellbender/engine/GATKToolUnitTest.java
src/test/resources/org/broadinstitute/hellbender/cmdline/GATKPlugin/changePluginPackages.properties
src/testUtils/java/org/broadinstitute/hellbender/testutils/BaseTest.java

rebase of https://github.com/broadinstitute/gatk/pull/4611 with fixes

rebase Dgs configure plugin packages

---

src/main/python/org/broadinstitute/hellbender/gcnvkernel/io/io_commons.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/io/io_consts.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/io/io_denoising_calling.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/commons.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/model_denoising_calling.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/utils/math.py

This PR adds two new files into the gCNV output directory - mean and the standard deviation of the denoised coverage, that is computed by drawing posterior samples from the computed model.

Added per-sample denoised coverage output to gCNV

---

build.gradle

This addresses issues #5568 and #5342.
#5568 Buffer resize messages are now turned on only for Debug builds.
#5342: Added better general error reporting for system commands. For the file synching error in question, implemented a workaround. With environment variable - TILEDB_DISABLE_FILE_LOCKING - set to true or 1, there is no file locking and file synching error will only log warning messages and not return an error. Hopefully, this will mitigate the issues on NFS and CIFS.

Move to GenomicsDB 1.0.0-rc2 for #5568 and #5342

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorDataSourceDownloader.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java

- Released new data sources to google bucket and FTP site for both somatic and germline (clinical pipeline)
- Updated data source download URL to point to the bucket for v1.6.20190124
- Updated minimum version of data sources to v1.6.20190124.
With the release and these changes, the following issues are addressed:
Fixes #5259 
Fixes #5428 
Fixes #5429

Updates for latest data source release.

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationMapUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
src/test/resources/large/funcotator/funcotator_dataSources/gencode/hg19/gencode.config
src/test/resources/large/funcotator/funcotator_dataSources/gencode/hg38/gencode.config
src/test/resources/large/funcotator/funcotator_dataSources_cloud/gencode/hg19/gencode.config
src/test/resources/large/funcotator/funcotator_dataSources_cloud/gencode/hg38/gencode.config
src/test/resources/large/funcotator/funcotator_dataSources_cloud_gnomad/gencode/hg19/gencode.config
src/test/resources/large/funcotator/funcotator_dataSources_cloud_gnomad/gencode/hg38/gencode.config
src/test/resources/large/funcotator/pik3ca_muc16_all_transcripts_ds/gencode_muc16/hg19/gencode.config
src/test/resources/large/funcotator/pik3ca_muc16_all_transcripts_ds/gencode_pik3ca/hg19/gencode.config
src/test/resources/large/funcotator/small_ds_clinvar_hg19/gencode_pik3ca/hg19/gencode.config
src/test/resources/large/funcotator/small_ds_pik3ca/gencode_pik3ca/hg19/gencode.config
src/test/resources/large/funcotator/small_ds_pik3ca/gencode_pik3ca/hg38/gencode_pik3ca.config
src/test/resources/org/broadinstitute/hellbender/tools/funcotator/small_pik3ca_dbsnp_ds/gencode_pik3ca/hg19/gencode.config

Store the NCBI build version in the Gencode datasource config files
in order to resolve an issue where this value was not always available
when annotating IGR variants.
Resolves #4404

Funcotator: get the NCBI build version from the datasource config file

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

Teeny tiny PR -- not happy with the AF thresholding for GVCF mode yet

Change default blocking and NON-REF LOD params for M2 GVCF mode

---

README.md

We forgot to update this when travis migrated.  We're seeing old output.

updating travis badge link

---

src/main/java/org/broadinstitute/hellbender/utils/downsampling/MutectDownsampler.java
src/main/java/org/broadinstitute/hellbender/utils/downsampling/PositionalDownsampler.java
src/main/java/org/broadinstitute/hellbender/utils/downsampling/ReservoirDownsampler.java
src/test/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSparkIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/downsampling/ReadsDownsamplingIteratorUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/downsampling/ReservoirDownsamplerUnitTest.java

Fixes https://github.com/broadinstitute/gatk/issues/4768.
The ReservoirDownsampler currently declares reads to be finalized immediately after they're submitted, but in order to guaranty that every read has equal probability of being discarded, it should consume the entire stream of input items before declaring any item to be finalized. When used with a ReadsDownsamplingIterator, no reads are ever downsampled because the iterator populates it's internal cache by eagerly consuming finalized reads as soon as they become available.
Also, PositionalDownsampler doesn't reset it's internal ReservoirDownsampler's state correctly.

Fix ReservoirDownsampler, PositionalDownsampler, and ReadsDownsamplingIterator.

---

src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java

Fixes #5644.
The issue was that different sequence dictionaries were being used.

ReadsPipelineSpark fails with "Interval not within the bounds of a contig"

---

README.md

As requested by @droazen. Please let me know if you'd like to phrase it a different way. I kept it as short as possible.

Add link to _GitHub basics for researchers_ article at top of README.md.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java

This was showing up in the profile, as with a few other places this was copying the cigar for each read over each pileup, which is not efficient.
Before:
After:

Removing an extraneous cigar copy from referenceConfidenceCalculation

---

docs/funcotator/forum_info/README.md
docs/funcotator/forum_info/forum_post_annotation_specifications.md
docs/funcotator/forum_info/forum_post_human_reference_discrepancies.md
docs/funcotator/forum_info/forum_post_tutorial.md

also added readme about where the forum posts live.

Added in Markdown files for Funcotator forum posts.

---

build.gradle
gatk
src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
src/test/java/org/broadinstitute/hellbender/utils/RandomDNA.java
testsettings.gradle

* updating google-cloud-nio from 0.62.0 -> 0.74.0
* fixes confusing gcloud warning about end user credentials that was output on every start up
* improves https://github.com/broadinstitute/gatk/issues/5447 by reducing the warning to an info

updating google-cloud-nio to 0.79.0?

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java

These methods were showing up as time syncs on the profile for #5607 
I ran these a few times vs. its root branch, its probably a small improvement in runtime over this chr15 snippet of an exome on my local machine:
#5607:
```
2m57.516s, 2m56.677s, 3m2.531s, 3m4.116s
```
This branch:
```
2m50.112s, 2m46.981s, 2m43.764s, 2m40.806s
```
Depends On #5607

More excessively micro micro-optimizations

---

src/main/java/org/broadinstitute/hellbender/engine/VariantWalkerBase.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionaryIntegrationTest.java

Fixes https://github.com/broadinstitute/gatk/issues/5087

Change UpdateVCFSequenceDictionary to use the specified dictionary uniformly.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java
src/main/java/org/broadinstitute/hellbender/utils/read/AlignmentUtils.java
src/test/java/org/broadinstitute/hellbender/utils/read/AlignmentUtilsUnitTest.java

This micro-optimization fell out of profiling of the HaplotypeCaller in GVCF mode. 
Profiler view over an Exome before this patch:
Profiler view over the same Exome after this patch:
I suspect given the remaining 9% runtime could be reduced further by looking more closely at the array operations in `isReadInformativeAboutIndelsOfSize()`  
(It should be noted that these profiler results lie within the ReferenceModelForNoVariation codepath which since this is over an Exome we expect the runtime to overall be skewed towards no-variation blocks)
Resolves #5648

Reduced some of the repeated steps in ReferenceConfidenceModel.calcNIndelinformativeReads

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHC.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java

With the new qual model as the default for HC as of 4.1, occasionally sites get output with a . ALT when the * allele gets dropped.  Expected behavior is no output at that site in the VC.
Also limit logging for DepthPerSampleHC annotation.
Note that the expected behavior in one of the existing tests was also wrong and had to be fixed.
Fixes #5650

Don't output VCs with no ALT if * gets dropped

---

scripts/mutect2_wdl/mutect2_nio.wdl

@takutosato The engine team tells us not to run GATK tools on CRAM files for another several months while Joel fixes htsjdk bugs.  This change lets the M2 WDL accept CRAMs by converting to BAM.
@LeeTL1220 This is needed for the SFARI induced pluripotency project.

CRAM support in Mutect2 WDL

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/PosteriorProbabilitiesUtils.java
src/main/java/org/broadinstitute/hellbender/utils/MathUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/CalculateGenotypePosteriorsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/PosteriorProbabilitiesUtilsUnitTest.java

posterior probabilities and calls
Closes #5666

Fix reported bug where no-call genotypes with no reads get genotype

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FilterFuncotations.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/filtrationRules/ClinVarFilter.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/filtrationRules/FilterFuncotationsExacUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/filtrationRules/FuncotationFilter.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/filtrationRules/FuncotationFiltrationRule.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/filtrationRules/LmmFilter.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/filtrationRules/LofFilter.java

Since Funcotation annotation can be multi-allelic, the filtration code needs to not assume that all Funcotated variants will have only one key of each funcotation.

Multi-Allelic Variant Funcotation Filtration

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEval.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEvalIntegrationTest.java

Fixes https://github.com/broadinstitute/gatk/issues/5674. All the tests are written using `IntegrationTestSpec` which creates the output files before running the test. Verified manually.

Change VariantEval to not require the output file to already exist.

---

scripts/m2_cromwell_tests/test_mitochondria_m2_wdl.json
scripts/mitochondria_m2_wdl/ExampleInputsMitochondriaPipeline.json
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

Small change to match the WDL that's going into gatk-workflows.

Changing variable name in MT WDL to match gatk-workflows

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/MutectReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingGraph.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/ChainPrunerUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingGraphUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

@meganshand Could you review this?  It fixes most of the homoplasmic missed calls in broadinstitute/dsp-spec-ops#116.
I reviewed all of the false positive that were introduced to our somatic validations when attempting to make this the default in non-mitochondria mode.  Everything was due to mapping error, which I do not expect to be an issue in mitochondria, and not an inherent problem with recovering more dangling ends.  You will still want to run this branch through some of your validations, however.  In mitochondria mode it's the same as the dangling-1-29.jar that I shared earlier with you and Sarah.

Option to recover all dangling branches -- default in M2 mito mode

---

src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java

Closes #5543.
@kachulis Could you review this PR?

waived an unnecessary IllegalArgumentException in PairHMM

---

scripts/mutect2_wdl/mutect2_pon.wdl

@takutosato This fixes a potential bug.

split MNPs in M2 pon WDL

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/Concordance.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/ConcordanceIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/concordance/noVariationAlleles.vcf

Fixed Concordance tool to allow for no variation alleles in the truth data.

Fixed Concordance tool to allow for no variation alleles in the truth data.

---

src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSBuildReferenceTaxonomyUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
src/main/java/org/broadinstitute/hellbender/utils/downsampling/AlleleBiasedDownsamplingUtils.java
src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
src/main/java/org/broadinstitute/hellbender/utils/nio/PathLineIterator.java
src/main/java/org/broadinstitute/hellbender/utils/text/XReadLines.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/tools/FixCallSetSampleOrderingIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/GatherVcfsCloudIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVIntervalVariantComposerUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVSegmentVariantComposerUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRendererUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/TruthSensitivityTrancheUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantGaussianMixtureModelUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/variant/writers/GVCFWriterUnitTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/IntegrationTestSpec.java

NIO output support for SelectVariants. Tested like so:
```
$ ./gatk SelectVariants \
--variant dbsnp_138.b37.excluding_sites_after_129.vcf \
--select-random-fraction 0.01 \
--output gs://mybucket/variants.vcf
$ gsutil ls -lh gs://mybucket/*.vcf
23.38 MiB  2018-10-30T23:58:12Z  gs://mybucket/variants.vcf
```
Includes the required changes under the hood, plus test updates.
This change also gives NIO support to **HaplotypeCaller**, so it can write its VCF to cloud storage.
Also, fixes #2128.

SelectVariants can now write VCF to cloud

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/CollectReadCounts.java

Goal was to get WGS coverage collection at 100bp at ~15 cents per sample.  Since this is I/O bound (takes ~2 hours to stream or localize a BAM, or about the same to decompress a CRAM), cost reduction can be most easily achieved by reducing the memory requirements and moving down to a cheaper VM.  
Memory requirements at 100bp are dominated by manipulations of the list of ~30M intervals.  There were a few easy fixes to reduce requirements that did not require changing the collection method (which can be easily modified for future investigations, see #4551):
-removed WellformedReadFilter.  See #5233.  EDIT: We decided after PR review to retain this filter by default and disable it at the WDL level when Best Practices is released.  Leaving the issue open.
-initialized HashMultiSet capacity …

Improved memory requirements of CollectReadCounts.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticLikelihoodsEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

@meganshand @ldgauthier This fixes the last homoplasmic missed call in broadinstitute/dsp-spec-ops#116.

handle negative infinity log likelihoods from Pair-HMM in Mutect2

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

@LeeTL1220 This is for Sachet's artifact, ready to review pending the results on Firecloud looking good.

handle unmarked duplicates with mate MQ = 0 in Mutect2

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java

Closes #5609.
@LeeTL1220 Could you review this?

output sample names in Mutect2 pon header

---

build.gradle

* updating google-clound-nio 0.80.0-alpha -> 0.81.0-alpha
* this finally fixes #5447 by moving the stacktrace to debug verbosity

Updating google-cloud-nio to 0.81.0

---

README.md

There is only a single conda environment now; remove dangling references to the intel conda environment from the README.md.

Update README.md to remove outdated references to the Intel conda environment.

---

docs/funcotator/forum_info/forum_post_tutorial.md

Quick update to docs to include an FAQ section with the first common question populated.
Already pushed to forum.

Updated documentation with FAQ section to respond to user comments.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java

- Running in mitochonrial mode
- Link to liquid biopsy blogpost will need to be added once it is posted
- Specifying tumor name is no longer necessary
- Af-of-alleles-not-in-resource is dynamically adjusted for modes
- Joint calling on multiple tumor and normal samples
- Mention and/or link to FilterMutectCalls, Funcotator and CreateSomaticPanelOfNormals
- Remove caveat and state instead M2's ability to handle extreme high depths
- Update HaplotypeCaller link from v3 to current
- Add 'Notes' section and make ordered list
- Move example AF resource snippet to 'Notes' section

Update Mutect2 javadoc to reflect v4.1 changes

---

src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
src/main/java/org/broadinstitute/hellbender/engine/spark/AssemblyRegionReadShardArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/engine/spark/LocusWalkerSpark.java

Closes #5479.  Closes #5478.
@lbergelson here you go.

kebab case some arguments in LocusWalker and Spark walkers

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/InbreedingCoeff.java

Closes #5712.
@ldgauthier can you look at this?

corrected javadoc for InbreedingCoeff

---

src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortSamSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java

Hopefully this will help better inform people as to how these tools should be run in cromwell.

Added some javadoc notes about disk throughput to MarkDuplicatesSpark and SortSamSpark

---

src/main/java/org/broadinstitute/hellbender/engine/spark/FindAssemblyRegionsSpark.java
src/main/java/org/broadinstitute/hellbender/utils/activityprofile/ActivityProfileStateRange.java

These are the changes needed to run on a whole genome in strict mode. We get out of memory errors without these changes.
Reads downsampling was missing for the part where `AssemblyRegion`s are filled with reads - this PR adds it in. Downsampling is not deterministic yet, since that depends on #5437, but that's an orthogonal issue so it's OK to merge this change and add #5437 later.

Run HaplotypeCallerSpark on WGS in strict mode

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/KBestHaplotypeFinder.java

This fixes a bug that @meganshand found.  Here's the background:
By construction we do not assemble graphs with cycles (although @kvg has something to say about this).  However, in rare cases recovering a dangling end may create a cycle.  Although it's debatable whether this is an issue for the new, Dijkstra's algorithm-based best haplotype finding algorithm, we remove cycles before finding best haplotypes.  It seems that the code for removing cycles can go into an infinite loop when, as in Mutect2's mitochondria mode, we allow for the recovery of forked dangling ends.
This PR deletes a single line. `parentVertices` is the set of previously visited vertices in the depth-first search.  When an edge is incident on one of these vertices it creates a cycle and we mark it for removal.  My best …

fixed rare infinite recursion in KBestHaplotypeFinder

---

scripts/mutect2_wdl/mutect2_nio.wdl

@jonn-smith I should have spotted this earlier but unfortunately M2 still has to carry around two WDLs.  I just copied your changes from #5735 verbatim.

bring Funcotator changes to M2 NIO WDL

---

src/main/java/org/broadinstitute/hellbender/utils/codecs/ProgressReportingDelegatingCodec.java
src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/IndexFeatureFile/header_only.vcf

IndexFeatureFile: fix a crash on VCFs with 0 records

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandBiasTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentCollection.java
src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtils.java
src/main/java/org/broadinstitute/hellbender/utils/pileup/ReadPileup.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtilsUnitTest.java
src/test/resources/org/broadinstitute/hellbender/tools/mutect/filtering/merged.stats

Closes #4959.  Closes #4958.  Closes #4933.
Improves indel sensitivity in particular without hurting precision.
@LeeTL1220 Can you review this one?

M2 modifies base quals instead of discarding overlapping read pairs

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandOddsRatio.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_StrandOddsRatio.java

Doc fix for SOR

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java

avoid error due to finite precision  error in M2 pon creation

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingGivenAllelesUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java

@lbergelson The merge vcfs code is notoriously hard to understand.  Removing a bunch of arguments that the GATK never uses seems like a start.

Unused args in VCF merge

---

scripts/funcotator/testing/testFuncotator.sh
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FilterFuncotationsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java

Also refactored the `VcfOutputRenderer` sanitization code.
Fixes #5671

Added `#` as a character to be sanitized by `VCFOutputRenderer`.

---

scripts/mitochondria_m2_wdl/AlignAndCall.wdl
scripts/mitochondria_m2_wdl/AlignmentPipeline.wdl
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

This update means the pipeline won't die on single-ended reads (it just filters them out).

Updating Picard version in mitochondria WDL

---

src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java
src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java

This read filter removes unnmapped reads and reads with unmapped mates. When used in combination with `MateOnSameContigOrNoMappedMateReadFilter` this subsets down to reads only on chrM whose mate is also on chrM. If we only used the `MateOnSameContigOrNoMappedMateReadFilter` we end up with reads whose mate is unmapped still in the BAM, but not the unmapped read, which causes problems downstream in the mitochondria pipeline. This read filter will make the subsetting step faster when we no longer need the NuMTs.
I would really appreciate this getting in before the next release (on Tuesday). (fyi @droazen) @ldgauthier @jsotobroad

Read filter for unmapped reads and their mates

---

scripts/spark_eval/README.md
scripts/spark_eval/exome_md-bqsr-hc_hdfs.sh
scripts/spark_eval/exome_reads-pipeline_gcs.sh
scripts/spark_eval/exome_reads-pipeline_hdfs.sh
scripts/spark_eval/genome_md-bqsr-hc_hdfs.sh
scripts/spark_eval/genome_reads-pipeline_gcs.sh
scripts/spark_eval/run_gcs_cluster.sh

- Increase master disk size
- Use Dataproc 1.3
- Use gz for known sites
- Script for running genome dataset on gcs
Fixes #5152

Spark script improvements

---

Dockerfile
src/main/java/org/broadinstitute/hellbender/utils/python/PythonScriptExecutor.java
src/main/java/org/broadinstitute/hellbender/utils/python/StreamingPythonScriptExecutor.java
src/test/java/org/broadinstitute/hellbender/GATKBaseTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariantsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/python/StreamingPythonExecutorIntegrationTest.java

Fixes #5751 and #4591. Longer term we'll still want to do package version-checking/verification per https://github.com/broadinstitute/gatk/issues/4995 as well.
@jamesemery I included tests for this change, but I need the tests to only run when the conda env is NOT activated. Unit tests are always run on the docker image, so thats out. Integration tests are run on both the docker and the travis image, so I throw a skip exception on the docker, which I detect using the "CI" env variable. But that seems fragile and confusing. Is there a better way to do this ?

Make sure the GATK tool python package is present before executing streaming commands.

---

src/main/java/org/broadinstitute/hellbender/tools/PrintBGZFBlockInformation.java
src/test/java/org/broadinstitute/hellbender/tools/PrintBGZFBlockInformationIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/PrintBGZFBlockInformation/expected_PrintBGZFBlockInformationIntegrationTest_testBamFile.out

The file extension check in this tool was redundant, since there is a subsequent check
that the input file is in BGZF format.
Resolves #5800

PrintBGZFBlockInformation: remove file extension check so that we can accept, eg., bams

---

build.gradle
src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java

Fix for gatk-5449

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java

Fix botched squash, clarify test asserts
Fixes #5650

Really don't output VCs with no ALT if * gets dropped 

---

src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineProgram.java
src/test/java/org/broadinstitute/hellbender/engine/spark/SparkCommandLineArgumentCollectionTest.java

Resolves issue #1370 by exposing the setting for Spark logging level with a separate CLI argument (`--spark-verbosity`). Also stifles overly-verbose executor INFO-level logging by setting the default to WARN.
This was much cleaner to implement than just applying the existing `--verbosity` to the Spark context for a few reasons. First, Spark's `INFO` level is far too verbose, but most GATK tools provide useful INFO messages. This gives the user the ability to tune them separately. Also, Spark offers more levels through log4j, and mapping from htsjdk logging levels with a bunch of `if` statements didn't seem ideal.
Verbose logging only seems to be a problem with when running `/gatk/gatk` inside the GATK docker (eg PathSeq log files easily in 100's of MB). Strangely, however, I found there …

Add spark verbosity argument and default to WARN

---

scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

When I turned off NIO for the first task, I forgot to redo the disk size. This now includes the size of the input bam/cram as a part of the disk size.

Bug fix for Mitochondria Pipeline

---

src/main/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/QNameFinder.java
src/test/java/org/broadinstitute/hellbender/tools/spark/sv/evidence/QNameFinderTest.java

Attempts to fix https://github.com/broadinstitute/gatk/issues/5685
I don't have test data from the users who reported the bug but it seemed like it was likely due to this issue.

Fix SV QNameFinder to handle reads with negative unclipped starts

---

src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java

Fixes https://github.com/broadinstitute/gatk/issues/5805.

Use GATKPathSpecifier for tmpDir arg.

---

src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java

Instead of a String previously.
Tested like this:
```bash
$ ./gatk SelectVariants \
--variant src/test/resources/large/VQSR/dbsnp_132_b37.leftAligned.20.1M-10M.vcf \
--select-random-fraction 0.01 \
--output gs://$BUCKET/variants.vcf
```
and
```
$ ./gatk SelectVariants \
--variant src/test/resources/large/VQSR/dbsnp_132_b37.leftAligned.20.1M-10M.vcf \
--select-random-fraction 0.01 \
--output /tmp/variants.vcf
```
If this works, the plan is to change all tools to use this format, so they can all write VCF output to Google Cloud Storage.

SelectVariants use a GATKPathSpecifier for output

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/ContaminationModel.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java

Closes #5821.  @bhanugandham With this PR we will no longer have to recommend against using `CalculateContamination` for gene panels.
@takutosato This puts in a last-ditch calculation that uses hom ref sites *and* uses sites that didn't get a clear minor allele fraction segmentation.  To avoid distorting the signal with LoH hets, it removes the hom ref sites with the highest allele fraction, which will work unless there's a huge amount of CNV.  This will result in a slight underestimate, but for a small gene panel there's not much you can do.

CalculateContamination works much better for very small gene panels

---

Dockerfile

Suppress the `cp: target '/gatk/srcdir' is not a directory` error message that appears in all of the travis logs by creating the target srcdir first in run_unit_tests.sh.

Eliminate error message in travis logs by creating the srcdir before copying to it.

---

src/main/java/org/broadinstitute/hellbender/cmdline/ReadFilterArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/engine/filters/FragmentLengthReadFilter.java
src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java

Also improved the existing tests for FragmentLengthReadFilter
Resolves #5884

Add a --min-fragment-length argument to FragmentLengthReadFilter

---

src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/markduplicates/MarkDuplicatesSparkUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java
src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java
src/test/java/org/broadinstitute/hellbender/engine/spark/SAMRecordToGATKReadAdapterSerializerUnitTest.java

Resolves #5653 
Blocked by #5607

Added TransientAttributes to GATKRead

---

build.gradle

@ldgauthier found a bug in GenomicsDBImport with overlapping deletions, specifically with  the * allele and the deletion spanning the interval specified - see https://github.com/broadinstitute/gatk/issues/5449#issuecomment-484558863. The fix for this issue(thanks @mlathara) is in 1.0.3 of GenomicsDB.

Move GenomicsDB to 1.0.3 for Importer fix to Issue 5449

---

src/main/java/org/broadinstitute/hellbender/utils/R/RScriptExecutor.java

Fixes https://github.com/broadinstitute/gatk/issues/5893.

Don't redundantly delete temporary directories in RSCriptExecutor.

---

src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSink.java
src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintVariantsSpark.java
src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSinkUnitTest.java

`VariantsSparkSink` will always sort variants before writing them out. However, `HaplotypeCallerSpark` always processes reads in coordinate-sorted order, and produces variants in the same order, so there is no need for `VariantsSparkSink` to sort variants. (In fact, in GVCF mode the sort is prohibitive since the engine creates a variant for every locus over the interval of interest, which go through the sort step before being merged into GVCF bands.)
This PR removes the sort step for `HaplotypeCallerSpark` (and `PrintVariantsSpark`, which doesn't need it either). All of the concordance unit tests pass, and as an additional sanity check I compared the GVCF output from running regular `HaplotypeCaller` on a large input BAM to `HaplotypeCallerSpark` (with and without variant sorting). …

No need to sort variants in HaplotypeCallerSpark.

---

src/main/java/org/broadinstitute/hellbender/utils/tsv/SimpleCSVWriterWrapperWithHeader.java
src/main/java/org/broadinstitute/hellbender/utils/tsv/SimpleXSVWriter.java
src/test/java/org/broadinstitute/hellbender/utils/tsv/SimpleCSVWriterWrapperWithHeaderUnitTest.java

This is what you asked for @droazen. This is one approach to table writing and importantly I found this exponentially less bothersome than the restrictions placed upon me by `TableWriter` when handling the table outputs in #5913. This probably needs more tests and I can add some more comprehensive ones if you would like. Let me know your thoughts

Added a simple TSV/CSV/XSV writer with cloud write support

---

build.gradle

I tested this using the following sketchy procedure: I temporarily reverted https://github.com/broadinstitute/gatk/pull/5936 on this branch, thereby re-introducing non-ASCII characters into the source. That builds without error, as it should. Then I temporarily changed the newly added encoding declarations included this PR in build.gradle from "UTF-8" to "US-ASCII", after which I was able to reproduce exactly the same errors as reported in https://github.com/broadinstitute/gatk/issues/5934, for both compile and gatkDoc tasks. So I think these changes achieve the desired result (accept UTF-8 in source).

Treat all source files as UTF-8 for java, javadoc, gatkdoc.

---

src/main/java/org/broadinstitute/hellbender/tools/AnalyzeSaturationMutagenesis.java
src/test/java/org/broadinstitute/hellbender/tools/AnalyzeSaturationMutagenesisUnitTest.java

write BAM of rejected reads
trim reads to length of short fragments

choose one disjoint read to report

---

build.gradle

See https://github.com/GenomicsDB/GenomicsDB/commit/10d9ea7ffdfa758a5775a995f9e911a076dbf55e for the relevant changes.

Move to GenomicsDB 1.0.4 version to get AS_QUALapprox and AS_VarDP fields treated as array of int vectors

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/KBestHaplotypeFinder.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/KBestHaplotypeFinderUnitTest.java

@davidbenjamin Was familiarizing myself with `KBestHaplotypeFinder` and decided to take a crack at this issue. 
I have no idea how much of a performance hit this will end up being at extreme sites. At worst it involves adding more paths into the priority queues than existed before which could slow down the whole search algorithm. 
Fixes #5907

Fixed an optimization in KBestHaplotypeFinder that caused some bestPaths to be lost while still preserving some of the optimization.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModel.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModelUnitTest.java

I don't doubt that there could be issues caused by reads with previously filled caches. Ultimately this shouldn't have too significant an impact except in very pathological circumstances with highly repetitive regions or reads that hang beyond a certain length into the next region and happen to have had good looking indel sites without the cirgar actually containing any indels for that read. This should eliminate any of these circumstances entirely so we can be sure the cache is clear before every call. 
Fixes #5908

Added a check to ensure previous caching information doesn't affect referenceConfidenceCalls

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

@meganshand This fixes the Sarah's recent bug, and just makes sense in general.
I am not adding a regression test because our work on linked de Bruijn graphs is going to moot stuff like this soon.

Fix edge case where dangling end merging creates cycles

---

src/main/java/org/broadinstitute/hellbender/engine/MultiVariantWalker.java
src/test/java/org/broadinstitute/hellbender/engine/MultiVariantWalkerIntegrationTest.java

Fixes https://github.com/broadinstitute/gatk/issues/5947.

Use UserException IllegalArgumentException for duplicate feature inputs.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/ContaminationModel.java

@takutosato This fixes a bug that Scott Carter found.

fixed a bug in CalculateContamination when contamination is zero

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/ModelSegments.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/formats/collections/CalledLegacySegmentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/formats/collections/LegacySegmentCollection.java

Also changed LegacySegmentCollection and CalledLegacySegmentCollection writers to overwrite instead of append.  (This was fixed for AbstractRecordCollection writers in an earlier PR but was missed in these collections that override the default writer.)
See https://gatkforums.broadinstitute.org/gatk/discussion/24048/a-few-things-need-help-about-output-of-command-modelsegments#latest for some context.  In principle, IGV should be able to handle linear scaling, but it scales automatically for seg files and I'm not sure if you can get around it without some additional steps.  Seems easier to just output log2 copy ratios.  (Perhaps we initially output linear copy ratios to maintain backwards compatibility with previous versions of GATK CNV?  If so, the *LegacySegmentCollections seem to be …

 Changed cr.igv.seg output of ModelSegments to give log2 Segment_Mean.

---

build.gradle

Bug fix release that fixes #5919 and https://github.com/disq-bio/disq/pull/101 (the latter caused BAM count errors).

Upgrade to Disq 0.3.1

---

src/main/java/org/broadinstitute/hellbender/utils/io/Resource.java

The problem is that Spark executors can't rely on the system classloader to load resources. This change falls back to the current classloader if the resource can't be loaded from the system classloader. I've tested it successfully on a cluster.

BaseRecalibratorSpark fails on a cluster due to system classloader issue

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/M2FiltersArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/Mutect2FilteringEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/NormalArtifactFilter.java

@takutosato Silly error on my part.  Made the argument parser crash whenever the argument was set to a non-default value.
@Closes #5978.

fixed a bug where normal p value argument in FilterMutectCalls was static

---

src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/CNVPlottingLibrary.R

Encountered this when doing some work on Google Colab, where your Google Drive is frustratingly named `/content/gdrive/My Drive/Colab Notebooks/`.  It's possible that other funky business could still break this, but it's an improvement.

Fixed CNV plotting script to allow spaces in input filenames.

---

scripts/funcotator_wdl/README.md
scripts/funcotator_wdl/funcotator.wdl

Moves the funcotator.wdl to its own supported area with a README.

Adding funcotator stand-alone WDL to supported area

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ValidateVariants.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/ValidateVariantsIntegrationTest.java

In validateVariants tool, made the default case behave so that it does the validations that can be done, and issues warning messages for the validations that cannot be done (ie, required external files)

Jc validate variants fixes issue5862

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEval.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/VariantEvaluator.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/util/EvaluationContext.java

We have a tool, VariantQC, that extends VariantEval.  This PR is a minor refactor to expose the code that creates the list of VariantStratifier and VariantEvaluator objects as protected methods, so subclasses could modify them.  This should have no functional difference on VariantEval itself.  We're hoping to use these changes in order to adapt our tool in response to reviewers, so if there is any way to push these changes we would appreciate it.

Refactor two VariantEval methods to allow subclasses to override

---

src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/validation/CompareDuplicatesSpark.java
src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSparkIntegrationTest.java

Add a command-line argument to toggle using NIO on reading for Spark

---

.travis.yml
README.md

testing if removing the codecov upload line in our yml disables the reporting on the pr

testing if removing codecov upload removes the check

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/Path.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/read/CigarUtilsUnitTest.java

Closes #6037 
@ldgauthier This fixes the Karlsson group's bug with long insertions.
@cwhelan This also fixes Giulio's bug.

fixed a GGA mode bug where added alleles' cigars had soft clips

---

src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountReadsSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountVariantsSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/FlagStatSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintVariantsSpark.java

Now that Disq runs tests on 'large' BAM and VCF files (https://github.com/disq-bio/disq/pull/103), we can remove the Beta label from some more of the Spark tools.

Remove Beta label from some Spark tools

---

README.md

* Java 8 doesn't come by default on many machines now.  Updating the
README with advice about where to download a java8 jdk.
* Part of https://github.com/broadinstitute/gatk/issues/6024

Adding links to download java 8 to the ReadMe.

---

README.md
gatk
scripts/sv/run_whole_pipeline.sh
scripts/sv/stepByStep/discoverVariants.sh
scripts/sv/stepByStep/scanBam.sh
src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqFilterSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSpark.java
src/main/java/org/broadinstitute/hellbender/utils/config/GATKConfig.java
src/main/resources/org/broadinstitute/hellbender/utils/config/GATKConfig.properties

spark.executor.memoryOverhead as warned by Spark 2.3
a trivial change.

change spark.yarn.executor.memoryOverhead to 

---

README.md

Saving wisdom that wasn't previously easy to find in the README.

Clarified the readme to warn users to set their Gradle JVM properly in Intellij.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQuality.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java

After spending some time to resolve this users issue, https://gatkforums.broadinstitute.org/gatk/discussion/24134/gatk4-rmsmappingquality-results-differ-between-v4-0-0-0-and-v4-1-1-0/p1, it became clear that the issue was that the user simply mismatched her versions of gatk, which seems to have caused their MQ annotations to tank. The user didn't notice the warnings of this fact until we had already nearly found the issue by debugging. I propose that we upgrade the warning to an exception with explicit override to make it harder for this issue to slip past people in the future.

Added an explicit override to RMSMappingQuality annotation to enable old code fallback.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/MutectReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java

This branch (or some variation therin) will be necessary to keep track of how well #5980 is doing at bringing down the number of found haplotypes.

Added secret arguments to ReadThreadingAssembler to track found haplotype counts and kmers used.

---

src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceFileSparkSource.java

a bug fix suggested by Louis.
@lbergelson I don't know how to add a test.
Without this you'd see
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 45 in stage 9.0 failed 8 times, most recent failure: Lost task 45.7 in stage 9.0 (TID 734, shuang-svdps-ceu-w-1.c.broad-dsde-methods.internal, executor 2): java.nio.file.FileSystemNotFoundException: Provider "gs" not installed
at java.nio.file.Paths.get(Paths.java:147)
at org.broadinstitute.hellbender.engine.spark.datasources.ReferenceFileSparkSource.getReferencePath(ReferenceFileSparkSource.java:53)
at org.broadinstitute.hellbender.engine.spark.datasources.ReferenceFileSparkSource.getReferenceBases(ReferenceFileSparkSource.java:60)
at org.broadinstitute.hellbender.engine.spark.datasources.ReferenceMultiSparkSource.getR …
```

A fix for reading GS:// references from a Spark cluster

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsUnitTest.java

Extracted GenotypeGVCFs engine from GenotypeGVCFs

Issue #5910: Extract engine from GenotypeGVCFs

---

scripts/cnv_cromwell_tests/germline/cnv_germline_case_scattered_workflow.json
scripts/cnv_cromwell_tests/germline/cnv_germline_cohort_workflow.json
scripts/cnv_wdl/cnv_common_tasks.wdl
scripts/cnv_wdl/germline/README.md
scripts/cnv_wdl/germline/cnv_germline_case_scattered_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl

This adds two new tasks that perform QC checks on gCNV output, namely:
- Check that number of events in segments VCFs does not exceed preset value
- Check that not all PCs are used by the model (even if one of the shards fails, the QC status will be negative)
Both tasks output *qc_status.txt file, for each sample and model respectively, and the file will contain string "PASS", or a string describing the fail condition

Added QC metrics to the Germline CNV workflow

---

scripts/m2_cromwell_tests/test_mitochondria_m2_wdl.json
scripts/mitochondria_m2_wdl/AlignAndCall.wdl
scripts/mitochondria_m2_wdl/AlignmentPipeline.wdl
scripts/mitochondria_m2_wdl/ExampleInputsMitochondriaPipeline.json
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

Adds NIO to the SubsetBam task and converts all the MT pipeline WDLs to WDL 1.0. I ran this on one sample in Terra and it worked.

Adding NIO and updating to WDL 1.0 to MT pipeline

---

scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl
scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl

- Substantially improves results on FFPE samples

Enable gc correction by default in somatic cnv panel workflow

---

src/main/java/org/broadinstitute/hellbender/engine/FeatureContext.java
src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
src/main/java/org/broadinstitute/hellbender/engine/FeatureWalker.java
src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
src/main/java/org/broadinstitute/hellbender/engine/IntervalWalker.java
src/main/java/org/broadinstitute/hellbender/engine/ReadWalker.java
src/main/java/org/broadinstitute/hellbender/engine/VariantWalkerBase.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/AnnotateIntervals.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/AnnotationUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_InbreedingCoeff.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_QualByDepth.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_RMSMappingQuality.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_RankSumTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_StrandBiasTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AlleleSpecificAnnotation.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/test/java/org/broadinstitute/hellbender/engine/DummyPlaceholderGatkTool.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/test/FuncotatorTestUtils.java

Addressing @droazen 's outstanding comments from #4947 
Also closes #5988

GnarlyGenotyper tech debt

---

src/main/java/org/broadinstitute/hellbender/tools/ApplyBQSRUniqueArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSparkIntegrationTest.java

Some new arguments have been added to `ApplyBQSRArgumentCollection` and `RecalibrationArgumentCollection` that were not reflected in `ApplyBQSRUniqueArgumentCollection`. This PR brings `ApplyBQSRUniqueArgumentCollection` up to date.

Handle all arguments in ApplyBQSRUniqueArgumentCollection

---

scripts/mutect2_wdl/mutect2.wdl

Reason: With the indentation before the closing bracket, the task Funcotate is ignored by tools such as dxWDL.

Remove the one-space indentation of last line

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngineUnitTest.java

I have tested that this explicitly works on the users data. I decided it was simplest to just check for mis-trimming at the very last stage. I'm a little weary about the change of the locus for the ref context from being the culledVC to being the mergedVC. 
Fixes #5994

Added trimming to the Allele removal code in the genotyping engine

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/FilterMutectCalls.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/Mutect2FilteringEngine.java

@takutosato This fixes two sources of the bug:
* Threshold was equal to the error probability of the worst unfiltered variant, but filtering was based on `errorProbability > threshold - EPSILON`, which ends up filtering this variant.
* Threshold was adjusted *and* filtering parameters were changed on the last pass, which means that error probabilities could shift slightly relative to those used to set the threshold.

fixed Mutect2 bug that overfiltered by one variant

---

src/main/java/org/broadinstitute/hellbender/utils/io/DeleteRecursivelyOnExitPathHook.java

* When running recursive deletion file hooks we now catch all exceptions and log them at DEBUG level instead of letting them propagate.
* This should reduce confusion when test have deletion failures.

Logging exceptions during deletion instead of throwing

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/BasicValidationResult.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutations.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/validation/basicshortmutpileup/ValidateBasicSomaticShortMutationsIntegrationTest.java

@samuelklee This is for you regarding #3884.

refactored table writing in BasicSomaticValidator

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/ArtifactPriorCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModelEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModelEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModelIntegrationTest.java

@takutosato Here's the bug fix I mentioned.  The idea is to use prior pseudocounts in case there are no effective counts from the data.

fixed edge case of small region in  orientation bias model

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/validation/CountFalsePositives.java

by overriding `requiresIntervals()`

CountFalsePositives now requires an intervals file

---

.travis.yml
build.gradle
src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
src/test/resources/org/broadinstitute/hellbender/tools/walkers/MarkDuplicatesGATK/expected.picard-2.15.0.sorted.chr1.1-1K.unmarkedDups.markDuplicate.metrics

* Updating google-cloud-nio   0.81.0-alpha:shaded -> 0.100.0-alpha:shaded
* Fixes #5935

Updating google cloud nio to 0.107.0

---

src/main/java/org/broadinstitute/hellbender/engine/MultiVariantWalkerGroupedOnStart.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/CombineGVCFs.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/FilterAlignmentArtifacts.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
src/test/java/org/broadinstitute/hellbender/engine/MultiVariantWalkerGroupedOnStartUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/FilterAlignmentArtifactsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngineUnitTest.java

Closes #6030.
@takutosato This a complete rewrite of the realignment filter, so I would review `FilterAlignmentArtifacts` and its engine from scratch, not from the diff.
There's still a bit of tuning to be done, but it's already far superior to the old version and I want to be using the release jar as much as possible for MC3.

Assembly-based realignment filter

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionaryIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary/variantsWithDictBadContigLength.vcf

I'm working on an imputation pipeline right now, and the contigs in the returned VCF header don't contain lengths. This fix to UpdateVCFSequenceDictionary allows me to force an update to the VCF's sequence dictionary so I have a valid VCF I can use with the rest of our tools when both --replace and --disable-sequence-dictionary-validation are set to true.

Allow updates to an invalid sequence dictionary in a VCF

---

src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java
src/test/java/org/broadinstitute/hellbender/engine/GatkToolIntegrationTest.java

As a compromise fix, I have added a check to the validation code that asserts the dictionaries actually exist to save ourselves the potential null-pointer exceptions. @droazen 
Fixes #6142

Added check for null sequence dictionaries 

---

src/main/java/org/broadinstitute/hellbender/Main.java
src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKAnnotationPluginDescriptor.java
src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyperEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/util/EvaluationContext.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/util/VariantEvalUtils.java
src/main/java/org/broadinstitute/hellbender/utils/ClassUtils.java
src/main/java/org/broadinstitute/hellbender/utils/help/GATKDocWorkUnit.java
src/main/java/org/broadinstitute/hellbender/utils/help/GATKHelpDoclet.java
src/main/java/org/broadinstitute/hellbender/utils/runtime/ProcessControllerBase.java
src/test/java/org/broadinstitute/hellbender/engine/FeatureManagerUnitTest.java
src/test/java/org/broadinstitute/hellbender/testutils/VariantContextTestUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/sv/utils/SVKmerShortUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/utils/LargeLongHopscotchSetTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/utils/LongBloomFilterTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/utils/LongHopscotchSetTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/StandardCallerArgumentCollectionUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/HistogramUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/hmm/HMMUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/pairhmm/VectorPairHMMUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/recalibration/RecalDatumUnitTest.java

Fix Java 11 deprecation warnings

---

build.gradle

* Expand the way the build.gradle checks if we're in a git repo to also understand git-worktree checkouts
This is useful to me since I've been using `git worktree` to maintain copies of gatk for java 8 and 11 separately.  
Also, I recommend `git worktree`

Don't fail the build if we're in a git worktree folder

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/M2FiltersArgumentCollection.java

Mitochondria mode documentation in FilterMutectCalls was missing a filter that is excluded, as can be seen here: https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/Mutect2FilteringEngine.java#L237

Fix Mitochondria Mode documentation in FilterMutectCalls

---

scripts/m2_cromwell_tests/test_mitochondria_m2_wdl.json
scripts/mitochondria_m2_wdl/AlignAndCall.wdl
scripts/mitochondria_m2_wdl/ExampleInputsMitochondriaPipeline.json
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

Kristen requested some small changes for the mitochondria pipeline. This renames the output vcf with the name of the sample and puts a default value for autosomal_median_coverage (meaning you'll now get the NuMT filter even if you don't provide the actual autosomal coverage). Happy to discuss if that's the right thing to do or if we really want to force people to put a value for autosomal coverage.

Default autosomal coverage and renamed output for mt pipeline

---

scripts/mutect2_wdl/mutect2_pon.wdl

mutect2 WDL and pon WDL had inconsistent input names

---

.travis.yml
build.gradle
src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
src/main/java/org/broadinstitute/hellbender/engine/spark/AssemblyRegionWalkerSpark.java
src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java
src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSparkSource.java
src/main/java/org/broadinstitute/hellbender/utils/Utils.java
src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java
src/main/java/org/broadinstitute/hellbender/utils/read/BDGAlignmentRecordToGATKReadAdapter.java
src/main/java/org/broadinstitute/hellbender/utils/read/GATKReadToBDGAlignmentRecordConverter.java
src/main/java/org/broadinstitute/hellbender/utils/runtime/CapturedStreamOutput.java
src/main/java/org/broadinstitute/hellbender/utils/runtime/ProcessController.java
src/main/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessController.java
src/test/java/org/broadinstitute/hellbender/tools/spark/PileupSparkIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java

Investigate the changes needed to run on Java 11.

Build and test on Java 11

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/BaseGraph.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java

After some painstaking debug work with @tlangs we managed to isolate it to the graphing code and furthermore find what methods in our part of the graph code produce non-determinisitc output. This doesn't address the underlying issue which was that the order in the graph zipping can make a significant difference in the weights of edges in the graph code which effects the found haplotypes. This does however apparently make the haplotype caller outputs more deterministic though this still doesn't quite explain the apparent connection to NIO.
Fixes #6003

Fix non-determinism in KbestHaplotypeFinding/SeqGraphZippingCode

---

src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBUtils.java

Move vid combine protobuf mapping overrides from GenomicsDB ExportConfiguration to Import. Overrides can still be performed via ExportConfiguration, but recommended to modify the mappings during the import phase as not all mappings can be effectively modified during export/queries.
There is a whole bunch of hardcoded allele-specific fields whose vid mappings are hardcoded in GenomicsDB - see https://github.com/GenomicsDB/GenomicsDB/blob/master/src/main/java/org/genomicsdb/importer/Constants.java. There is no harm in specifying the mappings in gatk as well. But, at some point we should move the mappings from GenomicsDB to gatk, as these are gatk-specific annotations.

Cleanup GenomicsDB vid combine protobuf mapping overrides

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/OutputMode.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/StandardCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF.java

- Modified GenotypeGVCFsEngine.OutputMode enum documentation to reflect this change

Renamed OutputMode.EMIT_ALL_SITES to EMIT_ALL_ACTIVE_SITES

---

src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotDenoisedCopyRatios.R
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotModeledSegments.R

I think the erroneous calls to the optparse `make_option` method got ported over accidentally from the original versions of these scripts.  These calls don't cause any issues with optparse 1.3.2 (which is the version currently in the GATK Docker image), but could possibly cause issues with later versions (and might be responsible for an issue noted by @knoblett).

Removed erroneous short argument names in R scripts for CNV plotting.

---

src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/CalculateContaminationIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummariesIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/MergeMutectStatsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/readorientation/LearnReadOrientationModelIntegrationTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/ArgumentsBuilder.java

ArgumentsBuilder in Mutect2 pipeline tool tests

---

scripts/mutect2_wdl/mutect2.wdl

@takutosato See the new comment in the M2 task command for explanation.  This occurred in the Broad blood biopsy pipeline for scatter count of 75, so it's not far-fetched by any means.

Fix an edge case for high scatter count in Mutect2 WDL

---

gatk

` The warning advises users to use equality tests (== and !=) instead`
[bpo-34850](https://bugs.python.org/issue34850)

fix SyntaxWarning while run gatk with python3.8

---

.gitignore

Adding the jenv .java-version file to gitignore so that I'm not annoyed by seeing it in git status.

Add .java-version to gitignore to support jenv users

---

src/main/python/org/broadinstitute/hellbender/gcnvkernel/tasks/inference_task_base.py

gCNV does not fail if the ELBO becomes NaN and just finishes the maximum number of allowed iterations. This check would save some time and lead to less cryptic errors downstream

Assert that ELBO did not become NaN during each step of inference

---

scripts/cnv_wdl/cnv_common_tasks.wdl
scripts/cnv_wdl/germline/cnv_germline_case_scattered_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl

Terra does not allow running a container without docker specified so here is a fix

Added docker to the gcnv QC tasks

---

testsettings.gradle

* Adding forkEvery 5 to cause the test jvm to be restarted every few test classes.
* This might fix a theoretical memory leak causing our builds to fail often.
This might help?

Restart test jvm every few test classes

---

build.gradle
src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionary.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/UpdateVCFSequenceDictionaryIntegrationTest.java

Upgrading htsjdk to 2.21.0.  
This includes a change that relaxes restrictions on loading vcfs with sequence dictionaries that are missing lengths.  This effected one of the tests which I changed a bit.  We could also implement blanket ban on sequence dictionaries with missing lengths in our sequence dictionary validation code, but we currently allow them for sam/bam as far as I can tell and have tests that take them into account.

update htsjdk to 2.21.0

---

build.gradle

* Upating disq 0.3.3 -> 0.3.4
* This release makes use of new features in htsjdk 2.21.0 which were previously part of disq itself.

Update disq to 0.3.4

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/DetermineGermlineContigPloidy.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCalls.java
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/case_denoising_calling.py
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/case_determine_ploidy_and_depth.py
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/cohort_denoising_calling.py
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/cohort_determine_ploidy_and_depth.py
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/segment_gcnv_calls.py

Closes #6235 
This PR allows users to more easily clobber individual theano flags.  This can be used to change the location of the theano compilation directory (see the above issue and #4782 for context).  These flags are set upon import of the theano module; see http://deeplearning.net/software/theano/library/config.html for details.
This solution is a little hacky, hence the code duplication.  Ideally, we'd be able to specify this directory (and potentially other flags) as a parameter to the tools.  As discussed with @cmnbroad, probably the cleanest solution would be to modify the PythonScriptExecutor to allow environment variables to be specified, e.g. via ProcessSettings.  This solution would also cover the initial import of the `gcnvkernel` package for validation purposes, rather …

Added ability to override THEANO_FLAGS environment variable in gCNV tools.

---

src/main/python/org/broadinstitute/hellbender/gcnvkernel/io/io_commons.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/commons.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/model_denoising_calling.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/model_ploidy.py
src/main/python/org/broadinstitute/hellbender/gcnvkernel/tasks/inference_task_base.py
src/main/python/org/broadinstitute/hellbender/setup_gcnvkernel.py
src/test/resources/large/cnv_germline_workflows_test_files/wes-do-gc-contig-ploidy-model.tar.gz
src/test/resources/large/cnv_germline_workflows_test_files/wes-do-gc-gcnv-model-0.tar.gz
src/test/resources/large/cnv_germline_workflows_test_files/wes-do-gc-gcnv-model-1.tar.gz

Closes #4824 (at least for underflow of overdispersion)
Closes #6226 
Closes #6227
Along with some other minor fixes.
I've done some manual testing and this change is most likely harmless, but ideally we'd have some better automated testing to cover this sort of minor model change...  Extremely conscientious users might want to rebuild models just to be safe, which we can mention in the release notes.

Added epsilons to overdispersion in gCNV models to avoid NaNs.

---

src/main/java/org/broadinstitute/hellbender/engine/FeatureManager.java
src/main/java/org/broadinstitute/hellbender/engine/FeatureWalker.java
src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java
src/test/java/org/broadinstitute/hellbender/engine/FeatureInputUnitTest.java
src/test/java/org/broadinstitute/hellbender/engine/FeatureManagerUnitTest.java
src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/VariantsSparkSinkUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java

Fixes https://github.com/broadinstitute/gatk/issues/6161. Requires an htsjdk update.

Cloud-enable IndexFeatureFile and change input arg name from -F to -I.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/utils/read/Fragment.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

@takutosato We have seen samples with a handful of cases and I would rather not force users to run with `--independent-mates` just to avoid an error at a few sites.

Mutect2 warns but does not fail when three or more reads have the same name

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
src/main/java/org/broadinstitute/hellbender/utils/collections/IndexedSet.java
src/main/java/org/broadinstitute/hellbender/utils/collections/Permutation.java
src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleList.java
src/main/java/org/broadinstitute/hellbender/utils/genotyper/IndexedAlleleList.java

I fixed some typos/intellij warnings in the AlleleSubsettingUtils and related files.

Fix some typos in the allele subsetting code

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/AlleleFraction.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/AlleleFractionGenotypeAnnotationUnitTest.java

Fixes bug in AlleleFraction annotator when run on multisample vcf.  In this situation, the AFs calculated for the final (right-most) sample in the vcf are used for all samples, instead of correctly putting the AFs associated with each sample in that sample's genotype annotations.  
Bug came from user on forum: https://gatkforums.broadinstitute.org/gatk/discussion/24579/plz-check-my-result-from-variantannotator/p1

Fix to Allele Fraction annotation bug

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/ContaminationModel.java

I found a sample that fails when CalculateContamination is run.
The exception I get is:
org.apache.commons.math3.exception.TooManyEvaluationsException: illegal state: maximal count (20) exceeded: evaluations
at org.apache.commons.math3.optim.BaseOptimizer$MaxEvalCallback.trigger(BaseOptimizer.java:242)
at org.apache.commons.math3.util.Incrementor.incrementCount(Incrementor.java:155)
at org.apache.commons.math3.optim.BaseOptimizer.incrementEvaluationCount(BaseOptimizer.java:191)
at org.apache.commons.math3.optim.univariate.UnivariateOptimizer.computeObjectiveValue(UnivariateOptimizer.java:148)
at org.apache.commons.math3.optim.univariate.BrentOptimizer.doOptimize(BrentOptimizer.java:225)
at org.apache.commons.math3.optim.univariate.BrentOptimizer.doOptimize(BrentOptimizer.java:43)
at …

Increase number of iterations in calculateContamination to 30

---

src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/model_ploidy.py

@samuelklee Could you review please?

Fixed model parameter assignment typo in gCNV ploidy model

---

src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java
src/main/java/org/broadinstitute/hellbender/utils/clipping/ReadClipper.java
src/main/java/org/broadinstitute/hellbender/utils/read/ArtificialReadUtils.java
src/test/java/org/broadinstitute/hellbender/utils/clipping/ClippingOpUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/clipping/ReadClipperUnitTest.java

Problem was ocurring in the presence of insertions and deletions. fixes #6139
1. Changed ReadClipper unit tests:
- The tests in many cases assumed that the unclipped alignment locations do not    change when the read is clipped. This is not true: for example if start for cigar
1M1I3M is 100, the unclipped start for 2H3M is 99. All assertUnclipped calls were
removed
- Alignment now check that the read length remains to be consistent with the CIGAR, that the aligned bases span are consistent with the CIGAR and that the number of clipped bases from the read is consistent with the requested clipping
2. Hard clipping in ClippingOps was buggy, thus we introduced new tests for it.
3. Text was refactored for readability
4. Clipping in ClippingOps did not treat insertions and deletions in the …

 Fixed a bug in hardClipCigar function that caused incorrect cigar calculation

---

src/main/java/org/broadinstitute/hellbender/engine/VariantLocusWalker.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java

Closes #6239.
@ldgauthier @bbimber Here's what I settled on:
* `GenotypeGVCFs` gets a new argument for force-genotyping intervals.  This is parsed exactly like any other interval argument, so the following are all valid:
```
--force-output-intervals 20:45000
--force-output-intervals intervals.interval_list
--force-output-intervals dbsnp.vcf
--force-output-intervals 20:1000-2000 --force-output-intervals 20:3000-4000
```
* Only the sites matter, so if a VCF is given the alleles are ignored.
* If the site is absent in the input gVCF, there is no output.  No data in yields no data out.
* If the site overlaps a record in the input gVCF, there is output, regardless of whether the record is a variant, a REF block, or a spanning deletion.

Added a force output sites argument to GenotypeGVCFs

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java

Closes #6302.  @bhanugandham would you mind reviewing this?

made callable sites a Long to avoid integer overflow

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/FilterAlignmentArtifacts.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMDestination.java
src/test/resources/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriter/expected/fromHeaderSAM.sam
src/test/resources/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriter/expected/testSAM.sam

Closes #6287.
@takutosato I'm just doing what David Roazen told me to do in #6287.

uniqify PG IDs in FilterAlignmentArtifacts

---

src/main/resources/org/broadinstitute/hellbender/tools/copynumber/case_denoising_calling.py
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/cohort_denoising_calling.py
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/cohort_determine_ploidy_and_depth.py

See https://gatkforums.broadinstitute.org/gatk/discussion/24650/cohort-mode-of-germlinecnvcaller-filenotfounderror.

Copy temporary files early in gcnvkernel to avoid inadvertent temporary directory cleanup.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/stratifications/AlleleFrequency.java
src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.index.template.html

The current top-level index document has a bogus tool category called "tools" in it (see https://software.broadinstitute.org/gatk/documentation/tooldocs/current/). This is created by the  `@DocumentedFeature` annotation on the AlleleFrequency stratifier class. We don't actually have a category for this, and most are not documented. If at some point we want to add those, we can do so with a real category, but for now this removes the annotation.
There are also some unnatural line breaks in the index, which are removed here. The html doc could use some more maintenance cleanup, but this fixes those two obvious issues.

Fix some GATK doc issues

---

src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantPipelineTest.java

See https://github.com/broadinstitute/gatk/issues/6307. This is causing quite a few branches to fail intermittently.

Disable CNNVariantPipelineTest.testTrainingReadModel until failures are resolved.

---

build.gradle

* Updating disq 0.3.4 -> 0.3.5
* This fixes a bug which caused it to effectively ignore the sbi index.
* Also added the sonatype snapshot repository to our build to let us resolve disq snapshots in the build.

Update disq to 0.3.5

---

src/main/java/org/broadinstitute/hellbender/engine/filters/ReadGroupBlackListReadFilter.java
src/test/java/org/broadinstitute/hellbender/engine/filters/ReadGroupBlackListReadFilterUnitTest.java

Fixes https://github.com/broadinstitute/gatk/issues/6299. Also removed obsolete code to populate read group filters from a file.

Propagate read group filters in ReadGroupBlackListReadFilter.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEval.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/CountVariants.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/MultiallelicSummary.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/VariantEvaluator.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/VariantSummary.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/stratifications/manager/StratificationManager.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEvalIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/TestEvaluatorWhichRequiresReferenceButDoesntSayItDoes.java

* Fixes an NPE that happened when using certain evaluators with VariantEval and not specifying a reference or intervals
* Fixes https://github.com/broadinstitute/gatk/issues/6212

Fix NPE in VariantEval when run with no intervals/reference

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/TandemRepeat.java

I don't think this is true anymore.  We've been using it successfully with gatk4's `HaplotypeCaller`.  I'd love some confirmation, and then the docs could be updated.

TandemRepeat works with HaplotypeCaller

---

src/main/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilter.java
src/test/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilterUnitTest.java

Added logic for generating a simplified read filter output in the case of multiple filters joined by AND
Fixes #3520

Modified ANDed read filter output message for readability

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCalls.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVIntervalVariantComposer.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVSegmentVariantComposer.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVVariantComposer.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCallsIntegrationTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/VariantContextTestUtils.java

Tests are "failing" with the "code is too big" error on the CNN testTrainingReadModel.
I had to update my conda yml template to use a newer Tensorflow @cmnbroad found -- should I add that here too?

Index output VCFs for GCNV postprocessing

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/CountNs.java
src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtils.java
src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/CountNsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReferenceConfidenceModelUnitTest.java

Closes #6336.  @fleharty could you verify that this branch fixes the error and review?  This uses code similar to other annotations that find an offset into a read's bases and are not buggy, as far as we know.

fixed out-of-bounds error in CountNs annotation

---

src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBOptions.java
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java

Not sure if this will resolve what is reported here: https://github.com/broadinstitute/gatk/issues/6275#issuecomment-574329688
My guess is that the user's issue is being caused by an extremely large String that Java can't handle...this PR passes along some parameters from GenotypeGVCFs (`max-alternate-alleles` and `max-genotype-count`) to GenomicsDB...which will hopefully result in us not having to deal with the large String.

[WIP] Passing max alternate alleles and max genotypes from GenotypeGVCFs to GenomicsDB. 

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeAlleleCounts.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeAlleleCountsUnitTest.java

GenotypeAlleleCount's toString function was broken, leading to a misleading debugging information showing up in the debugger
This PR fixes the bug and adds tests for toString output.

Yf fix GenotypeAlleleCount's toString

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadErrorCorrector.java

Actually output the corrected bases in the ReadErrorCorrector

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java

Closes #6370 
@droazen How do you feel about scrapping this argument?

removed the deprecated and obsolete use-new-af-calculator argument

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java

Closes #6344, I think.  @takutosato can you review this?

fixed error in RealignmentEngine due to inclusive vs exclusive ends

---

src/main/java/org/broadinstitute/hellbender/utils/runtime/ScriptExecutor.java

Issue a warning message when local script executor process receives SIGKILL signal. Addresses https://github.com/broadinstitute/gatk/issues/6362.

Add script executor error message for SIGKILL exit code 137.

---

src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java

We shouldn't call toAbsolutePath on our Paths since it resolves paths that are not already absolute to a (implementation dependent) default location, which will often return an incorrect result for non-default file systems.
This is the cosmetic part of the fix for https://github.com/broadinstitute/gatk/issues/6348. The actual fix requires an htsjdk that has https://github.com/samtools/htsjdk/pull/1449.

Fixes for IndexFeatureFile error reporting.

---

scripts/gatkcondaenv.yml.template

Fixes https://github.com/broadinstitute/gatk/issues/6396.

Pip install and pin numpy version.

---

scripts/docker/gatkbase/install_R_packages.R

Its been [2.5 days](https://cran.r-project.org/mirmon_report.html).

Temporarily remove dead Berkeley mirror to unblock builds.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/fasta/FastaReferenceMaker.java

* We now check if the writer is null before trying to close it.
* Fix for https://github.com/broadinstitute/gatk/issues/6434

fix an NPE in FastaReferenceMaker

---

src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java

* CigarUtils.isGood() which is used in GoodCigarReadFilter did a pointlessly expensive copy and sort operation.  Replaced it with a reversing list view which avoids a copy and sort.

Avoid a copy and reverse operation in CigarUtils.isGood

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_QualByDepth.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_QualByDepthUnitTest.java

Sometimes NON_REF gets a zero and sometimes it's empty.  This seems isolated to a much older version of ReblockGVCF, but that was what we were running for production pipeline tests.
@droazen I'd like this to go into this week's release

Parse combined AS_QUALapprox values from older reblocked GVCFs properly

---

src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java
src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java
src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
src/test/java/org/broadinstitute/hellbender/utils/GenomeLocParserUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java

Fixes https://github.com/broadinstitute/gatk/issues/6371.

Trim intervals loaded from interval files.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/clustering/SomaticClusteringModel.java

@takutosato This error should be thrown once detected.  Currently it leads to a divide-by-zero downstream, which only throws an error even further downstream when the NaN shows up.

Error message for no callable sites in M2

---

src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java

Closes #3672.
@ldgauthier The ADs, GTs, and PLs were inconsistent.

fixed incoherent unit test cases in allele subsetting utils

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticLikelihoodsEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticReferenceConfidenceModel.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

Closes #5561.
@ahaessly This dramatically speeds M2 mito GVCF mode.

Sped Mutect2 reference confidence model with fast likelihoods model

---

README.md
build.gradle

* You can now avoid the check for a git directory during build by manually specifying a version number
ex:  ./gradlew -DversionOverride=someVersionNumber
* Fix for #6395

Making .git directory optional during build

---

src/main/java/org/broadinstitute/hellbender/utils/read/GATKRead.java
src/test/java/org/broadinstitute/hellbender/utils/read/GATKReadAdaptersUnitTest.java

Closes #1550.  @SHuang-Broad do you still want this?

wrote getPairOrientation method for GATKRead

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java

* It no longer modifies state.  Closes #2537
* Upstream deletions are only recorded once they definitely will be emitted.  Closes #6031 
@ldgauthier Here's a `GenotypeGVCFs` bug fix for you.
@tfenne Your suspicion was correct.

improved checking for upstream deletions in GenotypingEngine

---

src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
src/main/java/org/broadinstitute/hellbender/engine/spark/GATKSparkTool.java
src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ValidateVariants.java
src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java
src/main/java/org/broadinstitute/hellbender/utils/read/ReadUtils.java

Closes #1288.  Closes #1289.
@takutosato Obsessively closing old GATK issues.

Better error messages for missing contigs in reference

---

src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java

The type of the method changed at some point and the references were never updated.

Fix a broken set of javadoc references in FeatureDataSource

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/ReadOrientationFilter.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/ReadOrientationFilterUnitTest.java

Mutect2 can filter MNVs with orientation bias

---

src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java
src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java
src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfCodec.java
src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfFeature.java
src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfFeatureBaseData.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/DataProviderForExampleGencodeGtfGene.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodecUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodecUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfCodecUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/test/FuncotatorTestUtils.java
src/test/resources/large/funcotator/e_coli.MG1655.expected_output.vcf
src/test/resources/large/funcotator/ecoli_ds/gencode/ASM584v2/gencode.config

This will allow the ENSEMBL GTF codec to decode any ENSEMBL GTF file that they host.
Fixes #6488

Making ENSEMBL GTF Codec more permissive

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/Haplotype.java
src/main/java/org/broadinstitute/hellbender/utils/read/AlignmentUtils.java
src/test/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/read/AlignmentUtilsUnitTest.java

@takutosato Two quick edge cases and new unit tests.  These were exposed when fixing other bugs.

Fix edge case when haplotypes have leading insertion after trimming

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/ModelSegments.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/segmentation/AlleleFractionKernelSegmenter.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/segmentation/CopyRatioKernelSegmenter.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/segmentation/MultidimensionalKernelSegmenter.java

Noticed this minor typo while doing some refactoring for a new feature branch.  The issue is that the MultidimensionalKernelSegmenter incorrectly uses `maxNumChangepointsPerChromosome = maxNumSegmentsPerChromosome`, when it should be using `maxNumChangepointsPerChromosome = maxNumSegmentsPerChromosome - 1` like the CopyRatioKernelSegmenter and AlleleFractionKernelSegmenter do. @fleharty mind reviewing?

Fixed an off-by-one segmentation argument in ModelSegments.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java

Currently specifying the `--correct-overlapping-quality` argument actually turns off the correction of base qualities for overlapping read-mate pairs, which seems counterintuitive.  This PR changes the argument name to be `--do-not-correct-overlapping-quality`, which matches the affect of specifying the argument.
Also annotates the option as advanced, and adds a small amount of documentation.

Invert correct-overlapping-quality argument 

---

src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceMultiSparkSource.java
src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceSparkSource.java
src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java

Another issue that came up on the URI migration branch. The implementation of this method declares that only the `ReferenceTwoBitSparkSource` implementation of `ReferenceSparkSource` is broadcastable, but the method is unused, and there are tools with tests (`CpxVariantReInterpreterSparkIntegrationTest`) that broadcast both the File and Hadoop implementations. So we should either take this, or fix the callers to be more discriminating.

Remove unused isCompatibleWithSparkBroadcast method.

---

scripts/mutect2_wdl/mutect2_pon.wdl
src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervalsIntegrationTest.java

@fleharty This should resolve Sachet's issue by allowing arbitrarily much scattering, reducing the memory required by `GenomicsDBImport`.

more control over scattering genomics DB in M2 pon wdl

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/MultivariateGaussian.java

The smallest value I see on my Mac is O(1e-36), but on whatever processor I'm getting from PAPI v1, one of the determinants is O(1e-101), which is less than the previous epsilon of 1e-100.

Decrease epsilon so production exome JG tests pass

---

src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.template.html

* Now docs won't include null, "", or [] in the default value list.
This is one of the changes I mentioned on the call.

Change doc template to no print null missing values.

---

scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
src/main/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotDenoisedCopyRatios.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotModeledSegments.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlottingUtils.java
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/CNVPlottingLibrary.R
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotDenoisedCopyRatios.R
src/main/resources/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotModeledSegments.R
src/test/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotDenoisedCopyRatiosIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/plotting/PlotModeledSegmentsIntegrationTest.java

Closes #6391.
Closes #5748.
Note that the *.denoisedLimit4.png output has been removed from the PlotDenoisedCopyRatios tool and the corresponding WDL task.  The default behavior has changed slightly, in that the remaining *.denoised.png output is now delimited to maximum copy ratio = 4.0 (instead of covering the entire range in the data).  @fleharty @droazen we may want to mention this in the release notes.

Exposed maximum copy ratio and point size for CNV plotting tools.

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/BaseFuncotatorArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/DataSourceFuncotationFactory.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotateSegments.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/vcf/VcfFuncotationFactory.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactory.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactory.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/genelistoutput/GeneListOutputRenderer.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/genelistoutput/GeneListOutputRendererUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRendererUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/test/FuncotatorTestUtils.java

- Added `--min-num-bases-for-segment-funcotation` parameter to Funcotator.
This will allow for segments of length less than 150 bases to be
annotated if given at run time (defaults to 150 bases to preserve
previous behavior).
- Added miles of piping to support new parameter.
- Added test to ensure that the logic for this is adhered to in the
output renderer where the UserError was being thrown before
(GeneListOutputRenderer).
Fixes #6575

Added a new FuncotateSegments parameter for minimum segment length.

---

src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/HostAlignmentReadFilter.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilter.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilterArgumentCollection.java
src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/HostAlignmentReadFilterTest.java

Adds an argument to PathSeq filtering that lets users specify any contigs that should be ignored. This is useful for BAMs aligned to hg38, which contains the Epstein-Barr virus (chrEBV).

Ignore specified contigs for pre-aligned BAMs in PathSeq

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java

update CreateSomaticPanelOfNormals javadoc

---

src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java

As @droazen and I have been investigating, providing the `--gcs-project-for-requester-pays` argument when accessing buckets where the user does not have storage.bucket.get permission will cause failures.  This clarifies the argument usage.

Arg clarification for requester pays to avoid confusion and failures

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervalsIntegrationTest.java

SplitIntervals originally named files with 4-digit padding, but then we exceeded 10,000 shards in production.  This should work forever.

SplitIntervals dynamic zero padding in filenames

---

src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java
src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoodsUnitTest.java

Closes #6586.  @droazen 
`AlleleLikelihoods` caches the evidence-to-index `Map`.  The previous implementation tried to update this map on the fly whenever evidence was removed.  The new approach is to simply invalidate the cache and allow the existing code to generate it to run later.
I don't expect this to cause performance problems for a few reasons:
1.  It only applies when we're doing contamination downsampling.
2.  It may save time whenever evidence is removed and we don't need the evidence-to-index map later.
3.  Regenerating the cache is O(N), but so is updating on-the-fly even when only one read is removed.

Fixed bugs and simplified AlleleLikelihoods evidence-to-index cache

---

src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSource.java
src/test/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSourceUnitTest.java

This fixes two issues discovered while testing my URI migration branch:
- ReadsSourceSpark.getHeader doesn't propagate the reference at all when a CRAM file input resides on GCS, so it always results in a "no reference was provided" error, even when a reference was provided.
- ReadsSourceSpark.checkCramReference always tried to create a Hadoop Path object for the reference no matter what file system it lives on, which fails when using a reference on GCS.

Fix ReadsSparkSource CRAM code paths.

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/DetermineGermlineContigPloidy.java
src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/model_ploidy.py

I ran a couple of tests - in case of single contig case the ploidy calls correspond to most likely apriori ploidies. In the case of multiple contigs there is no numerical changes to inference whatsoever.

DetermineGermlineContigPloidy can now process interval lists with a single contig

---

build_docker.sh
scripts/pathseq/wdl/README.md
scripts/pathseq/wdl/pathseq_pipeline.wdl
scripts/pathseq/wdl/pathseq_pipeline_template.json
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSBwaArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSBwaUtils.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSFilterArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqFilterSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqScoreSpark.java
src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSBwaUtilTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqBwaSparkIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/pathseq/PathSeqPipelineSparkIntegrationTest.java

This new PathSeq WDL redesigns the workflow for improved performance in the cloud. Downsampling can be applied to BAMs with high microbial content (ie >10M reads) that normally cause performance issues. 
Other improvements include:
* Removed microbial fasta input, as only the sequence dictionary is needed.
* Broke pipeline down to into smaller tasks. This helps reduce costs by a) provisioning fewer resources at the filter and score phases of the pipeline and b) reducing job wall time to minimize the likelihood of VM preemption.
* Filter-only option, which can be used to cheaply estimate the number of microbial reads in the sample.
* Metrics are now parsed so they can be fed as output to the Terra data model.
* CRAM-to-BAM capability
* Updated WDL readme
* Deleted unneeded WDL json …

PathSeq WDL overhaul

---

src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortSamSparkIntegrationTest.java

* Disabling SortSamSparkIntegrationTest.testSortBAMsSharded()
* This test is failing in master because of a disq bug.
* This should be re-enabled when https://github.com/broadinstitute/gatk/issues/5881 is fixed.

Disable SortSamSparkIntegrationTest.testSortBAMsSharded()

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/TandemRepeat.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java

@fleharty Here is a quick M2 and HC edge case bug for you.
In the edge case where an alt haplotype starts with an indel, and hence the variant context start is one base before the assembly region due to padding a leading matching base, there was a problem.  The variant start was before the reference context window (since in this part of the code the reference context window is pegged to the assembly region, which caused problems in the lines
```
final int startIndex = vc.getStart() - ref.getWindow().getStart();
final byte[] refBasesStartingAtVariantLocus = new String(refBases).substring(startIndex).getBytes();
```
The fix is for `refBasesStartingAtVariantLocus` to exclude the padding base, which as you can see was done previously in the line
```
final String refBasesStartingAtVCWithoutPad …
```

fixed bug in tandem repeat annotation

---

build.gradle

* This includes major improvements to the cram code.
* htsjdk 2.21.2 -> 2.22.0
* picard 2.21.9 -> 2.22.8
* disq 0.3.5 -> 0.3.6
* spark 2.4.3 -> 2.4.5

Update versions of htsjdk/picard/disq

---

src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortSamSpark.java

* A log message in SortSamSpark was using the wrong placeholder for inserting text so the message was printing
the literal characters %d instead inserting the correct value.  Now it puts in a number.

Fix typo in log message.

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/PostprocessGermlineCNVCalls.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/arguments/CopyNumberArgumentValidationUtils.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervalsIntegrationTest.java

This implements suggestion #2 proposed by @samuelklee from issue #5852

FilterIntervals now filters out any singleton intervals

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandOddsRatio.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_StrandOddsRatio.java

Fixes https://github.com/broadinstitute/gatk/issues/6599. This seems to work (see temporary commit with resulting html files). Note sure if there is a better way. @ldgauthier any suggestions ?

Fix equation rendering in annotation doc.

---

build.gradle
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBOptions.java
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBUtils.java
src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java

1. Add new arg `genomicsdb-shared-posixfs-optimizations` to help with shared posix filesystems like NFS and Lustre. This turns on `disable file locking` and for GenomicsDB import it minimizes writes to disks. The performance on some of the gatk datasets for the import of about 10 samples went from 23.72m to 6.34m on NFS which was comparable to importing to a local filesystem. Hopefully this helps with Issue #6487 and #6627. Also, fixes Issue #6519.
2. This version of GenomicsDB also uses pre-compression filters for offset and compression files for new workspaces and genomicsdb arrays. The total sizes for a GenomicsDB workspace using the same dataset as above and the 10 samples went from 313MB to 170MB with no change in import and query times. Smaller GenomicsDB arrays also help with …

Move to GenomicsDB 1.3.0 and add support for shared posixfs optimizations

---

src/test/java/org/broadinstitute/hellbender/tools/HtsgetReaderIntegrationTest.java

Re-enable tests for htsget now that the reference server is back to a stable version
* Some tests were disabled due to issues with the htsget reference server, now that it's back to running an older stable version
the tests which work on that version are re-enabled.
* Partial fix for #6640 another commit will be needed when the server is upgraded to support fields/tags
The field test had to be disabled because it doesn't seem like the current server version supports the parameter correctly.

Re-enable htsget tests

---

build.gradle

* A previouus change left a reference to an uninitialized property in build.gradle.
This caused a crash when trying to produce an error message warning that the JDK was not found.
Ex: Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'requiredJavaVersion' for root project 'gatk' of type org.gradle.api.Project
*  Fix the crash by removing the reference to the missing property.

Fix crash when building with a JDK instead of a JRE

---

src/main/resources/org/broadinstitute/hellbender/utils/recalibration/BQSR.R

* Fix a crash in the BQSR.R script by specifying stringsAsFactors = TRUE
* fixes https://github.com/broadinstitute/gatk/issues/6650

Fix crash in BQSR R script

---

src/test/java/org/broadinstitute/hellbender/utils/help/DocumentationGenerationIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/help/TabCompletionIntegrationTest.java

The tab completion integration test wasn't actually emitting any output because the classpath contained a list of class names (basenames only, without the ".class" extension), so no work units were ever created. This PR:
- changes the classpath to use package names that contain CLPs instead of class names
- runs the javadoc in the current JVM (which makes debugging the test so much easier...)
- adds an Assert to ensure the javadoc process succeeds
I made the latter change to the doc gen smoke test as well, to make debugging easier.

Fix tab completion tests.

---

build.gradle

* Updating htsjdk 2.22.0 -> 2.23.0
* This fixes https://github.com/broadinstitute/gatk/issues/6664

Update htsjdk to 2.23.0

---

src/test/java/org/broadinstitute/hellbender/tools/IndexFeatureFileIntegrationTest.java

Fixes https://github.com/broadinstitute/gatk/issues/5838.

Re-enable IndexFeatureFile test for uncompressed BCF.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CoverageOutputWriter.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CoverageUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/DepthOfCoverageStats.java

Running with default arguments locally the runtime (for a WGS full chr15) drops from ~8.9 minutes to ~4.7 minutes after this patch. If I had to peg something else to optimize it would be replacing CSVWriter which seems to be somewhat slow but I can be contented that this tool is reasonably fast when nothing pathological is being triggered.

Optimized DepthOfCoverage

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java

* There was an "optimization" put in place in SelectVariants which accidentally added a quadraticly scaling check on the genotypes.
* This keeps the optimization but makes it linear instead of quadratic on the number of samples.
* On one example with several thousand samples there was a speed up from ~5 minutes to .1 minutes.

Fix a performance regression in SelectVariants

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/MutectReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssemblerUnitTest.java

This seems to resolve the issue (which I had no problem reproducing) locally. Interestingly when I run the test suite locally I get test failures here but apparently we never caught this on travis. There must be something different about the tests on travis... I am happy for advice as to how to write a test for this fix though because the error seems to be occurring under a dizzying array of spark/hadoop internal serialization code and I'm not sure how to test that properly. 
Fixes #6513 #6738

Fixed concurrent modification exception for local runs of HapltoypeCallerSpark 

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotateSegments.java

Discovered by running the autogenerated tests for autogenerated WDL.

Use an inital value for FuncotateSegments MAPPING_FULL_NAME that the CLP can mutate.

---

scripts/cnv_wdl/cnv_common_tasks.wdl
scripts/cnv_wdl/germline/cnv_germline_case_scattered_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl

* Modifies gCNV WDLs to improve Cromwell performance when running on a large number of intervals, as in WGS
* Adds optional `disabled_read_filters` input to `CollectCounts`
* Enables GCS streaming for `CollectCounts` and `CollectAllelicCounts`

Germline CNV WDLs for WGS

---

scripts/mitochondria_m2_wdl/AlignAndCall.wdl
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

@ahaessly Could you please take a look at this? We had a request to change this argument which wasn't previously possible since it was hardcoded into the WDL task. Ideally I'd like to expose all of the arguments but even wiring this one through the imported WDL was annoying. I tried making it an input to the task with a value like this:
```
task M2 {
input {
Int max_reads_arg = 75
}
...
```
which looks a lot cleaner (don't have to make sure you wire it through from the main inputs), but when I looked in Terra it didn't actually expose the argument (I'm assuming because the M2 task is in a sub-workflow). Any thoughts on how to make this better so I can expose everything? Or is this the best way to do that at the moment?

Exposes an argument in the mitochondria WDL

---

src/main/java/org/broadinstitute/hellbender/utils/read/SAMRecordToGATKReadAdapter.java

* Add contig and start position to error message in setMatePosition
* Extract the check to a shared method with setPosition so it's not inconsistent
* Improves the unhelpful error reported in https://github.com/broadinstitute/gatk/issues/6776

Improve error message in GATKRead.setMatePosition

---

src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java

Documentation change for tmp dir in example command - GenomicsDB tool docs

Fix typo in --tmp-dir argument in GenomicsDB docs

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java

Documentation change  for tmp dir in example command - GenotypeGVCFs

Fixed typo in --tmp-dir argument in the GenotypeGVCFs docs

---

src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegion.java
src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
src/test/java/org/broadinstitute/hellbender/engine/AssemblyRegionUnitTest.java

* Replacing some cases of NPE with IllegalArgumentException with a clear message.
This should help clarify the issue we talked about at the meeting today if it comes up again.  I can't remember what the ticket was to link to though.

Improving exception messages in AssemblyRegion

---

README.md

Updated README to state that only 64-bit Linux distributions are supported. Made this edit under the Python dependencies section. Fix issue #6786

Updated README to mention that macOS is not supported at this time.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java

@samuelklee Here's the small adjustment I mentioned in our discussion this morning.

small tweak to M2's callable sites count

---

src/test/java/org/broadinstitute/hellbender/tools/HtsgetReaderIntegrationTest.java

Workaround https://github.com/broadinstitute/gatk/issues/6803. Temporarily disabling tests until this is resolved.

Temporarily disable HtsgetReader tests.

---

src/main/java/org/broadinstitute/hellbender/tools/AnalyzeSaturationMutagenesis.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/AlignmentInterval.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/ContigAlignmentsModifier.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/BaseQualityRankSumTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/MutectReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/AdaptiveChainPruner.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/main/java/org/broadinstitute/hellbender/utils/Tail.java
src/main/java/org/broadinstitute/hellbender/utils/read/CigarUtils.java
src/main/java/org/broadinstitute/hellbender/utils/read/ClippingTail.java
src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/TestUtilsForAssemblyBasedSVDiscovery.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/ChainPrunerUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/read/CigarUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/read/ReadUtilsUnitTest.java

@jamesemery This fixes the case you found, hopefully bringing us closer to turning on linked de Bruijn graphs.  I will start testing M2.  If you test in HC, continue to keep in mind that adaptive pruning is not default.
This change will be most important for rare complex graphs and in combination with junction trees but I did see modest improvements to indel sensitivity even with the old assembly.

Make adaptive pruner smarter in complex graphs

---

src/main/java/org/broadinstitute/hellbender/tools/HtsgetReader.java

Failures now include the url:
`org.broadinstitute.hellbender.exceptions.UserException: Invalid request https://htsget.ga4gh.org/reads/A1-B000168-3_57_F-1-1_R2.mus.Aligned.out.sorted.bam?referenceName=chr1&start=23999999&end=25000000, received error code: 404, error type: NotFound, message: The requested resource could not be associated with a registered data source
`

Report target uri in exceptions thrown by HtsgetReader.

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayCalculateMetrics.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/GenotypeCountsSchema.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ExcessHet.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyperEngine.java

Pulls down a temp table of genotype counts, calculates excess het and call rate and writes them to a tsv for future upload.

Tool for arrays QC metrics calculations

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/BasicArrayData.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ExtractCohortBQ.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/GT_encoding.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/RawArrayFieldEnum.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/RawArrayTsvCreator.java

remove compressed data, change GT to single char

ah update array extract tool

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/segmentation/KernelSegmenter.java

This seems to be a simple typo. The minimal data to calculate the segmentation cost should be `2 * windowSize`, rather than `windowSize`, as the error message indicates.
In the current logic, the segmentation cost at a particular point is calculated as the difference between the sum of costs of two windows to the left and right of that point and the cost of a big window of size `2 * windowSize`. If the # of the data points is less than the `2 * windowSize`, the cost for the full window will be wrong in the circular buffer representation; it will get the wrong cost of a window of size `2 * windowSize - data_size`, instead.

Fix typo in KernelSegmenter

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/CommonCode.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayCalculateMetrics.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/GenotypeCountsSchema.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/ProbeQcMetrics.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/ProbeQcMetricsSchema.java

The docs claim that the HWE in htsjdk is a two-sided test, so this is actually what we want for arrays.

Switch from ExcessHet back to HWE for array pipeline

---

.travis.yml
scripts/variantstore_cromwell_tests/README.md
scripts/variantstore_cromwell_tests/import_array_manifest_test.json
scripts/variantstore_cromwell_tests/local-with-gcs.conf
scripts/variantstore_cromwell_tests/run_variantstore_wdl.sh
scripts/variantstore_wdl/ImportArrayManifest.wdl
scripts/variantstore_wdl/README.md
scripts/variantstore_wdl/schemas/manifest_schema.json
src/test/resources/org/broadinstitute/hellbender/tools/variantdb/arrays/tiny_manifest.csv

I moved the WDL for importing the array manifest from the variantstore repo and added a test. The test here only checks that the WDL succeeded, it doesn't look a the results (yet). It's ingesting the manifest to a dataset with a 7 day TTL, so the tables eventually get cleaned up. That might be too long for this case, since it adds a table each time the test is run (so on push and PR). 
I plan to add more of the "end-to-end" pipeline with more testing in the future using a similar scheme, so welcome feedback on the structure.

Moving the WDL for importing array manifest to BQ

---

build.gradle

This was an issue with propagating polymorphic std::exception code from the native library's logger utility and has been fixed in the [1.3.2 release ](https://mvnrepository.com/artifact/org.genomicsdb/genomicsdb/1.3.2) of the GenomicsDB library. Also note that using java option `GATK_STACKTRACE_ON_USER_EXCEPTION` with gatk will also output a C/C++ limited stacktrace as requested by @lbergelson.

Get GenomicsDB Version 1.3.2 for better propagation of native exceptions and output a limited stacktrace

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java

This PR updates the `--use-posteriors-to-calculate-qual` mode to properly treat the star allele as a non-variant (for that site) allele. With this change, if a spanning deletion is present, it is treated as a non-variant allele for that site, and the posterior of no variant allele being present becomes the sum of the posteriors of all genotypes composed of combinations of the reference allele and the star allele.

Fix treatment of star alleles in use genotype posteriors for qual mode

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/StrandBiasUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_StrandBiasTestUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/StrandBiasUtilsUnitTest.java

revert code back to previous code that did not throw NPE. Add 2 unit tests to guard against this.

ah-6766-NPE

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/SplitIntervals.java

Thanks to Sophie for pointing this out.

Docs typo in SplitIntervals example command

---

src/main/java/org/broadinstitute/hellbender/utils/read/AlignmentUtils.java
src/test/java/org/broadinstitute/hellbender/tools/LeftAlignIndelsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/read/AlignmentUtilsUnitTest.java

Closes #6765.  @fleharty can you review this fix?

Fix a bug with soft clips in LeftAlignIndels

---

.dockstore.yml

Added .dockstore.yml file to the root directory of the gatk repo to allow automatic syncing to occur with workflows in [Dockstore](https://dockstore.org/organizations/BroadInstitute/collections/GATKWorkflows). 
**Problem:** 
The GATK workflows are currently organized in [Dockstore](https://dockstore.org/organizations/BroadInstitute/collections/GATKWorkflows), maintenance of the workflows requires manually refreshing the workflow profile in Dockstore in order to view the latest releases of the workflows. Also some workflows like germline_cnv fails to sync because Dockstore has trouble handling the number of branches/tags in the gatk repo.
**Solution:** 
Adding the dockstore yml file allows this syncing to happen automatically whenever there is a push to the gatk repo. This may also help …

Added dockstore yml file with workflow description

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2EngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

Closes #6724 
Closes #4885
Closes #3012 @takutosato The 1/3 factor fixes some missed low-AF calls reported on the forum.  In effect our active region code was subtracting 5 from alt base qualities.
In addition to recouping some sensitivity it does also increase false positives in DREAM by a bit.  However, I looked at these and without exception they were judgment calls that should be considered active, even if they are artifacts.  If we made a PoN with the new changes to M2 I'm sure it would catch most of these.

separate alleles in M2 isActive and account for one-third substitution factor

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java

A user found that a real event in his data was missing with the default FilterIntervals args: https://gatk.broadinstitute.org/hc/en-us/community/posts/360072134172-GATK-Germline-CNV-Segmental-Duplication-filtering-is-potentially-very-dangerous-?page=1#community_comment_360012450472

Gentle warning about loss of TPs with default FilterIntervals params

---

scripts/cnv_wdl/cnv_common_tasks.wdl
scripts/cnv_wdl/germline/cnv_germline_case_scattered_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl
scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl

Closes #6829
@mwalker174 Could you please review? 
I only added `gcs_project_for_requester_pays` input to tasks that need access to BAMs. Do we also need it for the ones that require reference such as `PreprocessIntervals`?

Added requster pays option to germline and somatic CNV WDLs

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/DepthOfCoverage.java

Fixed typo with "-genelist" argument to "-gene-list" in DepthOfCoverage documentation.

Fixed typo with "-genelist" argument to "-gene-list" in DepthOfCoverage documentation.

---

src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtils.java
src/test/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtilsUnitTest.java

I have observed the method adjustQualsOfOverlappingPairedFragments() has a tendency to penalize reads that might have indels relative to each-other. This branch aims to better handle the edge cases that come up when mates have mismatching numbers of bases at the start or end of the reads relative to each-other. As part of #6634 I fixed this behavior somewhat and I am pulling this out into a separate branch in order to ease the comparison for that PR.

Added functionality to better handle indels/spanning deletions in the cigar base quality adjustment code.

---

.travis.yml
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ArrayExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/ExtractCohortBQ.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/ProbeInfo.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/ProbeQcMetrics.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/arrays/tables/SampleList.java
src/main/java/org/broadinstitute/hellbender/utils/bigquery/StorageAPIAvroReader.java

Changes
- `--cohort-sample-file` can be used instead of `--cohort-sample-table` to provide the (sample_id,sample_name) map
- The Avro reader was changed to set the BQ client's parent to be the current project instead of the destination table's project. This was needed for AoU since our notebook users do not have BQ jobs permissions on the microarray dataset.

optionally provide sample-map-file instead of sample-map-table

---

.dockstore.yml

The dockstore yml file requires the version number at the top of file which was missing in the initial PR. 
Stated by dockstore team in the following thread [here](https://discuss.dockstore.org/t/setting-up-dockstore-app-with-existing-workflows/3932/2) and dockstore docs [here](https://docs.dockstore.org/en/develop/getting-started/github-apps/github-apps.html).

Added version number to dockstore yml file

---

scripts/variantstore_cromwell_tests/run_variantstore_wdl.sh
scripts/variantstore_wdl/README.md
scripts/variantstore_wdl/extract/Dockerfile
scripts/variantstore_wdl/extract/raw_array_cohort_extract.py
scripts/variantstore_wdl/extract/requirements.txt
scripts/variantstore_wdl/raw_array_cohort_extract.wdl
scripts/variantstore_wdl/raw_array_cohort_extract_inputs.json
scripts/variantstore_wdl/schemas/metrics_schema.json

I made no changes to the copied files. @kcibul @ahaessly let me know if I'm missing anything. I left some of the demo bash scripts thinking that we didn't necessarily need to keep them now that we have WDLs, but let me know if you want me to move anything else. 
The readme update here assumes that #6881 will get merged. I also turned off the tests.

Moving extract wdls from variantstore repo

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

Closes #6686
@fleharty This option did nothing because a copy of the original reads was modified.  By deleting the unnecessary mapping quality filtering (this is totally redundant with the M2 read filter), we finalize (and thereby discard soft clips if requested) an assembly region made from the original reads, not a copy.

dont-use-soft-clips actually works in Mutect2

---

.github/workflows/carrot_run_test_from_pr_comment.yml

Added a workflow file for enabling the GitHub Action which processes PR comments to determine if they are meant to trigger and CARROT test, and then processes them if they are formatted in that way.
BIG IMPORTANT NOTE: Before this is merged, we need to set two secrets for this repo:
- `CARROT_TOPIC_NAME`, which is the name of the Google Cloud PubSub topic that messages will be sent to if a comment should trigger a run, and
- `CARROT_SA_KEY`, which is the service account key JSON for the service account that has write access to the PubSub topic.
If this is merged before those are set, I'm fairly confident we're just gonna get an email saying the action failed each time someone posts a PR comment (CARROT or otherwise), which would be less than ideal.
Closes #6916

Added GitHub Actions workflow file for CARROT integration

---

README.md

This option no longer works, so I'm removing it from the README.
Resolves #6853

Remove reference to -Dtest.single from README

---

README.md

Fixing README.md to reflect current Git LFS download size as approximately 5 GB.
Fixes #6932

Updating current Git LFS download size in README.md

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/VetFieldEnum.java

This is a first pass, but at the very least hopefully won't blow up on older data (that has been reblocked). I'm currently leaving the raw rank sum values blank if they don't exist in the input. This means the data will look smaller than a real allele specific gvcf, but I didn't know how to fake those values from the data we have in the non-allele specific gvcf.

Making ingest work on gvcfs without allele specific annotations

---

scripts/variantstore_wdl/ImportArrays.wdl
scripts/variantstore_wdl/ImportGenomes.wdl

I'm not sure how this worked before, but adding a variable fixes it. @ahaessly, let me know what you think!

Fix partitioning in ImportGenome WDL

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/VetFieldEnum.java

When I ingested more non- allele specific GVCFs, I ran into some edge cases. Most of these missing annotations occurred at weird sites where the GQ was 0 (but it wasn't a ref block). These changes keep it from throwing an error when it hits these sites.

Fixes for non-allele-specific gvcfs for ingest

---

scripts/gatkcondaenv.yml.template
src/test/java/org/broadinstitute/hellbender/utils/python/PythonEnvironmentIntegrationTest.java

It looks like the conda env recently started resolving h5py to v3.1.0, which in turn appears to be incompatible with the keras version we're using, causing the CNNScoreVariants integration tests to fail when keras tries to load the model file (see https://github.com/tensorflow/tensorflow/issues/44467). This PR pins the version to the version used by the last build I could find that succeeded, which is 2.10.0.

Pin h5py version to 2.10.0.

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/CreateReadCountPanelOfNormals.java
src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDDenoisingUtils.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/CreateReadCountPanelOfNormalsIntegrationTest.java

Just a minor fix, but could conceivably change results by keeping/dropping samples/intervals on the edge of the filter. See discussion in https://gatk.broadinstitute.org/hc/en-us/community/posts/360057785591-Error-while-running-CreateReadCountPanelOfNormals

Adjusted logic for filtering zero-coverage samples and intervals in CreateReadCountPanelOfNormals.

---

.travis.yml
src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManagerUnitTest.java

fixed an error where the read mate key in SplitNCigarReads was not sufficiently strict about readnames causing cigar errors

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/CommonCode.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/SchemaUtils.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractTool.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java

I think this is ready for initial review while I start testing it on larger scale data. I've left adding in the full VQSR tranche filtering as TODOs for now.

Add filtering to ExtractCohort

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortEngine.java

Fixing a bug I noticed while spot checking sites. We should eventually add some tests that check expected outputs, but I'll save that for another day. We were accidentally applying filters to alleles in the filtering table that didn't exist in the cohort that was pulled out. Now we're only looking at VQSLODs in the filter table for alleles that are present in the output VCF.

fixing bug in filtering on export from variantstore

---

scripts/variantstore/wdl/ngs_cohort_extract.inputs.json
scripts/variantstore/wdl/ngs_cohort_extract.wdl

I added the scatter so we could easily scatter by more than 24 ways, but we still need to change how we are partitioning the filtering/PET/VET tables to line up with our scattered intervals.
Scattering 50 ways, each shard took about 10-15 min extracting 100 WGS samples.

Updating extract wdls to apply filtering

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java

This fixes the test that was accidentally disabled (when we added a flag for overlapping read adjustment we forgot to set it correctly for the test) and reinstated something like the code from #4926. It should now necessarily be the case that the finalize() method calls read.copy() at least once for every read (though many multiples of once are still quite possible).
Fixes #6882

Fixed a bug where overlapping reads in subsequent regions can have invalid base qualities

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotator.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorIntegrationTest.java

Added a check to VariantAnnotator that all read samples are present in the VCF

---

scripts/gatkcondaenv.yml.template

Let me double check this and expand if necessary.

Fixed typo in conda environment YML documentation.

---

scripts/travis/install_and_authenticate_to_gcloud.sh
scripts/travis/install_gcloud.sh

Our travis gcloud installation scripts relied on piping interactive responses
into the stdin of the installer, which is brittle.
This patch changes our script to instead run the installer in non-interactive mode.

Switch travis gcloud installation to use noninteractive mode

---

scripts/publish_gatk_tool_wdls.sh

This script runs the GATK WDL generation, and publishes the generated WDLs to https://github.com/broadinstitute/gatk-tool-wdls along with an auto-generated .dockstore.yml file.
It has already been used to successfully publish the 4.1.9.0 WDLs to that repo.

Added a script to publish GATK tool WDLs for each release

---

.travis.yml

If a core dump is produced while running tests on travis, this will echo the log file to the travis log (ie., it was triggered [here](https://api.travis-ci.com/v3/job/468677651/log.txt) by the pair hmm seg fault) so the java and native thread stacks can be inspected.

Echo log file after failed travis run.

---

src/main/java/org/broadinstitute/hellbender/utils/BaseUtils.java
src/test/java/org/broadinstitute/hellbender/utils/BaseUtilsUnitTest.java

Fixes a bug that was exposed in https://gatk.broadinstitute.org/hc/en-us/community/posts/360075631171-BQSR-no-output-table-found
The issue is that bytes are signed in java, and yet we were treating them as unsigned and directly indexing an array with them.....this works as long as you don't have weird characters in your bam/reference...but if you do you get an access error that is non-informative.

Yf make BaseUtils methods more robust to handle all possible byte values

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervalsIntegrationTest.java

Fixes a bug that I inadvertently introduced long ago in #5408. A method there originally assumed that the intervals to be filtered coincide with the annotated intervals when filtering on annotations, but this assumption can be violated when e.g. using `-XL` to further exclude intervals. This breaks the annotation-based filtering and will result in incorrectly retained/dropped intervals. Unfortunately, the integration test cases were not quite complete enough to catch this.
Fortunately, for typical data and parameters, the number of affected intervals is typically a very small percentage, especially in human (e.g., the default GC filters of [0.1, 0.9] affect <0.1% of 250bp bins); I only caught this when running on malaria data, since GC filtering has more impact there. I would also expect …

Fixed error in FilterIntervals logic when filtering on annotations with -XL.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java

This was an oversight from when the chain pruning step was moved in GATK. I have added a before and after chain pruning set of debug graphs which should help understand all the assembly stages better.

Fixed a bug in the --debug-graph-transformations argument where it didn't emit the graph before chain pruning

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/MutectReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/AbstractReadThreadingGraph.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/JunctionTreeLinkedDeBruijnGraph.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingGraph.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/JunctionTreeLinkedDeBruijnGraphUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingGraphUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

In helping @bhanugandham figure out why a particular site was failing it became apparent that merging dangling head code was failing to recover deletions in the dangling head. Furthermore there is some code in the dangling end recovery code that asserts a certain high standard of matching (usually 1 but sometimes dangling branch length/kmersize) `getMaxMismatches(final int lengthOfDanglingBranch)`. Both of these facts seem likely to cause dangling heads to be dropped despite their being still potentially informative, particularly the indel code. 
I have added the ability for the index recovery code to account for the cigar string when merging dangling ends. Addtionally rather than counting mismatches to reject the branch it simply requires a minimum matching end (which can be changed, I …

Added the ability for Indels to be recovered from dangling heads

---

src/main/java/org/broadinstitute/hellbender/tools/HaplotypeCallerSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java

Also removed some confusing (and not working!) code that made it seem the argument affected the read filters when in fact it did not because Barclay generates default read filters at the begining of time before that argument gets populated and thus it wouldn't affect the default read filter construction.
Fixes #7034

Updated --mapping-quality-threshold and its documentation to be less confusing

---

scripts/variantstore/wdl/ImportGenomes.example.inputs.json
scripts/variantstore/wdl/ImportGenomes.wdl
scripts/variantstore/wdl/LoadBigQueryData.wdl

- I sneaked in another change where I pass in a single file containing a list of input_vcfs instead of an array of input_vcfs. I made this because Terra couldn't save my inputs when I passed in 700 samples.
- Most of the logic was moved into `CreateTables`, including the determination for what files to load. It would have been cleaner to move all of the file loading logic into `LoadTable` but the current approach cuts down the on the number of `gsutil ls` calls made and more importantly, only spins up a shard if there are files to load.
- I pushed the logic into a separate workflow because I wanted to refactor it as two tasks and I couldn't find a way to get a Task to call another Task without wrapping it in a workflow.

Separate bigquery table creation and data loading in LoadData 

---

.travis.yml
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyperEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyperEngineUnitTest.java

For AoU/BQ solution we want to be able to produce VCFs w/o PLs.  In a 1k sample WGS VCF this reduces the .vcf.gz total size from 120GB to 73GB (almost 40%)

Option to remove PLs from VCF output 

---

src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalTextOutputArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/cmdline/argumentcollections/SimpleOutputCollection.java
src/main/java/org/broadinstitute/hellbender/tools/CountBases.java
src/main/java/org/broadinstitute/hellbender/tools/CountReads.java
src/main/java/org/broadinstitute/hellbender/tools/FlagStat.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/CountVariants.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/fasta/CountBasesInReference.java
src/test/java/org/broadinstitute/hellbender/cmdline/argumentcollections/OptionalTextOutputArgumentCollectionUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/CountBasesIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/CountReadsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/CountVariantsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/FlagStatIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/fasta/CountBasesInReferenceIntegrationTest.java

There's a small set of tools that only outputs their results to stdout, making it difficult to use the output in a pipeline/script. This PR adds a way to output simple results from such tools to an (optional) output file.
I Added this option to the following tools:
- CountBases
- CountBasesInReference
- CountReads
- CountVariants
- FlagStat
Other tools that might benefit from this (but it will require an API change, so I didn't do it):
- CompareIntervalLists
- ValidateVariants

Add option to save output for a small set of tools

---

src/main/java/org/broadinstitute/hellbender/utils/bigquery/StorageAPIAvroReader.java
src/test/java/org/broadinstitute/hellbender/utils/bigquery/BigQueryUtilsUnitTest.java

https://github.com/broadinstitute/dsp-spec-ops/issues/192
- Updated StorageAPIAvroReader.java
> - To handle the use case if no data is returned from BQ
- Updated BigQueryUtilsUnitTest.java
> - testQueryWithEmptyDatasetStorageAPI() function to test code changes

Update To handle if no data error

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MaxFilteredGenotypesSelection.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MaxFractionFilteredGenotypesSelection.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MinFilteredGenotypesSelection.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_MinFractionFilteredGenotypesSelection.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_NoGTs.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_RepeatedLineSelection.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_SetFilteredGtoNocall.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_SimpleExpressionSelection.vcf

Fixes #7068 
- When adding AC, AF, AN, DP header lines, SelectVariants now checks if these lines are in the original header already and if so, overwrites these lines with the respective standard lines
- Without this check, an issue in htsjdk causes duplicate header lines with the same ID if the description differs. This should be fixed there but this fix provides a downstream workaround
- Modified the integration test validation files, which have been invalid VCF files with duplicate header lines
- Removed addition of AC, AF, AN if `--set-filtered-gt-to-nocall` is set, because these lines will be added later anyway

Fixed SelectVariants generating duplicate header lines

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/AbstractReadThreadingGraph.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingGraphUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

It looks like the last rebase in the previous PR broke some things and tests were insufficient to catch them. I have added checks to the tests as to the actual contents of the paths as well as some more extreme tests. 
Fixes #7085

Fixed crashes in new dangling head merging code

---

.dockstore.yml
scripts/variantstore/wdl/ImportGenomes.wdl

This PR addresses spec-ops issue #235 - Use -m flag in final gsutil mv of files in ImportGenomes. 
Additionally, this PR adds branch filters to the dockstore.yml file that will help with development. The filter for each workflow indicates which branch(es) will show up for that workflow in dockstore. If we don't include these filters, dockstore will run checks of ALL workflows on ALL branches, which causes timeouts. We could remove these filters later (before merging to master) or not, but for now this could help us develop on ah_var_store. Note that we'll need to add feature branches to that file as we work on them.
This workflow was tested in Terra and the upload succeeded.
Also confirmed that if one file fails, the entire process throws an error code (i.e. -m flag will not cause …

Add -m flag to gsutil step; add dockstore branch filters to facilitate development

---

scripts/variantstore/wdl/extract/Dockerfile
scripts/variantstore/wdl/extract/ngs_cohort_extract.py

1. Add ngs_cohort_extract.py to the Dockerfile
2. Don't swallow exceptions thrown in the python script; results in succeeding workflows even if the script fails.

Some changes to the ngs cohort extract files

---

scripts/variantstore/wdl/ImportGenomes.wdl

in my previous PR I had removed the `storage_location` input to the CreateTables task but forgot to remove those imports from the calls! this removes them from the calls.

remove problematic storage_location inputs to CreateTables calls

---

.dockstore.yml
scripts/variantstore/wdl/ImportGenomes.wdl

both of these are updates to the ImportGenomes wdl:
- reduce memory/cpus for the CreateImportTsvs task from 10GB to 3.75GB and 2 CPU to 1 CPU. these settings were tested on 3000 gvcfs and none errored out because of memory. this ties out spec-ops issues #211 and #233
- before loading files using `bq load`, check for existing files in the gs bucket. only run `bq load` if there are matching files in the bucket. this will prevent an error if you run a subset of samples corresponding to a larger sample map such that you've created a pet_002 table but there aren't any samples to load for pet_002 yet. this was tested in Terra and worked as expected.

Reduce memory and CPU for CreateImportTsvs task, check for files before attempting load

---

scripts/variantstore/wdl/ImportGenomes.wdl

I added -m to `gsutil cp` in a previous PR but missed the `gsutil mv` step post-`bq load` - so here that is. tested it from the command line, works well. also confirmed that it will throw an error if one (or more) files has an error:
```
$ cat test_files_bucket.txt | gsutil -m mv -I gs://dsp-fieldeng-dev/test_mv/
If you experience problems with multiprocessing on MacOS, they might be related to https://bugs.python.org/issue33725. You can disable multiprocessing by editing your .boto config or by adding the following flag to your command: `-o "GSUtil:parallel_process_count=1"`. Note that multithreading is still available even if you disable multiprocessing.
Copying gs://dsp-fieldeng-dev/test_cp/test1.txt [Content-Type=text/plain]...
Copying gs://dsp-fieldeng-dev/test_cp/test2.txt …
```

Add -m flag to gsutil mv step

---

scripts/variantstore/wdl/ImportGenomes.wdl

add in service account auth for aou
localize with service account in same vm
update disk size
fix input_vcf to work with manual localization and streaming

ah - optional service account

---

.dockstore.yml
scripts/variantstore/wdl/ImportGenomes.wdl

spec ops issue #248
process implemented here:
- new task `SetLoadLock` is called at the beginning of `ImportGenomes` - it generates a UUID for the submission, writes that run_uuid to a lock file, and uploads that lock file to the output_directory (where the tsvs will be generated). 
- CreateImportTsvs and LoadTables take the run_uuid as an input, compare it against the contents of the lock file in the bucket, and only proceed if the uuids match. otherwise they exit out.
- after all LoadTables tasks have completed, a new task `ReleaseLoadLock` is called that removes the lock file from the bucket (again only if the uuid in the lockfile matches this run)
tested and confirmed that:
- the `loadlock` file is created and removed: https://app.terra.bio/#workspaces/broad-dsp-spec-ops-fc/1000G-high- …

Add load lock file to prevent accidental re-loading of data to BQ

---

build.gradle

Update to htsjdk 2.24.1.  This fixes a gross issue where we accidentally included Junit as a runtime dependency.

Update htsjdk to 2.24.1

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortEngine.java

when extracting more than one sample using ExtractCohort, multi-allelic sites get written with bad formatting for the AS_YNG field:
`AC=2,1;AF=0.028,0.014;AN=72;AS_QD=.;AS_VQSLOD=-6.7307,.;AS_YNG=[G, .];ExcessHet=0.0927;FS=0.000;SOR=0.693`
this PR processes the AS_YNG field properly, resulting in properly formatted AS_YNG fields:
`AC=2,1;AF=0.028,0.014;AN=72;AS_QD=.;AS_VQSLOD=-6.7307,.;AS_YNG=G,.;ExcessHet=0.0927;FS=0.000;SOR=0.693`

fix bug in ExtractCohortEngine

---

src/test/java/org/broadinstitute/hellbender/engine/spark/DataprocIntegrationTest.java

We should fix the dependency issue and then re-enable them.

Disabling some spark dataproc tests because of dependency issues.

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/CommonCode.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/SchemaUtils.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractFeatures.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractFeaturesEngine.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
src/main/resources/org/broadinstitute/hellbender/tools/variantdb/nextgen/feature_extract.sql

updated the query to calculate num hets and homvars
add in excess het and check threshold

AH- add excess het (approx) to feature extract

---

Dockerfile

Previously we were relying on the gcloud package signing key retrieved
during build of the GATK base image. However, the base image is updated
so infrequently that it's possible that the key it uses has expired. To
address this, we now retrieve an updated key at the start of the Docker
build.

Update the gcloud package signing key during the docker build

---

src/main/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMDestination.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriter.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/SAMFileDestination.java
src/test/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeBAMWriterUnitTest.java

In #6991 I introduced an option for HC to not print artificial haplotypes in the bamout. I overlooked the fact that when this option is enabled we should not include the read group for the artificial haplotypes in the header. The present PR fixes this and adds tests.

Do not add artificial haplotype read group to bamout when --bam-writer-type NO_HAPLOTYPES

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortEngine.java

Resolves https://github.com/broadinstitute/dsp-spec-ops/issues/271

change 0/0 GQ0 sites to no-calls

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/CommonCode.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/SchemaUtils.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/FilterSensitivityTools.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
src/test/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/FilterSensitivityToolsTest.java

specops issue #269 https://github.com/broadinstitute/dsp-spec-ops/issues/269
- user can provide either [snps-truth-sensitivity-filter-level, indels-truth-sensitivity-filter-level] or [snps-lod-score-cutoff, indels-lod-score-cutoff], or neither, in which case default values of snps-truth-sensitivity-filter=99.7 and indels-truth-sensitivity-fitler=99.0 are used.
- regardless of lod score cutoffs or truth sensitivity cutoffs, the filtering string is either "low_VQSLOD_SNP" or "low_VQSLOD_INDEL"
- if lod score cutoffs are provided, those are used for filtering. the header filter message looks like "Site failed INDEL model VQSLOD cutoff of 0.0"
- if truth sensitivity cutoffs are provided, the corresponding lod scores are looked up from the tranche table in BigQuery. the header filter message …

Allow users to specify VQSLOD sensitivity and apply threshold in ExtractCohort

---

src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/CreateVariantIngestFiles.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/PetTsvCreator.java
src/test/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/CreateVariantIngestFilesIntegrationTest.java

- updated integration test (removed that argument so it defaults to the same thing)
- tested that using "NONE" as an argument works

in CreateVariantIngestFiles, set default drop_state to 60, but allow NONE as input

---

scripts/variantstore/wdl/GvsImportGenomes.wdl

for issue 286, this adds a clustering (hardcoded) option as the location
successful in a manual test of the WDL

286 Add clustering to PET / VET tables

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.example.inputs.json
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.example.inputs.json

specops issue #287
tested with defined truth sensitivities here: https://app.terra.bio/#workspaces/broad-dsp-spec-ops-fc/gvs_testing_no_sa/job_history/39f8c4ea-8e21-46d4-a6ba-8e570ce75f8b

add vqsr cutoffs to GvsExtractCallset wdl; clean up dockstore yml

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/CreateVariantIngestFiles.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/PetTsvCreator.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/SampleInfoTsvCreator.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/VetTsvCreator.java
src/test/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/CreateVariantIngestFilesIntegrationTest.java

this PR:
- changes CreateVariantIngestFiles to name the output files in a predictable way - i.e. rather than using a sample_id, it uses the name of the input gvcf. e.g. `pet_001_NA12878.tsv` becomes `pet_001_NA12878.haplotypeCalls.reblocked.vcf.gz.tsv`
- added a test in CreateVariantIngestFilesIntegrationTest to assert that the files are named as expected
- changes the GvsImportGenomes.wdl to:
- check whether, for the given input gvcf file and for each of pet, vet, and sample_info, the output TSV already exists somewhere in the output directory. it checks subdirectories.
- if the output TSV exists in a `set_X` subdirectory, we move that file back into the parent directory so that subsetting works as desired when we get to LoadTables
- if the output TSV exists in a `done` subdirectory, we …

Enable call caching of TSV generation in GvsImportGenomes

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/VariantContextTestUtils.java

It seems fairly rare that the PL array is truly uninformative and consequently would be removed based on the fact that none of the integration tests seem to have failed as a result of this.

Removed some code from the allele subsetting block that was deleting Pl arrays

---

scripts/variantstore/README.md
scripts/variantstore/wdl/GvsImportGenomes.example.inputs.json
scripts/variantstore/wdl/GvsImportGenomes.wdl
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/CreateVariantIngestFiles.java

This also start the mark down for how to find cost info for the aou prod project

take sample name as a param

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEvalArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEvalEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEvalIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/walkers/varianteval/VariantEval/expected/testPedigreeValidation.expected.txt

Rationale: certain evaluators use a pedigree. This PR is a minor change that lets VariantEvalArgCollection supply the PedigreeValidationType. It defaults to the current behavior, which is to always use STRICT. It includes an integration test to cover this feature.

Allow VariantEvalArgCollection to supply PedigreeValidationType

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl

tested without SA: https://app.terra.bio/#workspaces/broad-dsp-spec-ops-fc/gvs_testing_no_sa/job_history/235c2316-d31a-42a5-8f25-a0397b8be42e
tested with SA: https://app.terra.bio/#workspaces/broad-dsp-spec-ops-fc/gvs_sa_testing/job_history/81aa9029-fb58-453b-a962-bad4fde09a2e
note this worked fine with localization optional for the SA

Use GatherVcfsCloud in GvsCreateFilterSet.wdl

---

.dockstore.yml

A while back I added a .dockstore.yml file to the gatk repo so that gatk workflows in the /script/ folder would be automatically synced in Dockstore after every push or release. This also allowed the workflows in every branch/release to be readily available in Terra. However, GATK’s 700+ branches has been causing problems for Dockstore syncs and in some instances associated released tags to be missing ([forum discussion](https://discuss.dockstore.org/t/dockstore-could-not-find-a-workflow-in-git-using-yml-though-it-worked-previously/4255/5)). 
This PR adds filters to the dockstore.yml so that only the master branch and the releases gets synced to dockstore, also any future branches aren’t automatically synced.  If anyone wants to sync their branch they’ll have to add their branch name to …

Added filter for only master branch

---

.travis.yml

* It turned out we weren't logging in to dockerhub on the wdl test cases in travis because I misunderstood how the DOCKER_TEST flag was used.
* Now we unconditionally authenticate to dockerhub in all test shards instead of trying to pick only the relevant ones.

Always login to docker on travis instead of qualifying it

---

scripts/variantstore/wdl/GvsImportGenomes.wdl

if there are tables that do not have samples to be loaded, it will not generate the output files. so make them optional

make outputs optional, change case in output

---

scripts/mitochondria_m2_wdl/AlignAndCall.wdl
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

This now outputs median coverage in addition to the mean coverage which was already being output before from the Mitochondria pipeline.
@ahaessly Could you please take a look at this?

Adding median coverage metric to mitochondria pipeline

---

scripts/variantstore/tieout/add_max_as_vqslod.py
src/main/java/org/broadinstitute/hellbender/tools/variantdb/SchemaUtils.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractFeatures.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractFeaturesBQ.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractFeaturesEngine.java
src/main/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractFeaturesRecord.java
src/main/java/org/broadinstitute/hellbender/utils/bigquery/StorageAPIAvroReader.java
src/main/resources/org/broadinstitute/hellbender/tools/variantdb/nextgen/feature_extract.sql
src/test/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortRemoveAnnotationsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohortTest.java
src/test/resources/org/broadinstitute/hellbender/tools/variantdb/nextgen/ExtractCohort/expected.vcf

The overarching goal of this PR is to reduce or eliminate the effect of cohort size on the filtering of variants for a specific sample.  As an example this means the filtering for the genotypes for a GIAB sample should be the same whether you make a VCF of the full cohort and then subset to the GIAB sample (expensive) or you just make a callset with just the GIAB sample.  This is good for users since their results won't get "better" with more samples that they don't care about in their VCF.
- calculate and store LowQual filter as a part of Filter Set creation
- use LowQual filter from filter set rather than recalculating it from QUALapprox at extract time
- flag (default is true) to perform VQSLod filtering at the sample/genotype level
Before/After results showing minimal impact are at: …

Support for FORMAT/FT VQSLod Filtering and cohort-wide LowQual filter

---

scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsPrepareCallset.wdl
scripts/variantstore/wdl/extract/create_cohort_extract_data_table.py
src/main/java/org/broadinstitute/hellbender/tools/gvs/common/SampleList.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeatures.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeaturesEngine.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeaturesEngineTest.java

For GVS Feature Extract, ~Cohort Extract~ and Prepare Callset we should add a bq labels to indicate the query and tool being
gvs_tool_name (e.g. feature-extract)
gvs_query_name (e.g. read-sample-table)
Python Prepare Callset:
Java GVS Feature Extract:
for Feature Extract
update the wdl to take in a query_labels optional string
update the GATK tool to take in a query_labels param
update the GATK tool to validate labels
update the GATK tool to add constant kv labels: "gvs_tool_name", "extract-features" and "gvs_query_name", "extract-features" (is there a way to get more explicit in the queries? isn't it just one query?)
test that this works with and without a label param passed in
for Prepare Callset
update the wdl to take in a query_labels optional string
update the python script to take …

279 labels

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/ASEReadCounter.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java

We found some links that needed to be fixed in the Funcotator, ASEReadCounter, and VariantRecalibrator tool docs. We updated them or removed the links as needed.

Update Broken Links in Tool Docs

---

build.gradle
src/main/java/org/broadinstitute/hellbender/utils/bigquery/StorageAPIAvroReader.java

Suggested by Micah @ Google, see broadinstitute/dsp-spec-ops#309

upgrade bq libraries

---

scripts/variantstore/wdl/GvsImportGenomes.wdl

query the partition table to see if samples have already been loaded

check for duplicate ids

---

src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortRemoveAnnotationsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortTest.java

Locally tested and the exclude-filtered flag removes filtered rows

Rc 274 passing sites only

---

src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java

Resolves one of the issues encountered when merging the DRAGEN-GATK gvcfs the #7108.

Fixed an edge case that could result in negative GQs when in USE_POSTERIOR_PROBABILITIES mode

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/PedigreeAnnotation.java

Consolidate code in PedigreeAnnotation, provide getters, and allow PedigreeValidationType to be set

Consolidate code in PedigreeAnnotation

---

.dockstore.yml
scripts/variantstore/wdl/GvsPrepareCallset.wdl

If the sample file is created by extracting a table from BQ, the file might be in a bucket that only the service account can access. Add an option for using the service account to pull the file.
Also, expose the service account input at the workflow (not the task) level

Ah prepare localize option

---

scripts/gatkcondaenv.yml.template
src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/model_denoising_calling.py
src/test/java/org/broadinstitute/hellbender/utils/python/PythonEnvironmentIntegrationTest.java

@fleharty this is a rebased version of the 17cadfa399643877c70ba830d0b4abf9e5b159a9 branch used to generate the Pf7 CNV call set. There are two minor changes: a) one to remove spurious negative dCR estimates reported by gCNV, which were negatively affecting genotyping of HRP2/3 deletions, and b) updating sklearn to the version used for clustering, so that we can reproduce everything exactly using just the GATK Docker. The latter change probably isn't absolutely necessary, but it doesn't seem to break anything so I'm going to go ahead with it. We might want to update to an even more recent version later on (especially if we make any breaking/non-refactoring improvements to the malaria genotyping code after the initial PR), but unfortunately this slightly changes the clustering assignment …

Removed mapping error rate from estimate of denoised copy ratios output by gCNV and updated sklearn.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/AlleleFraction.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/Coverage.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerAlleleBySample.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/DepthPerSampleHC.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/FisherStrand.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/MappingQualityRankSumTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/MappingQualityZero.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/QualByDepth.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RMSMappingQuality.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandBiasBySample.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandOddsRatio.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_BaseQualityRankSumTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_FisherStrand.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_InbreedingCoeff.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_MappingQualityRankSumTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_QualByDepth.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_RMSMappingQuality.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_StrandOddsRatio.java

In the "Related Annotations" section of the annotations tool docs, the links were broken redirecting to the GATK homepage. We decided to remove these links since there is not a good way to link to the mentioned tool without the link becoming outdated with new releases.

Remove broken links to related annotations in tool docs

---

src/main/java/org/broadinstitute/hellbender/engine/MultiVariantWalkerGroupedOnStart.java

This is related to #7287. 
By default MultiVariantWalkerGroupedOnStart will iterate over any variant that spans the user-provided intervals. This is not what one would typically want when running scatter/gather jobs, since variants spanning interval borders would be included in both jobs. There is a variable/argument for  IGNORE_VARIANTS_THAT_START_OUTSIDE_INTERVAL, but it's private and therefore subclasses cant read it. I would like our MultiVariantWalkerGroupedOnStart to view this value and at least log a warning if the current job hasUserSuppliedIntervals(), and ignoreIntervalsOutsideStart=false.
In this PR I just make that variable protected, but I could also add formal getter/setters if you prefer.

Allow MultiVariantWalkerGroupedOnStart sublcasses to view/set ignoreIntervalsOutsideStart

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl

create .bigqueryrc to suppress warning messages
change disk size to 150

Ah fix timestamp query

---

scripts/variantstore/wdl/GvsExtractCallset.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/common/ExtractTool.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortRemoveAnnotationsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortTest.java

There are params in Extract Cohort that can be tightened up
Extract Tool has two params that are not used by Extract Features and are _already_ in Extract Cohort
The filter_set_name is used in the BQ filtering tables and looks like we can set it to be completely required for any type of filtering.
There are 3 BQ filter tables -- 2 are needed for filtering (no matter what?) and 1 (tranches) is needed for thresholding and sensitivity calculations?
Genotype level filtering is true by default, but this doesn't seem like it should effect things after this cleanup. Though technically it should only be true if a filter_set_name has been specified. I will add another comment in the body of the code, but I would like to add this safety gate explicitly
Disable gnarly doesn't need to be a passed in …

313 Cleanup Extract Cohort params

---

scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl

I tried implementing this with https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#float-sizefile-string but the workflow runtime went from 1h to 4h with that implementation. Not sure why that is but the runtime went back to normal levels after implementing it directly into the extract workflow.

Variant Store extraction - Add VCF size to output

---

src/main/java/org/broadinstitute/hellbender/cmdline/StandardArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
src/main/java/org/broadinstitute/hellbender/utils/variant/writers/ShardingVCFWriter.java
src/test/java/org/broadinstitute/hellbender/engine/GatkToolIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/io/IOUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/variant/writers/ShardingVCFWriterUnitTest.java

Sharded output is extremely useful for pipelining. This adds the option `--max-variants-per-shard` to `GATKTool` to let users easily split out VCFs. The functionality is implemented in the `ShardingVCFWriter` class, which is a simple wrapper around `VariantContextWriter` that basically creates a new writer whenever the max shard size is reached.

Sharded VCF output option

---

.dockstore.yml
scripts/variantstore/wdl/GvsSitesOnlyVCF.example.inputs.json
scripts/variantstore/wdl/GvsSitesOnlyVCF.wdl

Added:
- service account support for SitesOnly task, added GATK flag to not output a timestamp info VCF to help Call Caching
- switch to SSD, increased size and moved to pre-emptibles for Annotate task
- service account support for BQ Loading
- service account support for BQ Smoke Test

VAT changes for alpha1

---

build.gradle

Generate multi-release jars, to automatically select the implementation version when running under Java 9 or newer.
This fixes https://github.com/broadinstitute/gatk/issues/7338

Fixes #7338 Java11 problem with log4j2

---

scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPrepareCallset.wdl
scripts/variantstore/wdl/GvsSitesOnlyVCF.wdl

Otherwise, when json is refreshed, contents of the file are different, hash of the file is different, and call-caching will not register a match, despite the same "account" being used.
- changed input type from `File` to `String`
- changed the name to make it more obvious/clear
Closes https://github.com/broadinstitute/dsp-spec-ops/issues/327

Replace service_account_json (file) with service_account_json_path (string) to allow call-caching

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl

The diff is probably a little confusing to look at because code was moved around.
Closes https://github.com/broadinstitute/dsp-spec-ops/issues/322
TODO before merge:

Parallelize create filterset by breaking out the 3 filter set file creation/loads into separate tasks

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorConstants.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorVariantArgumentCollection.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/ArgumentsBuilder.java

Added ability for user to override to annotate again
Wrote unit and integration tests for new feature and override ability
resolves #5679

Added feature to check if input has been annotated

---

.dockstore.yml
scripts/variantstore/wdl/GvsValidateVAT.wdl

The idea is that this WDL will run all the checks for each release of the VAT table, one call for each validation.  The first validation rule ("Validation Check confirms that data is put into the VAT table after completing without an error.") is included as a model for subsequent calls.
- workflow should succeed if it's able to try all tests
- workflow output `validation_results` will contain details of each test result in an array of `{"testName": "result details"}`:
Example 1 — [fail](https://job-manager.dsde-prod.broadinstitute.org/jobs/2728b55b-5344-492a-951a-48fd416e9d0d)
`{ "EnsureVatTableHasVariants": "FAIL: The VAT table spec-ops-aou.rsa_gvs_quickstart.rsa_scratch has no variants in it." }`
Example 2 — [pass](https://job-manager.dsde-prod.broadinstitute.org/jobs/83e3bd5a-9144-452e- …

Create WDL to validate VAT and add first test

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngine.java

Looks like a missing set of parentheses caused the logging output for HaplotypeCaller to become unusably flooded with garbage. @droazen we should really get this in before release.

Fixed regression where HaplotypeCaller logs were getting flooded with bogus warnings

---

src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java
src/main/java/org/broadinstitute/hellbender/engine/ProgressMeter.java
src/test/java/org/broadinstitute/hellbender/engine/ProgressMeterUnitTest.java

Added a master "disable" switch to the GATK ProgressMeter, and hooked it up to
GATKTool.disableProgressMeter(). This allows the ProgressMeter to be easily disabled
for all tools / traversals by overriding a single method.

Hook up GATKTool.disableProgressMeter() to allow the ProgressMeter to be completely disabled for all tools / traversals

---

.dockstore.yml
scripts/variantstore/wdl/GvsValidateVAT.wdl

Closes https://github.com/broadinstitute/dsp-spec-ops/issues/366 by putting into SQL what is in English in that ticket:
> All variants in the region, chr19:35,740,407-35,740,469, overlap transcripts with multiple genes and those genes are always IGFLR1 and AD000671.2. Do not consider rows that include a consequence of downstream_gene_variant or upstream_gene_variant in this validation.

Add task for VAT validation #3

---

.dockstore.yml
scripts/variantstore/wdl/GvsValidateVAT.wdl

Closes https://github.com/broadinstitute/dsp-spec-ops/issues/367 by translating this English into a SQL query:
> If a vid has a null transcript, then the vid is only in one row of the VAT.

Add task for VAT validation #4

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java

Removed instances of String.format to help funcotator performance

---

.dockstore.yml
scripts/variantstore/wdl/GvsValidateVAT.wdl

Closes https://broadworkbench.atlassian.net/browse/VS-16 by adding SQL for
> There is a non-zero number of transcript fields with null values in the VAT.

Add VAT validation rule #5 [VS-16]

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl

Processing an exome takes ~1 minute, which means most of the time is spent on spinning up a VM, pulling docker images, etc.  This is not very cost efficient.  This PR allows for a `batch_size` to be set and then each task processes that many samples as a unit.  The default is `1` which yields the current behavior, but in exomes I have set it to 20 and seen the cost to ingest drop dramatically
The GitHub PR makes it look like a lot has changed but really the changes are:
- a new parameter
- a new task to turn the Array[File] for the VCFs into set of FOFNs (file-of-file-names) similar to how we split up intervals
- a loop in the actual Create TSV task to loop over the files in the FOFNs.  For SA mode we copy down each file, and for non-SA mode we rely on the fact that localization is …

Batching of samples for create import TSVs

---

custom_annotations_template.tsv
scripts/variantstore/wdl/GvsSitesOnlyVCF.wdl
scripts/variantstore/wdl/extract/create_variant_annotation_table.py

Unlike the other validation rules, this does not test the validity of the VAT, but whether the pipeline completed as we expected it to--so I have added this as the singular test that runs during the pipeline.
Validation Rule 2: The number of passing variants in GVS matches the number of variants in the VAT. Please note that we are counting the number of variants in GVS, not the number of sites, which may add a difficulty to this task.
Another way to phrase it: "If I were to make a sites only VCF of GVS and split each passing variant into it's own line, that number should equal the number of unique VIDs in the VAT."
Measure number of unique variants in sites only VCF that is generated.
We don't want to count filtered variants so we can't count the GVS table.
NOTE:
this pr also has some …

Add VAT validation rule #2 [VS-19]

---

src/main/java/org/broadinstitute/hellbender/engine/MultiVariantDataSource.java

I don't want htsjdk to get a reputation as a loose library

comment fix in MultiVariantDataSource.java

---

.gitignore
scripts/variantstore/wdl/GvsAssignIds.example.inputs.json
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/README.md

Assign Ids to samples.
Update the sample info table.
Update import wdl to remove the generation of the sample_info.tsv files

implement GVS ID assignment

---

scripts/variantstore/wdl/GvsPrepareCallset.wdl
scripts/variantstore/wdl/extract/create_cohort_extract_data_table.py

Update GvsPrepareCallset step so that, instead of creating and inserting all the data into the `_pet_new` table in one step (which errors out with large callsets), add the data in smaller sections that correspond to each `pet_` in the GVS.
Closes https://broadworkbench.atlassian.net/browse/VS-48

divide up creation/population of temp pet table [VS-48]

---

src/main/java/org/broadinstitute/hellbender/tools/dragstr/ComposeSTRTableFile.java
src/main/java/org/broadinstitute/hellbender/tools/dragstr/STRDecimationTable.java

Improved the documentation text for ComposeSTRTableFile and related STRDecimationTable.

Fix issues with missing documentation for ComposeSTRTableFile.

---

scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl

add "id_loaded" column to schema
add "partition_id != '__UNPARTITIONED__'" to query so we don't get int conversion error

update import for is_loaded

---

.dockstore.yml
scripts/m2_cromwell_tests/test_mitochondria_m2_wdl.json
scripts/mitochondria_m2_wdl/AlignAndCall.wdl
scripts/mitochondria_m2_wdl/ExampleInputsMitochondriaPipeline.json
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

numt and low het filters are no longer being used

remove calls to filter Numt and low het sites

---

.dockstore.yml
scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
scripts/variantstore/wdl/GvsSitesOnlyVCF.example.inputs.json
scripts/variantstore/wdl/GvsSitesOnlyVCF.wdl
scripts/variantstore/wdl/extract/create_variant_annotation_table.py
scripts/variantstore/wdl/extract/extract_subpop.py
scripts/variantstore/wdl/schemas/variant_transcript_schema.json
scripts/variantstore/wdl/schemas/vat_schema.json

This pr adds the subpopulation AC/AN/AF calculations.
It does this by taking in the ancestry table and making sublists of each---then passing that list of samples into the SelectVariants GATK tool
Updated Lucid chart here: https://lucid.app/lucidchart/fee376a4-4b72-481e-a239-a027f7f6ab1f/edit?page=CsG3hy3S1zEH#
Design Doc for this work:
https://docs.google.com/document/d/1FnPu_Jkz2O9rElApAQld0v6iBEFGe22dKarVWcwNxGI/edit
misc:
how should I add the VAT validation to the VAT pipeline? Should it run automatically?
Anvil data version of this table: spec-ops-aou:anvil_100_for_testing.vat_aug19

Adding the subpopulation calculations to the VAT creation WDL

---

scripts/variantstore/wdl/GvsSitesOnlyVCF.example.inputs.json
scripts/variantstore/wdl/GvsSitesOnlyVCF.wdl

Should I make this backward compatible and allow either this input as a file of file names OR an array of files?

Scaling the VAT -- switch the input to take in a file of vcf shard file names

---

scripts/variantstore/callset_QC/README.md
scripts/variantstore/callset_QC/filter_set_samples_calculate_threshold.example.sql
scripts/variantstore/callset_QC/filter_set_samples_create_metrics.example.sql

- modified SQL and documentation to account for more than one callset in a dataset
- added note about permissions required to run the queries
Closes https://broadworkbench.atlassian.net/browse/VS-177

Update GVS sample QC to support multiple callsets per datasset [VS-177]

---

scripts/variantstore/wdl/GvsImportGenomes.wdl

Making GetSampleIds volatile so it doesn't call cache to outdated information (since BQ could have changed, and cromwell wouldn't know it)

Making GetSampleIds volatile 

---

scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsPrepareCallset.wdl

Adds the extraction uuid for the current job to the GvsPrepareCallset step so that we can calculate the billing cost of an extraction run.

Add extraction uuid BQ label to GvsPrepareCallstep from GvsExtractCohortFromSampleNames

---

scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/extract/create_cohort_extract_data_table.py

The manifest file describes the files produced by the GvsExtractCallset task and is uploaded to GCS once all the shards have finished running.
The existence of the manifest.txt file can be used to determine if the extraction is complete or not by just using `gsutil` command and not going through Cromwell/Terra.
Here's a snippet of what that looks like.
```
interval_number, vcf_file_location, vcf_file_bytes, vcf_index_location, vcf_index_bytes
0,gs://fc-secure-765db3ba-3e2d-432e-89eb-9efda7430f93/genomic-extractions/66f225d3-35cf-4ff7-a4ec-3d887a86ea8b/vcfs/interval_0.vcf.gz,879403,gs://fc-secure-765db3ba-3e2d-432e-89eb-9efda7430f93/genomic-extractions/66f225d3-35cf-4ff7-a4ec-3d887a86ea8b/vcfs/interval_0.vcf.gz.tbi,1682
1,gs://fc-secure-765db3ba-3e2d-432e-89eb-9efda7430f93/genomic-extractio …
```

Add manifest summary file to GvsExtractCallset

---

scripts/variantstore/wdl/GvsSitesOnlyVCF.wdl

The VAT pipeline creates 3 tables, 2 are intermediary tables used to create the third.
I was tired of deleting them, so I made them temp tables

Make the pre-vat tables temp tables

---

src/main/resources/org/broadinstitute/hellbender/tools/gvs/filtering/feature_extract.sql

sql for feature extract needed where for is_loaded = true

Ah check the is loaded field in feature extract

---

.travis.yml

* Adding a comment explaining why we checkout the entire repo history in travis.
* This caused some understandable confusion.  See https://github.com/broadinstitute/gatk/pull/7418
@YunLemon I've added a comment to the .travis.yml file about the depth.  It's definitely a bit weird and confusing if you don't know the history of why we ended up doing that.

Adding comment to .travis.yml about the checkout depth

---

scripts/variantstore/wdl/GvsPrepareCallset.wdl
scripts/variantstore/wdl/extract/create_cohort_extract_data_table.py

fix bad argument processing for bool
fix param name

Fix bool flag in prepare

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl

* disabled localization optional 
* changed datatype from Array[File] to Array[String]
* added parameter for indexes (since they can live in different locations)
* do our own localization in all cases

Support for TDR DRS URIs in Import

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/VariantsToTable.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/VariantsToTableIntegrationTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/IntegrationTestSpec.java

If VariantsToTable is run without any genotype field outputs (or on a vcf with no sample data), the header line contains an extra trailing tab, which is not included in the table rows.   This confuses many tsv parsers, which see the header as having an extra (blank) field, and so complain that the rows of the table do not contain enough fields.
This pr fixes this so that there is no longer a trailing tab in this case.

Remove trailing tab in VariantsToTable output header

---

src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/VetCreator.java

To test I ran this before and after the fix.  Before it would sit there after the line 
```
Tool returned:
0
```
for ~10 minutes before it would time out and exit.  After the fix it shuts down cleanly
```
gatk --java-options -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \
CreateVariantIngestFiles \
-V gs://fc-e2f6ffa2-4033-4517-98fc-889bee4cc7a6/5e6b194b-5f69-40f2-a6de-f4f3f80ce05a/ReblockGVCF/702cdbf7-0666-4ee5-b889-91ba0ffa90bd/call-Reblock/HG00405.haplotypeCalls.er.raw.vcf.gz.rb.g.vcf.gz \
-L chr20:1-100000 \
-IG FORTY \
--ignore-above-gq-threshold false \
--project-id broad-dsp-spec-ops \
--dataset-name gvs_qs_v2_kc \
--output-type BQ \
--enable-reference-ranges true \
--enable-pet false \
--enable-vet true \
-SN ERS4367795 \
--gvs-sample-id 99 \
--ref-version 38 …
```

close vet writer

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorConstants.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRenderer.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUnitTest.java

@jonn-smith Quick one when you get a chance - this fixes some things I noticed on my GATK branch when testing my  new htsjdk `VCFHeader` code. The `Funcotator.checkIfAlreadyAnnotated `code was checking for a header line that was never generated by `Funcotator` AFAICT, and this also ties together the `Funcotator` engine and test code to use the same constants. More could probably be done here but it would require a bigger refactoring.

Align the Funcotator checkIfAlreadyAnnotated test with the Funcotator engine code.

---

scripts/variantstore/wdl/GvsExtractCallset.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java

When running with multiple table (ie _001, _002) this would show up in the logs due to the bigquery client not being closed.  It didn't cause any harm, but is alarming!  Closing the ranges-based readers appropriately now.
```
Nov 23, 2021 5:45:53 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=121, target=bigquerystorage.googleapis.com:443} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrp …
```

close StorageAPIAvroReader appropriately

---

scripts/variantstore/wdl/GvsImportGenomes.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java

Quick PR to use the _default stream for writing to the load_status_table since it (a) commits immediately and (b) doesn't count towards the CreateStreamWriter quota

used _default stream instead

---

src/test/resources/large/mitochondria_references/.gitattributes

Prevent a git lfs error that was caused by accidentally checking storing a .gitattributes file
in gitlfs.
When checkout out the repository for the first time or moving from an old commit to a newish one, there's been an error report from git lfs.  This was caused by accidentally checking a .gitattributes file into git-lfs which then is read as part of the git lfs checkout process, but since the file is tracked by lfs at the point of checkout it is an lfs stub and throws an error.
The problem was introduced here:  #6694
See below to reproduce:
```
git checkout 9951f77c6
git checkout f548ccd708009ddcdfead6525edd23a68d73027b
https://git-lfs.github.com/spec/v1 is not a valid attribute name: src/test/resources/large/mitochondria_references/.gitattributes:1 …
```

Remove file causing git-lfs error

---

scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/LoadStatus.java
src/main/java/org/broadinstitute/hellbender/utils/bigquery/PendingBQWriter.java
src/test/java/org/broadinstitute/hellbender/utils/bigquery/LoadStatusBQTest.java

The BigQuery library upgrade for extract, broke ingest :/  This fixes that.  It also rethrows an exception we were eating that I noticed
The error seen during ingest was
```
java.lang.IllegalArgumentException: JSONObject does not have a bytes field at root.sample_id.
at com.google.cloud.bigquery.storage.v1beta2.JsonToProtoMessage.fillField(JsonToProtoMessage.java:306)
at com.google.cloud.bigquery.storage.v1beta2.JsonToProtoMessage.convertJsonToProtoMessageImpl(JsonToProtoMessage.java:138)
at com.google.cloud.bigquery.storage.v1beta2.JsonToProtoMessage.convertJsonToProtoMessage(JsonToProtoMessage.java:86)
at com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter.append(JsonStreamWriter.java:110)
at com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter.append(JsonStreamWriter.java:9 …
```

Kc fix type

---

src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBOptions.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyper.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCaller.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsIntegrationTest.java

This was unearthed by #7542 and is plumbed correctly in this PR.
Note that we need to still address the broader issue of hooking arguments to GenomicsDB - #6456 . GenomicsDB exposes a whole set of export arguments all added in response of gatk requests, some of them are hardcoded by certain tools(e.g GenotypeGVCFs uses --max-alternate-alleles while SelectVariants does not), many are unused.

Bug with passing max_alternate_alleles to GenomicsDB

---

scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
src/main/java/org/broadinstitute/hellbender/utils/bigquery/PendingBQWriter.java

@mmorgantaylor was seeing 
| Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Rows must be specified.
Due to flush() trying to write an empty buffer

fix empty flush

---

src/main/java/org/broadinstitute/hellbender/cmdline/ReadFilterArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/engine/filters/ExcessiveEndClippedReadFilter.java
src/test/java/org/broadinstitute/hellbender/engine/filters/ExcessiveEndClippedReadFilterUnitTest.java

- Added ExcessiveEndClippedReadFilter - a filter that will keep reads
that have fewer than the specified number of clipped bases on either
end.  This is designed for long reads, and has a default value of 1k.

Added ExcessiveEndClippedReadFilter

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/extract/Dockerfile
scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortRemoveAnnotationsUnitTest.java

Some notes from the 10k tieout:
- ~20 min per full ref_ranges table to insert
- ~7 min per full vet table to insert
- "bytes scanned" are same as data table size
**Original Run - 293 min**
- 103 minutes pulling down data, scanning 237 GB
- 43 min on 20m vet records (20:26 - > 21:09)
-  60 min on 291m vet records (21:09 -> 22:10)
- 190 minutes writing the VCF
**Prepare Extract with minor tuning of sorting  - 134 min**
- 25 minutes pulling down data ( faster), scanning 10 GB (50x reduction)
- 4 min on 20m vet records(02:43 -> 02:47)    - NOTE 103s of that was sorting (44s) and spilling to disk (59 s)
- 21 min on 291m vet records (02:47 -> 03:08) - NOTE 9 min of that was sorting (6 min) and spilling to disk (3 min)
- 109 minutes writing the VCF (this is the change to pre-sort the sample set …

WIP extract for ranges

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl

Dont rely on the length of the sample external name to limit the size of the batches of samples
Before:
After:

VS-268 import more samples at once

---

src/main/java/org/broadinstitute/hellbender/transformers/PalindromeArtifactClipReadTransformer.java

palindrome ITR artifact transformer skips reads whose contigs are not in sequence dictionary

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl

I was bugged by the fact that @rsasch calculated the latest callset read 1957 TB of data via the Read API when we knew the core extract tables were only ~100 TB.  Turns out that 90% of that scanning was actually reading the various un-partitioned, un-clustered VQSR related tables.  Each shard read the entire table (which is ~80 GB), multiplied by 20k shards --> is about 1600 TB of reads.  The cost of that represents ~20% of the total cost of making the 100k callset, so a big cost savings.
Clustering and partitioning these tables allows each shard to just consume the data it needs.

clustering vqsr tables by location

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCFUnitTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/VariantContextTestUtils.java

didn't merge with adjacent block

Fix case where hom-ref "variant" with no data had wrong sized PLs and

---

src/main/java/org/broadinstitute/hellbender/engine/ActivityProfileStateIterator.java
src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java
src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java
src/main/java/org/broadinstitute/hellbender/engine/spark/LocusWalkerSpark.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PileupReadErrorCorrector.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/FilterAlignmentArtifacts.java
src/main/java/org/broadinstitute/hellbender/utils/locusiterator/AlignmentContextIteratorBuilder.java
src/main/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByState.java
src/main/java/org/broadinstitute/hellbender/utils/locusiterator/ReadStateManager.java
src/main/java/org/broadinstitute/hellbender/utils/locusiterator/SamplePartitioner.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/locusiterator/IntervalAlignmentContextIteratorUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateBaseTest.java
src/test/java/org/broadinstitute/hellbender/utils/locusiterator/LocusIteratorByStateUnitTest.java

Closes #1495.  @droazen Adam's comments suggest that this feature has been unused since before GATK 3.  May we put it to rest?

Get rid of ancient, unused option to track unique reads in a LIBS

---

build.gradle

We had removed it because it was shutting down and our tests showed it was unnecessary.   It turns out that it's only unnecessary because we're getting jcenter results cached in the artifactory.  JCenter is now planning to remain online for the immediate future in read only mode so it should be fine to put it back.
Fixes https://github.com/broadinstitute/gatk/issues/7636

Adding back jcenter repository resolver

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/PossibleDeNovo.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/PossibleDeNovoUnitTest.java

PossibleDeNovo checks each trio's genotype (including parent hom ref genotypes) for likelihoods even though it doesn't actually use the PLs. The PLs can get dropped if GVCFs are reblocked which means this annotation no longer works as expected. This changes the check to look for GQs instead of PLs as the GQs are used as part of the annotation.
@ldgauthier Could you please suggest a reviewer?

Fix for PossibleDeNovo annotation to work without Genotype Likelihoods

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsCreateTables.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/extract/populate_alt_allele_table.py

The table names in GvsAssignId were not quoted with backticks, which is fine **except** if your dataset name starts with a number… which is a total valid identifier, but requires quoting.  
Recently we had a customer (AoU) supply a dataset with the name `1kg_wgs` which exposed this problem

Quoting of table names

---

Dockerfile

This should fix the travis failure by forcing lfs to overwrite the existing commit hooks.
The issue seems to be this:
We install lfs in the first part of the travis build, and then we run a docker build and mount the git folder into it.  Docker then installs lfs again.  The problem is occurring because git lfs 3.1.1 which released 2 days ago changed the format of the pre-push and other git hooks.  Then it throws an error when it's installed again and there are hooks that look different than it expects already in place.  Running install with `--force` fixes it.
The lfs devs actually have a system for ignoring these differences, but they forgot to update their list of allowed differences ( or however they match it) in 3.1.1.  They then released 3.1.2  today which fixes this.  In most cases …

install lfs with --force

---

src/main/java/org/broadinstitute/hellbender/engine/filters/MateDistantReadFilter.java
src/test/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibraryUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngineUnitTest.java

Fix bug with MateDistantReadFilter not being configurable

---

scripts/variantstore/TERRA_QUICKSTART.md

I think this is all I need to add?

VS 284 Add prepare step to Quick Start

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/BaseFuncotatorArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorVariantArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationUnitTest.java
src/test/resources/large/funcotator/custom_vc_order_files/bad_vc_name.tsv
src/test/resources/large/funcotator/custom_vc_order_files/custom_vc_expected_out.vcf
src/test/resources/large/funcotator/custom_vc_order_files/custom_vc_input_test.vcf
src/test/resources/large/funcotator/custom_vc_order_files/custom_vc_order_for_int_test.tsv
src/test/resources/large/funcotator/custom_vc_order_files/non_int_sev.tsv
src/test/resources/large/funcotator/custom_vc_order_files/test1.tsv
src/test/resources/large/funcotator/custom_vc_order_files/test2.tsv
src/test/resources/large/funcotator/custom_vc_order_files/test3.tsv
src/test/resources/large/funcotator/custom_vc_order_files/wrong_num_columns.tsv

- Added custom `VariantClassification` severity ordering.  This enables users to have variants annotated consistently in an alternate order by the results of their variant classification.  (user requested)

Added custom `VariantClassification` severity ordering.

---

build.gradle
src/main/java/org/broadinstitute/hellbender/tools/HtsgetReader.java
src/main/java/org/broadinstitute/hellbender/utils/dragstr/STRTableFile.java
src/main/java/org/broadinstitute/hellbender/utils/dragstr/STRTableFileBuilder.java
src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
src/main/java/org/broadinstitute/hellbender/utils/runtime/StreamingProcessController.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/ZipUtilsTest.java
src/test/java/org/broadinstitute/hellbender/utils/gcs/BucketUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/nio/GcsNioIntegrationTest.java

Fixes https://github.com/broadinstitute/gatk/issues/6179

Fix requester pays access by updating the google-cloud-nio library to the latest release

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/common/ExtractTool.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeatures.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/ExtractFeaturesEngine.java
src/main/java/org/broadinstitute/hellbender/utils/bigquery/BigQueryUtils.java
src/test/java/org/broadinstitute/hellbender/utils/bigquery/BigQueryUtilsUnitTest.java

GvsCreateFilterSet.wdl failed recently for Morgan because of this bug. When run in a brand new project, filter model creation fails because we expect the project to have a hard coded dataset named "temp_tables" which is likely does not have. The workaround is simply to manually create one. This ticket removes the need for this dataset altogether.
This is removed, and instead, the default dataset is used (that the many other tables created in this pipeline use as the default)
able to reproduce with a dummy dataset name:
tested here:
https://app.terra.bio/#workspaces/broad-dsp-spec-ops-fc/gvs_testing_ingest/job_history/1dd27d90-82c4-44e6-8172-15c10c8a9c7f

VS-222 dont hard code the dataset name!

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/FilterAlignmentArtifacts.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/Haplotype.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeUnitTest.java
src/test/resources/large/mutect/mito/alleles.vcf
src/test/resources/large/mutect/mito/alleles.vcf.idx
src/test/resources/large/mutect/mito/mito.bam
src/test/resources/large/mutect/mito/mito.bam.bai
src/test/resources/large/mutect/mito/mito_shifted_8000.dict
src/test/resources/large/mutect/mito/mito_shifted_8000.fasta
src/test/resources/large/mutect/mito/mito_shifted_8000.fasta.fai

Closes #7672.
@ldgauthier This is the bug fix for Sarah Calvo.  The allele was lost when trimming caused its haplotype to start with a deletion.  The solution is to inject force-calling alleles after trimming.  Are you able to review?

Fixed a bug where force calling alleles were lost upon trimming by placing allele injection after trimming

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java

There's no such thing as posterior likelihoods

Docs correction in Genotype calc args

---

Dockerfile

* previously the docker build would unnecessarily pull the test files

Docker build only lfs pulls main/src/resources/large

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl

Closes https://broadworkbench.atlassian.net/browse/VS-335

Add task to ExtractCallset that verifies filter_set_name exists in GVS dataset [VS-335]

---

scripts/mutect2_wdl/mutect3_training_data.wdl
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/AssemblyComplexity.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/FeaturizedReadSets.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReferenceBases.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/GatherNormalArtifactData.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/GetNormalArtifactData.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect3DatasetEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/NormalArtifactRecord.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/GetNormalArtifactDataIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java

@takutosato Are you able to look at this?  The two big changes here are 1) data for the M3 normal artifact filter and 2) outputting tensors for M3 as plain text rather than VCF.

Changes to Mutect2 to support Mutect3

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl

Fixing a regression--so that this workflow no longer relies on a temp-tables dataset
Bug show here:
https://job-manager.dsde-prod.broadinstitute.org/jobs/f0a97820-b3e4-47a8-90a5-c699adba94c3
Fixed here: 
https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRS_GVS_write_API_Scale_testing/job_history/29dfa775-1442-419c-a3d4-14c275775ba7

Pass dataset name to gatk ExtractFeatures

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl

Currently, only a public interval list is allowed--this changes that and copies down the SA before the interval list is used
used here:
https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/AoU_DRC_WGS_12-6-21_beta_ingest/job_history/f5ca0b70-1ae2-4e86-b4fc-3d7d19674347 
with interval list: 	gs://prod-drc-broad/beta-release-99k-v3/0000000000-scattered.interval_list

Allow interval lists that require the SA to see

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java

Now users will be better informed as to why the automatic `b37` conversion does or does not take place on their VCFs.
Fixes #7757

Added logging statements to b37 conversion process.

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py
src/main/java/org/broadinstitute/hellbender/tools/gvs/common/SchemaUtils.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortRecord.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortRecordUnitTest.java

This adds call_AD to the prepare step
and in the VCF:

Adding AD for scale testing VS 225 add AD

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl

The syntax is a little 🙁 but this does appear to work. Sample ids should now be assigned according to the sort order of the names of the samples being uploaded in this invocation of `GvsAssignIds` (existing sample ids should not be affected).
Before:
After:

Deterministic Sample ID assignments [VS-371]

---

.dockstore.yml
scripts/variantstore/wdl/GvsWarpTasks.wdl

In a step from CreateFilterSet, I was hitting what looks like an R limit
Longest line length was 101,412 on the failing shard

remove R scripts from filtering

---

.dockstore.yml
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl

We haven't stumbled on this recently because it's only used in the case where we provide a file of sample names to extract
But it shouldn't exist, so I'm cleaning it up
I also cleaned up some of dockstore while here!

Remove an old "temp table" dataset

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java

317 remove excess header values in VCF extract

---

scripts/variantstore/wdl/GvsImportGenomes.wdl

This task was already eligible for retry but only once, this changes the default retries to 3 and makes it an optional workflow input parameter. Incremental improvement toward VS-261.

LoadData `maxRetries` parameterized, default increased [VS-383]

---

Dockerfile

There's a dash missing in what should be the `--include` argument to a `git lfs pull` invocation in the Dockerfile that appears to have the net effect of `git lfs pull` doing nothing at all. This adds back the dash so the command does what it was intended to do, but I was a bit surprised the build doesn't seem to care if the `git lfs pull` actually pulls anything or not. 🤔 
Before:

Fix surprisingly harmless typo in Dockerfile

---

README.md

This was missed in #7754 
@droazen I even updated the all important badge...

Update Readme.md to reflect switch from Travis. 

---

codecov.yml

Repost of #7815 to test the "after_n_builds" functionality

Disable the red "X" from failing codeCov builds and delay the posting of coverage information to complete test.

---

scripts/get_gatk_stats_app_script.gs

This fixes the first day's downloads on a new release which previously were set to 0.
@jonn-smith This is what I was talking about.

fix initial 0 downloads bug

---

scripts/variantstore/wdl/extract/create_variant_annotation_table.py
scripts/variantstore/wdl/extract/test_create_variant_annotation_table.py
scripts/variantstore/wdl/extract/variant_annotation_table_test_files/vat_expected_likely_benign.json

currently clinvar grabs all values in the variants section of the annotation json---this is wrong because nirvana includes clinvar values from all overlapping variants.
this change limits the clinvar values to the correct variant only
and tests the change as well

VS 396 clinvar grabs too many values

---

src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/LoadStatus.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/RefCreator.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/VetCreator.java
src/main/java/org/broadinstitute/hellbender/utils/bigquery/BigQueryUtils.java

Makes CreateVariantIngestFiles robust to partially or fully loaded samples.
Commit 21828af8f5a925cc331dce6093c0d510042d7b64 is what I actually propose to merge, while commit de673204183a4c45059dc9ea4e05868e2ea6ae59 randomly injects failures covering all the known failure modes. I tested these changes using both commits and was able to verify that partially loaded samples were handled correctly on subsequent attempts to load the sample (unfortunately we can't actually prevent these partial loadings from happening in the first place because preemptions, among other possible reasons).

CreateVariantIngestFiles robust to partially / fully loaded samples [VS-262]

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsIngestTieout.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/LoadStatus.java
src/main/java/org/broadinstitute/hellbender/utils/bigquery/BigQueryUtils.java
src/main/java/org/broadinstitute/hellbender/utils/bigquery/CommittedBQWriter.java

The main issue was that the `StatusRuntimeException`s that the baseline error handling code was trying to catch in practice always seem to be wrapped in at least one layer of exception of a different type. There was no catch handing for these wrapper exception types so the `CreateVariantIngestFiles` tool would simply crash.
~The changes here also more generally try to follow the recommendations in the [BQ Write API documentation](https://cloud.google.com/bigquery/docs/write-api#error_handling), in particular `close`ing the `JsonStreamWriter` before retrying error codes not explicitly called out by the documentation.~
EDIT: actually closing the writer didn't work out too well as we use the writer in `PENDING` mode and closing it seems to lose all pending writes. 😬  So in this circumstance …

Ingest Error Handling Fixes [VS-261]

---

scripts/variantstore/InputValidation.ipynb

First cut at a python notebook to validate inputs.

---

.dockstore.yml
scripts/variantstore/TERRA_QUICKSTART.md
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsUnified.wdl

Closes https://broadworkbench.atlassian.net/browse/VS-392

Compute filter scatter [VS-392]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py
scripts/variantstore/wdl/extract/populate_alt_allele_table.py
src/main/java/org/broadinstitute/hellbender/tools/gvs/common/SampleList.java
src/main/resources/org/broadinstitute/hellbender/tools/gvs/filtering/feature_extract.sql

Allow CH to create custom cohorts with a subset of samples
Tested with sample_id=1 (sample name = ERS4367795)
Imported:
In the alt-allele
In the filter:
In the prepare:
In the extract:

remove withdrawn req

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/AdaptiveChainPruner.java

It turns out the java PriorityQueue implementation is is undefined in its behavior when elements are equal. It turns out it was possible for there to be non-deterministic behavior for chains that had identical scores and the same starting vertex (but different paths in the graph. I think this comparator should be airtight now. @davidbenjamin let me know what you think.

Fixed a rare non-determinism in the AdaptiveChainPruner

---

.dockstore.yml
scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl

Add VAT Validation check that aa_change and exon_number are consistentally set.

VS-402. Add VAT Validation check that aa_change and exon_number are consistentally set.

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsUnified.wdl
src/main/java/org/broadinstitute/hellbender/utils/bigquery/CommittedBQWriter.java

Setting a default batch size of 5 since that seemed to work out well in the two Stroke Anderson runs, overridable at the workflow level. Also cleaned up some logging and wrapping exceptions before throwing to avoid confusing stack traces when scanning through logs.

Ingest 10K [VS-344]

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/VetCreator.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/VetFieldEnum.java

- Added parameter to CreateVariantIngestFiles to allow the user to skip VQSR-specific fields.

VET Ingest Validation / Allow Ingest of non-VQSR'ed data

---

scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl

Similar issues to last time. Do we have a test case yet that simulates AoU's usage?
In addition to this, the workflow seems to function on an older version of GVS, as long as I make the following modifications:
- Add columns `sample_info.withdrawn`, `sample_info.is_control`
- Backfill true/false accordingly to these columns (backfilling withdrawn seems unnecessary)

Fix AoU workflow bugs

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl

Updates expectations for the X/Y scaling changes that went in a couple of weeks ago and slip in a few unrelated minor improvements.

Update Quickstart Integration for X/Y scaling changes [VS-464]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl

Integration test successful https://app.terra.bio/#workspaces/broad-firecloud-dsde/VS-415%20GVS%20Quickstart%20Default%20Extract%20Scatter/job_history/73ac71db-0488-46be-a8e8-7f00e795edec

Fix up FQ and race condition issues with volatile tasks work [VS-478]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/PileupSummary.java

Closes #7606.
@lbergelson This addresses the excessive memory issue that you triaged recently.  Would you mind reviewing it?

GetPileupSummaries streams output rather than storing it in memory

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py
scripts/variantstore/wdl/extract/populate_alt_allele_table.py

Label names are standard from https://docs.google.com/document/d/1eyPrpCSCMyf1CaBkc-aDi39xV7Bq9hthh07ludpgPNw
branch adds labels to:
- `bg query` calls in WDL command blocks
- queries run within python scripts called by WDLs
- datasets created with Utils.BuildGATKJarAndCreateDataset
Quickstart integration run here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/15442e08-92af-48bc-ab96-2bdd4f39a801

Add preliminary labels to queries [VS-381]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/Tranche.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/TruthSensitivityTranche.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VQSLODTranche.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/GatherTranchesIntegrationTest.java
src/test/resources/large/VQSR/expected/singleOverflow.tranches
src/test/resources/large/VQSR/expected/testSummedOverflow.tranches
src/test/resources/large/VQSR/test-single-giant-input-snps.tranches
src/test/resources/large/VQSR/test-very-large-one-snps.tranches
src/test/resources/large/VQSR/test-very-large-two-snps.tranches

Type change int -> long to prevent tranche novel variant count overflow

---

src/main/java/org/broadinstitute/hellbender/utils/codecs/SiteDepthBCICodec.java
src/main/java/org/broadinstitute/hellbender/utils/codecs/SiteDepthCodec.java

This was code left over from when we put the sample name in a header line rather than as a column.  It needs to go.

site depth bug

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorIntegrationTest.java

Fixes #7697. Added argument to allow RScriptExecutor to disable but still output Rscript file.

Added argument to disable RscriptExecutor 

---

src/test/java/org/broadinstitute/hellbender/utils/UtilsUnitTest.java

Fixes #7916. Data providers and unit tests for the various overloads of Utils.concat()

Unit tests for Utils.concat() 

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsUnified.wdl

Automatically choose appropriate import batch, preemptible, and max retry values for sample sets up to 20K. This makes 20K samples our effective threshold for where we feel comfortable with the current stability / performance of our import code.

 Rightsize import batches [VS-486]

---

.dockstore.yml
scripts/variantstore/wdl/GvsAoUReblockGvcf.wdl

This PR modifies the AoU-specific WDL `GvsAoUReblockGvcf` to support processing samples whose site_ids (usually lowercase) were sent in as uppercase.

[AoU DRC] Support uppercase site_ids for reblocking

---

scripts/variantstore/wdl/GvsUnified.wdl

unused and complicates the Beta WDL unnecessarily

remove accidentally added input

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsBenchmarkExtractTask.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsCreateVATFromAnnotations.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl

Have updated the gatk override jar with a fresh build (ah_var_store on 7/8/2022)
And updated the docker similarly.

VS_492 - Beta User Jar release

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsCreateVATFromAnnotations.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/workflow_compute_costs.py

```
% python3 workflow_compute_costs.py \
--workspace_namespace 'not' \                            
--workspace_name 'there'                
Traceback (most recent call last):
File "workflow_compute_costs.py", line 135, in <module>
costs = compute_costs(args.workspace_namespace, args.workspace_name, args.exclude)
File "workflow_compute_costs.py", line 32, in compute_costs
submissions = list_submissions(workspace_namespace, workspace_name)
File "workflow_compute_costs.py", line 14, in fapi_list_submissions
return fapi_error_check(fapi.list_submissions(workspace_namespace, workspace_name))
File "workflow_compute_costs.py", line 8, in fapi_error_check
raise Exception(j['message'])
Exception: workspace not/there does not exist or you do not have permission to use it
```

Cost WDL should throw on FISS API errors [VS-518]

---

src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortRecord.java

Code refactoring for better testability as part of the spanning deletions work that is being shelved.  
**Refactoring Changes**
One of the challenges with this PR was testing as the work is really done in the lower-level methods and it would be nice to have this as a unit test rather than an integration/end-to-end test. This motivated the following changes:
- don't write to VCF directly, instead have take a Consumer to emit VariantContexts. This lets us provide a different consumer in unit tests to collect our result.
- we previously had a chain of calls createVariantsFromSortedRanges -> processSampleRecordsForLocation -> finalizeCurrentVariant that returned void and as a side effect wrote to VCF. These deeper methods now return a VariantContext and the writing (via consumer) is done …

refactoring for testablity

---

build_docker.sh
build_docker_remote.sh
scripts/docker/README.md

created a new build_docker_remote.sh script for building the docker image remotely with google cloud build

---

.dockstore.yml
scripts/variantstore/wdl/GvsJointVariantCallsetCost.wdl

Simple WDL with the sole purpose of getting the cost for a callset based on the callset identifier

WDL to extract a single callset cost (BQ only, not Terra)

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsCreateVATFromAnnotations.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/create_variant_annotation_table.py
scripts/variantstore/wdl/extract/extract_subpop.py

Update GvsCreateVAT.wdl to build the subpopulation-specific files from the input ancestry file.
Have GvsCreateVAT.wdl only pull fields from the VCF for the selected subpopulations.
Update create_variant_annotation_table.py to set empty population-specific AC/AN/AF, etc. values if population is not present.

GL-548 - Update CreateVat code to handle samples that do not contain all population groups.

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl

Reverts VS-569 now that Temurin downloads are working again, leaves in the Corretto breadcrumbs and minor improvements like `-o xtrace`.

Restore Temurin 11 [VS-570]

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl

Successful run here: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/96ceaff0-810a-4e79-a59d-2f5d8405d487

Add table size check to quickstart integration test [VS-501]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngineUnitTest.java

Fixes issue reported in #6605
If a germline resource vcf (such as gnomad) used when running Mutect2 includes a variant record without the AF attribute in  its info field, this can lead to an IndexOutOfBoundsException.  This PR fixing this, and adds a warning when this is the case.

Fix Mutect2 IndexOutOfBoundException with germline resource

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsExtractHailAvroFiles.wdl

Successful run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/999fbeeb-af94-4970-8586-11f1de906bb5).

WDL to extract Avro files for Hail import [VS-579]

---

.dockstore.yml
scripts/variantstore/wdl/GvsAoUReblockGvcf.example.inputs.json
scripts/variantstore/wdl/GvsAoUReblockGvcf.wdl
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsBenchmarkExtractTask.wdl
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsCreateTables.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsIngestTieout.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsRescatterCallsetInterval.wdl
scripts/variantstore/wdl/GvsUnified.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/GvsWithdrawSamples.wdl
scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py
scripts/variantstore/wdl/extract/populate_alt_allele_table.py

Removed usage of service account from:
GvsAssignIds.wdl
GvsImportGenomes.wdl
GvsCreateAltAllele.wdl
GvsCreateFilterSet.wdl
GvsWithdrawSamples.wdl
GvsCreateAltAllele.wdl
GvsPrepareRangesCallset.wdl
GvsExtractCallset.wdl
GvsExtractCohortFromSampleNames.wdl
GvsUnified.wdl
GvsJointVariantCalling.wdl
GvsAoUReblockGvcf.wdl
GvsBenchmarkExtractTask.wdl
GvsRescatterCallsetInterval.wdl

Removed usage of service account from WDLs

---

scripts/variantstore/GVS_CLEANUP.md
scripts/variantstore/beta_docs/gvs-cleanup.md

Documents steps to clean up GVS assets in the following use case:
- the samples in the callset are going to be joint called once (no sub-cohorts, no re-using the model)
- the outputs (VCFs, indexes, interval lists, manifest, sample name list) have all been copied to an independent location (not in the workspace bucket)
- no need to maintain provenance
- the workspace where the pipeline was run is only being used for this GVS callset

Document steps for GVS cleanup for base use case [VS-586]

---

scripts/variantstore/wdl/GvsImportGenomes.wdl

Change backticks to single quotes in several error messages - causing shell to attempt to execute.
```
/cromwell_root/script: line 26: load_data_batch_size: command not found
Importing 25000 samples but  not explicitly specified; limit for auto batch-sizing is 20000 samples.
```

Change backticks to single quotes in several error messages

---

.dockstore.yml
scripts/variantstore/AOU_DELIVERABLES.md
scripts/variantstore/TERRA_QUICKSTART.md
scripts/variantstore/wdl/GvsBenchmarkExtractTask.wdl
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateAltAllele.wdl
scripts/variantstore/wdl/GvsCreateTables.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsIngestTieout.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsUnified.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/populate_alt_allele_table.py

- changed CREATE OR REPLACE TABLE to CREATE TABLE IF NOT EXISTS for `alt_allele`
- pass around max sample id already in `alt_allele` to figure out which `vet_` table to start with and what sample IDs data to grab
- tied out by comparing `gvs-internal.rsa_gvs_quickstart_dev.alt_allele` (done with existing version) vs. `gvs-internal.rsa_gvs_quickstart_dev.alt_allele_incremental` (done in two batches with code from this branch)
- renamed WDL to GvsPopulateAltAllele
Closed https://broadworkbench.atlassian.net/browse/VS-52

Allow for incremental addition of data to alt_allele [VS-52]

---

.dockstore.yml
scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl

In the VAT validation, give clearer error msg about which clinvar classification values are missing

clearer error when values are missing

---

.dockstore.yml
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl

Test run here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/7f2307e7-684d-45d7-a4e7-852a666ec440

Make CreateAltAlleleTable task volatile

---

.dockstore.yml
scripts/variantstore/wdl/GvsWithdrawSamples.wdl

Given a list of samples for a callset, withdraw samples from GVS that are not included by marking them as 'withdrawn' in the sample_info table with a passed in timestamp.
Test run here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/568919e6-3c51-4ce9-978c-75ffc5ff9997

File of callset samples -> samples marked as 'withdrawn' in GVS [VS-436]

---

scripts/variantstore/AOU_DELIVERABLES.md

Correct the number of CPUs to request from Google quotas for AoU callsets

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl

To address scalability failings with unbatched Avro exports.

Batched Avro export [VS-630]

---

.dockstore.yml
scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl

Simply replaced a custom version of the task with a standard one we are using elsewhere
Original run:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20hatcher/job_history/193c7c2b-2d29-4bab-8abc-6ab85a2f5270
Run from the modified branch:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20hatcher/job_history/575121f1-07e9-4821-bb20-35b6ed430560
Both ran within my quickstart workspace, but were pointed at George's dataset.  Both failed the same two predicted tasks.

VS-517   Use standard version of GetBQTableLastModifiedDatetime in GvsValidateVat

---

scripts/vcf_site_level_filtering_cromwell_tests/vcf_site_level_filtering_travis.json
scripts/vcf_site_level_filtering_wdl/JointVcfFiltering.wdl

- adds allele specific option
- handles empty VCF inputs to `ScoreVariantAnnotations`

Small updates to JointVcfFiltering WDL

---

.dockstore.yml
scripts/variantstore/wdl/GvsJointVariantCalling.wdl

I made it a non-optional paramater, but also have it defaulting to "FORTY" so beta users will have the same experience they did before by default, but we can override it trivially if we ever need to use a different drop state

Ah 617 exposing the drop_state parameter to the GvsJointVariantCalling wdl used for beta (and internal customer)

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsWarpTasks.wdl

Expose the maximum-training-variants parameter for both INDEL and SNP model creation in the `GvsCreateFilterSet` WDL.
Closes https://broadworkbench.atlassian.net/browse/VS-634

Expose maximum-training-variants VQSR parameter [VS-634]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCallsetStatistics.wdl
scripts/variantstore/wdl/extract/Dockerfile

Successful Quickstart run [here](https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/160b0035-c84e-4e54-a343-0e9c570c1da1), has not yet been run on larger datasets.

Callset statistics [VS-560]

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl

- go back to `drop_state` of "FORTY"
- add sort to table size check SQL to make sure the order is deterministic 
- use alpine SDK docker
- turn off `xtrace` on already chatty bash
successful run here: https://job-manager.dsde-prod.broadinstitute.org/jobs/7b8e1506-771d-425f-b545-6e0411b6f7c0

Small updates to GVS Integration WDL [VS-618]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/Dockerfile
scripts/variantstore/wdl/extract/build_docker.sh

Successful integration run https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/c711a4cf-ac33-4c93-a4b7-b46b2796f090

Alpine based Variant Store Docker image [VS-648]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCallsetStatistics.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl

FAILED runs with bad filter names:
- [GvsExtractAvroFilesForHail](https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/f01e2333-e1f8-4af9-b1e7-1b6e083b2f4b)
- [GvsCallsetStatistics](https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/7cc74c35-2aa4-4542-87b0-49718073a0f6)
Successful runs with good filter names:
- [GvsExtractAvroFilesForHail](https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/200d9e46-2fc3-466e-88c9-36c37515d167)
- [GvsCallsetStatistics](https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/f79c1e6a-5d7c-429a-a573-330ca3ba19b1)

Fail Avro extract and callset stats on bad filter name [VS-655]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/ExtractVariantAnnotations.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/LabeledVariantAnnotationsWalker.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/ScoreVariantAnnotations.java

Ticks off a few straggler issues noted in #7724.
@meganshand mind reviewing? Hopefully should be quick and we can get it in before @droazen cuts the next release. Note that this shouldn't change behavior in the Ultima pipeline, as the default toggle is still the same start-position resource-matching strategy inherited from VQSR, but we might want to explore the effect of choosing another strategy there.

Added toggle for selecting resource-matching strategies and miscellaneous minor fixes to new annotation-based filtering tools.

---

build.gradle
src/main/java/org/broadinstitute/hellbender/engine/spark/GATKRegistrator.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/StrandCorrectedAllele.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleAndContext.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/InverseAllele.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/FlowBasedHaplotype.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/Haplotype.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/testers/SamFileTester.java

This upgrades htsjdk to v3.0.0 which was attempted in #7867 and then reverted in #7960 in order to unblock the jukebox merge.

Upgrade htsjdk to v3.0.1 and picard to 2.27.5

---

scripts/variantstore/wdl/GvsJointVariantCalling.wdl

Updating the beta workflow to use the latest jar, representing the version of GATK tested against the quickstart workflow

VS-665 updating beta workflow to use changes tested in quickstart

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl

Integration run [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/76c46310-3c0d-43a8-9fce-072ef7750651).
As written the task requires `apt-get`. Converting this to Alpine would be non-trivial and not really worthwhile as it might even take longer to build all the extra things into the `alpine` image that we simply download with the `slim` image.

Revert Alpinizing of apt dependent task [VS-688]

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/utils/MergeAnnotatedRegions.java
src/test/java/org/broadinstitute/hellbender/tools/copynumber/utils/MergeAnnotatedRegionsIntegrationTest.java

Documentation specifies that a reference is required; this PR enforces this requirement.

require reference as asserted in documentation

---

build.gradle

* This updates us from commons-text:1.6.0 -> 1.10.0 to fix a vulnerability
* fixes https://github.com/broadinstitute/gatk/issues/8060

Add constraint to transitive dependency commons-text

---

.dockstore.yml
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/Dockerfile

Apparently I broke the inclusion of VAT schema JSONs in our Docker image when I was redoing the Dockerfile recently. Integration run [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/b270ddee-1bc8-4488-bc60-79d0cb82797e).

Fix missing vat schema JSONs [VS-699]

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl

Integration run [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/5bcd1072-f9c4-4885-805b-a29091e27791).

Fix integration expectations for fixed AD [VS-689]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCallsetStatistics.wdl

Lee has given us a list of columns that are no longer needed in the call set statistics file. This PR removes them.

VS-698 Remove unnecessary columns from Call set statistics

---

.github/workflows/carrot_run_test_from_pr_comment.yml

Updated the carrot github action workflow to the most recent version, which supports using #carrot_pr to trigger branch vs master comparison runs

Updated carrot publish github action version

---

src/main/java/org/broadinstitute/hellbender/exceptions/UserException.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotatorEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculators.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeLikelihoodCalculatorsUnitTest.java

The behaviour had been switched to warning

VariantAnnotator fails when the variant contains too many alleles

---

.github/actions/upload-gatk-test-results/action.yml

Fixing the path reported by the gatkbot when there are test failures

---

.dockstore.yml
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateVAT.wdl
scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py

Since we might need to run the GvsPrepareRangesCallset.wdl in the future just to help to get the callset stats, add an optional input to not create the __REF_DATA and __SAMPLES tables, since those won't be needed.
Test runs: 
- [with](https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/1ee2bc37-abd4-4185-a17d-e1f6b47a6914) `skip_ref_ranges_tables ` set to `true`:
- [with](https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/2849dfd1-fe41-4757-83f3-fc0f5451eaef) `skip_ref_ranges_tables ` set to `false`
- [with](https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/5e8c5c4d-6ae5-4117-a5ea-89a05d379cfd) `skip_ref_ranges_tables ` not set (default is false)
- [GvsCallsetStatistics …

Add option to not prepare __REF_DATA table to Prepare [VS-697]

---

.dockstore.yml
scripts/variantstore/docs/aou/vds/Removing Samples from a VDS.md
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl

(also fixed a broken link in [Removing Samples from a VDS.md](https://github.com/broadinstitute/gatk/compare/ah_var_store...rsa_vs_749#diff-74ddd9f71eec0cc8080c093e76fbecdb3fa8b9d443e7071591b635e3d47afca5))
test run here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/d2957947-0249-4197-9531-0b4203f2ea1c

Check for control samples in AVRO export [VS-751]

---

scripts/variantstore/variant_annotations_table/README.md

Update the VAT pipeline readme to know about the VDS inputs
This will need to further be edited once George's VDS VAT pipeline changes have been completed

VAT Readme updates

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java

Hello - we're interested in creating a custom extension of Funcotator with different output formats. This PR should be quite low risk - it just converts a handful of privates fields/methods to protected to make it easier to extend this tool.

Make several Funcotator methods and fields protected instead of private

---

build.gradle
src/main/java/org/broadinstitute/hellbender/cmdline/DeprecatedToolsRegistry.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerReadThreadingAssemblerArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/utils/help/GATKGSONWorkUnit.java
src/main/java/org/broadinstitute/hellbender/utils/help/GATKHelpDoclet.java
src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.index.template.html
src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/generic.template.html

Upgrades Barclay to 4.1.0. Adds an `@DeprecatedFeature` annotation that can be applied to any `@DocumentedFeature` or `@Argument`, and updates the handful of such features that are already tagged with the standard Java annotation `@Deprecated` to use the new annotation. Mutually exclusive with `@Beta` and `@Experimental`.
The output for `--use-new-qual-calculator`:

Add DeprecatedFeature annotation.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariants.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantTrain.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNVariantWriteTensors.java

The CNN tools launch python immediately even when they're just instantiated, rather than waiting until the tool actually starts executing. This can cause some build tasks (gatkDoc, gatkWDLGen, etc.) to fail if python isn't available.

Don't require python to just instantiate tool classes.

---

src/main/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilter.java
src/test/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilterUnitTest.java

Added a slightly more helpful error message to the reads filter

---

Dockerfile
src/main/java/org/broadinstitute/hellbender/utils/runtime/ProcessControllerAckResult.java
src/test/java/org/broadinstitute/hellbender/utils/runtime/ProcessControllerAckResultUnitTest.java

Fixes NPE reported in https://github.com/broadinstitute/gatk/issues/7811.

Test for presence of ack result message and simplify ProcessControllerAckResult API

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormalsIntegrationTest.java

Since GenomicsDB can be used with `CreateSomaticPanelOfNormals`, allow for the GenomicsDBArgumentCollection to be exposed with this tool.

Expose GenomicsDBArgumentCollection with CreateSomaticPanelOfNormals

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PileupDetectionArgumentCollection.java

- Added minValue and maxValue to the pileup arguments
- fixed documentation for pileup arguments to avoid using "percentage"

Small improvements to the pileup arguments

---

scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl

Removed commented lines from somatic CNV WDL.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/VariantAnnotator.java

I did a regex-search for other instances where we got this wrong in documentation and couldn't find any other obvious examples of this mistake anywhere else in our documentation. 
Fixes #8143

Fix minor documentation mistake in VariantAnnotator

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/hgdb_sv_multi_sample_mini.vcf

This PR is an attempt at improving SelectVariants by
- Rewriting unclear code;
- Adding documentation where needed; and
- Adding tests.
The initial motivation for this code change (#7497) was to improve performance of SelectVariants by adding an option to do the "INFO-level filtering" before doing "genotype filtering." Our assumption was that this would improve performance because  then we would avoid the expensive genotype "fully-decode" operation, which turns string format fields into appropriate object/types (int, array, etc.). This is (we think) done in `VariantContext.fullyDecode().`
This turned out not to be possible for the following reasons. First, there are roughly four types of genotype subsetting you could do:
a) By the sample names (`--sample-name NA12878`)
b) JEXL (`--select …

SelectVariants JEXL filter fixes and refactor

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngine.java

* Fixes #https://github.com/broadinstitute/gatk/issues/8158

Fix NPE from unintialized logger in GenotypingEngine

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java

Make several Funcotator methods and fields protected so it is easiest to extend the tool

Make several Funcotator methods and fields protected

---

scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/extract/hail_gvs_import.py

We now want to fully update the AoU documentation so that a VDS can be created  (no VCFs!)

VS-530 VDS creation documentation for AoU

---

.dockstore.yml
scripts/variantstore/wdl/GvsImportGenomes.wdl

Limiting scattering size in ingest to keep beta customers under quota.
Successful run on NHGRI AnVIL dataset: https://app.terra.bio/#workspaces/gvs-dev/NHGRI_AnVIL_3K%20hatcher/job_history/a9c2a81b-d81c-4f7a-a433-4096ccc7b579
Quota behavior during successful run:
Next successful run after minor refactoring: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Tiny%20Quickstart%20hatcher/job_history/8a34477f-af3b-4e19-8184-862ed1c2cba3

VS-816 Keeping ingestion under quota

---

src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java
src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java

* Exceptions thrown by a tool can be hidden by unsafe close methods throwing additional exceptions.
Avoid this by making use of try-with-resources suppressed exception handling in order to surface the
primary exception as well as the secondary ones.
* Fixes #528

Prevent close from hiding causal exceptions #528

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/qc/TransferReadTags.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/qc/TransferReadTagsIntegrationTest.java

TransferReadTags will throw an exception if the unaligned bam has no read.  This pr will allow the unaligned bam to have 0 reads, as long as the aligned bam also has 0 reads, which will result in an output bam which is just a copy of the aligned bam, with 0 reads.

Allow empty input in TransferReadTags

---

src/main/java/org/broadinstitute/hellbender/engine/filters/VariantTypesVariantFilter.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariantsIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/expected/testSelectVariants_VariantTypeSelectionForGVCF.vcf
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/SelectVariants/gvcfExample.g.vcf

Dependent on HTSJDK release after https://github.com/samtools/htsjdk/pull/1544
Fixes #7111 
- Added optional argument `--ignore-non-ref-in-types` to support correct handling of VariantContexts that contain a NON_REF allele
- Default behavior does not change
- Note that this only enables correct handling of GVCF input. The filtered output files are VCF (not GVCF) files, since reference blocks are not extended when a variant is filtered out
- Added integration test

Enabled GVCF type filtering support in SelectVariants

---

.dockstore.yml

Adds cloud-optimized (scattered) version of gcnv case wdl to the dockstore file. Should be equivalent to the regular case workflow, just faster.

Added scattered gcnv case wdl to dockstore file

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantDataManager.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibrator.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/VariantRecalibratorIntegrationTest.java

Modified VariantRecalibrator to only use a deduped version of the annotations list provided by the user once the list has been deduped.  Previously it was still sometimes using the list that could have duplicates
Fixes #8226 
Also fixed the logger warning that prints the duplicate annotations.

Fixed issue causing VariantRecalibrator to sometimes fail if user provides duplicate `-an` options

---

scripts/variantstore/docs/aou/vds/Creating a VDS.md
scripts/variantstore/docs/aou/vds/vds_validation.py

This includes:
* the GQ0 --> no call conversion
* the setting of the max ref block size (already 1000, but need to let the VDS know)
Bonus:
a validation script for the VDS itself

Vs 822 Add documentation for the work that we did on the latest iteration of Delta

---

.dockerignore
Dockerfile
scripts/docker/gatkbase/Dockerfile

I've updated the image and it seems to be working locally.  Now for the true test...

Update base image

---

.github/workflows/gatk-tests.yml

This should add an exclusion for tests so they don't run when only the var store scripts are changed.

Stop tests from running when only variant store scripts are touched

---

src/main/java/org/broadinstitute/hellbender/metrics/InsertSizeMetrics.java
src/main/java/org/broadinstitute/hellbender/metrics/QualityYieldMetrics.java
src/main/java/org/broadinstitute/hellbender/metrics/analysis/AlleleFrequencyQCMetric.java
src/main/java/org/broadinstitute/hellbender/metrics/analysis/BaseDistributionByCycleMetrics.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/loggers/PSFilterMetrics.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/loggers/PSScoreMetrics.java
src/main/java/org/broadinstitute/hellbender/utils/help/GATKHelpDocWorkUnitHandler.java
src/main/resources/org/broadinstitute/hellbender/utils/helpTemplates/metrics.template.html

Reflect the changes from https://github.com/broadinstitute/picard/pull/1782 in the GATK doc build.
Note that this requires a new version of Picard that is not yet released. Also, I suppressed deprecation warnings caused by the use of obsolete Java 8 javadoc classes (FieldDoc) for now, since it causes the Java 11 build to fail.
A new metrics category shows up in the doc now, with all of the Picard and GATK metrics:

Mirror of Picard metrics documentation generation changes.

---

.dockstore.yml
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPrepareBulkImport.wdl
scripts/variantstore/wdl/extract/generate_FOFNs_for_import.py
scripts/variantstore/wdl/extract/requirements.txt

The goal of this PR is to adjust the ingest in two ways:
1. To update the ingest to loop through all samples (not just the first 10k)
2. To update the ingest to be far more efficient in a few ways:
- To remove the files that are downloaded to each vm so that they do not carry around the extra weight
- To check that the samples in the fofns have not been ingested already so that additional work doesn't need to be done toward processing those samples.
There is still work to do around making the bulk ingest process significantly more user-friendly

Rc vs 778 spike import limit

---

.dockstore.yml
scripts/variantstore/variant_annotations_table/GvsCreateVATFilesFromBigQuery.wdl
scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsBenchmarkExtractTask.wdl
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCallsetStatistics.wdl
scripts/variantstore/wdl/GvsCreateTables.wdl
scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsIngestTieout.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/Dockerfile
scripts/variantstore/wdl/extract/build_base.Dockerfile

Integration run kicked off [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/e706347d-cae4-4138-a5a3-34692b39ae89). Previous versions completed successfully but failed cost comparison because the name of the WDL step changed and was unrecognized by the branches of the comparison code that cut slack.

Update variants base image [VS-866]

---

scripts/variantstore/tieout/legacy_wdl/JointGenotyping.wdl
scripts/variantstore/tieout/legacy_wdl/JointGenotypingTasks.wdl

Modern versions of womtool don't tolerate task inputs with the same name as task outputs and produce baffling error messages like [this](https://broadinstitute.slack.com/archives/C4GSMFXS9/p1654807836682679).

Prep for modern womtool [VS-860]

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java

Added guidelines for resource usage that we use for running gCNV to GermlineCNVCaller doc. This addressed #6166.

Added resource usage section to the GermlineCNVCaller java doc.

---

src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortTest.java

- Make test `public` so it can be run within IntelliJ.
- Make test clean up after itself.

ExtractCohortTest fixups [VS-860]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/common/SchemaUtils.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortLite.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortLiteEngine.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortLiteFilterRecord.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/filtering/CreateFilteringFiles.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java

Remove the unneeded SCORE field from the filter_set_info_vqsr table.
The SCORE field was added to the filter_set_info_vqsr_lite table during debugging at Sam’s behest. It is the value that is used internally to determine the CALIBRATION_SENSITIVITY which is the primary ‘score’ of vqsr_lite. It can be removed now that we are done with debugging an issue we had earlier in development.

VS-838. Remove the unneeded SCORE field from the filter_set_info_vqsr table

---

.dockstore.yml
scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl

Add additional validation around duplicated rows in the VAT
This has a successful run (except for one failure that is because it's being run on way less data)
https://job-manager.dsde-prod.broadinstitute.org/jobs/07ddde58-ac0d-4229-9f96-d093f5c11682
The failed test is:
SpotCheckForAAChangeAndExonNumberConsistency
Perhaps we want to update this to not run this test if there are less than 10k samples?
Yes we do:
Here's the ticket for that:
https://broadworkbench.atlassian.net/browse/VS-878

VS-775 vat validation shards

---

scripts/variantstore/wdl/extract/build_build_base_docker.sh
scripts/variantstore/wdl/extract/build_docker.sh

tl;dr Added sanity checks, a smoke test, and fixed sample invocations in Docker build scripts.
Last month I built a bad base image when I was unsuccessfully trying to combine GCP and Azure CLIs in one image. What's worse is I seem to have tagged this broken image with a tag previously used for a good version of the image. These changes harden the Docker image build script to refuse to write over an existing tag and execute a smoke test against the image before pushing to GCR. While I was in there I also fixed the sample invocations that we saw during mobbing did not work on all versions of `date`.

Sanity check variantstore images before publishing [VS-889]

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl

Passing run with VQSR Lite [Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/833a38e1-c3c9-427b-bda9-6d7a3c1cd9e6)
Passing run with VQSR Classic [Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/696194c7-4b17-4612-9391-7d9af7c7b1f8)

VS-895. Add VQSR lite support to 'extract cohort by sample names'

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/extract/gvs_avros_to_vds.py
scripts/variantstore/wdl/extract/hail_gvs_import.py

The first step of taking this code from the Hail team is just pasting it into our repo
Successful run:
https://job-manager.dsde-prod.broadinstitute.org/jobs/49d62f48-2dee-417c-aa65-411cbe47be17
GvsQuickstartHailIntegration--we remove the whl from the integration test---sure seems like we wont need one going forward!
Another ticket will be made for these next steps:
Likely this will need to end up in our docker image and the WDL that creates the Avro files can make a version of the input for this scripts instead
Next we will want to remove the Tranches calculations and instead of that value passed in as yet another parameter
Phasing and dropping GQ0

Add python script to our repo

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl

Doesn't appear to be comparing the VCFs, only the headers.

Fix potential bug in VCF Integration test

---

.dockstore.yml

To resolve this issue: https://discuss.dockstore.org/t/dockstore-automatic-sync-stopped-working-for-new-tags/7037/2
Basically when "filters/branches -master" was added to the dockstore all tags were filtered out as well, and no tags have been synced since the change happened. According to the dockstore people adding a tags filter matching all tags should resolve.

added tags to dockstore.yaml

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/ReferenceConfidenceVariantContextMerger.java

This is intended to tide the GVS team over until https://github.com/broadinstitute/gatk/issues/8317 is fixed.

Add a mergeWithRemapping() method in ReferenceConfidenceVariantContextMerger to perform allele remapping prior to genotyping

---

.dockstore.yml
scripts/variantstore/docs/Build Docker from VM/building_gatk_docker_on_a_vm.md
scripts/variantstore/variant_annotations_table/README.md
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsPrepareBulkImport.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/alt_allele_temp_function.sql
scripts/variantstore/wdl/extract/hail_create_vat_inputs.py

The empty alts that results from overtrimming in an alt allele UDF correlate strongly with VAT / alt allele mismatches, but from trial runs with and without this patch they don't seem to actually be causing the mismatches. Nonetheless I think this is a desirable change as it keeps VAT VIDs from getting weird. VIDs have the format `<contig>-<position>-<ref>-<alt>`; if the alt is empty the VID just ends in a dash which just seems like an edge case waiting to break something.

No empty alts if you please [VS-918]

---

build.gradle
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GATKGenomicsDBUtils.java

Move to using [GenomicsDB Release 1.5.0](https://github.com/GenomicsDB/GenomicsDB/releases/v1.5.0). 
Highlights in the release relevant to gatk are
-  [readthedocs](https://genomicsdb.readthedocs.io/en/latest/) for GenomicsDB design/usage/functionality - GenomicsDB/GenomicsDB#265.
- GenomicsDB/GenomicsDB#284
- GenomicsDB/GenomicsDB#271
- Exclude spark from genomicsdb core jar GenomicsDB/GenomicsDB#281
- General improved performance/logging.

Move to using GenomicsDB 1.5.0

---

scripts/variantstore/wdl/GvsJointVariantCalling.wdl

also exposing beta user flag, but as tighter_gcp_quotas so broad internal users can still get full speed ingest if they set it to false

wiring through the option for VQSR-Lite 

---

.github/workflows/gatk-tests.yml
build.gradle

- Change coordinates for xgboost artifact as the JCenter version has gone AWOL.
- "Borrow" Chris Norman's work for freeing up space on the GHA runner.

ah_var_store housekeeping

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleLikelihoodWriter.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/ramps/RampUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java
src/main/java/org/broadinstitute/hellbender/utils/Utils.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/Haplotype.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/PartiallyDeterminedHaplotype.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/haplotype/HaplotypeUnitTest.java

@jamesemery Getting into the `PartiallyDeterminedHaplotypeComputationEngine` now.  No change in output here.  I don't think there's anything controversial here.  The commit history is discrete and pristine.
My next DRAGEN PR might be where the fun begins.

Innocuous housekeeping changes in the partially determined haplotypes code

---

src/main/java/org/broadinstitute/hellbender/tools/sv/SVCallRecord.java
src/main/java/org/broadinstitute/hellbender/tools/sv/SVCallRecordUtils.java
src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVLinkage.java
src/test/java/org/broadinstitute/hellbender/tools/sv/SVCallRecordUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/SVTestUtils.java

Adds some flexibility to the allowed split-read strand annotations on SV records:
- Allow INS -+ strands
- Allow INV null strands
- When clustering, only require that strands match for INV/BND records
The changes affecting INS variants are commensurate with changing going into gatk-sv (see https://github.com/broadinstitute/gatk-sv/pull/553).
Added tests for the new functionality and improved some unit test coverage for a few related cases.

Update SV split-read strand validation and clustering

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngine.java

@jamesemery The fun begins.  No change in output yet, but a non-trivial change in implementation.
Instead of making preliminary event groups according to overlap, then merging them according to mutually excluded events, this PR does it all in one step while automatically handling transitivity by treating as a matter of finding connected components of a graph whose vertices are events and whose edges are reasons (overlap and mutex) for events to be in the same event group.
All the failures are from WDL tests.  I assume those are not related.

graph method for PDHMM event groups that unifies finding/merging and overlap/mutual exclusion

---

scripts/vcf_site_level_filtering_cromwell_tests/run_vcf_site_level_filtering_wdl.sh
scripts/vcf_site_level_filtering_cromwell_tests/vcf_site_level_filtering.json
scripts/vcf_site_level_filtering_wdl/JointVcfFiltering.wdl
src/main/java/org/broadinstitute/hellbender/utils/gvs/bigquery/BigQueryResultAndStatistics.java
src/main/java/org/broadinstitute/hellbender/utils/gvs/bigquery/BigQueryUtils.java
src/main/java/org/broadinstitute/hellbender/utils/gvs/bigquery/GATKAvroReader.java
src/main/java/org/broadinstitute/hellbender/utils/gvs/bigquery/StorageAPIAvroReader.java
src/main/java/org/broadinstitute/hellbender/utils/gvs/bigquery/StorageAPIAvroReaderAndBigQueryStatistics.java
src/main/java/org/broadinstitute/hellbender/utils/gvs/bigquery/TableReference.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java
src/test/java/org/broadinstitute/hellbender/utils/gvs/bigquery/BigQueryUtilsUnitTest.java

A collection of changes in non-GVS packages required to build a working version of GVS against master:
1. Support for an optional monitoring script for VQSR Lite `JointVcfFiltering.wdl`.
2. `VQS_SENS_FAILURE_PREFIX ` VCF header value updated for correctness.
3. Moved all BigQuery classes under a `gvs` package to make clear these are currently considered to be GVS specific.
4. Added method to BigQueryUtils.
5. ~ExcessHet calculation fixes for the case of no PLs.~ Removed, no longer required with Annotation changes in `ExtractTool`.

Non-GVS bits required for GVS [VS-971]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/GvsWarpTasks.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java

This PR fixes a bug I found in testing. I was extracting all the samples for an Exome run and it was widely scattered. So there occurred a situation where there no VET entries in one of the shards and a NPE happened.
This PR fixes that and makes it tool generate an empty (well, has a header) VCF, which the GVS workflow can handle.
Failing workflow showing the problem [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Exome%20Data%2049k/job_history/9f821329-f2bd-487c-a9af-4a81d0716072).
Passing workflow (after the fix) [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Exome%20Data%2049k/job_history/52ecbbaa-199d-413b-95fe-2a3285462b43)
Passing Integration Test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/a2f67baa-9613-4c4e-be3b-85a1b25 …

VS-942.  Fix an error where NO variants were found

---

.github/actions/purge-runner-disk/action.yml
.github/workflows/gatk-tests.yml

Add a github action to free up runner space for all jobs.

Free up space on github actions runners for all jobs.

---

scripts/gatkcondaenv.yml.template

- Pinned joblib to v1.1.1 because versions after this one no longer support the version of python in the env (3.6).

Pinning joblib for compatibility with python version

---

scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

due to error `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects` during RevertSam step in MitochondriaPipeline.wdl @meganshand

created variable for user to specify java heap size in picard

---

scripts/mitochondria_m2_wdl/AlignAndCall.wdl
scripts/mitochondria_m2_wdl/AlignmentPipeline.wdl
scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl

change runtime attrs to args

---

src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVCollapser.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVCluster.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVCollapserUnitTest.java

Implements allele collapsing for "breakend replacement" BND alleles, as described in section 5.4 of the [VCFv4.2 spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf).
Also:
- Validates symbolic alt allele for non-BND SV classes when attempting to collapse multiple alt alleles.
- Greatly improves unit test coverage for `CanonicalSVCollapser`.

Add support for breakend replacement alleles in SVCluster

---

scripts/get_gatk_stats_app_script.gs

- Now will count downloads of all artifacts in github releases instead of just the first one.

Fixed bug in download metrics script.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCFIntegrationTest.java

Adds argument to remove FORMAT level annotations from every genotype in the GVCF (for example, for removing the G-length PRI annotation in dragen GVCFs).
Also adds check to make sure the input VCF is a GVCF rather than a single sample VCF.

ReblockGVCFs cleanup

---

.dockstore.yml
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsCallsetCost.wdl
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/GvsVQSRClassic.wdl
scripts/variantstore/wdl/extract/generate_fofn_for_import.py

Also updated GATK docker to latest.
Latest run with missing columns [here](https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/d9e5ec21-da22-42de-944c-a43ccf83e220) to show what "failing" looks like.
Quickstart integration failed because of https://broadworkbench.atlassian.net/browse/VS-1010.

Update logic around missing sample data in TDM [VS-997]

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl

Integration run here: https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%203%20samples/job_history/acb5b878-af45-443d-8139-0f0044cbcb38
The basic problem: https://news.ycombinator.com/item?id=9255830
Repro:
```
% # make a file shaped like what was failing in ingest
% for i in $(seq 50000)
do   
echo foo,${i} >> file.csv
done
% # repro the pipeline that was failing
% set -o pipefail
% cat file.csv | cut -d, -f2 | sort -r -n | head -1
50000
% echo $?
141
% # repeat with temp file construct
% head -1 <(cat file.csv | cut -d, -f2 | sort -r -n)                              
50000
% echo $?
0
%
```
```

Fix AssignIds pipefail with `head` [VS-1011]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngine.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/PartiallyDeterminedHaplotype.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngineUnitTest.java

@jamesemery Here's another fun one, again no change in output but significant refactoring of `constructHaplotypeFromVariants` and `createNewPDHaplotypeFromEvents`.

Rewrite haplotype construction methods in PDHapComputationEngine

---

.dockstore.yml
scripts/variantstore/TERRA_QUICKSTART.md
scripts/variantstore/beta_docs/gvs-overview.md
scripts/variantstore/docs/DELIVERING_GVS_VCF.md
scripts/variantstore/docs/RUNNING_EXOMES_ON_GVS.md
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsIngestTieout.wdl

Ran into what looks like a limit of the WDL `read_string()` function, so converted all the sample-based inputs to be files (instead of strings).
Run that worked (until quotas kicked in): https://app.terra.bio/#workspaces/gvs-dev/GVS_190k_Exomes/job_history/49b92660-e5d6-4305-9857-1dcd19dde1e7

All sample inputs as files instead of strings [VS-1019]

---

.dockstore.yml
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsVQSRClassic.wdl

Allow VQSR Classic Memory overrides to be passed from GvsJointVariantCalling.wdl to GvsCreateFilterSet.wdl.
Increase memory overhead on a couple of tasks in GvsVQSRClassic.wdl
@RoriCremer is running the integration test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/8a8b5553-d9d4-47f5-80fb-ec5992172143).

VS-1004 Changes to make benchmarking VQSR Classic possible.

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/BaseFuncotatorArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotateSegments.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRendererUnitTest.java

Connected the splice site window size to CLI parameters.

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2EngineUnitTest.java

Allow users to turn off Mutect2 error model fix from 4.1.9.0

mutect2 expose param

---

.dockstore.yml
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl

What used to be 4 sequential bulk ingest tasks are collapsed into one to minimize the effect of Cromwell overhead, which can be [quite painful on a bad day](https://job-manager.dsde-prod.broadinstitute.org/jobs/d5c0acec-9983-48dd-bab7-f69e22a088fd). 
After (`GetToolVersions` is not part of bulk ingest):

Coaelesce 4 bulk ingest tasks into one

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerArgumentCollection.java

@droazen @jamesemery @lbergelson Is there a reason not to change this?

Changed the SmithWaterman implementation to default to FASTEST_AVAILABLE

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl

successful run:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/job_history/649ee4c9-1afc-473b-b460-2fc88d5f49d4
failing run with the bug:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/job_history/f1c952fc-7f05-4468-ae20-1c1cc5b9bf38
AC is:
Cohort builder subcohort extract in AoU and our extract workflow work with both VETS and VQSR callsets, including past callsets. (Note--I did not test in AoU, just on quickstart since the issue doesn't seem to be permission or scale related--see failure reproduced above)
Full extract with past callset & VQSR
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/job_history/649ee4c9-1afc-473b-b460-2fc88d5f49d4
Subcohort extract with past callset & VQSR
Full extract with new callset & …

Make extract backwards compatible with the new schema

---

scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/extract/hail_join_vds_vcfs.py
scripts/variantstore/wdl/extract/import_gvs.py

AC:
While in a Notebook, I can run Hail 120 and I can specifically run the new vcf_combiner code
merge_alleles() works in the 120
and we must use array_elements_required=False in import_VCF to get around the missing data issue Dan pointed out
Hail version 120 has been pinned in the Integration test -- pinned!
Integration test with above pin has succeeded.
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/a1c5e4c4-2058-4dad-8261-87b23c8bb0f3

Update hail version to 120 in Integration test VS 1025

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyResultSet.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PileupDetectionArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/utils/SmallBitSet.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java
src/main/java/org/broadinstitute/hellbender/utils/haplotype/PartiallyDeterminedHaplotype.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/PartiallyDeterminedHaplotypeComputationEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/utils/SmallBitSetUnitTest.java

@jamesemery here's another one for you.

More refactoring PDHCE and preparing for joint detection

---

.dockstore.yml
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/HailFromWdl.wdl
scripts/variantstore/wdl/extract/filter_VDS_and_shard_by_contig.py
scripts/variantstore/wdl/extract/run_in_hail_cluster.py

Largely taken from Lee's sample code, see JIRA ticket for details. Spins up a Hail cluster and runs a script to extract from a VDS to VCF files on a per-chromosome basis. Includes some refactoring to move some of the workspace-sniffing that was part of bulk ingest into more generic utility code.
In terms of cluster tracking:
- Cluster name is calculated in shell script and visible in the logs
- Cluster name is written to a file which is delocalized even if the workload script fails. 
Unintended but useful example [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/a96667a7-e08c-43f4-abad-b55fbe7f0c06) where not only is the cluster name logged and written to an output file which is delocalized, but the cluster gets shut down anyway by cleanup code.

Hail Dataproc from WDL, cluster tracking [VS-1013] [VS-1021]

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl

VS-857.
Change default behavior of GvsBulkIngestGenomes.wdl BACK to not dropping GQ0 ref blocks.
Updated AoU documentation to say we need to do it there (as an input).
Passing Integration Test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/c4f921d8-52e7-4a44-9e0b-9f876eac71f3)

VS-857. Change default behavior of GvsBulkIngestGenomes.wdl to drop state NONE.

---

.dockstore.yml
scripts/variantstore/docs/CHANGELOG.md
scripts/variantstore/wdl/GvsImportGenomes.wdl

Normally one provides passing workflow runs with a PR. For the integration run [that is here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/ab86fb6d-c5d6-48b6-8322-923af691751c). There's also a "real" run taking place using this branch [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/db59d5b8-e2ac-4619-9563-aa5631bf053c).
However for testing correctness of these changes with respect to the requester pays flag, my pet "does not have serviceusage.services.use access to the Google Cloud project". I therefore present instead a [run with my changes](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/9e712055-f466-4929-b6eb-5306f3cde1a0) that fails in exactly the same way as a [run without my …

Use `gcloud storage cp` to sidestep composite object issues [VS-1090]

---

scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/RefCreator.java

there was a code path that didn't get exercised in integration tests or quickstart data (writeMissingIntervals) that wasn't made aware of the storeCompressedReferences flag.  Updated to operate correctly in its presence

Fixing LoadData error discovered in delcho run

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
scripts/variantstore/wdl/GvsUtils.wdl

Creates integration testing datasets so the tables within them auto-delete at 2 weeks. See the tables in `gvs-internal.quickit_2023_10_24_vs_1049_tables_are_not_forever_265f343_beta` for an example, integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/72e3c830-b4ba-4e52-a264-07acb81a9b5b).

Integration testing tables are not forever [VS-1049]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/flow/FlowAnnotatorBase.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/flow/FlowAnnotatorUnitTest.java

minor changes and fixes to Flow Annotations.

Ultima.flow annotations.fix

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleFiltering.java
src/main/java/org/broadinstitute/hellbender/utils/read/FlowBasedRead.java
src/main/java/org/broadinstitute/hellbender/utils/read/FlowBasedReadUtils.java

Addresses the issue from broadinstitute/gatk:#8576

Removes unnecessary and buggy validation check

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsCreateVDS.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/hail_join_vds_vcfs.py

Integration run in progress: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/b0ba98ae-a81f-4be2-bd72-c374359b644c
I actually don't expect this to pass due to VS-1141, but hopefully once this lands VS-1141 will be the *only* thing preventing integration from passing.
Stowaway bug fixes:
- Hail version defaulted properly
- VDS tie out now waits for VDS creation to finish

Compressed reference smarts [VS-1138]

---

src/main/java/org/broadinstitute/hellbender/tools/AnalyzeSaturationMutagenesis.java

In some instances, a large amount of data is being discarded by ASM. This might not be the best behavior.
This PR adds a `noIgnore` flag that will change the behavior on disjoint reads to combine the genotyping rather than only using the first read.
This PR refers to this discussion on the GATK forums, too: https://gatk.broadinstitute.org/hc/en-us/community/posts/18309424568731-AnalyzeSaturationMutagenesis-behavior-with-disjoint-pairs

Add option to AnalyzeSaturationMutagenesis to keep disjoint mates

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsPrepareRangesCallset.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/create_ranges_cohort_extract_data_table.py

See run [here](https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/26bfc19e-a804-4d68-9c1e-fb08c491e238) (and [here](https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/17e15516-fa1d-483e-96ee-038ea4b4eaad), after PR changes) and then the tables created in `gvs-internal.rsa_gvs_quickstart_dev`.

 Add parameter to give tables created by prepare step a two week TTL [VS-597]

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsWithdrawSamples.wdl

This PR updates GvsWithdrawSamples to:
1) Use a "true" temporary table (uniquely named, goes away after 24 hours)
2) Check if there are any samples in the uploaded list of samples to withdraw that are NOT in the existing sample_info table. Fail and print out the list of samples if so.
3) Added a boolean flag to allow the user to pass the workflow if condition 2 is true.
A) Example [Run](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/26482e64-cc22-4191-b88f-f7765b173450) with 0 samples withdrawn and 0 new samples (samples in the withdrawn file that aren't in sample_info)
B) Example [Run](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/00f17100-18c4-4522-8dee-24630ef291b1) with 1 sample withdrawn and 0 new samples …

VS-1159 - Enhance GVSWithdrawSamples

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/groundtruth/GroundTruthScorer.java

A leftover from a previous merge of Ultima tools - javadoc for GroundTruthScorer (experimental tool,  already merged)

GroundTruthScorer doc update

---

scripts/variantstore/wdl/extract/import_gvs.py

This should work around a rare error in `_calculate_new_intervals` that could generate invalid partitioners in a way that
`calculate_new_intervals` cannot.

Use combiner's calculate_new_intervals for target_final_intervals

---

scripts/variantstore/wdl/extract/import_gvs.py

If the combiner finishes, but import_gvs fails, and this script is run again, the combiner output will be deleted and the finished plan will be used causing no new output to be generated causing the script to fail.

Do not delete raw combiner output

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl

straightforward addition of an optional parameter to the subcohort extraction workflow
Successful run with an interval list past: https://job-manager.dsde-prod.broadinstitute.org/jobs/54123177-21ea-4662-bc4b-67c39a545829
Successful run with no interval list past (to verify it continues to work that way): https://job-manager.dsde-prod.broadinstitute.org/jobs/8da5bd93-6e3f-4dac-bfcc-83ffb05cea7b

VS 678 - adding optional interval list to the subcohort extract workflow

---

build.gradle
src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java

* it now has a retry mechanism so we're asking for a lot of retries

Update http-nio and wire its new settings

---

src/main/java/org/broadinstitute/hellbender/tools/PrintFileDiagnostics.java
src/main/java/org/broadinstitute/hellbender/tools/filediagnostics/BAIAnalyzer.java
src/main/java/org/broadinstitute/hellbender/tools/filediagnostics/CRAIAnalyzer.java
src/main/java/org/broadinstitute/hellbender/tools/filediagnostics/CRAMAnalyzer.java
src/main/java/org/broadinstitute/hellbender/tools/filediagnostics/HTSAnalyzer.java
src/main/java/org/broadinstitute/hellbender/tools/filediagnostics/HTSAnalyzerFactory.java
src/test/java/org/broadinstitute/hellbender/PrintFileDiagnosticsIntegrationTest.java
src/test/resources/filediagnostics/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.txt
src/test/resources/filediagnostics/cram_with_crai_index.cram.crai.txt
src/test/resources/filediagnostics/example_pfFail_reads.bam.bai.txt

Print file diagnostics for cram, crai and bai.

PrintFileDiagnostics for cram, crai and bai.

---

build.gradle
src/main/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImport.java
src/test/java/org/broadinstitute/hellbender/tools/genomicsdb/GenomicsDBImportIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/spark/PileupSparkIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/azureHeader.vcf
src/test/resources/org/broadinstitute/hellbender/tools/GenomicsDBImport/azureSampleNameMap.txt
src/testUtils/java/org/broadinstitute/hellbender/testutils/ArgumentsBuilder.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/BaseTest.java
src/testUtils/java/org/broadinstitute/hellbender/testutils/CommandLineProgramTester.java

adding two new parameters which work together to allow passing through files from azure too genomicsDB
`--header <vcf>` which lets you specify a vcf file to use the header from as your merged header.  Do not mess this up or you will likely be doomed.
`--avoid-nio` which disables GATK sanity checks that involve reading the files since this would require opening them on azure.
This needs tests but I wanted to put it here for @meganshand to try.

GenomicsDB on azure

---

build.gradle

This should http access more seem less in a lot of places.  
The way this handles query parameters is not ideal for signed url cases so we'll need to revisit that.

update http-nio to 1.1.0 which implements Path.resolve() methods

---

src/main/java/org/broadinstitute/hellbender/tools/copynumber/gcnv/GermlineCNVIntervalVariantComposer.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCFUnitTest.java

PostprocessGermlineCNVCalls produces a GT header like this in one of its output files:
```
##FORMAT=<ID=GT,Number=1,Type=Integer,Description="Genotype">
```
which should have been `Type=String`. Incorrectly writing this as `Type=Integer` produces invalid VCF files and in particular causes bcftools to misparse records' genotype fields.
I searched for other similar problems and noted the inconsistencies in _ReblockGVCFUnitTest.java_. However this probably isn't causing any actual problems, so you may wish to include only the first commit — which very much is causing production problems.

Fix GT header in PostprocessGermlineCNVCalls's --output-genotyped-intervals output

---

src/main/java/org/broadinstitute/hellbender/tools/sv/SVCallRecord.java
src/main/java/org/broadinstitute/hellbender/tools/sv/concordance/ClosestSVFinder.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordance.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordanceIntegrationTest.java

The SVConcordance tool is currently too inefficient in terms of memory usage, requiring several 100's of GB of heap space on ~100K samples. This PR aims to reduce memory usage in two ways:
1. Truth VCF records are stripped of all genotype fields except `GT` and `CN`, which are necessary and sufficient for concordance computations.
2. A new option `--do-not-sort` is introduced to skip output record sorting. A major source of heap usage is the output buffer in the `ClosestSVFinder` class, which ensures records are emitted in coordinate-sorted order. This buffer quickly fills, however, when there is at least one record being actively clustered that spans a large interval because the buffer cannot be flushed until a variant beyond the maximal clusterable coordinate of that large variant is …

Reduce SVConcordance memory footprint

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/hail_create_vat_inputs.py

sites-only VCF created with VDS, ancestry file and `hail_create_vat_inputs.py` script  from this branch here: gs://fc-93670912-8238-4968-a446-efb36e7dfeb5/vat_inputs/quickstart_v2.vcf.gz

Replace LGT with GT within hail_create_vat_inputs.py [VS-1195]

---

src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFConstants.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotate.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngine.java
src/main/java/org/broadinstitute/hellbender/utils/SimpleInterval.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/SimpleIntervalUnitTest.java

Updates SVAnnotate's functional consequence annotation of complex SVs.
* Introduce PREDICTED_PARTIAL_DISPERSED_DUP annotation to describe dispersed duplications of coding sequence that are not expected to behave the same way as tandem duplications
* Ignore INV intervals in dDUP events
* Modify INV intervals in dupINV and similar events to more accurately capture the overall impact of the complex SV
* Ignore complex DUP segments for promoter, noncoding, and nearest TSS annotations because these DUPs are never in tandem
* Merge relevant intervals before annotating nearest TSS for complex events containing DELs
* Update documentation
Testing
* Add unit test for CPX SV segment determination
* Add CPX SV unit test cases
* Update unit/integration test expected outputs
* All unit & integration …

Rewrite complex SV functional annotation in SVAnnotate

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/filtering/NormalArtifactFilter.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFHeaderLines.java
src/test/resources/org/broadinstitute/hellbender/tools/mutect/expected.testExposureOfSmithWatermanParameters.M2.gatk4.vcf

This fixes a small math error in Permutect that was harming precision in tumor-normal mode.

normal artifact lod is now defined without the extra minus sign

---

src/main/java/org/broadinstitute/hellbender/tools/GatherVcfsCloud.java

Make the logging frequency used by the ProgressLogger available as an input. If not used, sets the default value.
Variants team is using a branch of gatk and have made this change there, so pulling this change into master to simplify future merges / branch updates.

Parameterize the logging frequency for ProgressLogger.

---

src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFConstants.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngineUnitTest.java

A record with SVTYPE=CTX and CPX_TYPE=CTX_INV was added to a recent GATK-SV VCF after manual curation. The following changes were made to be able to properly annotate this type of event.
* CPX_TYPE will be checked for CTX records, and if it is CTX_INV, the INV interval from CPX_INTERVALS will be added to the annotation segments.
* Additionally, instead of annotating two breakpoint intervals CHROM:POS-END and CHR2:END2-END2+1 for CTX events, we will now annotate 4 individual breakpoints to cover the case where END != POS+1. Those 4 breakpoints are CHROM:POS-POS, CHROM:END-END, CHR2:END2-END2, and CHR2:END2+1-END2+1.
* In the future, to be able to represent intervals on CHR2, POS2 may be added. SVAnnotate will need to be updated accordingly at that time.
* Unit tests for CTX_INV added
* …

Handle CTX_INV subtype in SVAnnotate

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/import_gvs.py

The ref matrix table has been rsynced over already and is here:
gs://prod-drc-broad/v8/wgs/vds/aou_srwgs_short_variants_v8.vds/reference_data
variant data still need to be transformed and written. This writes the variant data only and renames the as_vqsr to as_vets

Write variant mt and rename to as_vets

---

.github/actions/upload-gatk-test-results/action.yml
.github/workflows/gatk-tests.yml
scripts/docker/dockertest.gradle
src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java

* Changing test results directory for the docker tests to match the test results directory from the non docker test.
* Awkward handling of this seems to have been resulting in different test output paths and causing the reporting bot to sometimes fail to report the correct file location

Standardize test results directory between normal/docker tests

---

src/testUtils/java/org/broadinstitute/hellbender/testutils/VariantContextTestUtils.java

Tiny improvement that was languishing in an ancient and redundant PR  https://github.com/broadinstitute/gatk/pull/6736

Improve failure message in VariantContextTestUtils

---

src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/DefaultGATKReadFilterArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptor.java
src/main/java/org/broadinstitute/hellbender/cmdline/ReadFilterArgumentDefinitions.java
src/main/java/org/broadinstitute/hellbender/engine/filters/CountingReadFilter.java
src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilter.java
src/test/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKReadFilterPluginDescriptorTest.java

A quick and dirty implementation. The on thing that needs extra scrutiny is going to be the various conditions/failure states in the validate method. I think i caught most of the cases but there might be a gap somewhere.

added --inverted-read-filter argument to allow for selecting reads failing read filters from the command line easily

---

src/main/java/org/broadinstitute/hellbender/tools/GatherVcfsCloud.java

@droazen I noticed we never removed the beta marker from this.  I think it should be considered no longer beta given it's pretty intensive use for the last several years.

GatherVcfsCloud is no longer Beta

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java

Exclude the field AS_YNG from VCFs extracted from GVS.
This is the merge into ah_var_store to match the one into EchoCallset
Integration tests [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/5b513630-203f-4e4c-a14c-7423f300645e) - one failure for unrelated reasons.
Note that I had to update the truth data (since the contents of the VCFs had changed, and that there is one failure, but it's due to a slight cost difference - which is presumably in the noise.

VS-623 Exclude AS_YNG from Extract VCF

---

README.md
scripts/docker/gatkbase/Dockerfile
scripts/gatkcondaenv.yml.template

As the title suggests, this PR includes a quick update to our README to include documentation on what tools are included in our docker images.

Update README to include list of popular software included in docker image

---

codecov.yml

Codecov seems to be including test files in its coverage calculation, which is probably not ideal because obviously there are no tests for our tests.  This change should exclude them.

Exclude test folder from codecov scanning

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java

Don't print the very long and misleading "The following contigs are present in b37 and missing in the input VCF sequence dictionary" log message when we're not even doing b37/hg19 conversion.
Users are getting log messages like this even when they have an hg38 dictionary:
16:21:32.764 INFO  FuncotatorUtils -   The following contigs are present in b37 and missing in the input VCF sequence dictionary:
16:21:32.767 INFO  FuncotatorUtils -     1 (len=249250621,assembly=GRCh37)
16:21:32.767 INFO  FuncotatorUtils -     2 (len=243199373,assembly=GRCh37)
16:21:32.767 INFO  FuncotatorUtils -     3 (len=198022430,assembly=GRCh37)
16:21:32.767 INFO  FuncotatorUtils -     4 (len=191154276,assembly=GRCh37)
16:21:32.767 INFO  FuncotatorUtils -     5 (len=180915260,assembly=GRCh37)
16:21:32.768 INFO …

Funcotator: suppress a log message about b37 contigs when not doing b37/hg19 conversion

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateFilterSet.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCallsetPgen.wdl
scripts/variantstore/wdl/GvsExtractCallsetPgenMerged.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsPopulateAltAllele.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/GvsVQSRClassic.wdl
scripts/variantstore/wdl/MergePgenHierarchical.wdl

Use Cromwell's [noAddress](https://support.terra.bio/hc/en-us/community/posts/360060020871-noAddress-true-results-in-stalling-jobs) feature to avoid the unnecessary use of external IPs on Cromwell worker VMs on wide scatters that cause us Google quota problems.
For most of the GVS code this only involves adding `noAddress: true` to the existing runtime attributes. In the PGEN code this was slightly more work to change away from `docker: "ubuntu:22.04"` which is implicitly pulled from Docker Hub. Since `noAddress: true` means the VM can only interact with Google services, we have to switch to a GCR-hosted image as Docker Hub has become unreachable.
- [Mostly successful integration test](https://job-manager.dsde-prod.broadinstitute.org/jobs/32b9e2b5-3c56-4bf8-ab5e-66fa72c7cadb), delta some …

Use `noAddress` to limit use of external IPs [VS-1323]

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateTables.wdl

Reasoning:
- task will not recreate/overwrite table if it exists
- task does not take long, so unnecessary runs are not costly in time or $
- when not volatile, Beta users need to run with call-caching off if they re-run the pipeline
run where tables already existed: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/64782949-33dd-41ef-b3f7-5e88cc5a5dcc
integration run: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/9e79ef7f-9e64-46c7-8749-83909a5d423f (it failed the end tests, but the tables were created/populated as expected)

Make CreateTables volatile [VS-1328]

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl

This PR deals with the test failures that were occurring when we ran ALL chromosomes through the integration test, rather than just chr20 and X and Y (the default). It adds another truth set for all chromosomes.
Also two small changes.
- Skip the cost/table size check for the Hail integration, to allow it to get to the hail part if there are spurious test failures in cost.
- Change the name of the files used for table size and cost checking. Makes it easier to install new test data.
Passing integration test on all chromosomes [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/d8837252-26fa-4d40-bdf1-e42ff8932fd1)
Passing integration test on chr20/x/y [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/f552e7a3-d245-492d-b5e1-a35ba323fa …

VS-1324 Investigate integration test failures

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/build_docker.sh
scripts/variantstore/wdl/extract/build_docker_tag.py
scripts/variantstore/wdl/extract/test_build_docker_tag.py

- Push to `gvs` repo in `broad-dsde-methods` rather than `variantstore`.
- Fix the way image IDs are discovered.
- Support both `alpine` and non-`alpine` image types, setting up support for plink2.
Successful integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/c1c2fc65-104b-46af-a536-882d7c1e8954).

Fix GAR support [VS-1342]

---

.gitignore
src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleFiltering.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleFilteringUnitTest.java

A really tiny bug fix. Apparently allele filtering did not work well in case the allele with high SOR was not the one with the lowest quality.

Bug fix in flow allele filtering 

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallsetPgenMerged.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/build_docker.sh
scripts/variantstore/wdl/extract/build_docker_tag.py
scripts/variantstore/wdl/extract/plink_docker/Dockerfile
scripts/variantstore/wdl/extract/plink_docker/build_plink_docker.sh
scripts/variantstore/wdl/extract/test_build_docker_tag.py

Some of the Docker work from `ah_var_store` needs to be on `EchoCallset` to be able to do the PGEN subsets, particularly the PLINK Docker and GAR changes upon which the PLINK Docker changes depend. I have freshly baked the Variants, PLINK, and Docker images just now for this PR. 👨‍🍳 
Integration run in progress here https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/2585a1b6-c5da-48f0-a196-b5679e7f40a5

Docker untangling [VS-1279]

---

.dockstore.yml
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl

* Fixed cost calculation to ignore duplicate rows caused by preemption.
* Resetting tolerances to 5% across the board.

VS-341 improve test cost calc echo callset version

---

.dockstore.yml
build_docker.sh
scripts/variantstore/docs/Build Docker from VM/building_gatk_docker_on_a_vm.md
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
scripts/variantstore/wdl/GvsTieoutPgenToVcf.wdl
scripts/variantstore/wdl/GvsTieoutVcfMaxAltAlleles.wdl
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortVETSEngine.java

`ah_var_store` edition: Allows hard-filtering based on a maximum number of alt alleles [VS-1334], as well as fixing GATK Docker image building to use image IDs rather than git hashes [VS-1357].
Integration test _mostly_ successful [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/5d021859-5971-4fd7-8451-086c224fdb00).
`GvsQuickstartIntegration` failed with:
```
The bytes observed (89733530) for 'ExtractFilterTask.GvsCreateFilterSet.BigQuery Query Scanned' differ from those expected (85119360)
FAIL!!! The relative difference between these is 0.0514208, which is greater than the allowed tolerance (0.05)
```
Successful tieout run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/04b840f9-9779-48d6-8faa-4425d67ddadb).
[VS-1334]: …

[ah_var_store] VCF max alt alleles [VS-1334] [VS-1357]

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsExtractCallset.wdl

~Currently in draft status, I still need to test this the way I tested the PGEN version.~ Tested, works, ready for review!

[ah_var_store] Retry with more memory VCF extract [VS-1351]

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl

Optionally extract VCFs in bgzipped compression format.
Integration test - [Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/60357098-e6f2-4264-a322-c3088ce36152)
[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/2c4dea90-367f-4875-939a-ce0b9ae296e7) is an example extract using bgzip
[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/7a8413da-499b-4f93-ba85-554937249bd4) is an example extract not using bgzip (so, just '.gz')

VS-1335 bgzip on extract ah var store edition

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl

* Optionally extract to bgz format.
* Set bgzipping to be off (everywhere) by default.
* Update assert_identical_outputs to handle bgzipped outputs.

VS-1335 bgzip on extract Echo Callset version (#8809)

---

.dockstore.yml
scripts/variantstore/wdl/GvsAssignIds.wdl
scripts/variantstore/wdl/GvsCreateTables.wdl

This PR adds a task to GvsAssignIds to verify that there are no duplicate sample names in the file provided.
[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/af6651c5-37e1-48b6-8514-9c0d326dfc6f) is an example run of BulkIngest that replicates the original reported problem. No sample set provided, the sample id column is not sample_id and there's a duplicate in THAT column.
[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/25dc14df-c6e5-4710-b9b8-67b04906bc78) is an example run where the updated code runs and reports the problem early-ish without creating database tables that need to be cleaned up.
[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/b29d3eea-8330-464 …

VS_1327 ensure sample ids are unique

---

Dockerfile
scripts/docker/gatkbase/Dockerfile

As part of my work in the Pipeline Dev team, I created 2 GATK images to address issue discussed [here](https://github.com/broadinstitute/gatk/issues/8684) (ie. having too many docker layers, we hit ACR limits very quickly). The images are in terrapublic, a premium-tier ACR and is publicly accessible. I made two images, one is squashed to just 1 layer, the other is reduced to just 12 layers (from the original 45). With these changes and the fact that terrapublic is on [premium](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-skus#registry-throughput-and-throttling) tier, the maximum docker pulls per minute becomes  833 (ie. 10k readOps / 12 layers) for the reduced-layers image and 10,000 for the squashed one. We have yet to test these in our pipelines but I …

GATK Reduced Docker Layers for ACR

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltrationIntegrationTest.java

This allows the user to write their own description in the FILTER line in the header. Currently a user can define an interval list to filter with and name that filter, but the description line is always "Doesn't overlap a user-input mask" or "Overlaps a user-input mask", whereas it might be more useful to let the user provide a more detailed description (for example, "Outside of sequencing target intervals").

Adding arg to VariantFiltration to write your own description in Header

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl

- [Successful Quickstart extract](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/b814cff2-141c-454a-9677-43b7f2ef4d38) into 23 per-chromosome VCFs.
- [Successful exome extract](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Exome%20Data%2049k/job_history/24d1d49f-940c-4f3d-b91d-c575850d601e) with the new scatter width of 2500.

Scatter adjustments [VS-516]

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/common/FilterSensitivityTools.java
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/common/FilterSensitivityToolsTest.java

* Change extract so that when we filter at the genotype level (with FT) the VCF header has the FT filter definition in the comment/unspecified field.
* Also minor renaming of ExtractCohort argument.
* Point to updated truth.
[Here's](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/94129da8-6faf-419b-ab75-a46c228b1bbe) an integration test run. Passing everything except ValidateVDS because `reference_data` not being written due to issues beyond my control.

VS-1336 - It's not a site FILTER (#8773)

---

scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl

run with that interval list as a param: https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%20Echo%20Callset%20v2/job_history/098f06cc-3e99-4c6a-bfd1-e7bd9784e3b1

Clarify and set default for interval_list input [VS-1391]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/flow/FlowAnnotatorBase.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/annotator/flow/FlowAnnotatorUnitTest.java

Fixes #8788. Crash in calculating some annotations when the variant is very near the edge of a contig

[BIOIN-1570] Fixed edge case in variant annotation 

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngineUnitTest.java

See this forum issue: https://gatk.broadinstitute.org/hc/en-us/community/posts/25681424869787-Mutect2-Filtering-Discrepancy-with-Different-Versions-of-gnomAD-Germline-Data

Mutect2 germline resource can have split multiallelic format

---

scripts/mutect2_wdl/mutect2.wdl
src/main/java/org/broadinstitute/hellbender/tools/GetSampleName.java
src/test/java/org/broadinstitute/hellbender/tools/GetSampleNameIntegrationTest.java

@rickymagner we need this for Infogain.

Mutect2 WDL and GetSampleName can handle multiple sample names in BAM headers

---

scripts/mutect2_wdl/mutect2.wdl
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/FeaturizedReadSets.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2Engine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect3DatasetEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/SomaticGenotypingEngine.java

This is important for Infogain and other potential hybrid data because it will allow Permutect to separately normalize within each read group and otherwise keep track of different read groups downstream.
It also makes the data structures in Permutect much more convenient because numeric data is easier to write to a memory map.

Permutect dataset engine outputs contig and read group indices, not names

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleFilteringHC.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AlleleFilteringUnitTest.java

This PR fixes an Issue raised by one of our customers that allele filtering did not work correctly when variant calling was done on multiple samples.

Fixed a bug in AlleleFiltering that ignored more than a single sample

---

.dockstore.yml
scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl

Related to VS-1395. On the PR to EchoCallset, Bec had a couple of minor suggestions. I folded them into that PR and am now adding them here to `ah_var_store`
Passing test run without a backslash on output_path [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/f02829f5-d546-4f54-85e6-e7ea6be5829e).
Passing test run with a backslash on output_path [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/3003841c-0e62-4ef6-bb37-6eeb038da9af).

VS-1395 Related - Some UI Improvements for GvsCreateVATfromVDS.wdl

---

scripts/cnn_variant_wdl/cnn_variant_common_tasks.wdl

Fixes broken docker image pull that throws an error:
```
docker pull broadinstitute/genomes-in-the-cloud:2.1.1
2.1.1: Pulling from broadinstitute/genomes-in-the-cloud
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/broadinstitute/genomes-in-the-cloud:2.1.1 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

removing deprecated genomes in the cloud docker image that was causing test failures

---

build.gradle

This release fixes several bugs when using HttpPath resolve methods that have been affecting users. In particular, they were causing issues when trying to construct HTTP URIs for companion files such as fasta/bam indices.

Update http-nio to 1.1.1

---

build.gradle
src/test/java/org/broadinstitute/hellbender/engine/CRAMSupportUnitTest.java

Update HTSJDK to 4.1.1 and Picard to 3.2.0
Included a unit test to check for the presence of the fix in HTSJDK 4.1.1 for the CRAM base corruption bug reported in https://github.com/broadinstitute/gatk/issues/8768
Resolves #8768

Update HTSJDK to 4.1.1 and Picard to 3.2.0

---

src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFConstants.java
src/main/java/org/broadinstitute/hellbender/tools/sv/SVCallRecord.java
src/main/java/org/broadinstitute/hellbender/tools/sv/SVCallRecordUtils.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordance.java
src/main/java/org/broadinstitute/hellbender/utils/variant/GATKSVVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/tools/sv/SVCallRecordUtilsUnitTest.java

CTX events have CTX_PP/QQ or CTX_PQ/QP as CPX_TYPE values in GATK-SV VCFs. However, slashes are not allowed as part of enum values, so these are represented in the ComplexVariantSubtype enum as CTX_PP_QQ and CTX_PQ_QP. This caused the CTX subtypes to not be recognized and to be dropped during SVConcordance (https://github.com/broadinstitute/gatk-sv/issues/664).
This representation may merit further discussion, as it's not ideal that the ComplexVariantSubtype values are not a 1:1 match with the VCF values. But as one possible solution without altering the VCF, I've implemented a workaround that replaces the slash with an underscore during getComplexSubtype. I've also updated SVAnnotate to use this method, in the hopes that we can use it across all of the SV tools for more consistent …

Handle CTX_PP/QQ and CTX_PQ/QP CPX_TYPE values in SVConcordance

---

src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFConstants.java
src/main/java/org/broadinstitute/hellbender/tools/sv/SVCallRecord.java
src/main/java/org/broadinstitute/hellbender/tools/sv/SVCallRecordUtils.java
src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVCollapser.java
src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVLinkage.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/JointGermlineCNVSegmentation.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVCluster.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordance.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVSegment.java
src/test/java/org/broadinstitute/hellbender/tools/sv/SVCallRecordUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/SVCallRecordUtilsUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/SVTestUtils.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/CNVDefragmenterTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVCollapserUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/SVClusterEngineTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVClusterIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordanceIntegrationTest.java

- Complex (CPX) SV records no longer use `END2`/`CHR2` INFO fields and instead are defined by `CPX_INTERVALS` in addition to normal coordinates.
- Adds new class `SVCallRecord.ComplexEventInterval` for storing complex event intervals, which are associated with a particular SV type.
- SV clustering now takes into account CPX subtype and intervals, requiring intervals to match on type and interval similarity as defined by the clustering parameters (e.g. minimum reciprocal overlap).
- Improved reciprocal translocation (CTX) record handling. In particular, these records are now treated similarly to BNDs for clustering purposes.
- Added unit tests for new CPX cases.

Complex SV intervals support

---

scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/hail_create_vat_inputs.py

Apply a fix that Miguel made here: https://github.com/broadinstitute/gatk/pull/8785 but did not merge (yet - because he didn't want to disrupt the VAT that at time was under construction).
This fixes a bug in the partioning logic used in creating Hail VAT inputs.

Fix bug in Hail Create VAT Inputs Partitioning.

---

README.md

Clarify in the README which git lfs files are required to build GATK

---

.dockstore.yml
scripts/variantstore/beta_docs/gvs-exome-workspace-description.md
scripts/variantstore/docs/RUNNING_EXOMES_ON_GVS.md
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/GvsQuickstartVcfIntegration.wdl
scripts/variantstore/wdl/GvsRescatterCallsetInterval.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/extract/hail_join_vds_vcfs.py
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltration.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/filters/VariantFiltrationIntegrationTest.java

Currently two commits here: Megan's commit that is already on `master` and was approved in #8831, and the other commit with all of my changes for this ticket. 
Successful integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/6c033078-f6d3-47c8-926a-07176478823d).

Optionally filter off-target calls for exomes [VS-1375]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/variantrecalling/HaplotypeBasedVariantRecaller.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/variantrecalling/TrimmedReadsReader.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/variantrecalling/TrimmedReadsReaderUnitTest.java

Someone asked to adopt HaplotypeBasedVariantRecaller for Illumina reads. since it is a small fix, I think it is worth merging

Modified HaplotypeBasedVariantRecaller to support non-flow reads

---

src/test/java/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCFIntegrationTest.java
src/test/resources/org/broadinstitute/hellbender/tools/walkers/variantutils/ReblockGVCF/reblockEdgeCase.vcf

Running the scientific tests in WARP when updating GATK from 4.5.0.0 -> 4.6.0.0 caught a difference in ReblockGVCFs when a no call site with GQ=0 was derived from a low quality call where the PLs with a value of 0 were in an allele that was subset (e.g. `<NON_REF>`). I believe this new behavior is a feature because it now correctly outputs a ref block with GQ=0.
This test provides an example of one of these cases to ensure that the behavior stays the same in the future.

Adding a test to capture an expected edge case in Reblocking

---

.dockstore.yml
scripts/variantstore/wdl/GvsCalculatePrecisionAndSensitivity.wdl

When a target interval list is provided for exomes, create a saner truth bed that intersects the provided truth beds with this target interval list. Successful run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Exome%20Data%2049k/job_history/b3185159-e53e-4418-9803-a24c064df1a3).

Intersect target and truth for P&S [VS-1460]

---

README.md

Adds a short section to the README about how to cite GATK in publications (or rather, redirect users to our forum post about it).

Add docs about citing GATK

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallsetPgen.wdl
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortToPgen.java

Fix a bug where ExtractCohortToPgen does not write to the cost_observability table.
- Successful run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/df2420f5-0da3-4801-baa7-d651ce3d6910)
- Successful integration test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/13865dd1-f561-49a2-8581-87343bf79069)

VS-1470 Have Extract Cohort to PGEN write to cost_observability table

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl

Modify GvsExtractCallset so that you can change the value of 'output_gcs_dir' as an input and it won't cause the extract to be re-run (won't invalidate call caching).
Passing run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/a5fd0daf-8816-42e4-ad15-3aa432e2ed80).
Passing Integration test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/3c874e74-4fdd-4cbb-af75-a44bb7e17ea1).

VS-1466 restructure export vcf for copy reasons

---

src/test/java/org/broadinstitute/hellbender/GATKBaseTest.java
src/test/java/org/broadinstitute/hellbender/PrintFileDiagnosticsIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/engine/CRAMSupportIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/tools/PrintReadsIntegrationTest.java
src/test/resources/filediagnostics/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.txt
src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.v3.0.samtools.cram
src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.v3.0.samtools.cram.crai

This PR adds a CRAM v3.0 version of the existing (CRAM v2.1) test file `CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram` in git-lfs and in the cloud test resources bucket. In both cases, the old files are left intact  for now. Roundtrip tests using both the old and new versions of the local file are also added.
At some point, the old files can be removed, but when we do so, old branches will need to be rebased on this code or the cloud tests will fail, since the cloud test in this PR uses the new file name (that includes the CRAM version in the name).

Update the large CRAM files to v3.0.

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsExtractCohortFromSampleNames.wdl
scripts/variantstore/wdl/GvsJointVariantCalling.wdl
scripts/variantstore/wdl/GvsQuickstartIntegration.wdl

Added ability to call gatk tools to collect variant calling metrics.
It is optional, and defaulted to not collect.
Passing Extract run with metrics collected [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/97411a89-bd75-48dd-8dba-00d6af5373e7).
Passing Extract run where we don't (default) collect metrics [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/dfe6a72f-f2e0-4999-a7c9-f8243e0f1586).
Passing Integration test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/b11f03a9-16ef-4b1e-9b1c-c281f41b43a1)

VS-1485 - Optionally call CollectVariantCallingMetrics from ExtractVcfs

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsImportGenomes.wdl

Test run with `load_data_scatter_width` set: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/f10f47ab-8b5b-428a-b418-c9dc9f9c3a58
Test run with `load_data_scatter_width` not set: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/5bf5fe73-10d6-4df2-a5df-3f793c25ebde
integration run: https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/84f14232-dc62-4ce5-8031-7840f7f2aedc

Change Batch Size Parameter to Scatter Width For Ingest [VS-1218]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/M2ArgumentCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java

@davidbenjamin what I was talking about earlier. It comes with the very nice side effect of pasting this to the command line output: 
It also generally makes it much easier to track down "what does mito mode change exactly again?"

Swapped mito mode in Mutect to use the mode argument utils

---

.github/workflows/dependency_submission.yml

@droazen This submits our dependencies so that dependabot can analyze them in the background.  
It's from https://github.com/marketplace/actions/build-with-gradle#the-dependency-submission-action

Add dependency submission workflow so we can monitor vulnerabilities

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFs.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/gnarlyGenotyper/GnarlyGenotyper.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2.java

Re-added `--only-output-calls-starting-in-intervals` as a deprecated argument with warning.

---

build.gradle
src/main/java/org/broadinstitute/hellbender/engine/spark/RangePartitionCoalescer.java
src/main/java/org/broadinstitute/hellbender/tools/spark/pathseq/PSBuildReferenceTaxonomyUtils.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/StructuralVariationDiscoveryPipelineSpark.java
src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/ComplexityPartitioner.java
src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java
src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java
src/main/java/org/broadinstitute/hellbender/utils/logging/OneShotLogger.java
src/test/java/org/broadinstitute/hellbender/engine/spark/RangePartitionCoalescerUnitTest.java
src/test/java/org/broadinstitute/hellbender/testutils/FuncotatorReferenceTestUtils.java

Additional changes on top of #8998

Additional Dependency updates

---

build.gradle

* fix dependabot alert for jetty-xml
* bom version -> 9.4.56.v2024082

Use jetty bom to enforce uniform jetty versions

---

src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java
src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java

This feature was initially opened in this PR: https://github.com/broadinstitute/gatk/pull/8750, after which @lbergelson and @droazen made comments here; https://github.com/broadinstitute/gatk/pull/8752. 
The driving use-case is that we took over the GATK3 MergeVariantsAndGenotypes tool at DISCVRseq and users have been requesting the older behavior on VCF merges, such as: https://github.com/BimberLab/DISCVRSeq/issues/313. 
The original PR has been languishing since March and I'm hoping to finalize this feature. Because I cant write to the GATK repo and b/c @lbergelson made some suggestions on a GATK-based branch I am going to put every together into one clean PR, which responds to the code review from the thread above. 
To recap background: 
- In GATK3, when merging variants, the IDs of …

Retain all source IDs on VariantContext merge + test

---

.dockstore.yml
scripts/variantstore/wdl/GvsExtractCallset.wdl

Passing run of Extract with copying the outputs [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/e15a6d75-83dc-423d-aa90-29f578fda46f)
Passing run of Extract without copying the outputs [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/0af5eb18-4ede-492b-b15a-b73c93e02ad6)

VS-1526 - Fix error in Extract Manifest Creation causing it to run forever.

---

scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/wdl/GvsExtractCallset.wdl
scripts/variantstore/wdl/GvsRescatterCallsetInterval.wdl

Extract and WeightedSplitIntervals don't deal well with arbitrarily large numbers of alt alleles, so add an (overridable) guardrail of 1000 alt alleles max if the user neglects to specify the 100 alt alleles max recommended in our documentation for AoU callsets.

Maximum alt alleles guardrail [VS-1530]

---

.dockstore.yml
scripts/variantstore/scripts/hail_create_vat_inputs.py
scripts/variantstore/wdl/GvsUtils.wdl

Test to make a VAT from an integration test VDS [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/7be23bc6-efbd-4df6-a59f-491d3bf7b9b8)
Note that the failure in this run is based on most chromosomes being omitted.

VS 1528 Update the sharding of the samples in the VAT creation to be dependent on the number of samples

---

.dockstore.yml
build.gradle
scripts/variantstore/wdl/GvsImportGenomes.wdl
scripts/variantstore/wdl/GvsUtils.wdl

Successful integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/853ce451-8dc1-4311-bd03-facf22700ccd).

Fix curate input array files [VS-1490]

---

src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVCollapser.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVCollapserUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVClusterIntegrationTest.java

Makes some small adjustments to tiebreaker criteria for merging genotypes with the `CanonicalSVCollapser`, which is used in the `SVCluster` and `GroupedSVCluster` tools. We've empirically found, after considering ref vs non-ref and GQ, that prioritizing hets over hom-var genotypes improves variant quality in terms of hardy-weinberg equilibrium. This is also the preferred behavior for GATK-SV, as false hom-var genotypes (when truly a het) is considered one of the more egregious error modes, particularly in association studies. 
A similar adjustment is made to multi-allelic CNV merging, in which copy states closer to reference are now preferred. 
In addition, a tiebreaker has been added in the case of conflicting copy states that are equally far from reference, e.g. merging a variant with …

Prioritize het calls when merging clustered SVs

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortEngine.java

Integration test run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/e4267ee8-0393-4212-87c1-de078a636a65).
Follows the bread crumbs in VS-493 to drop filter info and sites outside of variant locations for the samples being extracted.
Test runs here:
- [Baseline ah_var_store](https://app.terra.bio/#workspaces/gvs-dev/MLC%20NHGRI%20AnVIL%20GVS%20copy/job_history/32b3f348-b74f-4346-a92a-cdbe4500ff8d)
- [This branch](https://app.terra.bio/#workspaces/gvs-dev/MLC%20NHGRI%20AnVIL%20GVS%20copy/job_history/e0472760-2d82-4d6d-9ede-d809da07f126)
Findings:
- This data set is the biggest non-AoU dataset we have but is decidedly on the small side for being able to measure the effects of changes like this.
- For the particular runs linked above, the code on this branch …

Extract Cohort optimizations [VS-493] [VS-1516]

---

.github/actions/upload-gatk-test-results/action.yml
.github/workflows/gatk-tests.yml

Update upload_artifact from 3 -> 4

Updating upload_artifact in github actions

---

scripts/variantstore/beta_docs/gvs-troubleshooting.md

no automated testing needed--just documentation edits

Add a few additional failures to our notes doc

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java

I missed this when it was merged, but we should really close out this FeatureReader.

Close a FeatureReader after use

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/FlowBasedAlignmentLikelihoodEngine.java
src/main/java/org/broadinstitute/hellbender/utils/read/FlowBasedRead.java
src/test/java/org/broadinstitute/hellbender/utils/read/FlowBasedReadIntegrationTest.java
src/test/java/org/broadinstitute/hellbender/utils/read/FlowBasedReadUnitTest.java

* remove the field FlowBaseRead.forwardSequence which was calculated at non-trivial cost and then only used for it's length
* removed the method seqLength because it was a more convoluted version of getLength
* fixed some typos and finals because I couldn't help myself

Remove unnecessary calculation

---

.dockstore.yml
scripts/variantstore/scripts/hail_gvs_import.py
scripts/variantstore/scripts/import_gvs.py
scripts/variantstore/scripts/import_gvs_ploidy.py
scripts/variantstore/scripts/run_in_hail_cluster.py
scripts/variantstore/wdl/GvsCreateVDS.wdl
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/test/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/test/GvsQuickstartIntegration.wdl
scripts/variantstore/wdl/test/GvsTieoutVcfMaxAltAlleles.wdl

```
$ python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hail as hl
>>> hl.init()
/opt/conda/lib/python3.10/site-packages/hailtop/aiocloud/aiogoogle/user_config.py:43: UserWarning: Reading spark-defaults.conf to determine GCS requester pays configuration. This is deprecated. Please use `hailctl config set gcs_requester_pays/project` and `hailctl config set gcs_requester_pays/buckets`.
warnings.warn(
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Running on Apache Spark version 3.3.0
SparkUI available at http://saturn-bfc0786f-af2f-4a56-8ecc-d5b615682edc-m.us-central1-c.c.terra- …
```

Ploidy for Foxtrot VDS [VS-1418]

---

.dockstore.yml
scripts/variantstore/scripts/cromwell_monitoring_script_with_heap.sh
scripts/variantstore/wdl/GvsExtractCallset.wdl

I needed to create a new new version of the cromwell monitoring script to grab specific heap data for identifying where our memory is being used during a previously problematic shard during our AoU extract.  It has been uploaded to gs://gvs_quickstart_storage/cromwell_monitoring_script_with_heap.sh
If you want to generate these high-level gatk histograms for extract, just replace the definition of `File monitoring_script `in the ExtractTask  within GvsExtractCallset.wdl to point to the new one.
Here's a successful AoU extract using the new monitoring script:
https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%20Echo%20Callset%20v2/job_history/aa5bb1e4-b860-48f3-9c8c-53dd5e6ec206

Vs 1561 Merging in new monitoring script

---

.github/actions/upload-gatk-test-results/action.yml
.github/workflows/gatk-nightly-docker.yml
.github/workflows/gatk-tests.yml

Upgrade all the v3 actions to v4. The CNN WDL job is still broken for unrelated reasons; maybe if we merged master that would go away?

v4 all the GitHub action things [VS-1573]

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/ScoreVariantAnnotations.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/ScoreVariantAnnotationsIntegrationTest.java

Hit when a user tried to score a very small input VCF.

Addressed an edge case in ScoreVariantAnnotations that can occur when one variant type is not present in the input VCF.

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl
src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/ScoreVariantAnnotations.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/vqsr/scalable/ScoreVariantAnnotationsIntegrationTest.java

Mostly successful run here, excepting an unrelated and well-known GCP Batch 50006 error condition which when combined with a lack of `maxRetries` in `PrepGenesAnnotationJson` led to an early demise.

Addressed an edge case in ScoreVariantAnnotations that can occur when one variant type is not present in the input VCF. [VS-1609]

---

.dockstore.yml
scripts/variantstore/scripts/run_avro_query_for_sample_info.py
scripts/variantstore/wdl/GvsExtractAvroFilesForHail.wdl
scripts/variantstore/wdl/GvsUtils.wdl

Updated run:
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20cremer/submission_history/31667bb0-94aa-4b26-a113-a5bc7cc1b9a8
here's the avro file--only has sample3!
Integration run fails but for auth reasons in the VAT creation and does not fail during the avro extract
https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/submission_history/e64a163b-704f-461e-a5b4-74dbbc179cc2

Extract avros for a VDS but only include the NEW samples that are in Foxtrot

---

.dockstore.yml
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/test/GvsQuickstartIntegration.wdl
src/main/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohort.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortToPgenTest.java
src/test/java/org/broadinstitute/hellbender/tools/gvs/extract/ExtractCohortToVcfTest.java

This PR modifies VCF extract to add the `reference=` line to the header of the VCFs
Passing integration test [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/submission_history/ecef50d4-b1d9-48e0-a2a5-a211c203de32)

VS-1449 add reference string to vcf

---

build.gradle

* This seems to have been accidentally commented out for testing and never un-commented

Uncomment line excluding bad version of bouncycastle library

---

build.gradle

@KevinCLydon This should fix the warning you noticed.

Exclude logback-classic to fix logger configuration warning

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/PermutectDatasetEngine.java

@LeeTL1220 Small change for Permutect data here, usually irrelevant.  In most use cases, it will be possible to train with a GIAB truth VCF to label data.  When there is not, this PR allows users to optionally specify a PoN as a hint that unlabeled data are probably actually artifacts.
This should not in any way be interpreted as Permutect using a PoN for variant calling.  It has zero effect on our DREAM and Linseq evaluations, which use an NA12878 sample for training.

Optional blacklist VCF to for labeling artifacts in Permutect weak-labeling mode

---

scripts/mutect2_wdl/mutect2.wdl

* generate normal MAF segments whenever Permutect test data is output
* increase the MergeBamouts disk space

Small changes to M2 WDL for Permutect

---

build.gradle

* fix for https://github.com/broadinstitute/gatk/issues/9140
* addresses security vulnerability

Update parquet to 1.15.1

---

src/main/java/org/broadinstitute/hellbender/tools/spark/sv/utils/GATKSVVCFConstants.java
src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/CNVLinkage.java
src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVLinkage.java
src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/SVClusterEngine.java
src/main/java/org/broadinstitute/hellbender/tools/sv/cluster/SVClusterLinkage.java
src/main/java/org/broadinstitute/hellbender/tools/sv/concordance/ClosestSVFinder.java
src/main/java/org/broadinstitute/hellbender/tools/sv/concordance/SVConcordanceAnnotator.java
src/main/java/org/broadinstitute/hellbender/tools/sv/concordance/SVConcordanceLinkage.java
src/main/java/org/broadinstitute/hellbender/tools/sv/concordance/StratifiedConcordanceEngine.java
src/main/java/org/broadinstitute/hellbender/tools/sv/stratify/OptionalSVStratificationEngineArgumentsCollection.java
src/main/java/org/broadinstitute/hellbender/tools/sv/stratify/RequiredSVStratificationEngineArgumentsCollection.java
src/main/java/org/broadinstitute/hellbender/tools/sv/stratify/SVStratificationEngine.java
src/main/java/org/broadinstitute/hellbender/tools/sv/stratify/SVStratificationEngineArgumentsCollection.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/GroupedSVCluster.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordance.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVStratify.java
src/test/java/org/broadinstitute/hellbender/tools/sv/SVTestUtils.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/BinnedCNVDefragmenterTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/CNVDefragmenterTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/CanonicalSVLinkageTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/cluster/SVClusterEngineTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/concordance/ClosestSVFinderTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/concordance/SVConcordanceAnnotatorTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/concordance/StratifiedConcordanceEngineTest.java
src/test/java/org/broadinstitute/hellbender/tools/sv/stratify/SVStratificationEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordanceIntegrationTest.java

Adds variant stratification functionality, similar to `GroupedSVCluster`, to `SVConcordance`. This allows one to assign different clustering criteria to variants depending on the "eval" variant's type, size, and reference context. Unlike `GroupedSVCluster`, however, `SVConcordance` does not enforce mutual exclusivity among stratification groups. From the tool doc:
```
* This tool also allows supports stratification of SVs into groups with specified matching criteria including SV type,
* size range, and interval overlap. Please see the {@link GroupedSVCluster} tool documentation for further details
* on how to specify stratification groups.
*
* Note that unlike {@link GroupedSVCluster}, this tool allows any variant to
* match more than one stratification group. If this occurs, groups will …
```

Add variant stratification and overlap metrics in SVConcordance

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordance.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVConcordanceIntegrationTest.java

Fixes a bug where the tool fails when any sample overlap thresholds are non-zero. While this is not a normal use case (we rarely would need concordance metrics to be conditioned on carrier overlap), it results in an unclear assertion error where the `ECN` FORMAT field is not found in truth records after being stripped of extra fields to save memory.
This PR adds `ECN` back to the stripped-down truth records. Requiring sample overlap to be 0 was an alternative solution, but would complicate the tool's design. I have added a paragraph to the doc that recommends setting sample overlap to 0 in this tool.
Includes a regression test.

Do not strip ECN fields from truth records in SVConcordance

---

scripts/variantstore/scripts/merge_and_rescore_vdses.py
scripts/variantstore/wdl/GvsUtils.wdl

The example below first selects a site of interest and shows that all samples have a called `LGT` genotype, despite the fact that `ERS4367796` has `GQ` 0. After applying the line of code from this PR, `ERS4367796` has an `LGT` of `NA`.
```
>>> def filter(vds):
...   vd = vds.variant_data
...   fvd = vd.filter_rows((vd.locus.contig == 'chr1') & (vd.locus.position == 1553619))
...   return fvd
...
>>> fvd = filter(vds)
>>> fvd.entries().show()
+---------------+-------------------------------+----------+-----------------------------------------------------------------+
| locus         | alleles                       | filters  | as_vets                                                         |
+---------------+-------------------------------+----------+---------------------------------------- …
```

Vs 1653 patch gq0 on merge

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngine.java
src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVSegment.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVAnnotateEngineUnitTest.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVSegmentUnitTest.java

SVAnnotate assumes CPX intervals are sorted by position. This caused an error (https://github.com/broadinstitute/gatk-sv/issues/808) when the order of the intervals was altered by SVConcordance. This PR adds SVSegment comparison methods and sorts CPX intervals by position during SVAnnotate to ensure consistent ordering.
* Unit tests updated and executed
* Tested SVAnnotate locally and in the GATK-SV AnnotateVcf workflow on a filtered VCF which failed annotation using the version in main, and the tool/workflow completed successfully

Sort CPX intervals by position in SVAnnotate

---

.dockstore.yml
scripts/variantstore/scripts/build_base.Dockerfile
scripts/variantstore/scripts/build_build_base_docker.sh
scripts/variantstore/variant-annotations-table/GvsCreateVATFilesFromBigQuery.wdl
scripts/variantstore/variant-annotations-table/GvsCreateVATfromVDS.wdl
scripts/variantstore/wdl/GvsCreateVDS.wdl
scripts/variantstore/wdl/GvsMergeAndRescoreVDSes.wdl
scripts/variantstore/wdl/GvsUtils.wdl
scripts/variantstore/wdl/GvsValidateVDS.wdl
scripts/variantstore/wdl/test/GvsQuickstartHailIntegration.wdl
scripts/variantstore/wdl/test/GvsTieOutVDS.wdl

Successful run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration%20mcovarr/submission_history/ae7a807b-5393-4b78-a5b2-f57f24c518bd).
Upgrading from Hail 0.2.130.post1 to 0.2.134 required upgrading our nearly 2-year-old version of the Google Cloud SDK images. The Dataproc client in the Google Cloud SDK version we had been using would not accept the arguments that the new `hailctl` gives it. This Google Cloud SDK upgrade turned out to be pretty disruptive as the Python versions on this image have been upgraded, and the new version does not allow for some of the constructs we were using. This newer Hail / Dataproc combo also required us to upgrade the version of Java we use for Hail from 8 to 11.

Upgrade to Hail 0.2.134 [VS-1660]

---

.dockstore.yml
scripts/variantstore/docs/aou/AOU_DELIVERABLES.md
scripts/variantstore/scripts/Dockerfile
scripts/variantstore/scripts/build_base.Dockerfile
scripts/variantstore/scripts/data_table_upload.py
scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
scripts/variantstore/wdl/GvsUtils.wdl

Bypass Terra Data Tables completely for Foxtrot. This makes an all-of-Foxtrot FOFN, uploads it to BQ to work out which samples are new to Foxtrot, and then downloads a new-to-Foxtrot FOFN which is used directly as input to `GvsBulkIngestGenomes`. 
There are some fixes to an upload script from an earlier vision for this PR, but this is no longer intended to be used in the Foxtrot process.
Integration run [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration%20mcovarr/submission_history/ccccbbd4-a4d3-4e7b-95a8-ea598f799460), sample run from FOFN [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration%20mcovarr/submission_history/fba14da7-3109-4df7-8bf1-354fd70b8644).

Bypass Terra Data Tables for Foxtrot [VS-1185][VS-1661][VS-1662][VS-1663]

---

src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java
src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java
src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java

Some of the newer GENCODE GTFs (at the very least GRCh37 liftovers of versions >v19) contain transcript IDs whose version numbers include a secondary number separated with an underscore, e.g. "ENST00000xxxxxx.yy_zz". The currently used regex only considers a single dot character followed by one or more digits and therefore fails to properly remove the version number. This PR should fix that.
Personal note: I don't like regexes in production code anyway, so instead of replacing it with one that works for now, I opted for a cleaner and more maintainable (in my opinion) alternative.
In addition, the recently introduced `--prefer-mane-transcripts` requires the file to be strictly of the GENCODE GTF format, but the hg19 data source with GENCODE v43 (backmapped to GRCh37) contains a GTF in the …

Fix Funcotator transcript override functionality

---

src/main/java/org/broadinstitute/hellbender/tools/walkers/sv/SVStratify.java
src/test/java/org/broadinstitute/hellbender/tools/walkers/sv/SVStratifyIntegrationTest.java

Changes the behavior of SVStratify when a variant belongs to more than one stratification group:
- Changes the `STRAT` field to a list type so that multiple groups can be listed
- Records belonging to multiple groups are no longer duplicated when writing to a single output file
- Mutual exclusivity is only enforced when using `--split-output`
- When using `--split-output`, all groups are listed in `STRAT` rather than only the one corresponding to the output file
Also adds tests and updates docs.

Improved handling of intersecting groups in SVStratify
